### ISSUE TITLE
add a parse octet-stream

### ISSUE THREAD

**Issue by thdotnet** [Azure/logicapps#1]
I was trying to use the Azure Blob conector to read the blob content and do a custom logic. In my case, the content of my blob is a JSON, however I could not parse it using the @json helper function, I had to create an azure functions to parse the content and return a valid json.

Maybe it's a small detail, but definetely it must be an easier way to do that. What about a simple connector or helper function "parse from octet-stream to json".

**Comment by joechung-msft** [comment]
That should work.  Make sure that your blob data doesn't have a byte order mark.  I'll talk to the team to see what we can do about ignoring BOM's when processing binary data.
