### ISSUE TITLE
Standard Logic app - Client Certificate auth in HTTP Action of Logic App returns missing privatekey

### ISSUE THREAD

**Issue by mvelraj** [Azure/logicapps#1006]
### Describe the Bug

I tried enabling client certificate auth for http action in standard logic app, but received "could not load the certificate private key. Please check the authentication certificate password is correct and try again." error message. Please help

### Plan Type

standard

### Steps to Reproduce the Bug or Issue

In the http action select auth type to client certificate and update the pfx and password

AB#27098454

**Comment by sadranyi** [comment]
This is still happening forme as well in a standard logic App

**Comment by rutger-smeets** [comment]
For anyone encountering this problem: in your Standard Logic Apps, add an environment variable for "WEBSITE_LOAD_USER_PROFILE" with value "1". 

This is referred to in the Important note at the bottom of this section: [https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app?tabs=azure-portal#client-certificate-authentication](https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app?tabs=azure-portal#client-certificate-authentication)

Note that setting WEBSITE_LOAD_ROOT_CERTIFICATES is _not_ required.
