### ISSUE TITLE
Value cannot be null. (Parameter 'provider') - Macbook

### ISSUE THREAD

**Issue by JackBruceShell** [Azure/logicapps#1009]
### Describe the Bug with repro steps 

1. Open workflow in Designer 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

Output:

15:17:18: Running command: "func host start --port 8001" with pid: "53788"…

Azure Functions Core Tools

 Core Tools Version: 4.0.5030 Commit hash: N/A (64-bit)

 Function Runtime Version: 4.15.2.20177

[2024-03-14T15:17:19.475Z] A host error has occurred during startup operation '93dbf60e-57d3-453e-99f8-f7826b74540a'.

 [2024-03-14T15:17:19.475Z] Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.WebJobs.Host.Listeners.IListenerDecorator' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.36.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

 Value cannot be null. (Parameter 'provider')

### Browser

Edge

### Additional context

*No response*

AB#27185602

**Comment by JackBruceShell** [comment]
Hi @ccastrotrejo 

I have ran the command and attached as many logs as I could grab from the terminal. Hope this helps.

[logs.txt](https://github.com/Azure/logicapps/files/14608260/logs.txt)

Anything else to try whilst we wait for the engineers?

Thanks.

**Comment by ccastrotrejo** [comment]
Hey @JackBruceShell I took a look at the txt that you attached and I couldn't see any issue in the logs. Were you able to see any error in your side?

Lets do two things:
1.- Could you please execute in the vscode terminal with your logic apps project open the following command? `/Users/<your username>/.azurelogicapps/dependencies/FuncCoreTools/func host start --verbose --port <any number, e.g 8005>` executing with the path will help us to make sure we start the functions process we do really 

2. Close your vscode, Go to `/Users/<your username>/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/` and delete all the folders over there and restart vscode. This will install a new extension bundle from scratch

**Comment by JackBruceShell** [comment]
Hi @ccastrotrejo 

1. I do not have that file path
<img width="773" alt="Screenshot 2024-03-14 at 22 33 45" src="https://github.com/Azure/logicapps/assets/102669576/9d8bbdef-1f27-44b8-a1f0-a3fb0a0a7b6f">

2. Tried this, still receiving the same error.

**Comment by ccastrotrejo** [comment]
@JackBruceShell do you have any values in these vscode extension settings? 
<img width="1327" alt="image" src="https://github.com/Azure/logicapps/assets/102700317/5bae9833-4341-4b88-9410-79823d33927a">

**Comment by JackBruceShell** [comment]
@ccastrotrejo I did not have any values in there... 

Steps taken:
1. Add values like yours above
2. Exit and Quit VSCode
3. Re-open VSCode and let dependencies download

Results:
<img width="1657" alt="Screenshot 2024-03-14 at 22 53 35" src="https://github.com/Azure/logicapps/assets/102669576/31468b8c-ede5-41e5-93a4-ae651bf8187b">

Looks to be working now so I can open the designer correctly.

**Comment by ccastrotrejo** [comment]
@JackBruceShell I am glad it's working now. So, the reason for this is because starting with version 2.81.5, the extension includes a dependency installer that automatically installs all the required dependencies. We did this to avoid users having different installations and versions, therefore we installed the ones we know will work and make it smoother. You can read more about it [here](https://techcommunity.microsoft.com/t5/azure-integration-services-blog/making-it-easy-to-get-started-with-the-azure-logic-apps-standard/ba-p/3979643)

**Comment by JackBruceShell** [comment]
Hi @ccastrotrejo thanks for this, very helpful!

The next problem I always seem to have is the below.

<img width="1245" alt="Screenshot 2024-03-15 at 08 03 55" src="https://github.com/Azure/logicapps/assets/102669576/62c478ee-09df-4e4a-ab86-e39acee091a6">

Following instructions from: https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#run-test-and-debug-locally - I always run into the issue now where I am unable to get a Callback URL from the overview.

Any thoughts appreciated, thanks!

**Comment by ccastrotrejo** [comment]
Hey @JackBruceShell , whenever this kind of issue occurs while opening the overview page its due to the runtime server not being up. Did you follow the step #3 in the [run, test and debug locally](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#) section?
<img width="775" alt="image" src="https://github.com/Azure/logicapps/assets/102700317/caab0799-2991-44b9-932d-4e677a1c877e">

**Comment by JackBruceShell** [comment]
@ccastrotrejo 

Yes I had already started the debugging sessions, please see below.

<img width="1287" alt="Screenshot 2024-03-25 at 09 45 55" src="https://github.com/Azure/logicapps/assets/102669576/ca7fa341-3010-4b10-bce9-0862f3829f5b">

**Comment by ccastrotrejo** [comment]
Hey @JackBruceShell

1.- Is your workflow still empty? It does seem that there isn't a trigger in it

2.- Does your `Func Core Tools Binary Path` extension setting have a value like this? `/Users/<username>/.azurelogicapps/dependencies/FuncCoreTools/func`
<img width="854" alt="image" src="https://github.com/Azure/logicapps/assets/102700317/6a037aca-b0dd-426c-aff6-2b7f60b4eda4">

2.- Does your `.vscode/tasks.json` have a similar structure? 
<img width="1474" alt="image" src="https://github.com/Azure/logicapps/assets/102700317/ac32447c-7817-486d-b3fb-0ff5248184aa">

It also seems that the func host start is not attaching to the `/.azurelogicapps/dependencies/FuncCoreTools/` dependencies that we download for users. It seems that is using your own function core tools

**Comment by JackBruceShell** [comment]
@ccastrotrejo 

I have opened it yesterday and now able to get the callback URL. Not sure what changed but maybe an update forced it to be working.

1. Start Azurite
2. Start Debugging
3. Open Overview
4. Callback URL now visible

<img width="1252" alt="Screenshot 2024-03-26 at 12 27 13" src="https://github.com/Azure/logicapps/assets/102669576/77a0e40d-75ce-469f-b471-d0d7164d182a">

Thanks for your help on this.

**Comment by ccastrotrejo** [comment]
@JackBruceShell I am glad to hear that!
