### ISSUE TITLE
Logic App Authentication Issue

### ISSUE THREAD

**Issue by KronemeyerJoshua** [Azure/logicapps#1013]
### Describe the Bug

This is a series of bugs that I cannot seem to figure out why it's behaving this way. Perhaps there was a cloud issue.
I've been working within the same Logic App for the last month. All of these logic apps and workflows have been created within portal.azure.com, NONE of them have been deployed from ARM or another IaC tool.

This weekend, Get Blob action starting failing authentication (403 Forbidden). Prior to that, it was telling me my storage name was incorrect. This is the same connection I've been using successfully for the last month, nothing has changed.
When I attempt to switch the connection in the designer or code, it pops up with this error.
<img width="172" alt="logicapperror" src="https://github.com/Azure/logicapps/assets/4635851/57deeeaf-fd5b-4933-8ad8-cf2c5efedb04">

After this happened, my run history for each of my workflows is no longer showing up.
I restarted the logic app, now it's showing up with this error at the top of the Overview
"System.Private.CoreLib: The user name or password is incorrect. : 'C:\home\data\Functions\secrets\Sentinels'."

with my Runtime version : Error

Checking the activity log, I have errors for "Run Web Apps Hostruntime Workflow Trigger" These include my sub and tenant Id and do not want to post the full log here, but the message is "  

```JSON
 "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": null,
        "statusMessage": "{\"Code\":\"BadRequest\",\"Message\":\"Encountered an error (ServiceUnavailable) from host runtime.\",\"Target\":null,\"Details\":[{\"Message\":\"Encountered an error (ServiceUnavailable) from host runtime.\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"Code\":\"BadRequest\",\"Message\":\"Encountered an error (ServiceUnavailable) from host runtime.\"}}],\"Innererror\":null}",
```

So I restarted the Logic App and refreshed the config. New errors arose when I did this. It's now stating in my activity log
"Sync Web Apps Function Triggers"
Bad Request, Encountered an error (InternalServerError) from host runtime.

This appears to have wiped out all of my workflows and connections.

This is in the East US Location

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Couldn't begin to tell you how to reproduce this

### Additional context

If you need anymore information or need to look closer at the resource group, please reach out to me. It's on the MCAPS environment, I'm part of the WWPS Group at Microsoft

AB#27212651

**Comment by samuel-peeters-pxs** [comment]
I experienced exactly the same after storage account keys were rotated.
So I was thinking just to renew the storage connection strings in both Environment Variables and restart but in no vein: this error persists.  Almost sure I can circumvent be re-deploying the Logic App (Standard SKU). 

When does Microsoft provide RBAC access on FileShare?
