### ISSUE TITLE
Migrated function connections to not render in UI

### ISSUE THREAD

**Issue by huidongl** [Azure/logicapps#1019]
### Describe the Bug with repro steps 

User used the VS code to migrate ISE logic apps ([https://learn.microsoft.com/en-us/azure/logic-apps/export-from-ise-to-standard-logic-app)](<https://learn.microsoft.com/en-us/azure/logic-apps/export-from-ise-to-standard-logic-app%29>). After migration of ISE to Logic App standard function app connection do not render in the UI. The connections.json file is automantically generated using the migration tool, which has the following upper case parameters,

- "Authentication" 
- "Function" 
- "TriggerUrl" 

This will cause error to view the function connection from portal, and also invalid connection error in the workflow.

User has to manually change them to lower case. Then the function connection will be rendered and the connection will become valid.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "functionConnections": {
        "yuaf-http-trigger-function-connection-1": {
            "Authentication": {
                "name": "Code",
                "type": "QueryString",
                "value": "@appsetting('yuaf-http-trigger-function-connection-1-key')"
            },
            "Function": {
                "id": "/subscriptions/b6eb7b1a-37a0-4d56-b939-71c027a73bb9/resourceGroups/yuaf-MS-Azure-Internal-Resource-Group/providers/Microsoft.Web/sites/yuaf-function-app/functions/yuaf-http-trigger-function",
                "name": "yuaf-function-app/yuaf-http-trigger-function",
                "type": "Microsoft.Web/sites/functions"
            },
            "TriggerUrl": "@parameters('yuaf-http-trigger-function-connection-1-triggerUrl')",
            "displayName": "yuaf-http-trigger-function-connection-1"
        }
    },
    "managedApiConnections": {},
    "serviceProviderConnections": {}
}
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/92560328/abedd9c5-9c75-495f-9f17-c9d5d005b4d7>)

![image](<https://github.com/Azure/LogicAppsUX/assets/92560328/2ac51926-8289-48dd-9df0-750b0015d80f>)

### Browser

Any browser

### Additional context

*No response*

AB#27306648

**Comment by ccastrotrejo** [comment]
Hi @huidongl , we have triaged the issue and both BE and FE will make the proper changes to handle these scenarios correctly. In the meantime, could you please continue using the workaround to manually change them to lower case.

**Comment by huidongl** [comment]
@ccastrotrejo Thank you for working on this issue and sharing the updates! We will continue using the workaround for the function connection. May I know if there is an ETA for the fix?

**Comment by ccastrotrejo** [comment]
Hey @huidongl , there isn't an ETA yet. Once we have it I will update it in here.
