### ISSUE TITLE
Twitter connection with BYOA: Failed to login. Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by abatishchev** [Azure/logicapps#1021]
### Describe the Bug with repro steps 

1. Add action "Post a tweet" 
2. Provide connection's name 
3. Paste "Consumer API Key" from Twitter Dev Portal to field "Consumer Key" 
4. Paste "Consumer API Key Secret" to "Consumer Secret" 
5. Click "Sign In" 
6. Observe a pop-up window appearing and disappearing quickly 
7. Observe an error: 

> Failed to login. Response status code does not indicate success: 401 (Unauthorized)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/351644/650ccae1-ee0d-4bbe-a11b-07d45006153b>)

### Browser 

Edge version 122.0.2365.92

### Additional context 

Demo request "Create a Tweet" on [public Postman workspace](<https://www.postman.com/twitter/workspace/twitter-s-public-workspace/request/9677191-652d8d82-ddfc-4c05-b191-a8a904f63a82?tab=overview>) requires 4 secrets, not 2:

1. Consumer Key 
2. Consumer Secret 
3. Token 
4. Token Secret 

and works even from a simple PowerShell command:

```powershell
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", "application/json")
$headers.Add("Authorization", "OAuth oauth_consumer_key=`"...`", oauth_token=`"...`", oauth_signature_method=`"HMAC-SHA1`",oauth_timestamp=`"...`", oauth_nonce=`"...`" ,oauth_version=`"1.0`", oauth_signature=`"...`"")

$body = @"
{
    `"text`": `"...`"
}
"@

$response = Invoke-RestMethod 'https://api.twitter.com/2/tweets' -Method 'POST' -Headers $headers -Body $body
$response | ConvertTo-Json
```

AB#27399144

**Comment by hartra344** [comment]
Moved this to our backend repo/issues list. This looks like it's an issue with the connector.

**Comment by deanward81** [comment]
I'm investigating this issue now, will post an update here once I've done some log spelunking

**Comment by deanward81** [comment]
Looking into this again today

**Comment by deanward81** [comment]
Nearly there, expect to get to the bottom of this, this week

**Comment by deanward81** [comment]
Reopening, still under investigation
