### ISSUE TITLE
string value  in this format "2024-03-15T10:00:00.000Z" getting changed to "2024-03-15T10:00:00Z" in logic app standard after saving it

### ISSUE THREAD

**Issue by swakMS** [Azure/logicapps#1028]
### Describe the Bug with repro steps 

In logic app standard at any action provide the string value "2024-03-15T10:00:00.000Z", and save.

 now go to code view or designer and look for this value- it would have changed to "2024-03-15T10:00:00Z". tried in standard new and old designer.

 its not happening in consumption.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/78227025/3983de56-564f-43ca-9671-6464623fe185>)

 here customer trying to add the value at headers by hardcoding.

### Browser 

chrome

### Additional context 

*No response*

AB#27558701

**Comment by edwardyhe** [comment]
Hi @swakMS , I can confirm this is related to JSON serialization/deserialization differences. However, is there a particular reason that the .000 is required? It is not needed based on ISO 8601, and APIs should not require them.
