### ISSUE TITLE
Logic App Action to call Integration account spins for minutes to hours before resolving

### ISSUE THREAD

**Issue by jdloucks** [Azure/logicapps#1080]
### Describe the Bug

Before using the map Json to Json action that is linked to an integration account, we first checked if that map existed in the integration account. This was working flawlessly for months and now will spin for a long amount of time before resolving. I've looked into the logs and getting null exception when trying to call the work dispatcher to perform the mapping or call the integration account. it keeps erroring out for null until eventually the integration account is found and moves on like nothing happened. I've had these actions take seconds for months and now they can take anywhere from 5 minutes to 2 hours. 

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Action to check integration account artifact, then action to perfrom json to json mapping.

**Comment by jdloucks** [comment]
@AbodeSaafan I see that you made changes 5 days ago. It doesn't look related to my issue, but it is when my problem started. Sorry to tag you indiscriminately, just looking through what might have changed. thanks!

**Comment by Shashi-MSFT** [comment]
@jdloucks could you share me couple of RunIDs, so that i can investigate this issue.

**Comment by jdloucks** [comment]
@Shashi-MSFT Here are some RunId's. The first three are ones that have the problem, and the last three are ones that were working correctly before. I did get a "workaround" to this issue by removing the action to check for integration account artifact, but it's still concerning that it will be doing this. 

08584838163263747685336540997CU00 
08584838163561434448317769408CU00
08584838163933778846443844946CU00
08584838164026026333320079778CU00

before
08584839027978993540814794013CU00
08584839028120171567614646827CU00
08584839028126500586512648757CU00

**Comment by Shashi-MSFT** [comment]
@jdloucks We’ve identified this as a bug and are working on a fix. It’s likely that the fix will be deployed by the end of July, I’ll provide an update if it’s sooner. Thank you
