### ISSUE TITLE
Unable to handle API Management instances that have enforced a Minimum Management API version

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/logicapps#1085]
### Describe the Bug with repro steps

The API Management team announced that they are enforcing a Minimum Management API version starting the 1st of June this year. [Here ](https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023) is the announcement. It looks like they already started rolling out this release since it is not possible to remove the enforcement of Minimum API version on one of our API Management instances. At least when using the Portal. 

As mentioned in a [StackOverflow thread](https://stackoverflow.com/questions/78209975/enabling-minimum-apiversion-to-2021-08-01-in-azure-api-management-causing-saving) the Logic apps designer is unable to handle an API Management version if it has an enforced Minimum API version. It is mentioned a workaround in an answer. 

It is the same issue for both Consumption and Standard and when using . Below are the steps for reproducing the issue for Consumption.

Prerequisites: an API Management instance which has not an enforced Minimum API version. (It looks like it must be in the same subscription as the Logic app.)

1. Create a new Logic app, select Consumption. 
2. Go to the Designer blade
3. Add a Recurrence trigger
4. Add an API Management shape.
5. Select an API Management instance in the list. 
6. Select an API and an Operation
7. Save
8. Go to another blade. 
9. Go to the API Management instance. 
10. Go to the Management API blade
11. Select Management API settings
12. Switch Enforce minimum API version to Yes
13. Save
14. Wait some seconds
15. Go back to the Logic app
16. Go to the Designer
17. Go to the API Management shape
18. It will show an error:
"Unable to initialize operation details for operation - xxxxx. Error details - Failed to connect to management endpoint apim-xxx-yyy.management.azure-api.net:3443 for a service deployed in a Virtual Network. Make sure to follow guidance at https://aka.ms/apim-vnet-common-issues for Inbound connectivity to Management endpoint. Check 'ApiManagement Control Plane - inbound' connectivity at https://aka.ms/apimnetworkstatus."

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "interval": 3,
          "frequency": "Month"
        }
      }
    },
    "actions": {
      "zzzzzzzzzzzzz": {
        "runAfter": {},
        "type": "ApiManagement",
        "inputs": {
          "api": {
            "id": "/subscriptions/zzzzzzzzzzzzzzz/resourceGroups/zzzzzzzz/providers/Microsoft.ApiManagement/service/yy/apis/xxxxxxxx"
          },
          "method": "get",
          "pathTemplate": {
            "template": "/xxxxxxxxxxx/yyyy",
            "parameters": {
              "zzzzzzzzzzzzzzz": "786"
            }
          }
        }
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {}
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/9644248/5a7d1ab6-2d80-44d9-8144-c4925faa2ce9)

### Browser

Edge

### Additional context

Since the API Management release being rolled out I expect that many others will run into this issue.

**Comment by daviburg** [comment]
This is getting fixed on the logic apps' end, and in the meantime the APIM version deprecation is maintaining compatibility with logic app service. @rarayudu

**Comment by ErikMogensen** [comment]
It seems that the enforcement of the Minimum Management API Version has started to rollout before the fix for APIM connector.  At least in one case. We are experiencing this issue with actions connected to a certain APIM instance. Actions connected to other APIM instances still look good though.

Do you know when the fix for the APIM connector will start to roll out? Perhaps it has already started...
