### ISSUE TITLE
DotNetSDK Installation Script Fails with Spaces in Path for -InstallDir Parameter

### ISSUE THREAD

**Issue by PhoenixUA** [Azure/logicapps#1096]
### Describe the Bug

While attempting to install the DotNetSDK using the provided installation script, I encountered an issue where the script fails if the path specified for the -InstallDir parameter contains spaces. The script works correctly when the path uses the short name (8.3 format) for the directory with spaces.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Download the DotNetSDK installation script from https://dot.net/v1/dotnet-install.ps1.
2. Execute the script using the following command, where the -InstallDir parameter includes a path with spaces:
```
powershell -ExecutionPolicy Bypass -File C:\Users\JOHNDO~1\AppData\Local\Temp\.azurelogicapps\DotNetSDK\DotNetSDK.ps1 -InstallDir "C:\Users\John Doyle\.azurelogicapps\dependencies\DotNetSDK" -Channel 6.0
```
3. The script fails with the following error message:
```
'Doyle\.azurelogicapps\dependencies\DotNetSDK' is not a supported value for -Quality option. Supported values are: 
daily, signed, validated, preview, ga. If you think this is a bug, report it at 
https://github.com/dotnet/install-scripts/issues.
```
4. When the path with spaces is replaced by its 8.3 format (e.g., JOHNDO~1), the script executes successfully:
```
powershell -ExecutionPolicy Bypass -File C:\Users\JOHNDO~1\AppData\Local\Temp\.azurelogicapps\DotNetSDK\DotNetSDK.ps1 -InstallDir C:\Users\JOHNDO~1\.azurelogicapps\dependencies\DotNetSDK -Channel 6.0
```

### Additional context

**Expected Behavior:**
The script should correctly handle paths with spaces when specified for the -InstallDir parameter without requiring the use of the 8.3 format.

**Actual Behavior:**
The script fails with an error when the path specified for the -InstallDir parameter contains spaces.

**Environment:**
OS: Windows 11 Home (10.0.22631 Build 22631)
PowerShell version: 5.1.22621.3672

Thank you for addressing this issue. Please let me know if any additional information is required.

**Comment by PhoenixUA** [comment]
In addition:

```
11:04:15 PM: Running command: "C:\Users\John Doyle\.azurelogicapps\dependencies\DotNetSDK\dotnet.exe --version"...
'C:\Users\John' is not recognized as an internal or external command,
operable program or batch file.
11:04:15 PM: Error: You must have the [.NET Core SDK](https://aka.ms/AA4ac70) installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions.

``

**Comment by SilentPenguin** [comment]
In case anyone else runs into this issue, I've found a simple workaround.

Within the vscode configuration there's an option named `azureLogicAppsStandard.autoRuntimeDependenciesPath`.
Setting this value to the 8.3 path as described above (ie `C:\Users\JOHNDO~1\.azurelogicapps\dependencies`) should allow the extension's setup process to run in its entirety.
