### ISSUE TITLE
"404 File path doesn't exist" - creating file in SFTP

### ISSUE THREAD

**Issue by pnl0ne26** [Azure/logicapps#1117]
### Describe the Bug with repro steps 

The requirement is to create a 'when new email arrives in shared emailbox' trigger and retrieve the attachments from mail, and send those attachments(.csv) files to a SFTP location. However, getting frequent errors in 'create file' step while placing files in SFTP location. Some runs are getting succeeded, while at times, am getting failures.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/e21573ae-b6c3-405d-892f-3d5f5faae5b6>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by daviburg** [comment]
@pnl0ne26 which SFTP connector are you using? Built-in or Managed (Azure)? Do include the workflow JSON, as well as failure runID, requestID, workflow application resource id, time of issue reproduction, and the Azure region for your reproduction.
