### ISSUE TITLE
Cannot deploy Logic App - Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by mkhoruzhiy** [Azure/logicapps#1126]
### VSCode Dump

Cannot read properties of undefined (reading 'kind')

![image](https://github.com/user-attachments/assets/244bb56c-6ac4-46ff-bfce-7a980eb41afc)

### Steps to Reproduce the Bug or Issue

I was trying to deploy the Logic App ai-sample\SampleAIWorkflows with use of the project instructions. The step "Deploy to logic app..." fails with the error message "Cannot read properties of undefined (reading 'kind')".
I checked the kind property of the workflow. It is set to "Stateful".
How can I fix the issue?

![image](https://github.com/user-attachments/assets/729e2715-cfa2-4218-9e0c-0cafaf15cb7f)
![image](https://github.com/user-attachments/assets/467d5b26-6633-4feb-b607-6c421f81435d)

Deploy your Logic App:
1. Go to the Azure Logic Apps extension
2. Click Deploy to Azure
3. Select a Subscription and Resource Group to deploy your Logic App

**Comment by matthieupetite** [comment]
Hello I am facing the same issue
