### ISSUE TITLE
Create blob (V2) does not set the content-type in the blob correctly. 

### ISSUE THREAD

**Issue by tithij** [Azure/logicapps#1128]
### Describe the Bug with repro steps 

1. Create a logic app 
2. Use the action `Create blob (V2)` 
3. I am fetching an image from a 3rd party via api. 
4. And then placing that on the blob 
5. When I upload the same image via the blob, the `CONTENT-TYPE` is set as `image/png` 
6. When I do that steps from 1 to 4, then the `CONTENT-TYPE` in the blob is set to `application/octet-stream` 
7. I have set the content type on `Create blob (V2)` and can see it set on the `INPUT` headers and body section of the run 
8. BUT, in the output there is no content type header. Only this `"MediaType": "image/png",` 

![image](<https://github.com/user-attachments/assets/acf8750a-2081-4e9c-b1ba-2a5fa4f1bf57>)

![image](<https://github.com/user-attachments/assets/3f544af8-194d-4fe2-b1ec-10a040f6c87c>)

![image](<https://github.com/user-attachments/assets/404e1331-5fa7-49b8-8fe6-05c95be5b57c>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by smendoza88** [comment]
I am experiencing the same issue with the Create Blob (V2) connector. When I manually drop a file via Azure storage explorer, the correct type is set on the blob, but that is not the case with the logic app.

Here is the screenshot of the logic app setting the MediaType to application/pdf. 
![2024-08-27_13-08-14](https://github.com/user-attachments/assets/8da0e275-f18d-43ff-89d8-65cf8f7c34b0)

Here is a screenshot of the file created in blob by the logic and the content type being set as application/octet-stream
![2024-08-27_13-08-42](https://github.com/user-attachments/assets/bdeaac46-4f86-4cc2-9e5d-38fa1710a65e)

**Comment by WCMV** [comment]
I am experiencing this same issue, setting the content-type parameter in Power Automate does not translate to the content-type being set on the new blob.
