### ISSUE TITLE
Support to enable system or assigned identity for Staging regions in Consumption SKU

### ISSUE THREAD

**Issue by ynauls** [Azure/logicapps#1131]
### Describe the Bug with repro steps 

1. Go to Logic Apps PM subscription 
2. Create Logic App Consumption SKU 
3. Go to Identity menu 
4. Turn status "on" 
5. Click on "save" 
6. Select "yes" on prompt 

![image](<https://github.com/user-attachments/assets/52ad591d-7a71-4974-8180-e19499def323>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/23a3f08e-e606-44fa-8e56-7d59b3f2c77d>)

### Browser 

Edge

### Additional context 

for staging regions, the backing region should be used

- eastusstage => eastus 
- centralusstage => centralus

**Comment by hartra344** [comment]
Looks like a backend issue

**Comment by chenshu-msft** [comment]
@hartra344 It seems there is no validation in the backend that would raise this `IdentityServiceUnavailable` error. Add the logic to handle managed identities is region-agnostic. Are there any validations in the frontend or UX that is blocking the creation of managed identities? As @ynauls mentioned, if we use a backing region for the stage region, then calling the MIRP endpoint of the backing region should still work.
