### ISSUE TITLE
Cannot work anymore in logic apps standard with Visual Studio Code since the last upgrade to V4.44.9

### ISSUE THREAD

**Issue by kblacquiere** [Azure/logicapps#1137]
### Describe the Bug with repro steps 

1\.Start a new Logic Apps Workspace

 2\.Select Logic Apps Standard With Custom Code Project

 3\.Complete Until the Workspace Open

4. Select the New Workflow 
5. Open Designer

 Nothing happens … 

There is an error that is repeating every few secs …

2024-08-15T21:43:54.667Z] An unhandled host error has occurred.

 [2024-08-15T21:43:54.667Z] Microsoft.Azure.Workflows.EventSource.Edge: Object reference not set

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Call_a_local_function_in_this_logic_app": {
        "type": "InvokeFunction",
        "inputs": {
          "functionName": "GenetecAI",
          "parameters": {
            "zipCode": 85396,
            "temperatureScale": "Celsius"
          }
        },
        "runAfter": {}
      },
      "Response": {
        "type": "Response",
        "kind": "http",
        "inputs": {
          "statusCode": 200,
          "body": "@body('Call_a_local_function_in_this_logic_app')"
        },
        "runAfter": {
          "Call_a_local_function_in_this_logic_app": [
            "Succeeded"
          ]
        }
      }
    },
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

![image](<https://github.com/user-attachments/assets/cb9b31f2-1ed7-4cae-97fc-094d9aa22a52>)

![image](<https://github.com/user-attachments/assets/d3d878d8-c93c-48cc-be21-61015366df72>)

### Browser

Visual Studio Code

### Additional context

*No response*

**Comment by kblacquiere** [comment]
Hi, I followed your recomendation and Everythin is working fine Now !

Thanks !

**Comment by swghimire** [comment]
hi @kblacquiere and @bjornomy we deployed a new version with a fix for the error you are experiencing so you can revert the host configuration to the original and test whether you are still experiencing the issue. 

additionally, we are investigating how this error occurred. could you please share whether you were using the logic apps extension in vscode on a machine that was using a non-windows operating system?
