### ISSUE TITLE
Provide support in Microsoft.Azure.Management.Logic

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#114]
Provide support in [Microsoft.Azure.Management.Logic](https://www.nuget.org/packages/Microsoft.Azure.Management.Logic/) for managing Logic App runs outside of Azure.

**Comment by MattFarm** [comment]
Can you add a little more detail on an example scenario you are thinking of here Tom?

**Comment by tomkerkhove** [comment]
Sure, we are using that SDK to build a testing framework for Logic Apps which we are open sourcing and would love to make it compatible with this new approach as well.

It allows you to create logic Apps on the fly, change behavior, etc.

**Comment by chris5287** [comment]
We use the SDK to monitor our Logic Apps from a custom dashboard, so this would be very important to maintain (listing logic apps, listing runs statuses, etc...)
