### ISSUE TITLE
Copy paste action not showing paste option

### ISSUE THREAD

**Issue by IDrumsey** [Azure/logicapps#1141]
### Describe the Bug

Right click on action. Click copy entire action. click plus button. Doesn't show option to paste action.

### Plan Type

Consumption

### Steps to Reproduce the Bug or Issue

See above

**Comment by AzureDev0012** [comment]
@IDrumsey 

Which Action are you trying to copy/paste ?
Are you trying to paste inside an condition / scope/.. ?

**Comment by IDrumsey** [comment]
> @IDrumsey
> 
> Which Action are you trying to copy/paste ? Are you trying to paste inside an condition / scope/.. ?

Honestly can't remember. It still probably shouldn't give you the option to copy if you can't paste.
