### ISSUE TITLE
Use Azurite instead of Azure Storage Emulator

### ISSUE THREAD

**Issue by EldertGrootenboer** [Azure/logicapps#115]
Everything points to Azurite becoming the new standard for local storage.

**Comment by tomkerkhove** [comment]
Relates to #96

**Comment by MattFarm** [comment]
Thanks Eldert, at the moment, Azurite is missing some key APIs that we need. We're working out what the best strategy is moving forward. Tagging @laveeshb and @rohithah for info.

**Comment by laveeshb** [comment]
+1 to @MattFarm 
We want to use Azurite as well; however, it does not have all the APIs we need at this time.

**Comment by laveeshb** [comment]
Resolving this as by design.
