### ISSUE TITLE
Standard LogicApps SQL Query Executor Action Gateway Time Out after 2 mins

### ISSUE THREAD

**Issue by AzureDev0012** [Azure/logicapps#1150]
### Describe the Bug

I configured the SQL Query Execute Action in Logic App Workflow and added the "ServiceProviders.Sql.QueryTimeout" :"00:03:00" in Configuration setting , but no luck on Timeout increase and added the same in host.json file but facing the same issue **Gateway Time Out.**

And I am using node version of 18

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Created a workflow and added the SQL Query Execute Action then created SQL connection using Managed Identity.
if the query is less than 2 mins no issues.
if it crosses more than 2 mins, getting **Gateway time Out** issue. 

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Execute_a_SQL_query_(V2)": {
                "inputs": {
                    "body": {
                        "query": "WAITFOR DELAY '00:02:50'"
                    },
                    "host": {
                        "connection": {
                            "referenceName": "sql-3"
                        }
                    },
                    "method": "post",
                    "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent(parameters('SQLServerName')))},@{encodeURIComponent(encodeURIComponent(parameters('SQLDataBaseName')))}/query/sql"
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Additional context

added the below value in App setting

{
    "name": "ServiceProviders.Sql.QueryTimeout",
    "value": "00:05:00",
    "slotSetting": false
  }

**Comment by AzureDev0012** [comment]
@ccastrotrejo 
can you please tag some one to this issue

**Comment by ccastrotrejo** [comment]
Hey @AzureDev0012 Same as this other ticket https://github.com/Azure/logicapps/issues/1167, there is a team that watches and triage backend issues, please if you need more direct interaction or prompt response, I would advise opening a ticket with support.
