### ISSUE TITLE
Critical: Cannot edit in read-only editor

### ISSUE THREAD

**Issue by itpropro** [Azure/logicapps#1158]
### Describe the Bug

There is a critical bug in the new Logic App experience. When you want to adjust the source code in the code view, it says `Cannot edit in read-only editor`.
The functionality to edit code in the code view is essential and as the old editor will be deprecated in September, it's very important to have a proper replacement before that happens.

Just to set this into context, if it's not possible to edit code directly anymore our customers alone will have a few hundred Logic Apps break down as they all rely on editing the source code directly due to several different issue with the graphical editor.

I had multiple afraid customers contact me already, so it would be great to get a timeline on when this will be fixed.
Thank you.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Open Logic App
2. Click on Code View
3. Try to edit code

**Comment by hartra344** [comment]
We are adding the capability back in the next few weeks. But even today it's possible to edit code directly, they need to select code view from the menu item instead of the designer.

**Comment by itpropro** [comment]
> We are adding the capability back in the next few weeks. But even today it's possible to edit code directly, they need to select code view from the menu item instead of the designer.

Thanks for your quick reply. Why is it not possible to open that from the designer and why is the code view not full screen?

**Comment by hartra344** [comment]
We had a lot of customers give themselves problems by editing the code directly from designer and we chose with new designer to force them as separate blades that require saving between so that mistakes are reversible.

Like I said, were adding this capability back but it'll come with earnings that it's for advanced users and carries a risk of lost work or broken workflows.

**Comment by hartra344** [comment]
Like I said, we plan to enable to old way of it working, but with proper warnings in place. here is the PR for it: https://github.com/Azure/LogicAppsUX/pull/5547
