### ISSUE TITLE
Provide setup script for clean install

### ISSUE THREAD

**Issue by EldertGrootenboer** [Azure/logicapps#116]
Make the steps needed for running Logic Apps on Functions runtime either into a installer or script. This should check for current installations, and install those components that are not there yet.

**Comment by tomkerkhove** [comment]
I've found that this one is actually pretty straight forward - https://github.com/Azure/logicapps/wiki/2.-Set-up-your-development-environment

**Comment by EldertGrootenboer** [comment]
Agreed that the documentation does a good job here, but having something that takes care of all the steps would be nice. Would say this is a Could have / Would have, so not high priority.
