### ISSUE TITLE
unable to query some of the schemas (EmailEvents, SecurityEvent) using Advanced Hunting

### ISSUE THREAD

**Issue by arearawerbaw3br** [Azure/logicapps#1161]
### Describe the Bug with repro steps 

I unified the MDE and Microsoft Sentinel Platform.

I can query all the tables in MDE portal.

In Logic apps, I can query tables like DeviceEvents, DeviceNetworkEvents.

However, I am unable to query some of the tables, like EmailEvents, SecurityEvent

"Failed to retrieve dynamic outputs. As a result, this operation's outputs might not be visible in subsequent actions. Error details: 'take' operator: Failed to resolve table or column expression named 'EmailEvents'. Fix semantic errors in your query."

suspect the backend URL are different

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

tried Both

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```
{
  "type": "ApiConnection",
  "inputs": {
    "host": {
      "connection": {
        "referenceName": "wdatp"
      }
    },
    "method": "post",
    "body": {
      "Query": "EmailEvents\n| take 10"
    },
    "path": "/api/advancedqueries/run"
  },
  "runAfter": {}
}
```

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/1c7cdfad-7a76-4aea-8dfb-292fbaf707e8>)

### Browser 

Chrome, Edge

### Additional context 

suspect the backend URLs are different

I faced similar problem in PowerBI which there are two different APIs

[https://api.securitycenter.microsoft.com/api/advancedqueries](<https://api.securitycenter.microsoft.com/api/advancedqueries>) (For DeviceEvents…)

[https://api.security.microsoft.com/api/advancedhunting](<https://api.security.microsoft.com/api/advancedhunting>) (For EmailEvents…)

**Comment by jeffreylauck** [comment]
I am not sure if this has been addressed yet but I am experiencing the same issue.

If I query `DeviceInfo | take 10` using Advanced Hunting in a Logic App, it works fine.
![Image](https://github.com/user-attachments/assets/e327f446-b3be-4003-a071-7f7fa9839ee6)

But when I try to query `EmailEvents | take 10`, it is giving me the same error.
![Image](https://github.com/user-attachments/assets/b40ca4f0-951f-4fa7-a13b-7beb4674678a)

**Comment by ThreatMatrix** [comment]
I'm experiencing this issue in Power Automate, and I believe it's due to the query being directed to "apis/wdatp." with a connection reference of "shared_wdatp". Meaning only device specific (WDATP) queries will succeed. In the same way the Defender ATP trigger in Power Automate only works for AV related alerts, rather than all the more modern unified alerts that defender 365 correlates into incidents.

**Comment by jeffreylauck** [comment]
@ThreatMatrix Thanks and I got the same answer from Microsoft Support. Basically they said the Advanced Hunting connector in Logic App only works for MDE, so Device* logs are available. However, since EmailEvents log table is part of Defender for M365, it is not available through this connector.

**Comment by dewardvide** [comment]
Thank you all for raising and commenting on this issue - I just wanted to mention that the issue still exists and affects tables such as the CloudAppEvents table as well. I hope the connector is updated soon : )
