### ISSUE TITLE
HTTP action running for multiple days

### ISSUE THREAD

**Issue by ERAV2** [Azure/logicapps#1162]
### Describe the Bug

We have observed that the HTTP action in some of our Azure Logic Apps (Standard) workflows keeps running for multiple days, causing delays in our processes. This is particularly problematic for our single instance workflows. 

We are currently using the default retry policy on the HTTP action, but we are unsure if this is the cause of the problem.
How can we best prevent this problem?

Thank you for your attention to this matter.

### Plan Type

Standard

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/fedd283a-75e2-4bb3-af55-862aaf5ff9e3)
![image](https://github.com/user-attachments/assets/0a22f949-5e0d-4b39-a350-f9c10888d45d)

**Comment by hartra344** [comment]
For this type of issue, directly effecting your production workloads, i would highly advise opening a support case if you haven't already. GitHub issues are useful but they aren't going to get the timely attention that a support case will.
