### ISSUE TITLE
SQL Server Connector GatewayTimeout

### ISSUE THREAD

**Issue by AzureDev0012** [Azure/logicapps#1167]
### Describe the Bug with repro steps 

1. Standard Logic App 
2. Workflow 
3. Add Execute a SQL query (V2) connector 
4. If execution crossed more than 2 minutes, getting Gateway time out issue. (Added configuration as mentioned in Microsoft docs for time out extend [ServiceProviders.Sql.QueryTimeout](<https://learn.microsoft.com/en-us/azure/logic-apps/edit-app-settings-host-settings?tabs=azure-portal#reference-for-app-settings---localsettingsjson>) 

 added value **ServiceProviders.Sql.QueryTimeout : 00:05:00** added value in both appsettings & host.json) but getting same issue again. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
transferring issue to backend for investigation

**Comment by AzureDev0012** [comment]
@Eric-B-Wu 

got this error in Git hub.

![image](https://github.com/user-attachments/assets/a42eecb1-6175-4d14-9a49-ae9557d8f0f6)

**Comment by AzureDev0012** [comment]
@Eric-B-Wu 

In backend no one looking on the issues, after 45 days tickets are closing automatically with **Stale Status**. 
Kindly guide me to whom I can inform the same.

Thanks

**Comment by hartra344** [comment]
@AzureDev0012 there is a team that watches and triage backend issues but they do not interact on GitHub as much as the front end team does. If you need more direct interaction or prompt response, i would advise opening a ticket with support.
