### ISSUE TITLE
Invalid template for features of Analyze Document for Prebuilt or Custom Models (v3.x API)

### ISSUE THREAD

**Issue by RiccardoGDev** [Azure/logicapps#1169]
### Describe the Bug with repro steps 

**Steps:**

 Logic app designer

 Add an Action

 Form Recognizer > Analyze Document for Prebuilt or Custom Models (v3.x API)

 Optional And Premium Features

 Add ["barcodes"] or ["ocrHighResolution"]

![screen4](<https://github.com/user-attachments/assets/2a36ce70-5781-4dcc-8d4d-28e4b693ea58>)

**Error:**

 The field Optional And Premium Features form accepts only an array, but at runtime I get this error:

 InvalidTemplate

 Unable to process template language expressions in action 'Analyze\_Document\_for\_Prebuilt\_or\_Custom\_models\_(v3.x\_API)' inputs at line '0' and column '0': 'Error reading string. Unexpected token: StartArray. Path 'queries.features'.'.

![screen1](<https://github.com/user-attachments/assets/b2de9cad-cc79-4dd9-817f-522325f0dd0c>)

**Workaround Steps:**

 Logic app code view

 Add only a string instead of an array

![screen5](<https://github.com/user-attachments/assets/7b46e17d-9214-426a-9f10-0214775ac6ab>)

By doing this I can successfully run the logic apps. However if I try to edit the logic apps using the designer I get an invalid template error.

![screen3](<https://github.com/user-attachments/assets/5ddc2ba1-abf1-4a6b-9814-ba02208e571d>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

Session ID: 331aaddf369d4373b3c121994836ad16

 HubsExtension: 14ms \| Version: 14.140.0.179303800.240830-0451

 Microsoft\_Azure\_EMA: 6ms \| Version: 2.40826.1.7

**Comment by hartra344** [comment]
Moving to the backend repo, the connector swagger specifies the type of this field as an array but runtime seems to disagree. This will need to be fixed by the connector owners.
