### ISSUE TITLE
Unable to get Callback URL for a deployed workflow

### ISSUE THREAD

**Issue by CarloGarcia** [Azure/logicapps#118]
Steps to reproduce:
1. Create simple workflow with HTTP Trigger.
2. Deploy workflow to Function App
3. Open workflow Overview to get Callback URL for the deployed workflow.
4. Error shown and Callback URL not available.

See screenshot for error message:
![image](https://user-images.githubusercontent.com/34681490/84147160-d70ab780-aa54-11ea-94f6-4e9010dc588d.png)

**Comment by MattFarm** [comment]
Thanks @CarloGarcia can you take a look at this known issue ti see if it fixes your problem? https://github.com/Azure/logicapps/issues/104

**Comment by CarloGarcia** [comment]
Thank you Matt, 

Setting CORS to "*" ( as per #104 ) has resolved the issue for me and I am now able to get the Callback URL for the deployed workflow.
