### ISSUE TITLE
Logic Apps Diagnostic Settings Failing to Deliver Messages to Event Hub (West Europe)

### ISSUE THREAD

**Issue by MarkOwen-CoditMT** [Azure/logicapps#1180]
### Describe the Bug

We are experiencing an issue in the **West Europe** region where Logic Apps, specifically those using the Consumption plan, connected to an Event Hub via Diagnostic Settings, are intermittently failing to send runtime messages. Runtime messages from different executions of the Logic Apps are randomly not being delivered to the Event Hub, resulting in data loss and inconsistent event tracking.

**Issue**: Logic App runtime messages are sporadically missing from the Event Hub, particularly affecting Consumption-based Logic Apps.

**Expected Behavior:** All runtime messages from the Logic Apps should reliably be delivered to the Event Hub , we do understand that some runtime messages can fail to arrive based on documention provided by Microsoft -  [click here](https://learn.microsoft.com/en-us/azure/logic-apps/monitor-workflows-collect-diagnostic-data?tabs=consumption)

**Observed Behavior**: While some runtime messages are successfully arriving, others are missing with no discernible pattern. This issue is predominantly affecting apps in the West Europe region.

A customer support ticket has been opened with Microsoft, but there is currently no ETA on a fix. The lack of consistent message delivery is causing significant operational challenges.

### Plan Type

Consumption

### Steps to Reproduce the Bug or Issue

We have followed the setup procedure as per documented [here](https://learn.microsoft.com/en-us/azure/logic-apps/monitor-workflows-collect-diagnostic-data?tabs=consumption)

### Additional context

This issue has been persisting since the 8th of september , a current resolution is that the Microsoft team is restarting instances based on an alert, a fix is on the way but we would like if anyone is else is being effected like us

**Comment by pim-simons** [comment]
Having the same issue

**Comment by spulkkinen** [comment]
Also facing the same the same issue in production environment, in **West Europe region** and with logic app standard. We have a monitoring solution which relies on diagnostic settings and terminating workflows in a failed state and now some of the WorkflowRunCompleted events are not reaching the logs. This is especially problematic for the events where the status is failed and we currently cannot rely fully on catching all the failures. We have over 60 workflows running so this poses huge problems.

**Comment by hichamveo** [comment]
Facing the same issue in west Europe. A dev environment with small workload and some logs are lost within logic apps standard

**Comment by MarkOwen-CoditMT** [comment]
The issue has been resolved and fixed by microsoft due to the below; https://m365admin.handsontek.net/multiple-services-partially-incomplete-log-data-due-to-monitoring-agent-issue/#google_vignette
