### ISSUE TITLE
JavaScript Execute Code limit of 1024 characters is just too low to do anything meaningful

### ISSUE THREAD

**Issue by oricawalid** [Azure/logicapps#1182]
### Describe the Bug with repro steps 

1. Use Execute Javscript code only 1024 character, please increase 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by shemsargent-ch** [comment]
I found this searching for the 1024-character limit error I received in testing, too. @Microsoft I'm paying for the consumption, please allow me to consume what I need. Or suggest a better alternative.

**Comment by pranav0612** [comment]
It's really frustrating issue. Kindly fix it. Is there any workaround. @MicrosoftGit
