### ISSUE TITLE
JavaScriptCode action incompatible with local function

### ISSUE THREAD

**Issue by RobBowman** [Azure/logicapps#1187]
### Describe the Bug

It seems that once a _JavaScriptCode_ action is added to a workflow of an app that contains a local function, it then becomes impossible to use vs code to attach debugger to the logic app

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Create a new BRE logic app (as an easy was to create an app with a local function). Build the function and test ability to attach debugger to logic app. Add a _JavaScriptCode_ action to the workflow. Attempt to attach debugger to the logic app - it will fail with: 
_Worker failed to load function: 'WorkflowNodeWorker' with functionId
Invalid entry point configuration. The function entry point must be defined in the format <fulltypename>.<methodname>_

### Additional context

I have published a demo project to this repo: https://github.com/RobBowman/la-javascript-error 

Windows VS Code Extension: v1.15.4
Node version: v22.9.0

**Comment by Andrew-Lahikainen** [comment]
This repo isn't monitored is it?

**Comment by Andrew-Lahikainen** [comment]
Rolling back version v4.57.7 of the Azure Logic Apps extension worked
