### ISSUE TITLE
Calling Local Azure Function From logic Apps Standard with Azure.Data.tables.dll assembly is Failing with The system cannot find the file specified.

### ISSUE THREAD

**Issue by kblacquiere** [Azure/logicapps#1189]
### Describe the Bug

Hello, I am trying to access an Azure Storage Table from a Logic Apps Standard Local Azure Function. 
We added the pakage in the .csproj and we are able to compile. 
We also added the following lines in the project file:
<PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
</PropertyGroup>

When the function is called, it fails with the following errors 

System.IO.FileNotFoundException: Could not load file or assembly 'Azure.Data.Tables, Version=12.9.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. The system cannot find the file specified.

When we look in the lib folder, we can see the assembly is present under the .net8 folder.

<img width="430" alt="image" src="https://github.com/user-attachments/assets/6e78a9db-070c-4103-b035-afe8aae7f426">

Is there something missing to make this work ?

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a new logic apps standard in visual studio code With custom code project
2. Add the Azure.Data.Tagble package 
3. Create a new Azure Function using Azure.Data.Table
4. Create a new logic apps
5. Call the Function from logic apps
6. Run and it fails
7. 

### Screenshots or Videos

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/b818972c-d04d-48fe-9491-f19e1852f2c7">

**Comment by Andrew-Lahikainen** [comment]
https://github.com/Azure/logicapps/issues/1146
