### ISSUE TITLE
multiple emails were sent

### ISSUE THREAD

**Issue by fmrib00** [Azure/logicapps#1192]
### Describe the Bug with repro steps 

go to 3qprint-email -> Run History

![image](<https://github.com/user-attachments/assets/adfe96c0-599d-4d47-a889-66b4dfb9fbe0>)

This run took 2 hours and sent the same email about 20 times! I can't find anything useful in the log to explain this. Can you please help? Thanks!

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Linux

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment]
transferring to backend as this is a runtime issue
