### ISSUE TITLE
Support for building custom connectors

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#120]
Support for building custom connectors which can be used locally in addition to the official ones.

**Comment by rohithah** [comment]
This is indeed one of the extensibilities we are planning to add. One model we are looking at is enabling users add a function extension where they can provide the implementation of the custom connector

**Comment by tomkerkhove** [comment]
What would that look like then? Ideally we can run those connectors in the same cluster as well, but as part of the logic apps editor it looks like an official action (so not a function call nor HTTP).

**Comment by rohithah** [comment]
As you may have noticed, there are 3 new connectors under built-in tab and they all are running in the same process as the core engine and connect to the end service directly unlike the cloud connectors where the connector runs as a separate service.

We do plan to expose this as an extensibility point where developers can implement their own connectors and plug them in to the workflow authoring experience as well as runtime. The extension primarily consists to two parts
1. Operation Description: extension will describe the operations being performed using a metadata language similar to open api that the Logic App designer will use to render the connector operations
2. Operation Implementation: implementation of the operations described in 1 

![image](https://user-images.githubusercontent.com/3781206/84534420-b897fc80-ac9e-11ea-8ab0-f5a023b2ec22.png)

**Comment by hajekj** [comment]
Amazing! So it will be possible to implement the connectors with code?

What about OpenAPI definitions for on-prem only REST APIs? Recently, I had an on-prem use case, where I had an API, inaccessible from the outside and had to use OAuth2 for authentication. I think this is one of the very common "edge" scenarios which would be great to address.

**Comment by tomkerkhove** [comment]
Good to hear, I hope we can also run them as a separate process and not as part of the same container? This would allow us to scale the connector separately.

**Comment by bydynamics** [comment]
Would love to see custom connectors based on openapi spec return to LAP!

**Comment by bydynamics** [comment]
Any word on the return of custom connectors in Logic Apps preview for onprem scenarios?

**Comment by bydynamics** [comment]
any updates?

**Comment by mirzaciri** [comment]
Any update?

**Comment by bydynamics** [comment]
bump. 18 months have passed. Please dev team respond to this question. Regards!

**Comment by tomkerkhove** [comment]
You can already achieve this today: https://techcommunity.microsoft.com/t5/integrations-on-azure-blog/azure-logic-apps-running-anywhere-built-in-connector/ba-p/1921272

**Comment by bydynamics** [comment]
> You can already achieve this today: https://techcommunity.microsoft.com/t5/integrations-on-azure-blog/azure-logic-apps-running-anywhere-built-in-connector/ba-p/1921272

Thanks Tom. Looked at that, but we are looking for the comfort of just importing a swagger file once and use this connector (and connection) many times just like with the v1 Logic Apps custom connectors. Any comments on this form product owners or devs?

**Comment by bydynamics** [comment]
https://stackoverflow.com/questions/69324490/custom-connector-not-found-in-azure-logic-appstandard

Currently we don’t support invoking the customer connector from Logic App standard. This is something product team are planning to support but no ETA yet.
