### ISSUE TITLE
How to determine master key for workflow in container?

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#121]
Based on the wiki we can run our workflows hosted as a docker container as following:

> The callback url for request triggers can be obtained by making the following request
POST /runtime/webhooks/flow/api/management/workflows/{workflowName}/triggers/{triggerName}/ listCallbackUrl?api-version=2019-10-01-edge-preview&code=<MASTER_KEY>

But how do we know what the master key is?

**Comment by MattFarm** [comment]
Thanks Tom - i've added details to the wiki page, you can also see the comment here: https://github.com/Azure/azure-functions-docker/issues/84

**Comment by MattFarm** [comment]
Will close for now, but please reopen if this doesn't work.
