### ISSUE TITLE
Error in logic app adding KeyValuePairs with new designer

### ISSUE THREAD

**Issue by corredma** [Azure/logicapps#1239]
### Describe the Bug with repro steps 

1. Create Logic App 
2. Add box for Analyze Document for prebuilt or custom models 
3. Add optional and premium features 
4. Add KeyValuePairs value 
5. With new designer you receive an error (see image attached). But with old designer is saved fine. 
6. Then if you enter ["KeyValuePairs"] logic app is saved successfully but you get an error when Logic App is executed (see image attached too) 

So please, let us know how we can get KeyValuePairs working with new designer.

 Or let us know if it is possible to use old designer and how to do it. In my team 2 of us have the new designer (without being able to change it to old one) and other 2 team members have the old designer.

Thanks,

 BR.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/bfe0fa61-a817-47de-8440-f851ef57488e>)

![Image](<https://github.com/user-attachments/assets/feac17e1-5146-4757-ab82-2c1aebb2597e>)

![Image](<https://github.com/user-attachments/assets/ee0fd32d-dd11-4291-88ac-85312955d7ca>)

### Browser

Edge

### Additional context

*No response*

**Comment by rllyy97** [comment]
Discussed with Milin and this does appear to be a backend issue.  We saw no outgoing requests related to the actions from my repro, so something in the backend is catching this and returning the error we see in UX.

**Comment by codyc1515** [comment]
Duplicate of https://github.com/Azure/logicapps/issues/1202

**Comment by corredma** [comment]
Thanks a lot! I could not find the duplicate before and I create a new one but it helped a lot.

Thanks again,
BR.
