### ISSUE TITLE
Workflow design time could not be started. 

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#126]
I have set up the development environment to locally build logic apps on function runtime. When I try to open the workflow file in designer, I get an error. Please see below screenshots

![image](https://user-images.githubusercontent.com/4720931/84374843-8ae78080-abd6-11ea-88b2-95d2871e0851.png)

![image](https://user-images.githubusercontent.com/4720931/84374850-8de27100-abd6-11ea-8d36-ddc6eb881ce7.png)

I am not sure if I am missing any component installation. Appreciate your help.

**Comment by tomkerkhove** [comment]
I had the same issue but it failed because Storage emulator was not running; maybe that's your issue?

**Comment by CarloGarcia** [comment]
Yip, I had the same thing at it was fixed when I started the storage emulator (I had only initialised it initially)

**Comment by shankarmaha** [comment]
Thanks @tomkerkhove and @CarloGarcia . I started the emulator and can now see the workflow.

**Comment by amirjalali65** [comment]
How should someone fix this issue on Mac os? I tried installing Azurite via VS code. I started Azurite Blob Service and Azurite Queue Service, but the issue persists.
