### ISSUE TITLE
Standard - Cannot set Custom tracking ID from service bus message correlationId in IN-APP trigger "When messages are available in a topic subscription (peek-lock)"

### ISSUE THREAD

**Issue by MrRosendahl** [Azure/logicapps#1265]
### Describe the Bug

We've been using service bus messages for a couple of years now, and we've been logging the previous CorrelationId (capital C) from the service bus message successfully using the **non** in-app topic subscription peek-lock triggers by setting the custom tracking id using checks and finally outputting the 

`triggerOutputs().body?['CorrelationId']`.

I've tried setting Custom tracking ID from the correlationId with these two different values (the correlation starts with lower case c in the In-app triggers)

- `@{triggerBody()?['correlationId']}` 
- `@{triggerOutputs().body?['correlationId']}` 

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

**Prerequisites**: Managed Identity authentication is setup for the logic app to the service bus.

**Steps to reproduce**

 In the Azure portal:

1. Create a workflow with a In-app trigger *When messages are available in a topic subscription (peek-lock)* 
2. Select the topic and subscription 
3. Set Maximum message batch size to 3 
4. Enable split on (defaults to `Array @(triggerOutputs)()?['body']` ) 
5. Concurrency control On, Degree of parallelism = 1 
6. Maximum waiting runs = 10 
7. Add a Custom tracking ID to fetch a correlationId from a service bus message
8. Send a message with a correlationId to the subscription
9. ...This step won't work since there is no run... but if it did: Open the run and see Client tracking ID on the trigger 

**Expected result**

- Trigger history added 
- Run history added 
- When viewing the Outputs on the trigger the Client tracking ID trigger should be showing the correlationId from the service bus message. 

**Actual result**

- No trigger history added. 
- No run history added. 
- No trigger output exists since there is no run. Delivery Count is incremented in the service bus subscription and finally the message goes to the dlq. 

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose_LogEventIn": {
                "type": "Compose",
                "inputs": {
                    "correlationId": "@triggerBody()?['correlationId']",
                    "body": "@triggerBody()"
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_messages_are_available_in_a_topic_subscription_(peek-lock)": {
                "type": "ServiceProvider",
                "description": "tada",
                "inputs": {
                    "parameters": {
                        "topicName": "TheTopic",
                        "subscriptionName": "TheSubscription",
                        "maxMessageBatchSize": 3
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "serviceBus",
                        "operationId": "peekLockTopicMessagesV2",
                        "serviceProviderId": "/serviceProviders/serviceBus"
                    }
                },
                "correlation": {
                    "clientTrackingId": "@{triggerOutputs().body?['correlationId']}"
                },
                "runtimeConfiguration": {
                    "concurrency": {
                        "runs": 1
                    }
                },
                "splitOn": "@triggerOutputs()?['body']"
            }
        }
    },
    "kind": "Stateful"
}
```

### Additional context

Example of the output from the trigger when a message is received (without trying to capture the correlation in the trigger):
```json
{
  "headers": null,
  "body": {
      "contentData": {
          "YourJsonPaylodFromServiceBus": {
            "Comment": "The correlationId from this service bus message should be used as correlation in the trigger"
          }
      },
      "contentType": "application/json",
      "userProperties": {},
      "messageId": "17269fbe2a2c4539bb9c0b6c9161af4b",
      "label": "some-label",
      "scheduledEnqueueTimeUtc": "1/1/0001 12:00:00 AM",
      "correlationId": "6953595a-1737-4b6d-b767-856da9827f6b",
      "timeToLive": "10675199.02:48:05.4775807",
      "deliveryCount": 2,
      "enqueuedSequenceNumber": 155,
      "enqueuedTimeUtc": "2024-12-12T08:15:11.658Z",
      "lockedUntilUtc": "2024-12-12T08:25:11.608Z",
      "lockToken": "afbd0afa-f979-4354-b1dd-3d61191fdc00",
      "sequenceNumber": 79
  }
}
```

**Adding the correlation clientTrackingId capturing in code view instead of in designer does not fix the issue.**

**_I also created a LogicAppUX issue not knowing if this is a UX or logic app issue:_** https://github.com/Azure/LogicAppsUX/issues/6247

**Comment by MrRosendahl** [comment]
The solution is to set the correlation in the splitOnConfiguration:

**This works**
```json
"splitOnConfiguration": {
        "correlation": {
            "clientTrackingId": "@{if(equals(string(triggerBody()),''), guid(), coalesce(triggerOutputs().body?['correlationId'], guid()))}"
        }
    }
```

This does not work
```json
"correlation": {
    "clientTrackingId": "@{if(equals(string(triggerBody()),''), guid(), coalesce(triggerOutputs().body?['correlationId'], guid()))}"
}
```

**Comment by karthikeyantc** [comment]
@MrRosendahl Would it be possible to use the same in consumption model? Also is there any approach for the same with trigger "when there are messages in a queue" storage queue trigger.
