### ISSUE TITLE
Add support for processing arrays / multiple items

### ISSUE THREAD

**Issue by EldertGrootenboer** [Azure/logicapps#127]
Currently there is no For Each and Do Until actions, please add these.
Also, as we are running these on our own infrastructure, it would be good if the restrictions on concurrent items was lifted / increased heavily.
Still have the option on the action to set a restricted concurrency, but don't throttle by default.
This combined with the stateless option would allow us to process a large amount of items quickly.

**Comment by hajekj** [comment]
I can use both For Each and Do Until there, however I agree that the limits should be rised or that there should be some easy way to manipulate them.

**Comment by EldertGrootenboer** [comment]
So I think you can use For Each and Do Until if you enable connectors from Azure, but not when just using local connectors? In this case I should rephrase my issue, saying I would like these actions to be available local as well, and lift the restrictions.

![image](https://user-images.githubusercontent.com/19503614/84406590-07478700-ac0a-11ea-98c6-9724117556df.png)

**Comment by hajekj** [comment]
I don't have Azure Connectors enabled... That is weird.

![image](https://user-images.githubusercontent.com/8337913/84407658-6b1e7f80-ac0b-11ea-88bf-c2798583e424.png)

This is the sample definition I tried it on (see what happens if you paste it in):
```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Parse_JSON": {
                "type": "ParseJson",
                "inputs": {
                    "content": [
                        "test1",
                        "test2",
                        "test3",
                        "test4"
                    ],
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "runAfter": {}
            },
            "For_each": {
                "type": "Foreach",
                "foreach": "@body('Parse_JSON')",
                "actions": {
                    "Set_variable": {
                        "type": "SetVariable",
                        "inputs": {
                            "name": "test",
                            "value": "@{items('For_each')}"
                        },
                        "runAfter": {}
                    }
                },
                "runAfter": {
                    "Initialize_variable": [
                        "Succeeded"
                    ]
                },
                "runtimeConfiguration": {
                    "concurrency": {
                        "repetitions": 1
                    }
                }
            },
            "Initialize_variable": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "test",
                            "type": "string"
                        }
                    ]
                },
                "runAfter": {
                    "Parse_JSON": [
                        "Succeeded"
                    ]
                }
            },
            "Response": {
                "type": "Response",
                "kind": "http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@variables('test')"
                },
                "runAfter": {
                    "For_each": [
                        "Succeeded"
                    ]
                }
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "schema": {}
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```

**Comment by tomkerkhove** [comment]
I see it as well

**Comment by hajekj** [comment]
Okay, I found it. When you use Staless workflow, it doesn't have the loops.

**Comment by EldertGrootenboer** [comment]
Ah, that would explain it then! Would be good to have them there as well, as having the combination of high concurrency and lowered latency would open up some interesting scenarios.

Cheers,
Eldert Grootenboer

**Comment by tomkerkhove** [comment]
Question is, should it since it's stateless? What if that means you have to have the "state" on a queue instead?

Brings me to #128 wondering what the effective difference is because if you have a for each and every action takes a while, should it persist state to track that or not? I can see this being a discussion frankly.

**Comment by EldertGrootenboer** [comment]
Would be a good discussion indeed. Personally I think it would still make sense to have these mechanisms in a stateless scenario, but would be good to know more about the reasoning not to include it currently.

**Comment by rohithah** [comment]
we are currently working on enabling this and should be able to get a revision with this support out soon.

**Comment by rohithah** [comment]
we have enabled both foreach and do-until control-flow actions for stateless workflows with the public preview
