### ISSUE TITLE
Ability to access Environment Variables

### ISSUE THREAD

**Issue by hajekj** [Azure/logicapps#131]
In regular Logic Apps you can have parameters. It would be great if they were supported here (tried it, but they seem to be removed from the definition upon save from editor).

And actually, I would love to be able to access environment variables - because Functions / App Service can fill it out from Key Vault as well, so it would really useful for dynamic configuration.

**Comment by rohithah** [comment]
This has indeed been added and you can use @apSetting('settingName'). Making this available in the expression editor is not yet done though.

**Comment by alfred-madl** [comment]
Can it read a local.settings.json when executing / testing locally ? No app config available there ;-)

Any chance for a function.settings.json or in this case maybe a "workflow.settings.json" for each workflow directory and reading it in the Logic App Workflow ?

**Comment by scale-tone** [comment]
> This has indeed been added and you can use @apSetting('settingName'). Making this available in the expression editor is not yet done though.

Yes. Except that it is not `@apSetting`, but `@appSetting`. 

@rohithah , I really wonder where to find documentation on this thing.
