### ISSUE TITLE
Are integration accounts going to run anywhere as well?

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#132]
Are integration accounts going to run anywhere as well?

**Comment by MattFarm** [comment]
Adding @divyaswarnkar - can you explain the case where the Integration Account runs anywhere as opposed to connecting to it from the cloud? Is this for isolated scenarios?

**Comment by tomkerkhove** [comment]
Yes, isolated & low-latency scenarios

**Comment by divyaswarnkar** [comment]
This is planned, we are still figuring out the details though on how we provide EDI/XML capabilities.

**Comment by tomkerkhove** [comment]
Great to hear!
