### ISSUE TITLE
Provide discovery API

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#134]
Provide discovery API that shows you all available workflows to improve discoverability. This would be super helpful for onboarding new people.

Note - Should be secured ofcourse

**Comment by MattFarm** [comment]
Can you elaborate on the use case here Tom - is this a different API to something we have in the public  service API, or the same?

**Comment by tomkerkhove** [comment]
I don't know if this is supported in cloud, actually don't think so, but think OpenAPI (UI) for Logic App apps.

Now you can ship multiple workflows in one app so would help with discoverabilty since you don't see seperate apps like in the portal - You really need to know what's part of the package.

Think an Orders app - Contains Create Order, Get Order and List Orders. 

Does this explain it a bit better?

**Comment by MattFarm** [comment]
So something like the APIM developer portal? Or more an api that searches based on keyword? Or both?

**Comment by tomkerkhove** [comment]
Just a way to see which workflows I can trigger, no specific details but a "list workflow" API should be enough

**Comment by rohithah** [comment]
we do have most of the APIs (both control plane and data plane) from the multitenant service available against the workflow-app host and that's what we use to list the workflows under a workflow-app in the portal (public preview) - is that what you are thinking? We still working on the documenting all the APIs (but you can look at t).

**Comment by tomkerkhove** [comment]
Yes that would definitely be what I'm looking for happy to have a look at those docs when they are available!
