### ISSUE TITLE
Provide health endpoint

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#135]
Provide health endpoint so that we can probe it to determine if the runtime is still up and running, can be used for Kubernetes for example.

**Comment by MattFarm** [comment]
Interesting idea. Tagging @laveeshb and @rohithah - this will be something we consider in our planning for next semester.

**Comment by tomkerkhove** [comment]
Thanks! This is pretty important for running/scaling on Kubernetes actually.

**Comment by MattFarm** [comment]
Understand, we're looking at this area - so bear with us for now.

**Comment by tomkerkhove** [comment]
Good to hear, thanks!
