### ISSUE TITLE
Azure Triggers

### ISSUE THREAD

**Issue by hajekj** [Azure/logicapps#136]
Right now, we can make use of Azure connector actions, would it also be possible to make the triggers work? Some of the scenarios which I have in my mind are with CDS <> on-premise database integration scenarios where we are not allowed to deploy the on-premises data gateway or the performance via the gateway is slower than needed - especially when dealing with larger data amounts or large scale operations.

Since triggers are mostly webhooks, for local development, I could imagine Azure Service Bus Relay / ngrok or something similar, or just source the address to register the webhook against from some appsetting.

**Comment by MattFarm** [comment]
Nice feedback. We'll take a look.
