### ISSUE TITLE
Support for Azure Functions Proxies

### ISSUE THREAD

**Issue by hajekj** [Azure/logicapps#137]
Is there going to be some more easier way to setup the Workflows with Function Proxies? I think it would be really awesome for scenarios like described in the blog post:  https://hajekj.net/2020/06/01/using-logic-apps-to-build-simple-APIs/

The issue is, that right now, I need to do a lot of manual work to get it to work with proxies (callbackUrls) and also source-controlling becomes an issue with that. It would also allow us to get nice URLs for API methods created with workflows more easily.

**Comment by MattFarm** [comment]
Is there a specific reason why Function Proxies and not APIM?

**Comment by hajekj** [comment]
I have some smaller scenarios running on the edge on my mind. For example ingesting data from local IOT sensors and passing them to the cloud. Or eventually using it for the small things, which I think don't need to have APIM in front of them (in order to lower complexity).

**Comment by tomkerkhove** [comment]
Frankly I haven't seen much investment in Function Proxies, so I'm not sure if it's worth the effort or what it's future is but that's my personal gut feeling.

**Comment by WillEastbury** [comment]
Functions Proxies do appear to work for me locally if I add a proxies.json file in the following format :-

{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "proxy1": {
            "matchCondition": {
                "methods": [ "GET" ],
                "route": "/"
            },
            "backendUri": "http://localhost/api/Stateless1/triggers/manual/invoke/2?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=UzKFDSuUDnQNMfQhmzOAjjNnn6UoWYO6R-MHCA2oJiU"
        }
    }
}

To make them work in the deployed app you will need to add something like this to your csproj file as the default deployment will not copy the proxy.json file so it doesn't get published. 

    <None Update="proxies.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>

Let me just test this to make sure there is no oddness with the runtime :)

**Comment by WillEastbury** [comment]
Yep, all seems to work fine for me. What's the manual steps you are referring to? Having to go into the overview to get the URI's SAS Signature? 

@MattFarm It would be nice to be able to disable that SAS URI requirement when running in your own application host like functions, as you might want it to be public or it might be placed behind a proxy like APIM or / authenticated with App Service EasyAuth etc.

**Comment by hajekj** [comment]
I think the ability to remove the need for SAS signature would solve this. The workflows in Dapr (https://github.com/dapr/workflows/) seem to have the SAS authentication turned off and as I understand it's basically the Logic Apps runtime running in Dapr directly. So probably something similar would solve this.

I exactly have the scenario with EasyAuth on my mind, actually using it already with Functions Proxies and regular Logic Apps nowadays (just requires the step of getting the URL manually or via ARM when deploying).

**Comment by WillEastbury** [comment]
Yes, I just checked that EasyAuth works when running over the top of a function hosted Logic App, pleased to report that it works exactly as you would expect. 

So Function Proxy to rewrite root of Fn App to proxy the http logic app endpoint + EasyAuth enabled on the Fn App == Consumption-Based, AAD Authenticated Workflow Webservice (All in one ARM resource). 

That is incredibly simple to configure and quick to deploy.

**Comment by shailesh-agre** [comment]
Though you may get option to create SAS or no with EasyAuth enabled, portal experience will be broken. May not be able to see Logic Apps, runs etc.
