### ISSUE TITLE
Workflow design time could not be started

### ISSUE THREAD

**Issue by carstenplemm** [Azure/logicapps#138]
Getting error 'Workflow design time could not be started' from Azure Functions extension in VSCode when trying to open workflow.json in Designer. Followed private preview demo video, installed prerequisites (Function Core tools, VSIX, storage emulator, ...). Tried on 2 different machines. Is there any logfile to check for errors?

**Comment by carstenplemm** [comment]
Fixed: didn't initialize & start the Storage Emulator after installation.

**Comment by tomkerkhove** [comment]
I just had this issue with a running instance of the storage emulator, feel free to re-open.

**Comment by carstenplemm** [comment]
Hi Tom,
emulator needs to run and also needs to be initialized - did you do the latter as well?
Thanks,
Carsten

**Comment by tomkerkhove** [comment]
Yes I did, some days it works fine and others it doesn't; even with a running emulator.

**Comment by MattFarm** [comment]
Hi Tom, if you are getting this error with the emulator running we should dig deeper to see what's going on. Adding @laveeshb @rohithah

**Comment by andDev123** [comment]
Hi, Also got this issue, I think it's the version of the emulator that is causing this issue. I had version 5.6, removed it and installed the latest one 5.10 and the designer opened up :)

**Comment by rohithah** [comment]
thanks - I updated the wiki include a note about using the latest version.

**Comment by MattFarm** [comment]
I'll close, if you're still having an issue let us know.

**Comment by haitham-shaddad** [comment]
I had the same issue and the latest storage emulator was installed and started and I can connect to it from Azure Storage Explororer.
Turned out that after uninstalling the azure functions core-tools and installing it from the link in the wiki, it didn't register "%programfiles%\Microsoft\Azure Functions Core Tools" in PATH. Once I added that, the designer worked perfectly.
