### ISSUE TITLE
Support for properly modifying dictionaries

### ISSUE THREAD

**Issue by mariussm** [Azure/logicapps#139]
Very often when handling an amount of users, I need to store references in a dictionary, for being able to look up information later in the LogicApp. Dictionaries are supported in LogicApps, but there is no GOOD way to modify them, especially not in a foreach where parallellization becomes an issue because we need to use a temp variable and variable copying currently.

Currently, the only sad workaround for handling dictionaries that I have found is to:

a) Define variable "Dict" as {}
b) Define variable "Dict_TEMP" as {}

When adding a new key to the dictionary:
- set the variable "Dict_TEMP" to addProperty(variables('Dict'), 'KEY', 'VALUE)
- set the variable "Dict" to variables('Dict_TEMP')

First of all, this is messy, and second it does not work in a foreach scenario where you want the foreach to be concurrent.

Please add feature a proper step for this action :)

**Comment by MattFarm** [comment]
Thanks for the suggestion - would be useful to get more detailed info on the scenarios you use these for, size etc. How would you want/expect this to work in the designer?

**Comment by mariussm** [comment]
Today there is a "add value to array variable" method for variables, and essentially having a "add key to dictionary" method is what I want. Same with removing key from dictionary, and essential dictionary operations. Here are a few examples from the Identity Management world:

- Create a lookup table from user objectid to user object, where the lookup table is loaded once, and just used as a "local in-memory cache" not needing external lookups
- When parsing a list of objects, where the list may contain the object several times, but you only want to process each object once - store the ID of the object in a hashmap and check if it is already there

Having essential dictionary functionality would greatly reduce the need for adding "helper functions", through Azure Functions. Things I today need helper functions for when it comes to dictionaries:

- "Group by" - a.k.a an array of objects as input, and a dictionary indexed by a property as output
- User objectid to user object lookup table creation
- Working my way from appRoleAssignments (MS Graph concept) to related user objects (lookup by objectid)

The size of the dictionaries can surely be 10 000 objects in some circumstances, meaning they should not be copied and merged, but rather modified in place as an object.

**Comment by mariussm** [comment]
Really?
