### ISSUE TITLE
Custom Connectors in Azure Logic Apps that use API Key Authentication do not work at all

### ISSUE THREAD

**Issue by Cloudmersive** [Azure/logicapps#14]
Repro steps:

- Create a custom connector in Azure Logic Apps using Sagger JSON; here is an example we tried:

https://api.cloudmersive.com/validate/docs/v1/swagger

- Create an Azure Logic app and add a scheduler and then an instance of the custom connector for the above URL

Expected: Azure Logic Apps asks you to put in an API key

Observed: There is no way to actually set the API Key!  The docs say that when you create the connection it should ask for the API Key but it *does not* and there is no way to set it manually

This seems completely broken, please advise.

**Comment by grik001** [comment]
@Cloudmersive - Where is it stated in the documentation of LogicApps that and input for API Key is supplied?

The reason I am asking is because I am facing the same issue.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
