### ISSUE TITLE
Move wiki to Git repo so we can contribute

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#140]
Move wiki to Git repo so we can contribute doc proposals/fixes to ease the process.

I introduced this via https://github.com/Azure/logicapps/pull/122 which was reverted since a Wiki has a Git repo behind it; but unfortunately we cannot open PRs against it.

**Comment by rohithah** [comment]
closing this since we have moved all the documentations to docs.microsoft.com with the public preview release
