### ISSUE TITLE
Connection only available in portal

### ISSUE THREAD

**Issue by eloekset** [Azure/logicapps#141]
I'm trying to follow the getting started video, except I use Outlook.com to send email instead of Office 365. I don't have a connection, so I'm guided to create it in the portal, but I don't understand how to do that.

The button in the designer in VSCode is disabled, and when I deploy the application to Azure, it doesn't contain anything, since the connection error/warning prevents me from saving the workflow.json file. A bit too hard to get started. Even after googling and reading docs, I don't understand how to create the connection in the portal, when I'm not able to save and deploy the send mail action.

Some screenshots:
![image](https://user-images.githubusercontent.com/791721/85899449-60b0d800-b7fe-11ea-884a-ce4be8f33f4a.png)

This is what I'm able to deploy to Azure, since I'm prevented from saving the workflow. The designer in Azure Portal just displays spinning wheel forever.
![image](https://user-images.githubusercontent.com/791721/85899580-8b9b2c00-b7fe-11ea-9b65-2aae4a765fec.png)

**Comment by mikaelsand** [comment]
Since you have no Azure subscription enabled for exposing Azure connections, it cannot be created.
It was in the e-mail that was sent out:

> If you wish, you can also **enable Azure connectors** – to do so, reply to this email with the subscription id you would like to use to test the preview, (this is optional and not required to use the preview.

If they have not been enabled they cannot be used. I simply skipped that step.

**Comment by eloekset** [comment]
Thanks, I've tried that now. What connectors did you use, that didn't require activation on any subscription, @mikaelsand?

**Comment by mikaelsand** [comment]
> Thanks, I've tried that now. What connectors did you use, that didn't require activation on any subscription, @mikaelsand?

I have just used the Called Function. But I know that Service Bus and SQL server should work.

**Comment by rohithah** [comment]
this has been fixed in public preview
