### ISSUE TITLE
Logic Apps and Functions connections overview

### ISSUE THREAD

**Issue by mikaelsand** [Azure/logicapps#142]
Something that I have always wanted for Logic Apps is being able to show how different Logic Apps are connected to one another. Having a microservices architecture is a very good approach when building apps (and integrations) with Logic Apps.
I am looking at the Function - Integration page for inspiration as to how this would look. 

This overview approach is even more important if you are using (and reusing) Logic Apps _and_ Functions between applications.

![image](https://user-images.githubusercontent.com/20858407/85992826-bd2a1800-b9f5-11ea-8261-d0941d26cca7.png)

I think this "dream" is closer when both Logic Apps and Functions can emit information so this can be built dynamically.

**Comment by tomkerkhove** [comment]
Happy to give this a :+1:
