### ISSUE TITLE
Problems sending a message to Service Bus using the Built In connector

### ISSUE THREAD

**Issue by mikaelsand** [Azure/logicapps#143]
I am using the sample outlined in the video. I want to take the information that comes back from the Function and send it to a ServiceBus Queue. 
As usual I simply take the output of the function and put is as a body in the service bus connector action and also add application/json as content type. However: I get this strange error:

ServiceProviderActionFailed. Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JValue'.

I am fully aware that the problem might be me and not the connector code.

![image](https://user-images.githubusercontent.com/20858407/86240071-c99ea400-bba0-11ea-990d-becea1fa8516.png)

**Comment by rohithah** [comment]
this is because the content of property expect a base64encoded string of the byte array for the content and the body from the previous action is an object. for example you can return  "new JObject { x=<base64encodedstring>}" and then pass @body('function').x as the inputs to "content"

**Comment by mikaelsand** [comment]
Great! Thanks, I love when the fault is mine 😊 easier to fix.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________
