### ISSUE TITLE
Can't send parameters to a local function with WorkflowActionTrigger

### ISSUE THREAD

**Issue by haitham-shaddad** [Azure/logicapps#144]
I am using the action "Invoke a function in this function app" and when I click add new parameter button, it shows nothing in the list.

![image](https://user-images.githubusercontent.com/8037988/87365223-0020e980-c5b9-11ea-9f92-6025fa58176e.png)

Do I have to add something to the local function code to make it available in the workflow designer?

When I debugged this code, the parameters object was null. I need to be able to send a parameter from the workflow into this function.

```
    public static class WorkflowActionTrigger1
    {
        [FunctionName("WorkflowActionTrigger1")]
        public static JToken Run(
           [WorkflowActionTrigger] JToken parameters,
           ILogger log)
        {
            return new JObject { { "Message", "Hello from the workflow triggered function" } };
        }
    }
```

**Comment by rohithah** [comment]
you need to check the box "function parameters" before it will show up as a input parameter in the designer:

![image](https://user-images.githubusercontent.com/3781206/88114057-ee66b580-cb67-11ea-9036-49cb2028c1d0.png)

**Comment by haitham-shaddad** [comment]
Thanks @joechung-msft , I tried that and I can bind the parameters to dynamic content and I was able to see it in the WorkflowActionTrigger1 parameters.
