### ISSUE TITLE
Getting callback URL requires POST, instead of GET

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#145]
Getting callback URL requires POST, instead of GET which is counter-intuitive.

**Comment by joechung-msft** [comment]
Tom, I've forwarded the feedback to the rest of the team for review.

**Comment by joechung-msft** [comment]
A quick summary of why POST instead of GET is enable protection of the secret (callback URL) with RBAC permissions.

Verbatim response from engineering lead:

> Yes, this is how APIs are modelled in ARM to allow proper RBAC permissions. Listing secrets (listing keys of a storage account, listing connection string of a SB namespace, list call back url of the logic app) of the resource requires more than GET permissions as any user who has GET permissions on the resource shouldn’t be able to do that.
>
> With POST operation, user is performing an action on the resource and users who only has permissions to perform the actions can list the keys.
>
> What is the issue with the POST operation? Customer can also perform this action of listcallbackurls in ARM templates as well if they are looking for a way to get this in ARM templates.

**Comment by tomkerkhove** [comment]
Ok, thanks for sharing!

**Comment by SahinOzdemir** [comment]
> Getting callback URL requires POST, instead of GET which is counter-intuitive.

Do you have any directions on how to get the callback / workflow url? Struggling with this for 2 days now.
