### ISSUE TITLE
Function namespace - `Company.Function` appears instead of my specified namespace

### ISSUE THREAD

**Issue by ecfan** [Azure/logicapps#146]
While adding a new function to my project by selecting **Create Function**, I specify the name for the function and for the namespace.

However, the .cs file shows `Company.Function` as the namespace, not the name that I specified, which was "MyExampleFunctionNamespace":

![image](https://user-images.githubusercontent.com/13206671/89976040-3e431480-dc1c-11ea-864a-34c41a086ec6.png)

**Comment by rohithah** [comment]
closing this since we are revisiting the functions integration
