### ISSUE TITLE
Logic Apps in Functions - Actions doesn't timeout in 2 minutes

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#147]
**_NOTE: I don't see the below to be an issue. This is just an observation._** 

In the current Logic Apps world, each action will timeout in 2 minutes in the shared landscape and 4 mins in ISE. I created a sample logic app locally- I added a call to a local Azure function which had a sleep call for 3 minutes. Surprisingly the action didn't timeout. For adding long running capabilities in Logic App, I have used durable functions along with Http Webhook. If the local azure function could support long running, could we now directly use the functions instead of the former?  

![image](https://user-images.githubusercontent.com/4720931/90505647-e0965700-e14a-11ea-8bdf-faef257ec405.png)

**Comment by saroja-sattigeri** [comment]
In standard logic apps(single-tenant), timeout duration is 230 seconds( 3.9 minutes) and 'Response' action does timeout if overall run-duration is more than 230 seconds : https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-limits-and-config?tabs=azure-portal#timeout-duration

![image](https://user-images.githubusercontent.com/85295842/121379876-10288100-c962-11eb-8c34-3d4863a73c04.png)

![image](https://user-images.githubusercontent.com/85295842/121380370-6eedfa80-c962-11eb-841f-d05a137d2fd9.png)
