### ISSUE TITLE
"Invalid Connection" error when viewing Logic App in Azure portal

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#148]
I have a simple logic app which has a File System action (Azure managed connector). The Logic Apps is working locally. I am able to deploy the code to Azure portal. 

![image](https://user-images.githubusercontent.com/4720931/90509753-bc8a4400-e151-11ea-9c58-167a5c8c1150.png)

As you can see, the connections.json file has been uploaded correctly. I added the connection reference to application config. Later, I restarted the function app. But, when I opened the designer, I get the below error

![image](https://user-images.githubusercontent.com/4720931/90509945-0b37de00-e152-11ea-80f2-4122b0e7920c.png)

Everything seems to be in order, but not sure why it is throwing this error.

**Comment by tonytang-microsoft-com** [comment]
shankarmaha, this issue should be fixed now.
