### ISSUE TITLE
Logic apps on docker - High CPU usage 

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#149]
I have successfully deployed my logic app into a docker container. However, I see very high CPU usage on the docker instance

![image](https://user-images.githubusercontent.com/4720931/90538743-dd18c500-e176-11ea-83c6-1c561f3201cc.png)

**Comment by shankarmaha** [comment]
It's basically doing nothing. I just have a request and response actions in them

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@triggerBody()"
                },
                "runAfter": {}
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "schema": {}
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}

**Comment by shailesh-agre** [comment]
@shankarmaha are you trying to run it locally? In that case this may be related to https://github.com/Azure/logicapps/issues/193

**Comment by shailesh-agre** [comment]
Currently closing as related to 193
