### ISSUE TITLE
Creating a Custom Connector in Azure Logic Apps from Swagger JSON URL does not work at all

### ISSUE THREAD

**Issue by Cloudmersive** [Azure/logicapps#15]
1.  Create a custom connector in Azure Logic Apps

2.  Choose "Use an OpenAPI URL"

3.  Paste in this URL:

https://api.cloudmersive.com/validate/docs/v1/swagger

Expected: Works

Observed: "We weren't able to download the Swagger 2.0 metadata.  Please make sure the URL is publicly accessible."

Manually saving this file to a JSON and then manually uploading it works.  This seems pretty broken.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
