### ISSUE TITLE
Is it not possible to build Docker image using AzureDevOps pipeline?

### ISSUE THREAD

**Issue by sd-suresh** [Azure/logicapps#150]
Is it not possible to build the docker image using Azure DevOps pipeline?  

My docker file contains below statements:

FROM mcr.microsoft.com/azure-functions/dotnet:3.0.13614-appservice AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["*.csproj", ""]
RUN dotnet restore "./CurrentDateTime.Get.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "CurrentDateTime.Get.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CurrentDateTime.Get.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

I am getting error saying **NU1101: Unable to find package Microsoft.Azure.Workflows.WebJobs.Extension. No packages exist with this id in source(s): nuget.org**

Step 5/16 : WORKDIR /src
 ---> Running in f765e38a7242
Removing intermediate container f765e38a7242
 ---> 83c507c8805c
Step 6/16 : COPY ["*.csproj", ""]
 ---> fcad4198f490
Step 7/16 : RUN dotnet restore "./CurrentDateTime.Get.csproj"
 ---> Running in 24fae5b1a25e
  Determining projects to restore...
/src/CurrentDateTime.Get.csproj : error NU1101: Unable to find package Microsoft.Azure.Workflows.WebJobs.Extension. No packages exist with this id in source(s): nuget.org
  Failed to restore /src/CurrentDateTime.Get.csproj (in 4.54 sec).
The command '/bin/sh -c dotnet restore "./CurrentDateTime.Get.csproj"' returned a non-zero code: 1
##[error]The command '/bin/sh -c dotnet restore "./CurrentDateTime.Get.csproj"' returned a non-zero code: 1
##[error]/usr/bin/docker failed with return code: 1

**Comment by hajekj** [comment]
I suppose you need to add reference to the private Nuget repo to be able to get the extension. When you scaffold a new project, the Nuget.config is located in the root of the project.

**Comment by sd-suresh** [comment]
@hajekj 

I can reference from private Nuget repo, if I have any reusable component & package it as NuGet. But Microsoft.Azure.Workflows.WebJobs.Extension.dll is Microsoft library right, why you are suggesting to create a nuget package for that library?

**Comment by hajekj** [comment]
I am not suggesting to create a package, I am suggesting to use the private Nuget repository as part of the preview in order to get hands on your package. Without the Nuget.config present in your project, the restore action for Nuget only looks into public Nuget.org where the package hasn't been published yet.

**Comment by sd-suresh** [comment]
@hajekj 

Thanks for the clarifications. I updated my docker file to copy *.config file too and that fixed the issue in Azure DevOps Build process. 

Here is my multi stage build Docker file. I am setting the AzureWebJobsStorage ENV value in my Deployment file. 


FROM mcr.microsoft.com/azure-functions/dotnet:3.0.13614-appservice AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["*.csproj", ""]
COPY ["*.config", ""]
RUN dotnet restore "./CurrentDateTime.Get.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "CurrentDateTime.Get.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CurrentDateTime.Get.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
ENV WEBSITE_HOSTNAME=localhost
ENV AZURE_FUNCTIONS_ENVIRONMENT=Development
