### ISSUE TITLE
Workflow design time could not be started. (Mac OS users)

### ISSUE THREAD

**Issue by amirjalali65** [Azure/logicapps#152]
Hi, I know that this issue is related to Azure Storage Emulator not being installed or not being initialized. However, since Azure Storage Emulator is not supported on Mac OS and only alternative is Azurite, would you please provide resolutions on how this issue can be resolved using Azurite on Mac OS? 
I have installed Azurite on VS code, started the service and verified it was up and running on localhost and then tried to open workflow in designer, but the issue persisted.
Thanks.

**Comment by derek1ee** [comment]
As a workaround, you can create a storage account on Azure, and use its connection string in both `./local.settings.json` as well as `./workflow-designtime/local.settings.json`.

**Comment by lynnaloo** [comment]
@derek1ee this is a great work-around!
