### ISSUE TITLE
Logic App Preview - VS Code freezes when "Start Debugging" or "Run without Debugging" is clicked

### ISSUE THREAD

**Issue by scottxrobertson** [Azure/logicapps#153]
When following along to the video here:

https://github.com/Azure/logicapps/wiki/3.-Develop,-test,-and-deploy-a-workflow-app

I get to the step of "Start Debugging" which outputs what seems like the same text as the video, all the way up to:

> [25/08/2020 6:12:53 AM] Service started: serviceName='Microsoft-Azure-Workflows-Functions', name='v4.0.30319', value='(null)', version='(null)', message='Started the worker app with environment name 'Flow function extension', Number of cores: '12'. Memory: '96935936'.', subscriptionId='(null)', correlationId='(null)', principalOid='(null)', principalPuid='(null)', tenantId='(null)', organizationId='(null)', activityVector='(null)', realPuid='(null)', altSecId='(null)', additionalProperties='(null)'.
> [25/08/2020 6:12:53 AM] Host started (743ms)
> [25/08/2020 6:12:53 AM] Job host started
> Hosting environment: Production
> Content root path: C:\Code\LogicAppsV2\bin\Debug\netcoreapp3.1
> Now listening on: http://0.0.0.0:7071

But then VS code immediately freezes, and a popup appears:

![image](https://user-images.githubusercontent.com/53551506/91130333-d4803b80-e6ee-11ea-8d2b-6187cafbd629.png)

After waiting a few minutes, VS Code eventually popups up with:

![image](https://user-images.githubusercontent.com/53551506/91130365-e5c94800-e6ee-11ea-9726-d39cad78018a.png)

At which point I click "Reopen".

Note that the same thing happens if I click "Run without Debugging" instead.

Interestingly, if I type the command below in the terminal:

> func host start

Then the function/app starts and I can call it without any issues.

**Comment by foppenm** [comment]
Got the exact same problem any update on this?

**Comment by zhangadreedom** [comment]
Hello, @scottxrobertson May I know this you are still facing the same error? Our Product Team upgraded Logic App and make it more stable. Now it names Logic App(Standard), do you mind to follow the doc https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#set-up-visual-studio-code try again?

**Comment by zhangadreedom** [comment]
Hello, @scottxrobertson May I know this you are still facing the same error? Our Product Team upgraded Logic App and make it more stable. Now it names Logic App(Standard), do you mind to follow the doc https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#set-up-visual-studio-code try again?
