### ISSUE TITLE
Windows Design Time could not be started

### ISSUE THREAD

**Issue by Roshan456** [Azure/logicapps#154]
I am not able to open Logic Apps in desginer mode in Visual Studio Code.

I have followed the steps mentioned in the read me file.
Installed and initialize the correct storage emulator(5.10).

**Comment by rohithah** [comment]
can you share the logs from the outputs terminal of the VSCODE?

**Comment by Roshan456** [comment]
@rohithah I was able to solve this. The issue was with Azure Functions Runtime version and Azure Storage Emulator.
