### ISSUE TITLE
Run Logic app preview local on an alternative port

### ISSUE THREAD

**Issue by scleynen** [Azure/logicapps#155]
When I Try to run the Azure function project localy on another port then 7071, this is working fine but the "overview" screen of a workflow (LogicApp) isn't working anymore.

It seems like always localhost:7071 is used in the overview screen

**Comment by mbarqawi** [comment]
No way to change it right now, however you can use tools like [tcptrace](https://www.pocketsoap.com/tcptrace/ )
to forward the traffic from 7071 to the real port
