### ISSUE TITLE
Reuse signature when running Logic App Preview (Docker) with HTTP trigger

### ISSUE THREAD

**Issue by scleynen** [Azure/logicapps#156]
Everytime you start a new version of your Logic App Preview container image, a new "secret" is generated. So this means that everytime you need to go to the storage, get the Master Key and call a url to get the sig.

Isn't there a way to make this more transparent so that we can pass by a key fe to make it possible to use the same url again and again and use this one in fe APIM

**Comment by markharrison** [comment]
Further to this - how do I know what `{deployment-name}` is ... each time I spin up the docker container it takes a different sequence of digits?  Ideally would like this to be a fixed / known value that I can control for my container instance.

**Comment by markharrison** [comment]
ive worked out that I can control the first part of the deployment name  with a `-h` on the Docker Run command.
`docker run -e WEBSITE_HOSTNAME=localhost -p 8080:80 -h FRED  local/workflowcontainer`

Where is the second part `2137340777` coming from / can I control it to a known value .

![image](https://user-images.githubusercontent.com/5177824/98749938-aa1c5100-23b4-11eb-8439-040ce9674ee2.png)

**Comment by tomkerkhove** [comment]
Frankly, this is a big blocker @joechung-msft @divyaswarnkar @laveeshb

**Comment by rikroe** [comment]
It is possible to force this hostId by setting the environment variable `AzureFunctionsWebHost:hostid` (c.f. https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Config/ConfigurationSectionNames.cs#L14).

You will get a warning like below, but it will always take the content of this environment variable.
```
warn: Host.Startup[400]
      Host id explicitly set in configuration. This is not a recommended configuration and may lead to unexpected behavior.
```

**Comment by inuvano-labs** [comment]
The two environment variables that need to be set when running in docker are:

`WEBSITE_SITE_NAME` and `WEBSITE_HOSTNAME`

Set `WEBSITE_SITE_NAME` what you want the container name to be in azure-webjobs-secrets.
