### ISSUE TITLE
Show Logic Apps outside of Azure in Azure portal

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/logicapps#159]
Are there plans to show Logic Apps running outside of Azure in the Azure portal? This might be a good one to integrate with Azure Arc to follow the current Azure strategy.

As far as I know, this is not supported yet but sorry if I've missed this.

**Comment by tonytang-microsoft-com** [comment]
You are correct tomkerkhove. It's not supported yet. It's something we will explore in future. Thanks for your feedback.
