### ISSUE TITLE
VS Code Extension Logic Apps (Preview) Broken Links

### ISSUE THREAD

**Issue by PalmEmanuel** [Azure/logicapps#161]
When trying to leave feedback regarding another issue with the new VS Code extension for Logic Apps (Preview) I noticed that several links were broken and linked to the https://github.com/microsoft/vscode-azurefunctions-clone, such as the Repository link and the License link in the Details section.

This made it confusing and unclear on where to report feedback, and it would be great if it was fixed.

**Comment by tonytang-microsoft-com** [comment]
Thanks PalmEmanuel for the report. We've just published another release that contains the fix for this.

**Comment by vikash-anand** [comment]
This has been fixed in the latest extension release Logic App (Preview) v0.0.3.
