### ISSUE TITLE
VS Code author errors on api connections

### ISSUE THREAD

**Issue by swiftsolves-msft** [Azure/logicapps#162]
Testing VS Code authoring experience for Logic App preview, getting an error anytime I need to authenticate Oauth or other auth methods with Microsoft and Azure connectors. Please see below. Can you advise on how to troubleshoot or fix this, I would like to test end to end locally ?

![image](https://user-images.githubusercontent.com/30509195/93964815-95192f00-fd2e-11ea-9066-fd87c4772e37.png)

![image](https://user-images.githubusercontent.com/30509195/93964831-9fd3c400-fd2e-11ea-8d8c-cc101d533324.png)

**Comment by rohithah** [comment]
what regions are you trying to create the connections in? only west central us and west us2 are supported currently and we are in the process of making other regions available.

https://github.com/Azure/logicapps/blob/master/articles/logic-apps-public-preview-known-issues.md

**Comment by swiftsolves-msft** [comment]
Many Thanks the rg was east us, will redeploy rg and project in west us2 and test.

**Comment by swiftsolves-msft** [comment]
@rohithah thanks West US2 did the trick. One other thing I noticed in a stateful logic app in local debug mode where trigger is schedule, a timer trigger does not seem to fire for local testing - 

![image](https://user-images.githubusercontent.com/30509195/93969861-ddd6e500-fd3a-11ea-8d5f-dca15b254a34.png)

![image](https://user-images.githubusercontent.com/30509195/93969883-e7f8e380-fd3a-11ea-9d3d-b3745f875ae4.png)

**Comment by rohithah** [comment]
would you be able to try enabling "debug" level tracing and share the logs?

![image](https://user-images.githubusercontent.com/3781206/94088110-78c7d180-fdc4-11ea-8191-503d92e1e738.png)

**Comment by rarayudu** [comment]
The changes for connections are deployed to all regions. You should be able to use connections in all regions now

**Comment by devin-simoneaux** [comment]
@swiftsolves-msft do you have any further questions on this thread?

**Comment by narenderreddy-satty** [comment]
@swiftsolves-msft We have not heard from you and was wondering if you still need further assistance from us?

**Comment by narenderreddy-satty** [comment]
Since the fix was deployed, I will go ahead and close the issue for now. If you still need assistance, please feel free to drop a message.
