### ISSUE TITLE
Can't delete actions in the new logic app designer

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#164]
According to the documentation, actions can be deleted by pressing the delete button. 

![image](https://user-images.githubusercontent.com/4720931/94139347-6780d280-fe61-11ea-8918-d9d7204657aa.png)

However, I can't see the ellipses button in this case

![image](https://user-images.githubusercontent.com/4720931/94139454-9303bd00-fe61-11ea-82d0-8bc5fe44aac1.png)

Or in this case, there is an ellipses button, but no delete option

![image](https://user-images.githubusercontent.com/4720931/94139514-a878e700-fe61-11ea-87cf-ed4fa81720d5.png)

**Comment by hajekj** [comment]
You hit the same thing, it's a UX.. there's another 3 dots in top right corner, took me a while to figure it out in this new design.

![image](https://user-images.githubusercontent.com/8337913/94139859-a2d3cf00-fe6a-11ea-8515-1535136993f2.png)

**Comment by shankarmaha** [comment]
Yeah, got it. I had re-size the window to see the dots. Thanks mate
