### ISSUE TITLE
Error while creating an Azure connection from VS Code

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#166]
I am trying to add the Outlook connector and am getting the below error

![image](https://user-images.githubusercontent.com/4720931/94179188-11795280-fe94-11ea-95cf-d91b5236ae85.png)

Not sure what I am missing here.

**Comment by rarayudu** [comment]
The changes are being deployed to all regions. ETA for all regions is end of this week (9/26).
The regions where this is currently supported are documented here - https://github.com/Azure/logicapps/blob/master/articles/logic-apps-public-preview-known-issues.md#available-regions

**Comment by rarayudu** [comment]
The changes are deployed to all regions. You should be able to use connections in all regions now

**Comment by devin-simoneaux** [comment]
Just wanted to follow up here @shankarmaha... Are you still seeing this error?

**Comment by shankarmaha** [comment]
@devin-simoneaux Just tested this again in UK South and it works.
