### ISSUE TITLE
National Cloud Support for the VS code extension

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/logicapps#168]
As more customers migrate to the national clouds supporting local development would be extremely helpful. 

Currently when logging on with an Azure Gov subscription no subs are found, most likely because the proper management endpoints are not present.
![image](https://user-images.githubusercontent.com/18233035/94229633-12c77100-fece-11ea-859c-b0e18066748e.png)

**Comment by tonytang-microsoft-com** [comment]
jcbrooks92, thanks for trying out our Logic Apps (preview) offering. It is currently in preview and we are focusing on public cloud first.
