### ISSUE TITLE
Where can I find the signature when executing the Logic App locally?

### ISSUE THREAD

**Issue by mikaelsand** [Azure/logicapps#169]
I am able to start the Logic App. I get the address in the output window: http://localhost:7071/api/INT001/triggers/manual/invoke.
Then I get asked for the version, ok I find it by faking another version, but then I get this error.

`
{
    "error": {
        "code": "AuthorizationFailed",
        "message": "Required parameters for shared access URL are permissions ('sp'), version ('sv'), and signature ('sig')."
    }
}
`
If I look in the designer it says that I cannot get the URL because I am running locally. Where can I find the params I need to execute the Logic App locally?

**Comment by tomkerkhove** [comment]
During preview it was stored in an Azure table

**Comment by tomkerkhove** [comment]
Seehttps://github.com/Azure/logicapps/issues/123#issuecomment-644137876

**Comment by rarayudu** [comment]
If you are running from VS Code, you can open overview of the workflow and you can find the trigger url there.

![image](https://user-images.githubusercontent.com/11560406/94252723-30e69e80-fed9-11ea-9fce-eff51c44ab13.png)

**Comment by mikaelsand** [comment]
This is my Overview:
![image](https://user-images.githubusercontent.com/20858407/94258390-0faf9d80-ff2d-11ea-90f4-9452a66ab61c.png)

So I started my local environment by doing an F5:
![image](https://user-images.githubusercontent.com/20858407/94258503-3ec60f00-ff2d-11ea-8140-f5f5d4d351a7.png)
And this is a very empty result.

**Comment by mikaelsand** [comment]
> See [#123 (comment)](https://github.com/Azure/logicapps/issues/123#issuecomment-644137876)

Thanks. I read it and I just got dizzy from reading all that text.
This should not be hard, I feel.

**Comment by tomkerkhove** [comment]
Jup but maybe it got easier in public preview

**Comment by rohithah** [comment]
can you make sure your workflow is running locally? (either F5 from VS code or do a "func start" from the project folder)?

**Comment by lynnaloo** [comment]
I'm getting this same "failed to fetch" error in the Overview and when I deploy, it does not deploy the workflow even though it will run locally.

**Comment by rasavant-ms** [comment]
Same thing.

**Repro Steps:**
After creating workflow with HTTP trigger, click `Overview` option on the workflow.json file.
The complete URL to be used to send in an HTTP request is not visible. 
![image](https://user-images.githubusercontent.com/6465709/98164530-4a481680-1e99-11eb-8799-3b7d77190f6c.png)

**System Info:**
Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
Windows 10.0.19042 Build 19042
VSCode:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mikaelsand** [comment]
Hey guys? Any progress on this. I just downloaded the latest version. I am running the Logic App and this is my design surface and overview. Where can I _please_ find the signature for calling the Logic App Locally? Where am I _supposed_ to find it? I can't even find that anywhere? Or am I just supposed to deploy it to Azure during this part of the preview?
![image](https://user-images.githubusercontent.com/20858407/98566979-b4a0f280-22af-11eb-8e8d-9c95a2ab1dc1.png)
![image](https://user-images.githubusercontent.com/20858407/98567008-be2a5a80-22af-11eb-8e75-d6bede43398a.png)

**Comment by rohithah** [comment]
can you make sure you follow the below steps:
1. Run the app (press F5) and make sure you have success logs in the terminal window (you will see errors if the workflow failed to load):
![image](https://user-images.githubusercontent.com/3781206/98571288-41748d80-2269-11eb-8599-c4715a073575.png)

2. Select the workflow.json, right click and select "overview"

![image](https://user-images.githubusercontent.com/3781206/98571494-6c5ee180-2269-11eb-961e-a0a227f86265.png)

3. #2 should open a tab and that will show you the overview with the callback url:

![image](https://user-images.githubusercontent.com/3781206/98571618-931d1800-2269-11eb-88fc-3862457f414a.png)

**Comment by StefanPuntNL** [comment]
Also don't forget to start the Storage Emulator if you have set "AzureWebJobsStorage": "UseDevelopmentStorage=true" in local.setting.json

**Comment by mikaelsand** [comment]
Great! Now it works! I think that I opened the Overview window while the app was not running, and after I started the function the "Refresh" did not work ... or something.

Honestly: I think do not know the exact difference, but now it works. Thank you :-)

**Comment by ahmedsza** [comment]
I am having the same issues and none of above works :-(
