### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by JSaaS** [Azure/logicapps#170]
When starting up a new Logic App in Designer mode, I cant get hold of a list of trgger actions:

![image](https://user-images.githubusercontent.com/14349335/94276918-2663ed80-ff49-11ea-9962-a4e9b9e2b98c.png)
 I can't search for any of the builtin triggers/actions, only way to get a result is through the "Azure" tab.

**Comment by JSaaS** [comment]
Found this in the output window in VS Code:

Running command: "func host start --port 8000"...
'func' is not recognized as an internal or external command,
operable program or batch file.

Something is not installed. What dependencies are there?

**Comment by rohithah** [comment]
looks like you are missing the functions core tools - you can use the MSI from here to install;
https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2931

**Comment by JSaaS** [comment]
Installed it, but now the design-time features does not start at all...
Where can I see dependencies?

**Comment by JSaaS** [comment]
After uninstall, restart, install, restart sequence of VSCode I got this error in the output:

There was an error performing a read operation on the Blob Storage Secret Repository. Please ensure the 'AzureWebJobsStorage' connection string is valid.

Still the error "Failed to fetch" in the GUI...

**Comment by rohithah** [comment]
do you have the storage emulator installed and running
https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#storage-requirements

**Comment by pkarda** [comment]
Hello @rohithah,

I have the same problem. I've tried to reinstall function core tools, reinitialize the AzureStorageEmulator but still getting "Failed to fetch" for built-in connectors (it works OK for the Azure connectors). I don't have any errors in VSCode output.

![image](https://user-images.githubusercontent.com/12649718/94901731-5d7d5600-0497-11eb-9bbb-26d068139803.png)

**Comment by pkarda** [comment]
Hello @rohithah, @tonytang-microsoft-com 

It works well now with **v0.0.4** Azure Logic Apps (Preiview) extension.

Thank!

**Comment by roeb** [comment]
Hello,

the same issue here with:

- Azure Functions Core Tools 3.0.2931
- Logic Apps Preview Plugin 0.0.4
- VSCode 1.50.1

@pkarda Did you only update to Logic Apps Preview v0.0.4 or change anything else? I use `"AzureWebJobsStorage": "UseDevelopmentStorage=true"`, but I have the same problem with an Azure Storage. 

Thanks!

**Comment by pkarda** [comment]
@roeb  You might try to reinitialize AzureStorageEmulator (clear -> init -> start) or eventually "Repair" installation of the emulator.

**Comment by mcollier** [comment]
I recently started getting the "Failed to fetch" error in the VS Code designer. I get it on my connectors, and when trying to add a new action.

- Azure Logic Apps (Standard) extension v1.0.0
- Windows Azure Storage Emulator 5.10.0.0
- Azure Functions Core Tools 3.0.3477
- VS Code 1.56.2

![image](https://user-images.githubusercontent.com/1142273/119918004-a063d080-bf35-11eb-9e73-c650d6eeeed4.png)

**Comment by craigofnz** [comment]
@mcollier - I have experienced the same issue for existing LogicApps, but not a new one. Comparison found new config key in `local.settings.json` that seems to resolve this when added to an existing project. Mileage may vary.

`"WORKFLOWS_MANAGEMENT_BASE_URI": "https://management.azure.com/"`

**Comment by adrianscs** [comment]
> @mcollier - I have experienced the same issue for existing LogicApps, but not a new one. Comparison found new config key in `local.settings.json` that seems to resolve this when added to an existing project. Mileage may vary.
> 
> `"WORKFLOWS_MANAGEMENT_BASE_URI": "https://management.azure.com/"`

Thanks a lot, this worked for me!

**Comment by HariAnkasala** [comment]
Is this issue resolved ..? if so what is the solution for it..?
