### ISSUE TITLE
Getting Unable to write to Workspace Settings because azureLogicAppsV2.projectLanguage is not a registered configuration. error while create new project

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure/logicapps#173]
Does this occur consistently? 
Repro steps:

1.Selected Stateful project type
2.Provided name of the wofkflow, hit enter and got error.

Action: azureLogicAppsV2.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureLogicAppsV2.projectLanguage is not a registered configuration.

Version: 0.0.2
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
D.reject workbench.desktop.main.js:5744:839
D.resolveAndValidate workbench.desktop.main.js:5747:741
D.doWriteConfiguration workbench.desktop.main.js:5742:70
Object.factory workbench.desktop.main.js:5741:789
u.consume workbench.desktop.main.js:131:309
file:/workbench.desktop.main.js:131:124
u.queue workbench.desktop.main.js:131:48
D.writeConfiguration workbench.desktop.main.js:5741:774
I.writeConfigurationValue workbench.desktop.main.js:5768:356
file:/workbench.desktop.main.js:5758:320
```

</details>

**Comment by tonytang-microsoft-com** [comment]
rahulvmarathe, how did you repro this?

I suspect it might be the below setting is missing from the settings.json.
  "azureLogicAppsV2.projectLanguage": "C#"

What is your settings.json file look like? below is mine.

{
  "azureLogicAppsV2.deploySubpath": "bin/Release/netcoreapp3.1/publish",
  "azureLogicAppsV2.projectLanguage": "C#",
  "azureLogicAppsV2.projectRuntime": "~3",
  "debug.internalConsoleOptions": "neverOpen",
  "azureLogicAppsV2.preDeployTask": "publish"
}

**Comment by johnjobs** [comment]
@rahulvmarathe Had a similar issue as you, just double check you have followed these steps: https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#set-up-visual-studio-code

My settings file now by default looks like what tonytang mentioned.

**Comment by tonytang-microsoft-com** [comment]
@johnjobs , did it steps you mentioned help you resolve the issue?

**Comment by johnjobs** [comment]
@tonytang-microsoft-com, Yes it did the only setting I changed was: Azure Logic Apps V2: Project Runtime to version 3.

**Comment by vikash-anand** [comment]
We have fixed the bug in our latest release. Please try out the Azure Logic Apps (Preview) extension version 0.0.3.
