### ISSUE TITLE
Error when creating new project

### ISSUE THREAD

**Issue by alfred-madl** [Azure/logicapps#174]
Does this occur consistently? Yes
Repro steps:
1. Logic Apps Preview - Create New Project
2.Select empty folder

Action: azureLogicAppsV2.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureLogicAppsV2.projectLanguage is not a registered configuration.

Version: 0.0.2
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
D.reject workbench.desktop.main.js:5744:839
D.resolveAndValidate workbench.desktop.main.js:5747:741
D.doWriteConfiguration workbench.desktop.main.js:5742:70
Object.factory workbench.desktop.main.js:5741:789
u.consume workbench.desktop.main.js:131:309
file:/workbench.desktop.main.js:131:124
u.queue workbench.desktop.main.js:131:48
D.writeConfiguration workbench.desktop.main.js:5741:774
I.writeConfigurationValue workbench.desktop.main.js:5768:356
file:/workbench.desktop.main.js:5758:320
```

</details>

**Comment by tonytang-microsoft-com** [comment]
Thanks @alfred-madl for your report. We are working on a fix and will try to release an update early next week.

**Comment by vikash-anand** [comment]
We have fixed the bug in our latest release. Please try out the Azure Logic Apps (Preview) extension version 0.0.3.

**Comment by alfred-madl** [comment]
Fix confirmed ;-) thanks.
