### ISSUE TITLE
Extension not enumerating Logic Apps in subscriptions at all

### ISSUE THREAD

**Issue by JSaaS** [Azure/logicapps#175]
I have three subscriptions in the list. None of them show any Logic Apps at all in this extension:

![image](https://user-images.githubusercontent.com/14349335/94343503-f2f09400-0018-11eb-969e-fa17dfc4b92a.png)

With the "normal" Logic Apps extension I can see the complete list:

![image](https://user-images.githubusercontent.com/14349335/94343540-26332300-0019-11eb-90a0-a156ef9a60e8.png)

No errors in the output at all.

/Joakim

**Comment by tonytang-microsoft-com** [comment]
JSaaS, the Logic Apps (Preview) is a new type of resource than the Logic Apps. We do plan to combine them in the future, but currently Logic Apps only show in the logic apps extension, and the Logic Apps (preview) only shows in logic apps (preview) extension. Seems that you don't have any logic apps (preview) deployed yet.

**Comment by NitashaV** [comment]
Closing this issue.
