### ISSUE TITLE
Error when trying to use Azure Connections

### ISSUE THREAD

**Issue by JasonBSteele** [Azure/logicapps#176]
I'm following the guide at https://docs.microsoft.com/en-gb/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code.
I selected the "Use connectors from Azure" option and created new RG in "West Central US".
When I selected the "azure" tab in the right hand panel of the designer I get the following error:

![image](https://user-images.githubusercontent.com/1202763/94374391-daa97380-0103-11eb-9695-43324b5727d4.png)

I have tried deleting the project and going through the guide again, but got the same result.

**Comment by NitashaV** [comment]
Thanks for reporting this issue @JasonBSteele . We identified the problem and are working to deploy a fix starting Monday PDT. We plan to start with West Central US.

**Comment by tonytang-microsoft-com** [comment]
We've updated the vsix and deployed the first to West Central US. Could you please download the latest vsix, create a new project and try again?

BTW, If you are still seeing this in your old project, you could try:
1.	Delete "WORKFLOWS_SUSCRIPTION_ID" from local.settings.json
2.	Before opening the designer,  choose "Use connectors from Azure" to config again.
