### ISSUE TITLE
Workflow design time could not be started - Maybe problem with Azurite on VSCode on macOS ?

### ISSUE THREAD

**Issue by alfred-madl** [Azure/logicapps#178]
7:38:57 AM: Running command: "func host start --port 8000"...
Azure Functions Core Tools (3.0.2912 Commit hash: bfcbbe48ed6fdacdf9b309261ecc8093df3b83f2)
Function Runtime Version: 3.0.14287.0
There was an error performing a read operation on the Blob Storage Secret Repository. Please ensure the 'AzureWebJobsStorage' connection string is valid.
A host error has occurred during startup operation 'f620cfa3-1f81-4955-b86f-a9b766fa5e80'.
Microsoft.Azure.WebJobs.Script.WebHost: Connection refused. System.Net.Http: Connection refused. System.Private.CoreLib: Connection refused.
Value cannot be null. (Parameter 'provider')
Application is shutting down...
7:43:19 AM: Running command: "func host start --port 8000"...
Azure Functions Core Tools (3.0.2912 Commit hash: bfcbbe48ed6fdacdf9b309261ecc8093df3b83f2)
Function Runtime Version: 3.0.14287.0
A host error has occurred during startup operation '12f619fe-781a-4659-93c4-d51236efdad9'.
Microsoft.WindowsAzure.ResourceStack: Connection refused. System.Net.Http: Connection refused. System.Private.CoreLib: Connection refused.
Value cannot be null. (Parameter 'provider')
Application is shutting down...

Error is shown after "long" time...some timeout ?

After pressing "View output"...designer appears but trigger selection shows "Failed to fetch" error...

Additional Info: Happens always
Environment: VSCode macOS
Logic Apps Plugin: 0.0.3

"AzureWebJobsStorage": "UseDevelopmentStorage=true", ...is set

Azurite is running...standard ports 10000 (Queue) and 10001 (Blobs)

**Comment by rarayudu** [comment]
This is one of the known issue that we are working on to fix with the next update.
Here are the list of known issues - https://github.com/Azure/logicapps/blob/master/articles/logic-apps-public-preview-known-issues.md#issues

**Comment by alfred-madl** [comment]
Thx !
