### ISSUE TITLE
Logic app with event grid trigger doesn't work

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#183]
I have created a Logic app with a event grid trigger. As this is a workflow of type "ApiConnectionWebhook", I understand that it won't work locally. I was able to successfully deploy the Logic App to Azure. However, I noticed several issues.

1. An event grid subscription was not added to the Event grid topic automatically. For e.g. when a cloud version of Logic app is deployed, an event grid subscription is automatically added. Please see below.

![image](https://user-images.githubusercontent.com/4720931/94789439-d19ef780-03cc-11eb-80de-d6762762f2bc.png)

2. I tried disabling the Logic app. I got a message that it got successfully disabled. But, the logic app is still enabled. 

![image](https://user-images.githubusercontent.com/4720931/94789235-93093d00-03cc-11eb-80a1-181dce239e10.png)

3. I went to the monitor option on the Developer blade and got the below error info

![image](https://user-images.githubusercontent.com/4720931/94789623-0ad76780-03cd-11eb-8131-6201544307c3.png)

4. With the cloud version of logic apps, I use the parameters and variables within ARM templates to parameterize the application. 
For e.g, I use the below in the cloud version of logic apps. 

![image](https://user-images.githubusercontent.com/4720931/94790170-d6b07680-03cd-11eb-9316-b3dcc2f6646e.png)

With the new logic apps version, I tried using @appsetting  and @concat, but the engine doesn't work. I would really appreciate if you could advise us on this, as this is very essential for CI/CD.

**Comment by rohithah** [comment]
web hook triggers are not supported yet, and we are working on adding that support in an upcoming iteration.

**Comment by shankarmaha** [comment]
Hi @rohithah @derek1ee ,

Yesterday Derek mentioned that the new public preview version supports Logic apps with Event grid trigger. 

I tried setting the below. 

 I have a Event grid connector as a trigger. I ran the Logic app. Set up NGROK to point to 7071. When I tried setting up a webhook subscription on the azure event grid topic, it failed setting up. Could you pls advise on how to set this up?
