### ISSUE TITLE
Logic app run locally doesn't work with Office 365 Outlook Trigger 'When a new email arrives V3'

### ISSUE THREAD

**Issue by Jimbwlah** [Azure/logicapps#184]
I've been trying to build a sample logic app that triggers on a new email arriving in my O365 inbox with a specific keyword in the subject line. 

Putting it together and running throws an error specific to the Outlook action -

Workflow Error: operationName='WorkflowDefinitionProvider.GetEntryPoint', message='Workflow trigger type 'ApiConnectionNotification of workflow 'TestLogicAppV2'is not supported.', exception='', extensionVersion='1.0.0.0', siteName='', slotName=''....

I have the resource group setup for Central US. 

Any ideas?

**Comment by rarayudu** [comment]
Hi Jimbwlah,

we are working on enabling the support for this action as part of our next refresh. For now, this is not supported.

**Comment by nidubey1** [comment]
@Jimbwlah I have tested this scenario and it works fine now.
