### ISSUE TITLE
Azure portal loads previously opened Logic App in Chrome

### ISSUE THREAD

**Issue by devosmos** [Azure/logicapps#186]
While working on a Logic app and when you navigate to resource group from the working pane and select another Logic app, Azure portal loads the previously opened Logic app.

Steps to reproduce the issue on Google Chrome (This is issue does not seem to occur on Firefox)

1. Create a Resource Group. Let's call it  LogicAppView
2. Create a Logic App. Let's call it LogicApp-One.
3, Add a simple trigger to LogicApp-One - HTTP trigger -  to complete the Logic App. 
4. Create another Logic App. Let's call it LogicApp-Two.
5. Add a simple trigger to LogicApp-Two - Recurrence trigger -  to complete the Logic App. 
6. Open LogicApp-One 
7. Click on overview tab in the Resource Manager pane.
8. Click on Resource Group name in the working pane to navigate to the Resource Group overview.
9. Click and open LogicApp-Two.
10. Click on Logic App designer. Portal switches to load the designer for LogicApp-One. (You might have to click Logic app designer twice - first click might not result in any action at all)

Chrome Version 86.0.4240.75

![Step-6](https://user-images.githubusercontent.com/58045204/96251549-44fc5800-0fce-11eb-9a93-23004d9ca479.png)
![Step-8](https://user-images.githubusercontent.com/58045204/96251575-4cbbfc80-0fce-11eb-9d83-b59a0dabb8f0.png)

**Comment by tonytang-microsoft-com** [comment]
Thanks for reporting. We are looking at it.
