### ISSUE TITLE
Error creating project

### ISSUE THREAD

**Issue by lynnaloo** [Azure/logicapps#188]
When I try to create a new Logic Apps project using the Preview extension, I get this error:

Error: Command "dotnet "c:\Users\me\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-0.0.4\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\me\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\me\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "logic-apps-test" --arg:AzureFunctionsVersion v3" failed with exit code "2147614729":
Error: Could not install "c:\Users\me\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg".
Error: Could not load file or assembly 'Microsoft.TemplateEngine.Edge, Version=5.0.0.0, Culture=neutral, PublicKeyToken=abc'. The system cannot find the file specified.
Error: Could not install "c:\Users\me\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg".
Error: Could not load file or assembly 'Microsoft.TemplateEngine.Edge, Version=5.0.0.0, Culture=neutral, PublicKeyToken=abc'. The system cannot find the file specified.
{
  "Message": "Could not load file or assembly 'Microsoft.TemplateEngine.Orchestrator.RunnableProjects, Version=5.0.0.0, Culture=neutral, PublicKeyToken=abc'. The system cannot find the file specified.",
  "Status": -2147352567,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}

I've tried uninstalling VS Code and all of the extensions and re-installing just what's needed for this extension and I'm seeing the same issue.

**Comment by vikash-anand** [comment]
Hi @lynnaloo This seems like an issue with installation. Can you please go to **C:\Users\<Username>\.vscode\extensions** and delete all **ms-azuretools.vscode-azurelogicapps-*** and then try to install the extension again?

**Comment by toddwhitehead** [comment]
Same issue. Have uninstalled extensions and vscode completely and still get the same issue.

12:29:49 pm: Error: Command "dotnet "c:\Users\towhit\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-0.0.4\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "la-local-demo" --arg:AzureFunctionsVersion v3" failed with exit code "2147614729":
Error: Could not install "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg".
Error: Could not load file or assembly 'Microsoft.TemplateEngine.Edge, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Error: Could not install "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg".
Error: Could not load file or assembly 'Microsoft.TemplateEngine.Edge, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
{
  "Message": "Could not load file or assembly 'Microsoft.TemplateEngine.Orchestrator.RunnableProjects, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.",
  "Status": -2147352567,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}

**Comment by toddwhitehead** [comment]
Same issue. Have uninstalled extensions and vscode completely and still get the same issue.

Noticed that at top the trace its is referring to "dotnet "c:\Users\towhit.vscode\extensions\ms-azuret....." shouldn't that be "dotnet "c:\Users\towhit\vscode\extensions\ms-azuretools.vscode"?

12:29:49 pm: Error: Command "dotnet "c:\Users\towhit.vscode\extensions\ms-azuretools.vscode-azurelogicapps-0.0.4\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "la-local-demo" --arg:AzureFunctionsVersion v3" failed with exit code "2147614729":
Error: Could not install "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg".
Error: Could not load file or assembly 'Microsoft.TemplateEngine.Edge, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Error: Could not install "c:\Users\towhit\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg".
Error: Could not load file or assembly 'Microsoft.TemplateEngine.Edge, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
{
"Message": "Could not load file or assembly 'Microsoft.TemplateEngine.Orchestrator.RunnableProjects, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.",
"Status": -2147352567,
"TemplateFullName": "Azure Functions",
"ResultInfo": null,
"OutputBaseDirectory": null,
"CreationEffects": null
}

**Comment by rasavant-ms** [comment]
@vikash-anand - I tried deleting the extension and installing it again. Still get the same error.

**Comment by fortunkam** [comment]
I am seeing the same issue.  It only seems to affect the logic app preview extension -> Create new project.  I can still create a function project (using the vscode functions extension) and then add a logic app workflow to it.

**Comment by tonytang-microsoft-com** [comment]
We've release a new version of the extension that fixed the issue. Could you please give it a try?

**Comment by nidubey1** [comment]
@lynnaloo , @toddwhitehead & @fortunkam I have tried to create the Project with the Logic App Standard extension and I am successfully able to create the Project. Reference Document: https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code
