### ISSUE TITLE
Logic App Preview HTTP Connector with Managed identity

### ISSUE THREAD

**Issue by joshfria** [Azure/logicapps#191]
**HTTP Connector**
The first issue is with this connector. The authentication parameter requires the raw JSON to be added instead of the previous drop downs. Not a big deal, but certainly a drop in the user-friendliness. I'm using-
`{
  "audience": "https://vault.azure.net",
  "type": "ManagedServiceIdentity"
}`

**Managed Identity**
The second and more pressing issue. When using the HTTP connector via the portal I am trying to use a System Assigned Managed Identity. Every time I try it I receive the error-
`The workflow 'Testworkflow' does not have managed identity enabled. If the managed identity of the workflow is updated recently, please wait for 2 minutes and try again. See https://aka.ms/logicapps-msi for details. `

I have restarted the app multiple times. I have tried removing and adding the System Assigned Managed Identity back to the app. Is this a bug or am I missing something?

**Comment by rarayudu** [comment]
Hi joshfria,

Ability to use Managed identity in the actions (includes http) is not enabled yet. This will be enabled in the upcoming releases.

**Comment by erwinkramer** [comment]
Does the same count for the **Active Directory OAuth** option in the HTTP Connector?

**Comment by erwinkramer** [comment]
> @rarayudu Does the same count for the **Active Directory OAuth** option in the HTTP Connector?

I tested recently and it just works fine

**Comment by liliankasem** [comment]
@rarayudu Any idea which release will support managed identity / are there any updates? 

@erwinkramer Active Directory OAuth works for me, but I had to add the auth extension in the host file.

**Comment by daharmon** [comment]
Is there a document somewhere which explains which built in actions support managed identity authentication? You would think the http action would support this. I would love to start using logic apps (preview) but this is a show stopper right out of the gate.

**Comment by nidubey1** [comment]
@joshfria & @liliankasem  The Logic App Standard(single tenant) supports System Assigned Managed Identity. I have tested the same and it works fine:
![image](https://user-images.githubusercontent.com/85997053/123632770-f29a5900-d835-11eb-8e13-ea564647487f.png)

@erwinkramer : A single-tenant (Standard plan) based logic app currently supports only the system-assigned identity. Reference Document: https://docs.microsoft.com/en-us/azure/logic-apps/create-managed-service-identity#where-to-use-managed-identities
