### ISSUE TITLE
Create Logic Apps Public Preview on Docker (From Portal)

### ISSUE THREAD

**Issue by shankarmaha** [Azure/logicapps#192]
I tried creating a Logic App from scratch using portal and selected "Docker Container". I used the below settings

Region: UK South
Plan type: App service plan
SKU and size: F1

I got the below error while deploying

![image](https://user-images.githubusercontent.com/4720931/97879505-f95ce480-1d17-11eb-8cfb-667932dff810.png)

I changed the setting and tried creating again.

Region: Central US
Plan type: App service plan
SKU and size: Premium V2 P1v2

The deployment completed, but it threw the following error 

![image](https://user-images.githubusercontent.com/4720931/97879751-417c0700-1d18-11eb-96dc-4c0a91ae7cf1.png)

When I tried to browse the App service, I got the error "The Function host is not running". We had this issue during private preview and had to add the below while building the docker image

ENV AZURE_FUNCTIONS_ENVIRONMENT Development

Not sure if this is still relevant. But, if this is required, then the docker image that is used for creating (mcr.microsoft.com/azure-functions/dotnet:3.0.13614-appservice) needs to be updated. 

Please refer to this github issue for more details. https://github.com/Azure/logicapps/issues/123

**Comment by laveeshb** [comment]
@shankarmaha thanks for reporting this issue. We have deployed a fix for it. Could you try again?

**Comment by shankarmaha** [comment]
Hi Laveesh,

Thanks. I can now deploy the LA by selecting the "Docker Container" option. The function host is also running now. But, when I tried to add a new workflow, I get a confirmation that the workflow is created. But, I can't see the workflow. 

![image](https://user-images.githubusercontent.com/4720931/98095638-be2af480-1e82-11eb-8d71-a98f9a9ec5dc.png)


![image](https://user-images.githubusercontent.com/4720931/98095792-eb77a280-1e82-11eb-99d5-7c74991894d2.png)
