### ISSUE TITLE
"Send an email (V2)" action's "Body" output value is empty [Preview]

### ISSUE THREAD

**Issue by nandkishorenair** [Azure/logicapps#195]
Repro steps - following the steps listed in the docs [here ](https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#return-a-response-to-the-caller)(steps 3 and 4)
Expected outcome: The contents of the email body should be visible in the http response body
Actual outcome: Contents of the email body (from previous step) is not visible in http response. All static text added manually is visible (the issue is reproducible with or without static text being included in the body)

Azure Functions core tools version: 3.0.2931

Workflow designer in VSCode:
![image](https://user-images.githubusercontent.com/3322650/98164261-01e92280-1eb2-11eb-9bab-3d6821596ecc.png)

Run overview with "send an email" parameters:
![image](https://user-images.githubusercontent.com/3322650/98164315-162d1f80-1eb2-11eb-9071-8371a9ea0ba9.png)

Run overview with http response parameters:
![image](https://user-images.githubusercontent.com/3322650/98164360-247b3b80-1eb2-11eb-83d8-391e9636ff64.png)

Response snapshot:
![image](https://user-images.githubusercontent.com/3322650/98164401-352bb180-1eb2-11eb-92ad-2fb5b72f9f58.png)

**Comment by shailesh-agre** [comment]
Tested the scenario again - it is working fine - as expected. Able to get the HTTP Request Body in the email body.
From screen shots I see that you are using GET. Should it be POST? 
You will have to add parameter to the Request Trigger to use POST method.
Let us know if you still finding issues.
