### ISSUE TITLE
New Action to get Request Response is not executed in subsequent runs of the workflow locally

### ISSUE THREAD

**Issue by rasavant-ms** [Azure/logicapps#196]
**Repro Steps**
Followed steps here to create example-workflow - https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code

Created workflow with HTTP trigger and Send an email actions. Ran debug on that successfully.
Added action to get Request response. Saved workflow. Ran debug and sent http request using previous URL, Http request does not fail but Run history does not show updated workflow and new request response is not seen.

![image](https://user-images.githubusercontent.com/6465709/98166096-be83b980-1e9b-11eb-91c7-4d1f27fd3796.png)

**System Info**
Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
Windows 10.0.19042 Build 19042
VSCode:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Acceptance Criteria**
Create workflow with HTTP trigger and Send an email actions. Run debug on that successfully.
Add action to get Request response. Save workflow. Run debug and send http request. Updated workflow is executed with request response.

**Comment by jodoroth** [comment]
Hi,  Were you able to check the flow. Please let me know if you are still seeing issues.

**Comment by jodoroth** [comment]
Hi, Gentle reminder. Could you please let me know if you are still seeing issues.

**Comment by jodoroth** [comment]
Hi, We are closing this github case since we are not seeing the reported issues. Please feel free to reopen incase if you are still seeing issues.
