### ISSUE TITLE
O365 Send an Email (V2) response code is success but email is not actually being sent

### ISSUE THREAD

**Issue by rasavant-ms** [Azure/logicapps#197]
**Repro Steps**
Followed steps from tutorial till this point - https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#run-and-debug-locally

Workflow shows success on executing debug run, but does not generate email.
Have used Microsoft login id for Office 365 and sending email to same account.

Unable to provide screenshots as none of this works now due to issues # 169 and # 196 

**System Info**
Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
Windows 10.0.19042 Build 19042
VSCode:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Acceptance Criteria**
Workflow shows success on executing debug run, and generates email.

**Comment by rarayudu** [comment]
rasavant-ms, can you share the connection details from connections.json file? And also, you can check for the inputs and outputs of the debug run from the overview on VSCODE. Does the action completed successfully?

**Comment by jodoroth** [comment]
I have tested the below scenario and it works as expected.

Scenario:

Create workflow with HTTP trigger and Send an email actions. Ran debug successfully. Email is generated as expected. 

image

Reference : https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code.

**Comment by jodoroth** [comment]
Hi,  Were you able to check the flow. Please let me know if you are still seeing issues.

**Comment by jodoroth** [comment]
Hi, Gentle reminder. Could you please let me know if you are still seeing issues.

**Comment by jodoroth** [comment]
Hi, We are closing this github case since we are not seeing the reported issues. Please feel free to reopen incase if you are still seeing issues.
