### ISSUE TITLE
Adding new workflow to existing project doesn't allow for debugging it

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/logicapps#198]
I created a new LA Preview Stateful workflow solution in VS Code using the preview extension. I then added a Stateless workflow to the current window. This resulted in `Stateful1` and `Stateless` being present in the directory. When I F5 in the IDE, only the first workflow (`Stateful1`) gets launched & is able to be debugged. There appears to be no way to change it to either fire them both up or allow me to launch & debug the Stateless one.

**Comment by vikash-anand** [comment]
@brandonh-msft Hi I just tried adding a stateful and stateless workflow in a Logic App local project was able to run them correctly. Can you share more details on how to repro it?
1. What connectors and operations did you use in your workflows?
2. Do you see two workflows loaded in the terminal logs? It should b something like the screenshot below
![image](https://user-images.githubusercontent.com/647513/98983721-0fb42e80-24d6-11eb-98ef-88a9ea09dd4f.png)

3. Are you able to load the overview page of the two workflows?

Please provide us the above information. It will allow us to debug further. Thank you!

**Comment by brandonh-msft** [comment]
User error.

When I created the Stateless one and added my HTTP Trigger I must've not hit 'save' on the screen. I think the usual "dot" that appears next to the filename in the Tab would be helpful here to remind me of this :D
