### ISSUE TITLE
non-Preview extension labeled as Preview; description title has 'Preview'.

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/logicapps#199]
I'm confused by the extension listings in the VS Code extension marketplace. The **non-preview** LA extension is labeled as preview while its listing also has Preview in the title. However there also exists an extension whose _name_ has `(Preview)` in it.

![image](https://user-images.githubusercontent.com/20270743/98169099-7e730580-1ea0-11eb-9957-79dbe3ea03b5.png)

**Comment by brandonh-msft** [comment]
seems like a great solution so long as the descriptions also help devs choose the appropriate one.

**Comment by devin-simoneaux** [comment]
@brandonh-msft yes, we updated the descriptions as well to point to the respective solutions that the extensions are for as well for more clarity.

**Comment by brandonh-msft** [comment]
Hm. seems the first few lines of each extension are identical. I would suggest updating the one-liner so folks don't have to read the entire MD description to pick the right one

![image](https://user-images.githubusercontent.com/20270743/121218187-6220b800-c837-11eb-8577-530e39b8f5f8.png)

**Comment by devin-simoneaux** [comment]
@brandonh-msft great suggestion! I'll pass this along to the engineering team for them to update.

**Comment by KiranmaiS** [comment]
@brandonh-msft, we heard your feedback! Our engineering team has accepted to update the description to distinguish between the resource types (Standard and Consumption). You should be able to see the changes soon. On this note, I shall proceed to close this request. Thank you!
