### ISSUE TITLE
Logic app blob trigger not fired on subfolder

### ISSUE THREAD

**Issue by CrazyTuna** [Azure/logicapps#20]
I am referring to these issues:

 - [Logic app blob trigger not fired on subfolder](https://stackoverflow.com/questions/49334524/logic-app-blob-trigger-not-fired-on-subfolder)
 - [Azure Storage Blob Trigger to fire when files added in Sub Folders..](https://feedback.azure.com/forums/287593-logic-apps/suggestions/20164843-azure-storage-blob-trigger-to-fire-when-files-adde)

I have a Azure Logic App that is fired every time every time a blob is added in a container. This works fine when all the documents are at the root of the container.

Inside my container, I have a dynamic number of (virtual) sub-folders. When I add a new document in a subfolder (path = mysubfolder/mynewdocument.txt), the logic app is not triggered.

This does not really make sense for me as sub-folders in the blob container are virtual.

Is it a known issue/limitation ? Do you have a plan to fix it ?

Anyway a BIG Thanks for the great job you are doing with Logic App, I really love it !!!

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
