### ISSUE TITLE
Azure Storage Emulator is sunsetting in favor of Azurite; docs should direct to Azurite

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/logicapps#201]
From https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator : 

![image](https://user-images.githubusercontent.com/20270743/98169310-e0cc0600-1ea0-11eb-9c68-1dc3a6bac31e.png)

Docs & implementation for utilizing LA v2 locally should center around Azurite

**Comment by hannesne** [comment]
When trying to open the design view while using Azurite for local storage emulation, the extension shows the following error: 

```
2:00:10 pm: Running command: "func host start --port 8000"...
Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
[2020-11-03T01:00:22.003] A host error has occurred during startup operation '81eb352f-23e5-41d4-92ca-badd2aadce66'.
[2020-11-03T01:00:22.005] Microsoft.WindowsAzure.ResourceStack: No connection could be made because the target machine actively refused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because the target machine actively refused it.
Value cannot be null. (Parameter 'provider')
Application is shutting down...
```

This could either be because of Azurite v3  not yet supporting table storage, or because the app is trying to communicate over https and Azurite doesn't have a cert installed. I did try using the self-signed dotnet cert path described here: https://github.com/Azure/Azurite/blob/master/README.md#pfx but it didn't work.

**Comment by ecfan** [comment]
Hi @brandonh-msft and @hannesne, thanks for your comments. The Azure Storage Emulator is required at this time as the Azurite emulator doesn't yet meet the team's requirements.

**Comment by tomkerkhove** [comment]
Related: https://github.com/Azure/logicapps/issues/115

**Comment by ecfan** [comment]
Adding @rohithah @laveeshb as FYI

**Comment by Bandgren** [comment]
@ecfan Do we have any update on this?

Running into the same issue running on WSL2.
```
[2021-01-18T12:34:06.018Z] Microsoft.WindowsAzure.ResourceStack: Connection refused. System.Net.Http: Connection refused. System.Private.CoreLib: Connection refused.
Value cannot be null. (Parameter 'provider')
```

**Comment by ecfan** [comment]
@rohithah and @laveeshb, could you please help with the [issue](https://github.com/Azure/logicapps/issues/231) involving the [storage setup steps described here](https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#macos)?

**Comment by ecfan** [comment]
With the public release, Azurite is now supported: 

https://docs.microsoft.com/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#storage-requirements
