### ISSUE TITLE
Documentation doesn't explain how to deploy the logic app programmatically (from the CLI)

### ISSUE THREAD

**Issue by hannesne** [Azure/logicapps#202]
Currently the documentation only shows how to deploy the logic app from VS Code using the extension. Providing some guidance on using the CLI will help developers setting up CI/CD pipelines.

**Comment by ecfan** [comment]
Hi @hannesne, 

I've asked the team your question, and they're working on an answer for you.

**Comment by alfred-madl** [comment]
...and how to retrieve the HTTP trigger URL to call a workflow. We used Get-AzLogicAppTriggerCallbackUrl in Powershell so far ;-) Thanks.

**Comment by liliankasem** [comment]
There's a sample available now with some documentation. I think there is more to come in this space, but it's a start!

https://github.com/Azure/logicapps/tree/master/templates/devops-sample

**Comment by ecfan** [comment]
For Standard logic apps, this CLI ref doc now exists: [az logicapp deployment](https://learn.microsoft.com/cli/azure/logicapp/deployment?view=azure-cli-latest)
