### ISSUE TITLE
dotnet build doesn't work in a linux dev container - nuget packages restored incorrectly.

### ISSUE THREAD

**Issue by hannesne** [Azure/logicapps#203]
The nuget package seems to be copying files with incorrect paths to the nuget packages folder. When trying to do a build you get this error:

`error MSB3030: Could not copy the file "/root/.nuget/packages/microsoft.azure.workflows.webjobs.extension/1.0.0.8-preview/lib/netcoreapp3.1/Microsoft.Azure.Workflows.ServiceProviders.Abstractions.dll" because it was not found. [/workspaces/la-v2-devcontainer/la-v2-devcontainer.csproj]` 

Looking at the contents of the nuget packages folder using 

`ls /root/.nuget/packages/microsoft.azure.workflows.webjobs.extension/1.0.0.8-preview/`
reveals the following file list, where the direcoty path with `\` seems to be part of the filename:

```
LICENSE.txt
 NOTICE.txt
'_rels\.rels'
'contentFiles\any\'
'contentFiles\any\any\'
'contentFiles\any\any\JS\analysis.js'
'contentFiles\any\any\JS\customError.js'
'contentFiles\any\any\JS\esprima.js'
'contentFiles\any\any\JS\estraverse.js'
'contentFiles\any\any\JS\finalizeExports.js'
'contentFiles\any\any\JS\functionInputHandler.js'
'contentFiles\any\any\JS\index.js'
'contentFiles\any\any\JS\initExports.js'
'lib\netcoreapp2.2\ClearScript.dll'
'lib\netcoreapp2.2\ClearScriptV8-32.dll'
```

**Comment by hannesne** [comment]
It would be good if a dev container is provided with all the dependencies installed, to help developers get going quicker. The one issue so far is that Azurite doesn't seem to work with the Logic apps, so an alternative solution is needed. Possibly guidance to use a real storage account.

**Comment by hongzli** [comment]
Thanks for reporting this. We've made a fix that should go out with the next release.

**Comment by tomkerkhove** [comment]
I'm facing the same issue, what's the workaround for this for now?

**Comment by hongzli** [comment]
Try this:
-  In your Logic App folder, delete the 'bin' and 'obj' folders if they exist
-  Change the contents of the host.json file, located at the root of your Logic App's folder, to the following:
```
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
        "version": "[1.*, 2.0.0)"
    }
}
```

**Comment by hongzli** [comment]
Closing as the nuget filename issue has been fixed in the latest release
