### ISSUE TITLE
Workflow designer doesn't re-use AzureWebJobsStorage setting from root local.settings.json

### ISSUE THREAD

**Issue by hannesne** [Azure/logicapps#204]
When clicking the open designer item on a workflow, the new folder with it's own local.settings.json defaults the storage setting to  `AzureWebJobsStorage": "UseDevelopmentStorage=true"` 
It would be better to use the setting from the root local.settings.json, as that allows the developer to provide an alternative to a real storage account if they can't run the local storage emulator. This is especially important for cross plat development where the only option is Azurite, which doesn't currently work because of the table storage dependency.

**Comment by tonytang-microsoft-com** [comment]
Thanks @hansesne for the feedback. We are evaluating the options and continue to improve the experience in vs code.

**Comment by tonytang-microsoft-com** [comment]
For now, you should be able to manually update the settings to point to any storage URL after the folder is created, and restarting the function runtime will use the new settings.
