### ISSUE TITLE
Unable to switch from Stateful workflow to Stateless in local dev environment

### ISSUE THREAD

**Issue by scgbear** [Azure/logicapps#206]
Attempting to switch from stateful to stateless results in an error saying it's not possible. Even just locally on a development machine after purging the bin/obj and storage accounts. I assume there is something being cached outside of the these locations that is preventing me from doing this switch. 

At any rate, we shouldn't have to completely purge and change directory structure to switch from Stateful to Stateless on a local development machine. Can see a problem when doing so in a deployed scenario.

**Comment by hongzli** [comment]
hi @scgbear , are you developing locally with Azure Storage Emulator? If so, can you try doing "AzureStorageEmulator.exe clear all" in the storage emulator UI? Switching between stateful and stateless works for me after doing that. It should look like: 

![image](https://user-images.githubusercontent.com/69482556/98748810-4c194a80-236f-11eb-8679-c4ed48ff8bfd.png)

**Comment by nidubey1** [comment]
@scgbear I have tested the same by changing the "kind": from "Stateful" to "Stateless" in VS code for an existing LA Standard project and able to successfully deploy it on Azure Logic Apps and it works fine-
![image](https://user-images.githubusercontent.com/85997053/128478309-536a9c11-8ac1-4019-aabb-52c895c4f87c.png)
