### ISSUE TITLE
No support for Integration Accounts in LogicAppsV2

### ISSUE THREAD

**Issue by scgbear** [Azure/logicapps#207]
There is not away to configure the integration account available in the portal and the transformation related actions are not available. Don't see this listed as a known unsupported feature here:  https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#unavailable-or-unsupported-capabilities.

If there is a way to configure the integration account via app settings? I don't see any documentation for doing that.

**Comment by hongzli** [comment]
Hi @scgbear , unfortunately integration accounts are not supported in this preview. In the doc section you linked, it's hidden among a few other unsupported features.

![image](https://user-images.githubusercontent.com/69482556/98744578-ce514100-2366-11eb-86ef-f6d706024d2d.png)

**Comment by skyaddict** [comment]
@hongzli not that logic apps standard has released any word on support for Flat File Decoding?
