### ISSUE TITLE
Not able to authenticate Logic App through Api Management

### ISSUE THREAD

**Issue by shivendra-aggarwal** [Azure/logicapps#21]
Hi,

Would require some assistance in my below scenario:

I want to apply authentication on Logic App through Api Management.

Currently I have configured Logic App instance + App Service ( Web API) under same API Management.

While registering apps inside API Management, I have selected OAuth2.0 options to validate all calls to API Management through generated token.

To my surprise my App Service (Web API) is able to validate token but Logic app is not.

Can you please help me in this scenario ASAP.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
