### ISSUE TITLE
Logic Apps (Preview) VS Code extension - Prompt to start storage emulator

### ISSUE THREAD

**Issue by mcollier** [Azure/logicapps#212]
The default experience for creating a new Logic Apps (Preview) workflow in VS Code sets the `AzureWebJobsStorage` in the local.settings.json file to a value of "UseDevelopmentStorage=true".

If the local Azure Storage Emulator is not started when the developer attempts to view the workflow in the designer, an error is thrown (screenshot below).  It would be nice if the VS Code extension could check if the emulator is not running, and then pop a warning to prompt the developer to start the emulator.  I think the Azure Functions VS Code extension may do this.

![image](https://user-images.githubusercontent.com/1142273/98963874-23f82b80-24d6-11eb-9aa3-572d2f0c6d1f.png)

**Comment by tonytang-microsoft-com** [comment]
Thanks @mcollier for your feedback. We will continue to improve the experience on vs code.
