### ISSUE TITLE
VSCode preview - Designer can't start

### ISSUE THREAD

**Issue by allymparker** [Azure/logicapps#213]
Running inside WSL2, ubuntu 18.04

```
2:27:25 PM: Running command: "func host start --port 8000"...
/bin/sh: 1: func: Exec format error
```
Azure Functions installed via linux brew:
azure/functions/azure-functions-core-tools@3: stable 3.0.2996, HEAD

VS Code
Version: 1.51.0 (system setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Extensions:
Azure Account 0.9.4
Azure Functions: 1.0.1
Azurite 3.9.0

**Comment by hongzli** [comment]
Hi @allymparker , we've improved Linux and Mac support as well as a bunch of other bug fixes in the latest release. Can you update your VSCode extension, create a new project, and try again?

**Comment by manish-jain-1** [comment]
This still doesn't work for me on mac. My VSCode version 1.53.0. The designer shows a blank screen.
