### ISSUE TITLE
404 error when polling location header location on stateful asynchronous workflow

### ISSUE THREAD

**Issue by ethan-aer** [Azure/logicapps#217]
Using the http request trigger and response action with asynchronous response enabled executes properly and generates a location header, but when the location is polled a 404 response is received

![30 11 2020_10 51 41_REC](https://user-images.githubusercontent.com/56736283/100645709-44a7ea00-32fa-11eb-8767-d9fe32445b1b.png)
![30 11 2020_10 54 15_REC](https://user-images.githubusercontent.com/56736283/100645809-728d2e80-32fa-11eb-8027-1cce9bfc72ec.png)

**Comment by rarayudu** [comment]
@ethan-aer, thanks for reporting this. it will be fixed as part of next refresh release.
