### ISSUE TITLE
CosmosDB Changefeed Function Trigger as Workflow Trigger 

### ISSUE THREAD

**Issue by alfred-madl** [Azure/logicapps#218]
Any chance of using the CosmosDB Changefeed Azure Functions Trigger also for triggering Logic Apps Workflows in V2 ?

**Comment by rarayudu** [comment]
we don't have this specific trigger in the plan yet. But you can add support for new (function based)triggers or built in connector actions using our Service Provider based approach. The following blog post from @praveensri-zz explains how you can do it.
https://techcommunity.microsoft.com/t5/integrations-on-azure/azure-logic-apps-running-anywhere-built-in-connector/ba-p/1921272
