### ISSUE TITLE
foreach in parallel and variables

### ISSUE THREAD

**Issue by MysticWolf** [Azure/logicapps#22]
Hello,

I get a strange behavior with the foreach executed in parallel. Sometimes "Compose" action takes data from another thread. To prevent that I removed the parallelism and also added the shape to force to reinit my string. Is it a bug ?

Please find below my workflow

![image](https://user-images.githubusercontent.com/28396240/39005561-d65fc724-4400-11e8-9e1f-78fc6e0a86ab.png)

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
