### ISSUE TITLE
Support for Consumption Plan

### ISSUE THREAD

**Issue by alfred-madl** [Azure/logicapps#221]
Are there plans to support Logic Apps using the "Consumption" Plan similar to Azure Functions ? Would be great so support true "server less" scenarios. Thanks.

**Comment by shailesh-agre** [comment]
The plans are now available at https://azure.microsoft.com/en-in/pricing/details/logic-apps/
More details will be added soon.

**Comment by tomkerkhove** [comment]
Are there plans to support consumption with the new runtime/containerized workflows?

**Comment by shailesh-agre** [comment]
@tomkerkhove Are you referring to Azure connectors in this? Because there are plans to create built in connectors in phased manner. If that is not your query, can you please give some more context?

**Comment by tomkerkhove** [comment]
Will we be able to deploy a containerized workflow to Azure Logic Apps (Consumption) and get pay-as-you-go billing?

**Comment by shailesh-agre** [comment]
@tomkerkhove This will not be a supported scenario.
