### ISSUE TITLE
Unable to create Azure Logic apps Preview project / Azure Function app project using VS Code 

### ISSUE THREAD

**Issue by amarmanchalagithub** [Azure/logicapps#223]
Does this occur consistently? Yes
Repro steps:

1. Open Visual Studio code
2. Select Azure Function in the Azure subscription
3) click on new Function app project
4) Select folder
5) Select Language as C#, Select timer Trigger, Provided name space, Entered Corn Expression, Select Use local Emulator, 
6) Open in Current Window
 Error Ocuurred

Action: azureLogicAppsV2.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\aam5268\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-0.0.7\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "testLGPSample" --arg:AzureFunctionsVersion v3" failed with exit code "2097158":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}

Version: 0.0.7
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:136301
fulfilled extension.bundle.js:1:135124
processTicksAndRejections task_queues.js:94:5
```

</details>
this window.

**Comment by vikash-anand** [comment]
Hi @amarmanchalagithub Are you also facing the issue while creating a Logic App project? Can you share the error message when you create a LogicApp project?

**Comment by amarmanchalagithub** [comment]
Does this occur consistently? 
Repro steps:


1.
2.

Action: azureLogicAppsV2.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\aam5268\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-0.0.7\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurelogicapps\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "sfsfswewe" --arg:AzureFunctionsVersion v3" failed with exit code "2097158":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}


Version: 0.0.7
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:136301
fulfilled extension.bundle.js:1:135124
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by amarmanchalagithub** [comment]
HI Vikas,

 Could you please provide us an update on it

**Comment by vikash-anand** [comment]
[TemplateProject.zip](https://github.com/Azure/logicapps/files/5823513/TemplateProject.zip)

@amarmanchalagithub I have attached a project template for now, while we investigate the issue.
To use the template
1. Unzip the file on your local machine. It will create a folder named "TemplateProject"
2. You can rename the folder to your project name
3. Rename the "*.csproj" file as with the project name
4. Open the folder in VSCode

You can then add workflows and run the project locally

**Comment by nidubey1** [comment]
@amarmanchalagithub I have tested the same and am able to successfully create the Logic App standard project in VS code. Reference Document: https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code
