### ISSUE TITLE
Read data from Azure PostgreSQL Database

### ISSUE THREAD

**Issue by jerrendeloitte** [Azure/logicapps#228]
Hi,

Is there anyway to read data from Azure PostgreSQL Database.

There is a postgres connector but seems like it only supports on-prem postgres database.

I saw there is a [feedback](https://feedback.azure.com/forums/287593-logic-apps/suggestions/36672061-add-trigger-and-connector-for-azure-postgre-sql) for this request, is there a timeline for this request?

**Comment by joechung-msft** [comment]
This repository is for issues with the artifacts of this repository and for the new preview Logic Apps runtime and Visual Studio Code extension.

If you have questions about Logic Apps, please visit [Microsoft Q&A](https://docs.microsoft.com/answers/topics/azure-logic-apps.html).

If you have feedback regarding Logic Apps, such as suggestions for features or other observations, please visit [feedback.azure.com](https://feedback.azure.com/forums/287593-logic-apps).
