### ISSUE TITLE
XML Transform - Xslt Parameters converted to string

### ISSUE THREAD

**Issue by Morgma** [Azure/logicapps#232]
In the Azure Logic Apps designer, the XML Transform block accepts a JSON object of the input parameters for the Map. In the VS Code extension, the Xslt Parameters are converted to an escaped string value, and then saving the workflow results in an error:

![image](https://user-images.githubusercontent.com/887392/104971129-74e33f00-59b3-11eb-8b32-526732639e45.png)

Code view:
![image](https://user-images.githubusercontent.com/887392/104971231-bd026180-59b3-11eb-9f17-7de2ecbb1355.png)

**Comment by rarayudu** [comment]
Thanks for reporting this. The fix for this will be released in next update.

**Comment by nidubey1** [comment]
@Morgma I have tested the same and it works fine in Logic App (single tenant) standard both in VS code as well as on Azure Portal:
![image](https://user-images.githubusercontent.com/85997053/123762789-c25bc480-d8e0-11eb-9085-3da88cd27c62.png)
