### ISSUE TITLE
Error when converting pdf to image

### ISSUE THREAD

**Issue by Paprika-a11y** [Azure/logicapps#233]
It seems it is a bug that converting pdf to image using Azure Logic App.

Here is my flow:

![image](https://user-images.githubusercontent.com/58552796/104982483-bde3d380-5a45-11eb-8ade-2b4978608c86.png)

I tried to change the output format and add the optional parameter, it still cause an error like before:

![Reproduce400Error](https://user-images.githubusercontent.com/58552796/104982594-f84d7080-5a45-11eb-8478-9bfd884cc1a0.png)

Or it would run more than one minute and cause 502 error:
![image](https://user-images.githubusercontent.com/58552796/104982775-4e221880-5a46-11eb-956b-97bd2d310518.png)

 Is this a bug? Or I got some mistake operation?

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit [Microsoft Q&A](https://docs.microsoft.com/answers/topics/azure-logic-apps.html).

If you have feedback regarding Logic Apps, such as suggestions for features or other observations, please visit [feedback.azure.com](https://feedback.azure.com/forums/287593-logic-apps).

**Comment by Paprika-a11y** [comment]
> If you have questions about Logic Apps, please visit [Microsoft Q&A](https://docs.microsoft.com/answers/topics/azure-logic-apps.html).
> 
> If you have feedback regarding Logic Apps, such as suggestions for features or other observations, please visit [feedback.azure.com](https://feedback.azure.com/forums/287593-logic-apps).

Do you mean I cannot post this here?
