### ISSUE TITLE
Logic app Json function rounds decimal numbers

### ISSUE THREAD

**Issue by kostadinSpiridonov** [Azure/logicapps#234]
The logic app rounds long decimal numbers when you try parse json.

On the screenshots bellow you can see the setup and the result. When you use the json function over a string which contains long decimal number, the number in the result is rounded.

Is it expected behavior? Is there any workaround except azure function?

**Setup**
![image](https://user-images.githubusercontent.com/18635867/106294290-ab447800-6257-11eb-99f4-859262c413fb.png)

**Result**
![image](https://user-images.githubusercontent.com/18635867/106294632-1130ff80-6258-11eb-88fa-c3a50f355e47.png)

**Comment by kostadinSpiridonov** [comment]
Could provide some feedback please? It's a blocking issue.

**Comment by joechung-msft** [comment]
This is a known limitation of [floating point precision](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems).

**Comment by shailesh-agre** [comment]
@kostadinSpiridonov Can you please confirm if this is happening with Single Tenant Logic App also?

**Comment by shailesh-agre** [comment]
This issue does not happen with Standard (single tenant) Logic App.
