### ISSUE TITLE
need to be able to use @appsetting references to enable multi-subscription environments

### ISSUE THREAD

**Issue by bluechiperic** [Azure/logicapps#235]
We use different subscriptions for non-prod and production environments.  In order to automate the deployment of a logic app, we need some way to be able to parameterize the connections.json file per subscription.  Right now the @appseting function works great for things like function keys and sql connection strings, but it appears that you can't use them for things like api connection ids.

I am trying to figure out how we would automate deployment of the same logic app to different subscriptions.

Thanks.

**Comment by rarayudu** [comment]
@bluechiperic, this is something we are working on to improve the experience with connections.json while you deploy to different environments and subscriptions.

**Comment by bluechiperic** [comment]
Good to know.  For now, we are just copying an environment specific connections.json file in during the build pipeline and creating a separate deployment package for each environment.  It works, but definitely not optimal.

**Comment by liliankasem** [comment]
Another way to handle this in dev ops is to generate the connections.json file [using a script like this one](templates/devops-sample/.pipelines/scripts/Generate-Connections.ps1). This is how my team and I are managing multiple environments.

**Comment by bluechiperic** [comment]
> Another way to handle this in dev ops is to generate the connections.json file [using a script like this one](https://github.com/liliankasem/logicapps/blob/main/.pipelines/scripts/Generate-Connections.ps1). This is how my team and I are managing multiple environments.

Lilian, that's a great script!  I think the only thing I might need to tweak is that we like to keep our function app keys in key vault secrets and link to them via app settings rather than writing them out to plain text in the connections.js file.  I think if I name the app setting key and the KV secret key both using a consistent convention based on the function name, i can probably script out the app setting reference in the json file.

**Comment by liliankasem** [comment]
Modifying for use with KV sounds like a great idea!

**Comment by brandonh-msft** [comment]
<details><summary>internal tracking</summary>
CSEF 434874
</details>

**Comment by SahinOzdemir** [comment]
Hi, could you tell us what the current status of this issue is? It's much needed functionality in order to be able to neatly deploy through CI/CD pipeline.
