### ISSUE TITLE
Logic Apps v2 Service Bus API connection

### ISSUE THREAD

**Issue by rbehra** [Azure/logicapps#236]
Hi,
I am trying to migrate a Logic App from v1 to v2 (Preview), however Logic App v2 doesn't take the API connection from Resource Group previously created for Logic App v1.

What should be the best way to migrate the Service Bus API connection in v2? Should it be recreated again in Logic App v2 (Preview)?

Because I am unable to Edit the existing connection, only way is to add a new Service Bus Connection.

**Comment by devin-simoneaux** [comment]
@rbehra - Yes, you will need to create a new API connection for use in v2 because the connections are stored inside of the Logic App (Preview), so you will be unable to access connections that were created from multi-tenant Logic Apps.

**Comment by saroja-sattigeri** [comment]
There is no way to migrate consumption logic app(multi-tenant) API connections to standard logic app(single-tenant) and also existing multi-tenant API connections will not be available/visible in standard logic app. So, you will need to create a new API connection in standard logic app.
