### ISSUE TITLE
Breakpoints in Debug Mode not hitting - No Symbols have been loaded for this document (Preview)

### ISSUE THREAD

**Issue by erwinkramer** [Azure/logicapps#239]
During debugging, breakpoints are not being hit, with the message while debugging:

> No Symbols have been loaded for this document 

![image](https://user-images.githubusercontent.com/4255748/107031774-096edf00-67b3-11eb-8bd5-574682015bfb.png)

The documentation specifies that it should work on actions 

> Set the starting breakpoint on the line that shows the action's name. When this breakpoint hits during the debugging session, you can review the action's inputs before they're evaluated.

I've forced loading as much symbols as it could get, by specifying my launch.json like this:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "justMyCode":false,
      "requireExactSource": true,
      "name": "Attach to .NET Functions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureLogicAppsV2.pickProcess}",
      "suppressJITOptimizations": true,
      "symbolOptions": {
        "searchMicrosoftSymbolServer": true,
        "moduleFilter": {
            "mode": "loadAllButExcluded"
        }
      }
    }
  ]
}
```

My global.json looks like this:
```
{
    "sdk": {
       "version": "3.1.405",
       "rollForward": "disable"
    }
}
```
Azure Core Tools versions:
```
Azure Functions Core Tools
Core Tools Version:       3.0.3233 Commit hash: d1772f733802122a326fa696dd4c086292ec0171 
Function Runtime Version: 3.0.15193.0
```

**Comment by hongzli** [comment]
Hi @erwinkramer ,  it's difficult to diagnose this without the full project. Can you zip this project folder and share it? Either as a download link or you can email it to me (liu.henry@microsoft.com) directly and I'll take a look.

**Comment by erwinkramer** [comment]
After reopening in vscode I noticed the 'Initialize project for use with VS Code' notification, after pressing OK for that, it works.  Awesome!
