### ISSUE TITLE
Bug in docker-file example

### ISSUE THREAD

**Issue by runemy** [Azure/logicapps#243]
Hi,

On this page: https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#requirements

The docker-file example do maybe have a bug.
Replace "FROM mcr.microsoft.com/dotnet/core/sdk3.1 AS installer-env"
With "FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS installer-env"

Missing ":"

**Comment by ecfan** [comment]
Hi @runemy, thanks for catching this issue!

**Comment by ecfan** [comment]
Hi @runemy, this Dockerfile will change and be updated on March 2, 2021.

**Comment by ecfan** [comment]
Hi @runemy, for the extension update, here's the updated Docker file example: 

[https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#requirements](https://docs.microsoft.com/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#requirements)
