### ISSUE TITLE
I need to build the Body dynamically within the HTTP Request to use the PATCH method.

### ISSUE THREAD

**Issue by e-pfigueiredo** [Azure/logicapps#246]
I need to build the Body dynamically within the HTTP Request to use the PATCH method. Does anyone have any suggestions?

For example. If "var1" or "var2" is equal to null. This does not enter the construction of the Body. The goal is to update only the fields that are informed of the values ​​to update.

![2021-03-02_125121](https://user-images.githubusercontent.com/54986929/109655613-62842580-7b5b-11eb-986b-c93ec7c676c2.jpg)

**Comment by shailesh-agre** [comment]
You can compose the body before HTTP call - using IF condition - so that you can exclude the null values. Then used the composed variable in the body.
