### ISSUE TITLE
.csproj v 0.0.10 logic apps preview

### ISSUE THREAD

**Issue by wirefusion** [Azure/logicapps#248]
v 0.0.10 is new update,

after updating from v 0.0.9 to v 0.0.10 new projects do not create .csproj file

**Comment by hongzli** [comment]
Hi @wirefusion , this is the expected behavior. We've made some changes to the Logic App project structure to improve start time and enable cross-platform support for more actions. The new project structure should behave the same as the previous one. If you do need the csproj for something like custom connectors, you can switch to the old structure by right clicking on the project folder in VSCode and selecting "Move to a Dotnet based Logic App project". Note that this is a one-way operation. 

![image](https://user-images.githubusercontent.com/69482556/110150830-8bdbc600-7d94-11eb-881e-4cdb70d69b55.png)

**Comment by wirefusion** [comment]
Thanks for your response @hongzli 

issue I am facing is that my build pipeline (build step ) is failing in the absence of .csproj, 

What other step I can use in absence of .csproj please

**Comment by hongzli** [comment]
@wirefusion , can you tell me a little more about your build pipeline scenario? Are you using a CI/DI pipeline to create/deploy your Logic App, or are you trying to add additional build steps in the csproj? Or something else?

**Comment by wirefusion** [comment]
@hongzli 

Yes build pipeline is to deploy logicapp v2  to azure ,

logic app v2 is developed in vs code

**Comment by hongzli** [comment]
Using the "Move to a Dotnet based Logic App project" operation should work for your for scenario and add back the csproj, though I would recommend updating to the new project structure in the future. Let us know if that helps or if you run into additional issues.  CC: @Bec-Lyons

**Comment by wirefusion** [comment]
Thx @hongzli 

I would like to move to new project structure, 

Does new project structure support deployment pipeline in any other way ?

**Comment by hongzli** [comment]
The new project structure does not improve deployment pipeline support over the previous structure, though @liliankasem is working on an example pipeline using the new structure and we should be able to share it sometime next week.

**Comment by wirefusion** [comment]
Thx @hongzli 

I am not looking for improvement in the deployment pipeline for the new structure , 

My question is does new structure support deployment old/existing/new way ?

**Comment by liliankasem** [comment]
The new version does support deployment pipelines in a similar way, the only difference is that we would _not_ use the `dotnet publish` command to create the zip file that the CD pipeline would deploy, you will have to package up the project for deployment another way. Everything else should stay the same.

**Comment by wirefusion** [comment]
Thanks @liliankasem 

I build step required or just zip everything?

If yes,

How does build step look like

**Comment by liliankasem** [comment]
You will no longer need a build step

**Comment by wirefusion** [comment]
Thx @liliankasem I tried with below 

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


But Artifact has no files in it

**Comment by liliankasem** [comment]
Well it of course depends on your project / folder structure. Just make sure to update the `rootFolderOrFile` property to point to your project. 

Here is an example: https://dev.azure.com/logicappsdemo/Logic%20Apps%20v2%20Sample/_build/results?buildId=143&view=logs&j=e7e87dd7-913b-5f21-122a-3dc430580ff1

**Comment by wirefusion** [comment]
Thanks, @liliankasem

I am unable to see yaml of this pipeline, are you able to share or email me at wirefusion@gmail.com please

**Comment by wirefusion** [comment]
release pipeline give error 
Functions runtime error System.IO.FileSystem: Could not find file 'C:\home\site\wwwroot\s\.git\branches'.

below is the structure of the app after the release 

Directory of C:\home\site\wwwroot\s

03/07/2021  12:48 AM    <DIR>          .debug
03/07/2021  12:48 AM    <DIR>          .git
03/07/2021  12:48 AM    <DIR>          .vscode
03/07/2021  12:48 AM    <DIR>          arm
03/07/2021  12:48 AM    <DIR>          RoadBike
03/07/2021  12:48 AM    <DIR>          workflow-designtime
03/07/2021  12:48 AM                66 .funcignore
03/07/2021  12:48 AM                73 .gitignore
03/07/2021  12:48 AM               857 azure-pipelines.yml
03/07/2021  12:48 AM               146 host.json
03/07/2021  12:48 AM                72 proxies.json
03/07/2021  12:48 AM               985 README.md
               6 File(s)          2,199 bytes
               6 Dir(s)               0 bytes free

C:\home\site\wwwroot\s>dir

**Comment by liliankasem** [comment]
The CI pipeline is here: https://github.com/liliankasem/logicapps/blob/main/.pipelines/classic/ci-pipeline.yml

**Comment by jptarqu** [comment]
Are there updated instructions on how to build a docker container using the new project structure? The instructions I found assumed a “dotnet publish” into the wwwroot of the container (https://microsoft.github.io/AzureTipsAndTricks/blog/tip311.html).

**Comment by brandonros** [comment]
How to wrap a logic app (aka its JSON workflow) in a Docker container? Do you need dotnet runtime? I don't see where .csproj/dotnet project comes into play when the logic app "code" is just JSON workflow, no node.js or dotnet?
