### ISSUE TITLE
support creating logic apps in bicep

### ISSUE THREAD

**Issue by skyaddict** [Azure/logicapps#249]
logic apps are being saved as arm json. I am using bicep to deploy all the other resources. It would be wonderful if logic apps could be written and read as bicep files natively.

**Comment by Bec-Lyons** [comment]
Thanks for the feedback. If you could fill in the following survey (aka.ms/logicappsdevops) that would help us prioritize this ask for the next round of features. Cheers!

**Comment by tedescomicchidev** [comment]
Hi @Bec-Lyons  - unfortunately the link provided above (aka.ms/logicappsdevops) results in an error "Sorry something went wrong". Is this still the preferred way to give feedback? If yes, could you please check why the form doesn't work anymore? Thanks :-)

**Comment by Bec-Lyons** [comment]
Unfortunately the form is down at the moment - please try again in a couple of hours.

**Comment by shailesh-agre** [comment]
@tedescomicchide hope that you were able to fill the form- if so, we can close this issue?

**Comment by tedescomicchidev** [comment]
Yes, I found the Form -. thanks :-)
