### ISSUE TITLE
How do i use service account in Azure Logic Apps?

### ISSUE THREAD

**Issue by ganeshchippada** [Azure/logicapps#25]
I am using the office 365 connector as part of my workflow in the azure logic apps to listen to calendar events. Right now i am receiving notifications on the events only to the account i linked. I have a requirement to listen to more than one account. Say for ex: I want to receive event notifications from a set of users i want. I have a service account which has impersonation privileges. I mapped this service account in the connector. But i dont see any events flowing from other user accounts. My question, is it really possible to achieve this? If yes, how?

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
