### ISSUE TITLE
trackedProperties not working

### ISSUE THREAD

**Issue by erwinkramer** [Azure/logicapps#252]
I'm trying to make Tracked Properties work in the preview Logic Apps. I've got App Insights set up in the resource. And I'm running from the resource itself. The following doesn't seem to work:

` "trackedProperties": {
                    "myId": "@{triggerBody()['myId']}"
                }`

My http trigger body looks something like this:

`{
  "myId": "128379123",
  "someOtherId" : "blabla"
}`

I see my shapes being logged in App Insights, however, no **myId** custom property. Is the support not there yet?

**Comment by bydynamics** [comment]
I am facing the same issue. Heavily relying on trackedproperties (servicebus messageId) to bind backend with Logic Apps (Preview) as integration platform. Same question to the team, is this supported yet?

**Comment by rohithah** [comment]
tracked properties should work. can you take a look at the example in this [blog](https://techcommunity.microsoft.com/t5/integrations-on-azure/azure-logic-apps-running-anywhere-monitor-with-application/ba-p/2003332).

"myId" tracked property will be nested as below:

customDimensions["prop__properties"]["trackedProperties"]["myId"]
