### ISSUE TITLE
Functions host is no longer running when trying to run Logic App (Preview) locally.

### ISSUE THREAD

**Issue by enoleainoa** [Azure/logicapps#253]
Followed instructions https://docs.microsoft.com/en-gb/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code and tried to run logic app and got an error found below. I also tried to run template example found from https://github.com/Azure/logicapps/tree/master/github-sample and that did not work either.

Does this occur consistently? Yes
Repro steps:

1.
2.

Action: azureLogicAppsV2.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.0.10
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:89097extension.bundle.js:334:89097
fulfilled extension.bundle.js:334:86519
```

</details>

**Comment by hongzli** [comment]
We have identified this as an issue related to the recent February release of VSCode (version 1.54.x). The temporary workaround would be to roll-back to VSCode version 1.53.x (https://code.visualstudio.com/updates/v1_53) . We are actively working on a fix.

**Comment by enoleainoa** [comment]
Thanks @hongzli ! Will try this workaround. Thanks for your quick response.
