### ISSUE TITLE
This keeps happening... How do I stop the function manually?

### ISSUE THREAD

**Issue by mikaelsand** [Azure/logicapps#254]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsV2.pickProcess
Error type: Error
Error Message: Failed to stop previous running Functions host within "30" seconds. Make sure the task has stopped before you debug again.

Version: 0.0.10
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.54.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:87294extension.bundle.js:334:87294
fulfilled extension.bundle.js:334:86519
```

</details>

**Comment by vikash-anand** [comment]
@mikaelsand You can kill the function process using the task manager. Look for "func" process in the task manager and "End" the task.

**Comment by mikaelsand** [comment]
Wow, that is really hacky but I'll take it.
