### ISSUE TITLE
Logic App preview - shows readonly after deployment

### ISSUE THREAD

**Issue by mmaulik13** [Azure/logicapps#255]
I tried to deploy logic app preview and saw that It was deployed but was in readonly format, I can not make any changes in that. But Only deploying. Is there any flag I messed up with?

**Comment by vikash-anand** [comment]
As of now we do not allow edit to a Logic App deployed in Azure. The deployed logic apps open in read-only view in the VSCode extension. However, if you would like to make changes, you would need to make changes to your local project and deploy the Logic App again.

**Comment by ahmedsza** [comment]
Can a logic app that was created in Azure be imported into a local project, then edited and deployed - overwriting the existing one.
