### ISSUE TITLE
401 Unauthorized - Get callback URL for Request trigger

### ISSUE THREAD

**Issue by kscerri96** [Azure/logicapps#258]
Hi, 

I created a logic app locally using the Logic App (Preview) extension from VS code and followed the deploy to Docker steps from the below documentation.

https://docs.microsoft.com/en-us/azure/logic-apps/create-stateful-stateless-workflows-visual-studio-code#deploy-to-docker

Whenever I try to get the callback URL for the request Trigger I get 401 Unauthorized. Can anyone point me to where this issue is coming from. Thanks.

**Comment by rohithah** [comment]
The likely reason is the master key used to get the callback url is not valid or formatted incorrectly.  you can also update your host.json file to include the master key

so you can upload a host.json file that looks like

{
  "masterKey": {
    "name": "master",
    "value": "MASTER_KEY",
    "encrypted": false
  }
}

**Comment by devin-simoneaux** [comment]
Just wanted to follow up here - @kscerri96 were you able to get it working following the instructions above?

**Comment by shailesh-agre** [comment]
Verified - working fine. Steps are documented here
https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#find-master-key-for-storage-account
