### ISSUE TITLE
Logic app is giving error from TFS (on premise)

### ISSUE THREAD

**Issue by pandeyit** [Azure/logicapps#26]
I am trying to reach Logic app(as a GATE) in my release definition.
I am getting following error 

Response: An error was encountered while processing request. Exception: {"error":{"code":"DirectApiAuthorizationRequired","message":"The request must be authenticated only by Shared Access scheme."}} 

where as logic app end point is reachable from other clients like Postman.

I have already checked sp, sv and sg values. they are correct

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
