### ISSUE TITLE
[VS Code] cannot deploy to logicapp

### ISSUE THREAD

**Issue by Mortana89** [Azure/logicapps#261]
Does this occur consistently? Yes
Repro steps:
1. New VS Code project
2. Pump over workflow.json files
3. Try to push to an existing LogicApp preview v2 plan

Action: azureLogicAppsV2.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 0.0.11
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:1:84766
Object.<anonymous> extension.bundle.js:1:626893
fulfilled extension.bundle.js:1:626093
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by vikash-anand** [comment]
@Mortana89  Can you please provide more information
1. Did you create the Logic App project from scratch? or did you try to deploy an existing project?
2. Can you check the setting "azureLogicAppsV2.projectLanguage" in your local project? This should be found in settings.json under .vscode folder

**Comment by Mortana89** [comment]
Hi,

Steps I've done:
- Create a new logicapp project from scratch, deploy to azure
- Create a new repo, and move the logicapp project to a folder in the new repo
- Try to push to azure

The language is correct, it says:
{
    "azureLogicAppsV2.deploySubpath": ".",
    "azureLogicAppsV2.projectLanguage": "JavaScript",
    "azureLogicAppsV2.projectRuntime": "~3",
    "debug.internalConsoleOptions": "neverOpen"
}

I've tried now moving my 'workspace' folder to the same level as the workflow json files (so not the root repo folder) and then it works though

**Comment by nidubey1** [comment]
@Mortana89 , hope you are doing well. Can you please share the screenshots of the working and the non working project structures to troubleshoot further this issue. Please feel free to contact in case of any concerns.

**Comment by Mortana89** [comment]
Hello,

Sorry, this is almost of half a year ago, I'm afraid I cannot pop up these requirements that easy anymore...

**Comment by nidubey1** [comment]
@Mortana89 thanks for the update. Will it be possible for you to try to replicate a similar scenario and confirm if it works. I am pasting the documentation for your reference to Create an integration workflow with single-tenant Azure Logic Apps (Standard) in Visual Studio Code: https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code

Please let me know in case of any concerns.

**Comment by nidubey1** [comment]
@Mortana89 Hope you are doing well. Can you please help me with the below ask if possible. Otherwise if you are not able to replicate the scenario now you can reach out to me later when you face it. 

"Will it be possible for you to try to replicate a similar scenario and confirm if it works. I am pasting the documentation for your reference to Create an integration workflow with single-tenant Azure Logic Apps (Standard) in Visual Studio Code: https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code

Please let me know in case of any concerns."
