### ISSUE TITLE
Incorrect Webhook Status

### ISSUE THREAD

**Issue by Nemadjo94** [Azure/logicapps#263]
Hi

As seen on the image bellow, webhook status is sometimes incorrect. 
Webhook is resolved and the logic app completed its execution but the webhook status is still stuck on "waiting".
This posses an issue because we are fetching actions from the logic app run to do assertions in our integration tests, and tests fail because we expect the status of the webhook action to be "succeeded".

![2](https://user-images.githubusercontent.com/22825924/112492671-bf9d8080-8d81-11eb-8499-0bff2bc419d2.PNG)

**Comment by rohithah** [comment]
is this something that repros consistently or one time occurrence? if it is just one time, would you be able to share the app name if this is running in azure or the logs if running locally? if repros consistently, can you share the workflow definition?

**Comment by nidubey1** [comment]
@Nemadjo94 I have tried the similar scenario for Logic App Standard and it works fine every time. Please refer the below screenshots:
Caller Logic App with a Webhook action->

![image](https://user-images.githubusercontent.com/85997053/129690933-fd62645e-1b3c-4b80-95a2-5f65fac9dc61.png)

Subscriber Logic App called by the above caller Logic App->
Run Screenshot:
![image](https://user-images.githubusercontent.com/85997053/129690984-5fe2bc1a-2add-4cf7-956c-68246f866c7d.png)

Design Screenshot:
![image](https://user-images.githubusercontent.com/85997053/129691409-558cfd0a-65d7-46f6-b613-8889b9a9bde0.png)

**Comment by nidubey1** [comment]
@Nemadjo94 Please let me know if you are still facing similar issue or have further queries related to this issue. And if it is working now is it fine if we close this issue.
