### ISSUE TITLE
Event grid trigger topic not created when deploying workflow through pipelines

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/logicapps#264]
# Description

This is a bug within Logic Apps preview. When deploying a new logic app workflow that uses an event grid trigger through pipelines, the event grid topic subscription isn't automatically created like it used to be with logic apps v1. This leads to new deployments being broken and having to manually recreate the event grid connection and trigger in order to force a creation of the topic.

# Repro steps

Create an IoT Hub through ARM
Create a new logic app preview through ARM
Deploy a logic app workflow that uses an event grid trigger, through pipelines (e.g. az func deploy task in AzDO)

## Actual Result
When an event happens, the logic app never gets triggered. This is because an event grid topic subscription has not been created.

## Expected Result
Event grid topic subscription gets created on the workflow deployment. Logic app triggers when a new event comes to the IoT Hub.

<details><summary>internal tracking</summary>
CSEF 434819
</details>

Possibly related to #183

**Comment by gitdj** [comment]
I have similar issue for Logic dataverse webhook trigger, when I manually configure it works but if any changes are done on the logic app and deployed it doesn't work any more even though I manually configure it post the deployment.
