### ISSUE TITLE
connections.json files are painful

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/logicapps#266]
# Description

This is an issue with logic apps preview. The whole idea of the connections.json file is painful to deal with. The file looks different for local debugging than it does in when doing a cloud deployment; and there are values in that file that are difficult to come by.

On the cloud side, we found a workaround: you gitignore the connections.json file then run a script in your devops pipeline to generate a connections.json file based on the connections you have deployed in a given resource group. This works fine.

Locally, this is a lot of work. When trying to debug locally you need to have a connections.json file with the auth type set to 'Raw, which requires a connection key. The only way to get this key is to have the logic apps extension generate the connections file for you. The only way to have the logic app generate that file is to recreate all of your connection operations in your workflow. When you have 7 API connections in your workflow and you need to tell every engineer that clones this project that they need to recreate every connector operation so that they can debug locally, it becomes a very tedious and painful user experience and is likely to lead to human error in changes to workflow operations.

Ideally: when a user clones the repo locally and opens the workflow in the designer view for the first time, instead of telling them the operation is broken because of a missing connections file, given them the option to point to an existing API connection that has already been deployed, or to create a new connection in order to repair the operation. This is a way better experience than forcing users to delete an entire operation and recreate it.

<details><summary>internal tracking</summary>
CSEF 434879
</details>

**Comment by rohithah** [comment]
This is an area we are currently working on to simply. Stay tuned for more details soon.

**Comment by mirzaciri** [comment]
> This is an area we are currently working on to simply. Stay tuned for more details soon.

Any more information regarding this? It is still a pain to deal with different connections and access policies and such. Especially when you want to use devops for deployment
