### ISSUE TITLE
Logic App Preview SQL On Prem - Gateway still needed?

### ISSUE THREAD

**Issue by bakes82** [Azure/logicapps#268]
Im trying out the Logic App Preview, and have configured our app service to be on our vnet (which all of our other function apps/app services are).  Im trying to configure a workflow to write data to the SQL server, and I configure it w/out a gateway but it doesnt seem to be able to see the server.  Do you still need a gateway even with the vnet enabled, doesnt the defeat the purpose?

**Comment by rarayudu** [comment]
You shouldn't need gateway for the built-in connector. If the app is connected to the VNET, you should be able to connect. Please make sure you are not using the Azure connector, but the built-in action to connect to SQL. Currently the built-in action only has the execute query operation.

If you are using the Azure connector, yes, you still need gateway.
