### ISSUE TITLE
When using WSL remote connection, Overview tab is blank

### ISSUE THREAD

**Issue by Morgma** [Azure/logicapps#269]
Environment details: 

> Azure Logic Apps (Preview) Extension: v.0.0.1.1
> Functions Runtime: v3.0.15193.0
> Core Tools: v3.0.3233
> Storage Connection: Azure Storage, not an emulator / Azurite
> WSL: Ubuntu v18.04

When selecting the "Overview" from the context menu:

![image](https://user-images.githubusercontent.com/887392/113438351-060c6400-93ae-11eb-9b14-a5a46bd9afc8.png)

The Overview tab is blank:

![image](https://user-images.githubusercontent.com/887392/113438793-e6297000-93ae-11eb-9966-11c3d1af2ece.png)

Running the same workflow on Windows, the Overview tab works as expected:

![image](https://user-images.githubusercontent.com/887392/113439549-6a302780-93b0-11eb-9efb-52a05d97a411.png)

I can verify the function runtime is working and the WorkflowDispatcher is processing successfully. The Designer tab and other features seem to be working as expected, but without the Overview, run history can't be navigated.

**Comment by manualbashing** [comment]
I am experiencing the same issue on WSL: Ubuntu v20.04. 

There is at least a workaround for getting the callback URL of the http trigger:

1) Run your logic app with F5

2) Send a POST request to the following URL:
```
http://localhost:{Port your Logic App uses}/runtime/webhooks/workflow/api/management/workflows/{Name of your Logic App}/triggers/manual/listCallbackUrl
```

![image](https://user-images.githubusercontent.com/5665209/114000964-c76a2400-985b-11eb-8667-3ceb9c111dba.png)

**Comment by puspraj-repos** [comment]
@Morgma , can you try using the latest update of the logic apps standard extension( v1.0.0). I tried in both WSL (Ubuntu 18.04 and 20.04), I'm able to access overview tab with all details.
