### ISSUE TITLE
Chunked Messages

### ISSUE THREAD

**Issue by grik001** [Azure/logicapps#27]
I am trying to implement an API Action to accept messages larger than 100mb by Logic Apps.

I am following the below documentation to understand what headers are passed and what responses I should return. What I have noticed is that no chunk identifier is mentioned in the document. If this is not available, how can I determine which part belongs to which file?

https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-handle-large-messages

Also by any chance do you know of or have a sample of how the function should be implemented?

Thanks,
Keith.

**Comment by grik001** [comment]
Also:

It states that the below is not required, yet it is, is the documentation updated?

Location | String | No | The URL location where to send the HTTP PATCH messages

I am also facing a problem that after the first POST call the following call is a POST where as in the doc it states that it should be a PATCH

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
