### ISSUE TITLE
ServiceProviderActionFailed. System.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by wirefusion** [Azure/logicapps#272]
Suddenly,
I am getting this error, from SQL inbuilt connector

I am running a simple SQL "Select @@version"

**Comment by wirefusion** [comment]
v0.0.11

.NET Core SDK (reflecting any global.json):
 Version:   3.1.407   
 Commit:    d3244d0e44

Runtime Environment:  
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.407\



Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0

**Comment by wirefusion** [comment]
logic app preview works fine in Azure, 
when I download in VS Code , I get this error 
ServiceProviderActionFailed. System.Data.SqlClient is not supported

**Comment by rohithah** [comment]
can you share latest version number from this folder:
C:\Users\<user>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows

**Comment by hongzli** [comment]
@wirefusion , I noticed your core tools version is an older one. Can you also try with the latest core tools release from here? https://github.com/Azure/azure-functions-core-tools/releases

**Comment by nidubey1** [comment]
@wirefusion I have tested the same and it works fine on Azure Portal as well as in VS code. Reference Document: https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code

![image](https://user-images.githubusercontent.com/85997053/123764141-2468f980-d8e2-11eb-98aa-b2103c2fc6e6.png)
