### ISSUE TITLE
Issue opening Logic Apps Preview template in VS Code

### ISSUE THREAD

**Issue by AnaghaPirangute20** [Azure/logicapps#273]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsV2.createNewProject
Error type: Error
Error Message: Failed to get latest templates: ESOCKETTIMEDOUT

Version: 0.0.11
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.1
Language: en

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:164:445981
fulfilled extension.bundle.js:164:442536
```

</details>

**Comment by puspraj-repos** [comment]
@AnaghaPirangute20 , can you try using latest version of LA-Standard VS code extension, If you're still having problems, add more detailed repro steps
