### ISSUE TITLE
ENOENT: no such file or directory, scandir azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows

### ISSUE THREAD

**Issue by ianisms** [Azure/logicapps#274]
Does this occur consistently? Yes
Repro steps:

1. Create new local logic app in VS Code, 
2. Run via F5

Action: azureLogicAppsV2.getDebugSymbolDll
Error type: ENOENT
Error Message: ENOENT: no such file or directory, scandir '<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows'

Version: 0.0.11
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

**Comment by hongzli** [comment]
Can you try opening your workflow in designer first before doing F5? (Right click the workflow.json file --> Open in Designer)

**Comment by devin-simoneaux** [comment]
@ianisms are you still facing this issue?

**Comment by lwalker-kforce** [comment]
I am facing this same issue. I have tried running vscode as admin also. The only difference is the file path in the message.
