### ISSUE TITLE
Unauthorized Response when connecting to docker container deployed on Azure App Service

### ISSUE THREAD

**Issue by sriksmachi** [Azure/logicapps#279]
I created an Azure App Service and deployed the container (https://hub.docker.com/r/vishwanathsrikanth/logicappspreview-helloworld) on App Service, I copied the master-key from the host.json from the deployment-name folder created in the attached storage account, but I get 401 response. The same docker image works perfectly fine on localhost. Is there a difference in steps for app service? What is the significance of "encrypted": true on host.json for deployment created from app service?

Below is the request 

```
curl --location --request POST 'http://logicappspreview-sample.azurewebsites.net/runtime/webhooks/workflow/api/management/workflows/contoso-logicapp/triggers/manual/listCallbackUrl?api-version=2020-05-01-preview&code=somecrypticmasterkeyhere'
```

**Comment by mkhurana14** [comment]
As suggested by Product Group Team as of now we are not using docker for App service. But they will be introducing Azure Arc based logic app which is currently in public preview but with help of that you would be able to deploy the logic app anywhere be it Docker or Kubernetes.

Also, once the Azure Arc is available, we can host the container anywhere provided the platform is supported by Azure Arc.

Please refer the below links for the same:
https://docs.microsoft.com/en-us/azure/logic-apps/azure-arc-enabled-logic-apps-overview

https://docs.microsoft.com/en-us/azure/logic-apps/azure-arc-enabled-logic-apps-create-deploy-workflows?tabs=azure-cli
