### ISSUE TITLE
Create SAS URI by Path: Cannot use returned Web Url as query paramter

### ISSUE THREAD

**Issue by woter324** [Azure/logicapps#28]
I can't find your GitHub repo for Logic App actions, so this will have to do.

I want to use the return `Web Url` from `Create SAS URI by Path` as a query parameter for an API in an `Http` action, however, the SAS token contains `&` and `=`. This makes the query invalid.

I see the action is in preview, therefore, can you make sure the proper escaping happens. I belive if you added a return value of just the token, I could use the `variable` action to concatenate the value.

Thanks

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
