### ISSUE TITLE
Could not load type Microsoft.Azure.Workflows.ServiceProviders.Abstractions.IServiceProviderLogger

### ISSUE THREAD

**Issue by erwinkramer** [Azure/logicapps#280]
Deploying a zipped NuGet based Logic App (preview) package used to work, now it seems something has broken.  

The following message is displayed on the Overview page:

`Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.Workflows.ServiceProviders.Abstractions.IServiceProviderLogger' from assembly 'Microsoft.Azure.Workflows.ServiceProviders.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
 `

My csproj file conatains the following reference to packages:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Workflows.WebJobs.Extension" Version="1.0.1.*-*"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9"/>
  </ItemGroup>
```

I tried using the latest versions on both packages, the versions displayed here are the versions that are used when you convert a nodejs based package in VSCode. 

I also provisioned a new Logic App (preview) resource and tested it there, same issue.

**Comment by YingjieShi-MS** [comment]
Hello @erwinkramer, may I know if you are still facing the same error now? The Logic App Standard has go-live now. Could you please follow the doc https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#set-up-visual-studio-code and try again?
