### ISSUE TITLE
ProjectLanguage Defaulting to JavaScript

### ISSUE THREAD

**Issue by prbeegala** [Azure/logicapps#281]
When creating a new LogicApps Preview project in Visual studio code, irrespective of the Preferences --> Settings --> Extensions value, the project is defaulting to JavaScript. 

"azureLogicAppsV2.projectLanguage": "JavaScript"

This is causing settings.json file to have wrong values and unable to debug and run the Logic app from VS Code. I have tried resetting the values, uninstall and reinstall the extension - but it isn't making any difference. 

Logic Apps preview extension - 0.0.12

**Comment by vikash-anand** [comment]
@prbeegala We have released a new version of our extension. Can you update your extension and try again? Let us know if it does not resolve the issue for you.

**Comment by mkhurana14** [comment]
@prbeegala Can you please update if the issue is still happening after updating it to new version?

**Comment by mkhurana14** [comment]
@prbeegala Please let me know if the issue is still occurring?

**Comment by mkhurana14** [comment]
@prbeegala Hello Prakash please let me know if the issue is still occurring or if you need any help here.
