### ISSUE TITLE
Salesforce connector updates run status as failed though Platform Event is inserted successfully

### ISSUE THREAD

**Issue by naridnevahgar** [Azure/logicapps#282]
I am using the Salesforce connector to create Platform Event record through [Create Record](https://docs.microsoft.com/en-us/connectors/salesforce/#create-record) action. 

My Platform Event has 3 fields, name, email & phone; no nested objects. 
Corresponding connector code is: 

```
 "Create_record": {
     "runAfter": {
         "Set_vEmail": [
             "Succeeded"
         ],
         "Set_vName": [
             "Succeeded"
         ],
         "Set_vPhone": [
             "Succeeded"
         ]
     },
     "type": "ApiConnection",
     "inputs": {
         "body": {
             "Email__c": "@variables('vEmail')",
             "Name__c": "@variables('vName')",
             "Phone__c": "@variables('vPhone')"
         },
         "host": {
             "connection": {
                 "name": "@parameters('$connections')['salesforce']['connectionId']"
             }
         },
         "method": "post",
         "path": "/v2/datasets/default/tables/@{encodeURIComponent(encodeURIComponent('AgentCreation__e'))}/items"
     }
 }
```

On every run, the logic app is able to insert a new record inside Salesforce. 
However, the run status is updated as failed. The connector's output phase shows it produced HTTP 404, ID does not exist. 
I believe the limitation could be from Salesforce's Platform Events rest api design. 
But is there a workaround to recognize platform events on logic apps side?

**Comment by shailesh-agre** [comment]
As you mentioned, this appears more of an API issue itself and not related to Logic Apps platform - same error can happen with shared environment also. If your intention is to handle the errors, you can follow https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-exception-handling. Or if you need more assistance w.r.t. this connector, you may open incident with the Microsoft Support team.
