### ISSUE TITLE
HTTP connector fails MS Graph query with "Request_UnsupportedQuery"

### ISSUE THREAD

**Issue by noendscripting** [Azure/logicapps#283]
When sending following MS Graph query "https://graph.microsoft.com/beta/groups?$filter=onPremisesSyncEnabled%20ne%20true" HTTP connector gets following error: 
{
  "error": {
    "code": "Request_UnsupportedQuery",
    "message": "Unsupported property filter clause operator 'NotEqualsMatch'.",
    "innerError": {
      "date": "2021-05-13T14:10:40",
      "request-id": "0f32659a-5bfe-4a7a-a357-b3093816b9f9",
      "client-request-id": "0f32659a-5bfe-4a7a-a357-b3093816b9f9"
    }
  }
}

The exact same query executed with Powershell Invoke-WebRequest or Invoke-RestMethod runs successfully

**Comment by shailesh-agre** [comment]
If you use the  [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to run the same query, you will get exact same error. 

`{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported property filter clause operator 'NotEqualsMatch'.",
        "innerError": {
            "date": "2021-05-15T03:19:44",
            "request-id": "0bf5169a-c472-471b-bd6e-3d0eec6d681d",
            "client-request-id": "0bf5169a-c472-471b-bd6e-3d0eec6d681d"
        }
    }
}`

You can use Graph Explorer to create appropriate query and then use it in any other HTTP client.
You may approach Graph forum for further assistance.

**Comment by noendscripting** [comment]
Could you help me understand  how Graph Explorer impacts ability of LogicApps to run Graph queries? I'm don't want to run into scenario where Graph team will send me back to LogicApps  space

**Comment by shailesh-agre** [comment]
As HTTP action is being used and error is coming from the end point called, the issue is on the server side. Graph Explorer is just a tool for doing quick tests - it is being used for isolation.
