### ISSUE TITLE
Logic app parameters being erased when using designer

### ISSUE THREAD

**Issue by jamesseiwert** [Azure/logicapps#284]
Parameters that are defined in the json file for a workflow are being erased. If you update a logic app in the designer and click save, any parameters defined in the json file are removed.

**Comment by shailesh-agre** [comment]
Can you please provide sample snippet you were using?

**Comment by shailesh-agre** [comment]
@jamesseiwert Please use the released version of the Standard Logic App and try to repro.  If it fails there also, we can take it forward. Till then, I will close this issue.
