### ISSUE TITLE
Callback URL and other info not available in overview when using different port

### ISSUE THREAD

**Issue by ahmedsza** [Azure/logicapps#287]
I had some issues on my machine with port 7071 so changed the port in local.settings.json to 87

"LocalHttpPort": 87

I started the logic app on the command line with _func host start --verbose_ 
and also tried _func host start --verbose --port 87_

In both cases the debug output showed this

Stateful1:  http://localhost:87/api/Stateful1/triggers/manual/invoke

When I went into the overview windows for the workflow though , I see this

![image](https://user-images.githubusercontent.com/37135205/118930716-63e91100-b946-11eb-9cc7-7214342c0188.png)

I subsequently fixed my port issues and confirmed that when using the default 7071 port -- all works.. 

Surely it should also work with a port other than 7071 (note I tried 7073 as well - and it did not work as well)

**Comment by vikash-anand** [comment]
@ahmedsza We do not support the functionality to run the function host on a port different from the default port. We will implement this feature soon. Thanks for the feedback.

**Comment by ahmedsza** [comment]
Thanks @vikash-anand . Can i recommend we just add this to the docs in the interim
