### ISSUE TITLE
Logic App deployment (azureLogicAppsV2.deploy) from Vs Code to Azure does not work

### ISSUE THREAD

**Issue by samuel-weber** [Azure/logicapps#288]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsV2.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 0.0.13
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:1:84733
Object.<anonymous> extension.bundle.js:1:626860
fulfilled extension.bundle.js:1:626060
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by vikash-anand** [comment]
@samuel-weber We have updated our extension which includes several bug fixes. Can you update your extension and try again? Let us know if the issue exists.

**Comment by devin-simoneaux** [comment]
@samuel-weber are you still experiencing this issue? Or, did Vikash's suggestion above work for you?

**Comment by samuel-weber** [comment]
It's working now, thanks
