### ISSUE TITLE
New Extension unable to debug logic app

### ISSUE THREAD

**Issue by hmntrathore** [Azure/logicapps#290]
Does this occur consistently? 
Repro steps:

1. Create a New Logic app in VS Code using the standard Extension
2. Start Debugging

Action: azureLogicAppsStandard.getDebugSymbolDll
Error type: ENOENT
Error Message: ENOENT: no such file or directory, scandir 'C:\Program Files\Microsoft VS Code\%%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
Usage: func [context] [context] <action> [-\--options]

Contexts:
azure       Commands to log in to Azure and manage resources
durable     Commands for working with Durable Functions
extensions  Commands for installing extensions
function    Commands for creating and running functions locally
host        Commands for running the Functions host locally
kubernetes  Commands for working with Kubernetes and Azure Functions
settings    Commands for managing environment settings for the local Functions host
templates   Commands for listing available function templates

Actions: 
start   Launches the functions runtime host  
    --port [-p]        Local port to listen on. Default: 7071
    --cors             A comma separated list of CORS origins with no spaces. Example: https:\functions.azure.com,https:\functions-staging.azure.com
    --cors-credentials Allow cross-origin authenticated requests (i.e. cookies and the Authentication header)
    --timeout [-t]     Timeout for on the functions host to start in seconds. Default: 20 seconds.
    --useHttps         Bind to https:\localhost:{port} rather than http:\localhost:{port}. By default it creates and trusts a certificate.
    --cert             for use with --useHttps. The path to a pfx file that contains a private key
    --password         to use with --cert. Either the password, or a file that contains the password for the pfx file
    --language-worker  Arguments to configure the language worker.
    --no-build         Do no build current project before running. For dotnet projects only. Default is set to false.
    --enableAuth       Enable full authentication handling pipeline.
    --functions        A space seperated list of functions to load.
    --verbose          When false, hides system logs other than warnings and errors.

new     Create a new function from a template. Aliases: new, create
    --language [-l]  Template programming language, such as C#, F#, JavaScript, etc.
    --template [-t]  Template name
    --name [-n]      Function name
    --authlevel [-a] Authorization level is applicable to templates that use Http trigger, Allowed values: [function, anonymous, admin]. Authorization level is not enforced when running functions from core tools
    --csx            use old style csx dotnet functions

init    Create a new Function App in the current folder. Initializes git repo.  
    --source-control       Run git init. Default is false.
    --worker-runtime       Runtime framework for the functions. Options are: dotnet, node, python, powershell, custom
    --force                Force initializing
    --docker               Create a Dockerfile based on the selected worker runtime
    --docker-only          Adds a Dockerfile to an existing function app project. Will prompt for worker-runtime if not specified or set in local.settings.json
    --csx                  use csx dotnet functions
    --language             Initialize a language specific project. Currently supported when --worker-runtime set to node. Options are - "typescript" and "javascript"
    --managed-dependencies Installs managed dependencies. Currently, only the PowerShell worker runtime supports this functionality.

logs    Gets logs of Functions running on custom backends  
    --platform Hosting platform for the function app. Valid options: kubernetes
    --name     Function name\Microsoft.Azure.Functions.ExtensionBundle.Workflows'

Version: 0.0.14
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

**Comment by vikash-anand** [comment]
Hi @hmntrathore What version of Azure function core tools are you using? Can you please update your functions core tools to version 3.0.3477 (https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.3477) or higher?
Let us know if the issue exists.

**Comment by hmntrathore** [comment]
> Hi @hmntrathore What version of Azure function core tools are you using? Can you please update your functions core tools to version 3.0.3477 (https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.3477) or higher?
> Let us know if the issue exists.

Thanks Vikash, updating the Function Core tools resolved this.
