### ISSUE TITLE
"Load More..." option gives error. I have zero Logic Apps within this subscription.

### ISSUE THREAD

**Issue by JeroenLeeflang** [Azure/logicapps#292]
Does this occur consistently? Yes
Repro steps:
1. Click on "Load Mor..."
2. nextPageLink cannot be null or undefined

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 0.0.14
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4633620
fulfilled extension.bundle.js:2:4632662
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by vikash-anand** [comment]
@JeroenLeeflang Unfortunately, we are not able to repro the issue. Can you share a screenshot of the "Load More..." link that you click? Also, what Azure resource are you trying to fetch?

**Comment by JeroenLeeflang** [comment]
See screenshot:

When I click on "Load more...", I get the message in the corner.

![image](https://user-images.githubusercontent.com/17065880/119807944-ec862500-bee3-11eb-863f-a6c93430a0ea.png)

**Comment by devin-simoneaux** [comment]
@JeroenLeeflang are you using the most up-to-date version of the Logic Apps (Standard) VS Code extension?

**Comment by JeroenLeeflang** [comment]
All extension I have are up-to-date. 

I'm not sure whether this is the Logic Apps extension?

It is an overview of all your Azure resources and there I get the error.

**Comment by narenderreddy-satty** [comment]
@JeroenLeeflang are you still facing the issue?

**Comment by narenderreddy-satty** [comment]
@JeroenLeeflang there has been no contact from you on this issue, and this leads us to believe that the problem no longer exists or you have other more pressing business priorities. I will go ahead and close this thread for now.
