### ISSUE TITLE
XSLT 2.0 functions supported in Transform XML for Logic Apps (Standard)

### ISSUE THREAD

**Issue by PiMaik** [Azure/logicapps#293]
Hi, issue with running the Transform XML in Logic Apps (Standard) workflow using XSLT 2.0 function, was using fn:current-dateTime() but got an error:

`{"error":{"code":"InvalidXsltContent","message":"An error occurred while transforming the given input with the provided map. Details: ''current-dateTime()' is an unknown XSLT function.'."}}`

Could not find any information if the Logic Apps (Standard) supports XSLT 2.0 or 3.0 and when uploading maps there is no option for specifying which version the map is using, as is the case with map uploads in the integration account for usage in Logic Apps (Consumption) version.

Cheers!

**Comment by zhangadreedom** [comment]
Hello @PiMaik, can you attach some screenshots for which action you are using to transform XML  in Logic Apps (Standard)?

**Comment by PiMaik** [comment]
Hi,

Like this?
![image](https://user-images.githubusercontent.com/60649133/121342968-7db4bd00-c922-11eb-8e65-7228b7b558ab.png)

**Comment by zhangadreedom** [comment]
> Hi,
> 
> Like this?
> ![image](https://user-images.githubusercontent.com/60649133/121342968-7db4bd00-c922-11eb-8e65-7228b7b558ab.png)

Hello @PiMaik, thanks for reporting this issue. We have checked with the Logic App Product Team that Logic App Standard doesn't support XSLT 2.0 at this moment, but it is in the road-map. current-dateTime() is a native function which only supports with XSLT 2.0.

**Comment by shailesh-agre** [comment]
This similar to [291](https://github.com/Azure/logicapps/issues/291)
