### ISSUE TITLE
Show the error 'message' part of the error in run history for Logic Apps (Standard)

### ISSUE THREAD

**Issue by PiMaik** [Azure/logicapps#294]
Hi, when running the new Logic App (Standard) (preview) and getting an error, in this case in the Transform XML, the only information presented in the run history is the 'code' part of the actual error message, that is `InvalidXsltContent` which isn't much.
It would be great and a big help if the 'message' part of the error was also available, in this case: `An error occurred while transforming the given input with the provided map. Details: ''current-dateTime()' is an unknown XSLT function.'.`

Thanks!

**Comment by saroja-sattigeri** [comment]
Currently custom dll for XSLT transform logging is not supported in logic app standard however, item has created to address the behavior and will update once it is in place.

**Comment by saroja-sattigeri** [comment]
similar to issue #291
