### ISSUE TITLE
[DevOps] Guidance for Connection deployments for multiple environments

### ISSUE THREAD

**Issue by GFPhillips** [Azure/logicapps#297]
Hi All,

After going through the sample from:

https://github.com/Azure/logicapps/tree/master/azure-devops-sample

and Generate-Connections.ps1

https://github.com/liliankasem/logicapps/blob/main/.pipelines/scripts/Generate-Connections.ps1

I was wondering if the process for deploying the connections.json has changed following the general release of V2? - Basically, did a way to abstract this connection.json creation process been proposed?

I am asking this because this is what understand what it will do based on the current setup:

- We need to run the CI pipeline per environment - Ideally would be better to have a single package that is created that it can be re-used through all stages/environments
- serviceProviderConnections are not created as part of the CI/CD process? (i.e. Service bus)
- Will need to modify Generate-Connections.ps1/Get-FunctionConnections to work with functions outside the same resource group and add filters for specific functions? - Not every single function from the resource group would be used by logic apps.

Thanks!

**Comment by Bec-Lyons** [comment]
Hi @GFPhillips yes it has been updated. You can now parameterize your connections.json file, meaning you will have one connections.json file and multiple parameter files which you can promote per environment. You can also call app settings from your parameter files. https://docs.microsoft.com/en-us/azure/logic-apps/parameterize-workflow-app here are the docs for parameterisation and please refer to this azure sample to see an example of using multiple parameter files https://github.com/Azure-Samples/digital-integration-hub/tree/master/logic.  The steps are now: 
- develop your logic app
- move any variable that changes between environments (connection API, ID, endpoint URL, Auth object) into parameters.json. From here you can reference app settings if needed 
- Once you have tested everything locally, you can then check in your project to source control and in your CI/CD pipelines swap out your parameter files with your other environment variables.

**Comment by GFPhillips** [comment]
Thanks @Bec-Lyons we will revise and try implementing on our CI/CD pipelines. - Will close this and raise an issue if we encounter something.
