### ISSUE TITLE
Unauthorized calling Azure Function

### ISSUE THREAD

**Issue by matslo** [Azure/logicapps#30]
Calling function from logic app suddenly returns "Unauthorized". When adding header x-functions-key with the function key response is "Ok".

This worked without the function key before 05.09.

I can't find any documentation regarding this change.

The function is running on version 2.0.12050.0.

![image](https://user-images.githubusercontent.com/5337287/45155308-dc313780-b1da-11e8-8239-cb079d305823.png)

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
