### ISSUE TITLE
Log analytics workspace with Logic Apps standard not working

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/logicapps#300]
Hi I have a question.

Currently, with the Logic Apps Consumption based model, we're using Log Analytics with the Logic Apps solution
![image](https://user-images.githubusercontent.com/7938059/120295927-e8814b00-c2c7-11eb-8c0e-42da62c3d559.png)
![image](https://user-images.githubusercontent.com/7938059/120295945-edde9580-c2c7-11eb-966d-182004de09c0.png)

For consumption based, this gives us a lot of information on the runs on Logic Apps and overall health, failures and tracked properties in a very nice and manageable manner.
For consumption based, you currently configure it in the workflow itself and you select the log option "Workflow runtime".
![image](https://user-images.githubusercontent.com/7938059/120296277-401fb680-c2c8-11eb-9986-9a2046a0b4b3.png)
![image](https://user-images.githubusercontent.com/7938059/120296335-4ca40f00-c2c8-11eb-96d6-664a1fee00f8.png)

With the standard version of Logic Apps Standard, you connect the App Service, via diagnostics to a Log Analytics workspace, you send the function App Logs. While we see that it sends the data to Log Analytics, the information is not visible in the Logic App solution.
![image](https://user-images.githubusercontent.com/7938059/120296498-7b21ea00-c2c8-11eb-959a-21daacdea504.png)

Any idea if this will be resolved somewhere soon? We would like to move to Logic App Standard, but missing this functionality is a showstopper from maintenance and support perspective.

And while you can see some stuff in application insights (https://techcommunity.microsoft.com/t5/integrations-on-azure/azure-logic-apps-running-anywhere-monitor-with-application/ba-p/2003332), it's still not as good as the log analytics solution.

Looking forward to responses/plans for this functionality.

**Comment by SahinOzdemir** [comment]
@hongzli Could you perhaps help us on this?

**Comment by zhangadreedom** [comment]
Hi @SahinOzdemir, the Log analysis workspace functionality migration from consumption to standard is in progress, we will support more feature as well. Please let us know which feature you are more interested in, we will collect them and report to Product team to set the priority.

**Comment by zhangadreedom** [comment]
Hi @SahinOzdemir, Thanks for you feedback, we will check this with Product team. Please let us know which feature you are more interested in, we will collect them and report to Product team to set the priority.

**Comment by SahinOzdemir** [comment]
Hi @shailesh-agre if we were able to push the workflow runtime to the log analytics workspace with the logic apps solution installed, we should be able to see the same information in log analytics as it is now with logic apps consumption.

Having that said, things like the workflow statuses, amount of runs during timeframe, tracked properties and the individual steps per run are thing that my client is waiting for.

Is this something you can take to the product team?

**Comment by zhangadreedom** [comment]
Hello @SahinOzdemir, I am checking this with Product Team now.

**Comment by assyadh** [comment]
Hi @SahinOzdemir ,

We don't support Log Analytics Workspaces for now as we have chosen to enable a first party integration with Application Insights. This integration adds what Log Analytics Workspaces offers (logs and metrics to build alarms with) in addition with other Application Insights useful features (request correlation, application map, live metrics etc..).

Here are two blog posts that explain how to onboard/enable Application Insights and have a few sample queries for logs and tracked properties:

https://techcommunity.microsoft.com/t5/integrations-on-azure/azure-logic-apps-running-anywhere-monitor-with-application/ba-p/1877849
https://techcommunity.microsoft.com/t5/integrations-on-azure/azure-logic-apps-running-anywhere-monitor-with-application/ba-p/2003332

Thanks,

H

**Comment by umashankarsharma** [comment]
That's unfortunate. It was so good when consumption based workflows appear on the portal, and all runs were easily tracked by Monitoring team based on tracking ID. Sad to hear :( .
