### ISSUE TITLE
Not able to retrieve Workflow URL from ARM template

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/logicapps#301]
We're having difficulties with retrieving the workflow URL in logic app standard through the ARM template. We need this in order to register an event grid subscription for the logic app trigger in event grid.

With consumption based logic apps we'd use ListCallbackUrl in the ARM template and it would retrieve the correct url.
With standard, this not seems possible. Also tried to see if listsecrets and listkeys could be of any help, but unfortunately we're stuck

![image](https://user-images.githubusercontent.com/7938059/120487490-4db36a00-c3b6-11eb-9de4-571006676a37.png)

It would be possible to concatenate the url in ARM, but the we need to know how to get the SIG (sas token) part of the url.
&sig=<SAS>

Any help on this would be really helpful, since we're not able to find it in the documentation.

AB#16391584

**Comment by SahinOzdemir** [comment]
@hongzli or anyone else know how to do this?

**Comment by GFPhillips** [comment]
Also having the same issue since standard the logic apps are of type "Microsoft.Web/sites" . Also tried Invoke-AzResourceAction to listsecrets but no luck.

We need this so we can setup the backend URL policies on APIM through our CI/CD pipelines

**Comment by NikolaiBlackieKiwirail** [comment]
Ok this seems to work

az rest --method post --uri https://management.azure.com/subscriptions/$(ResourceGroupName)/resourceGroups/$(ResourceGroupName)/providers/Microsoft.Web/sites/$(LogicAppName)/hostruntime/runtime/webhooks/workflow/api/management/workflows/$(YourWorkflow)/triggers/manual/listCallbackUrl?api-version=2018-11-01

**Comment by SahinOzdemir** [comment]
> Ok this seems to work
> 
> az rest --method post --uri https://management.azure.com/subscriptions/$(ResourceGroupName)/resourceGroups/$(ResourceGroupName)/providers/Microsoft.Web/sites/$(LogicAppName)/hostruntime/runtime/webhooks/workflow/api/management/workflows/$(YourWorkflow)/triggers/manual/listCallbackUrl?api-version=2018-11-01
> 
> edit: would be nice to have the ARM template method =)

Good to know that it can be done through the management API! 

Nevertheless, if you have a lot of logic apps and you have need to do a lot of rest calls and passing it to arm template, the process becomes unnecessary complex in Azure devops.

Also found out that you still cannot create an event grid topic subscription with this url, it ends in an error.

**Comment by jaap-vdijkeM10** [comment]
Anyone found a way to retrieve the SIG [sas token] of a Logic App Standard workflow via listCallbackURL in ARM/Bicep? 

This expression returns a 'Not Found' error:
listCallbackURL('${resourceId(ResourceGroupName, 'Microsoft.Web/sites/workflows', 'LogicAppName>', 'WorkflowName')}/triggers/manual', '2022-03-01').queries.sig

**Comment by SahinOzdemir** [comment]
I think this is still an open issue. Haven't seen any updates other than using the rest API since I had opened it.

**Comment by arjendeblok** [comment]
This is still an issue. I am having the same problem. You can list secrets from consumption logic apps but not from logic app standard.

**Comment by arjendeblok** [comment]
This is still an issue. I am having the same problem. You can list secrets from consumption logic apps but not from logic app standard.
