### ISSUE TITLE
Cannot create event grid topc subscription based on workflow url - handshake fail

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/logicapps#302]
Just tried to create an event grid topic subscription manually, since we can't get the full workflow URL currently.
When doing so, based on the full workflow URL, event grid topics subscription gives the following error:
![image](https://user-images.githubusercontent.com/7938059/120529322-a85fbc80-c3dc-11eb-913c-524b440cc014.png)

A lot of our logic apps work on an event based model, with egt triggers. Any idea how to solve this?

**Comment by SahinOzdemir** [comment]
@hongzli do you know if this an known bug currently?

**Comment by SahinOzdemir** [comment]
Seems that this can be closed.
Event Grid topics need to be added to the CORS section of the app service in order to create the subscription in event grid.

![image](https://user-images.githubusercontent.com/7938059/120532243-c67aec00-c3df-11eb-8419-7c67b3d9e93e.png)

**Comment by WillCasc** [comment]
Hi @SahinOzdemir.
This is a known limitation as of now. We are looking into what is the best way to support this on the new Logic Apps Standard.
Please check the following doc: WebHook Event delivery - Azure Event Grid | Microsoft Docs . It says “If you're using any other type of endpoint, such as an HTTP trigger based Azure function, your endpoint code needs to participate in a validation handshake with Event Grid”. If we modify the Workflow with Response action to return the response with Validation code sent in request for validation and able to successfully create the Event Grid Subscription.
![Event Grid](https://user-images.githubusercontent.com/85908703/121969743-26ec2080-cd32-11eb-8d68-b6cd0768d89b.png)

**Comment by SahinOzdemir** [comment]
@WillCasc thanks for letting me know. We have implemented the http validation last week and this seems to work. Needless to say that it would be better to be able to use the out of the box triggers for this. Hopefully the product team will find a viable solution somewhere soon!
