### ISSUE TITLE
getting this error when i select language to initialize in vs code for logic app when i try to publish my existing logic app

### ISSUE THREAD

**Issue by sidwar76** [Azure/logicapps#303]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 1.0.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:2:4762258
Object.<anonymous> extension.bundle.js:2:4778078
fulfilled extension.bundle.js:2:4777254
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by WillCasc** [comment]
Hello @sidwar76 . Please verify all required extension and Prerequisites are ready in your environment, this is the official doc for you: https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code. if it doesn't work for you, please provide more details like you failed in which steps.
