### ISSUE TITLE
VScode designer loses state when switching tabs

### ISSUE THREAD

**Issue by obiwanjacobi** [Azure/logicapps#309]
Using the new VScode extension for LogicApps (Standard) - the designer loses all unsaved state when you switch to another tab - for instance: to create a new file. This hampers development productivity and is unexpected.

**Comment by ShreeDivyaMV** [comment]
Hi @obiwanjacobi, Sorry for the delay in getting back on this. I verified the above scenario and I could confirm that the state is retained when new tab is opened or we switch to another tab. Could you please verify if you observe the same behavior with the latest version of Azure Logic app  extension(v1.0.2)?

**Comment by ShreeDivyaMV** [comment]
@obiwanjacobi, did you get a chance to verify this in the latest version of Logic app extension?. Please let us know if any further questions

**Comment by obiwanjacobi** [comment]
Just back from vacation. Yes, updated to the latest version fixes the issue. Thanks!
