### ISSUE TITLE
Logic App Designer is useless in Azure Portal.

### ISSUE THREAD

**Issue by enoleainoa** [Azure/logicapps#311]
Usability of Logic Apps Designer via Azure Portal is really really bad. Please revert to the old version and publish a new one when you have done some improvements. Current version is really slow and copy-pasting into text fields is almost impossible. When you click plus sight to add an action, you cant go back from that, but instead you need to select an action and delete it. At least for me this is a big red flag that the usability is going worse and worse in every release and it will eventually lead me to choose other tools.

**Comment by derek1ee** [comment]
Hi @enoleainoa, you should be able to right-click and delete the "Choose an action" card to remove it, without having to first select an action to add. But I've taken this feedback and will see how to improve the experience.

Can you share more info on what you meant by "copy-pasting into text fields is almost impossible"?

For the performance issue, would it be possible for you to share a copy of the workflow so we can take a look at what the issue might be? You can email it to logicappsemail (at) microsoft [dot] com.

**Comment by inaun** [comment]
@derek1ee -- you responded to a point concern. But I want to echo the original feedback from enoleainoa. Logic App Designer in the Azure portal is SO BAD it is almost useless. There are bugs everywhere. I have lost work multiple times due to the bugs. Often when opening a step the parameters simply don't show up, or show up wrong!

I am shocked this was pushed out to GA in the current state. The old designer worked, the new one is broken in so many places it has been made basically worthless.

**Comment by derek1ee** [comment]
Hi @inaun and @enoleainoa, I'd love to learn more so we can prioritize fixing the issues, if you can send me an e-mail with more details, at deli [at] microsoft [dot] com, or [simply grab a 30-minute meeting](https://book.ms/deli@microsoft.com/s/SVRwCe7HMUGxuT6WGxi68g2) so we can chat, that'd be great.

**Comment by tonytang-microsoft-com** [comment]
@inaun / @enoleainoa, are you using logic app standard or logic app consumption? If it's consumption, can you use below URL to switch to the old designer? https://portal.azure.com/?feature.experimentation=false&feature.experimentationflights=cfv2

Mean while, our PM has reached to you in the above post, and it would be great if you could help us understand the issues you are encountering so we could fix the issue.

**Comment by enoleainoa** [comment]
Hi @derek1ee. Thanks for your reply! I'll write you an email about the issues we are encountering in Portal.

@tonytang-microsoft-com Thanks for the link, we will try it out.

**Comment by derek1ee** [comment]
Hi @enoleainoa, did you get the chance to send the email? Just want to make sure I didn't miss it. Thanks.

**Comment by derek1ee** [comment]
Hi @enoleainoa, I'm closing this ticket for the time being, but would still love to hear your feedback. You can send me an e-mail with more details, at deli [at] microsoft [dot] com, or simply grab a [30-minute meeting](https://book.ms/deli@microsoft.com/s/SVRwCe7HMUGxuT6WGxi68g2) so we can chat.
