### ISSUE TITLE
Over the weekend, something changed in regards to the Office 365 Outlook API Connector....

### ISSUE THREAD

**Issue by ebachert** [Azure/logicapps#312]
Prior to the weekend of June 19th, 2021, I have had an Azure LogicApp setup and working properly for well over a year.  It would send the 'Approval' emails as Actionable Messages and would then record the userId of the user that responded/approved and/or denied a given 'Approval' email.  Suddenly, this week, all of my 'Approval' emails are not rendering as 'Actionable Messages' anymore... they are showing as just plain, HTML formatted emails.  Did something change in regards to the Office 365 Outlook managed API connector recently? Specifically in regards to 'Approval' emails and rendering as 'Actionable Messages'?

**Comment by shailesh-agre** [comment]
@ebachert - this appears issue with connector within consumption logic apps. Can you update the action to the latest version and validate? 
Also please look at the notes from documentation in case if it is applicable.
https://docs.microsoft.com/en-us/connectors/office365/

When sending emails with options or approval emails, action card (actionable message) rendering in Outlook will not support HTML in the body message. The rendering behavior depends on the option Use only HTML message:

If set to Yes, all the mail clients will only show the HTML message. The action card will not be rendered.
If set to No, some mail clients will show both action card and HTML message, some mail clients will only show the HTML message. Please refer to the following link regarding the support of action cards in different mail clients: https://docs.microsoft.com/outlook/actionable-messages/#outlook-version-requirements-for-actionable-messages.
