### ISSUE TITLE
Logic App Single-Tenant parameters.json file CI/CD

### ISSUE THREAD

**Issue by GFPhillips** [Azure/logicapps#314]
Hi All,

Two questions regarding parameters.json - https://docs.microsoft.com/en-us/azure/logic-apps/parameterize-workflow-app?tabs=azure-portal

1. Are there any plans for having different **parameters.json** files per workflow? I can see this getting very chunky even if we group our workflows by a common service/destination.
2. Is it possible to specify somewhere a different file name for **parameters.json**? for the workflows to use - i.e. in **appsettings workflow.parameterfilename = parameters.dev.json** . I am asking this, as working for multi-tenant , one can freely use different parameters files per environment. Also, want to use app settings for key vault integration only (or if I REALLY need to) due to the logic apps having to restart on app settings update.

Thanks

George

**Comment by Bec-Lyons** [comment]
Hi George - thanks for the patience on this one. 
1. We have no immediate plans to do so, but it is something that we are aware of. Currently the workaround is to group and differentiate your parameters with a prefix for easier navigation. 
2. You can have multiple param files and differentiate them with .dev etc. but you would need to make sure you swap out your parameter files either at build time or via the CLI like so:  az functionapp deploy --resource-group <your rg> --name <your name> --src-path  <path>/test.parameters.json --type static --target-path parameters.json
