### ISSUE TITLE
Forced to set edifact qualifiers for "encode by identities"

### ISSUE THREAD

**Issue by mystiqu** [Azure/logicapps#316]
When working with the logic app actions for edifact decode and "encode by identities", there seems to be some inconsistencies in how the qualifiers are used.

If you have a partner with multiple identities, we need to use "encode by identities" in order to dynamically create edifact messages based on business identities in our business message.

**Sample from eidfact partner in integration account**
 "businessIdentities": [
     {
         "qualifier": "ZZ",
         "value": "372051318"
     },
     {
         "qualifier": "ZZ",
         "value": "372051319"
     },
     {
         "qualifier": "ZZ",
         "value": "372051320"
     },
     {
         "qualifier": "ZZ",
         "value": "372051321"
     }
     
     
However, that only works if the qualifiers are included (they are optional) or if they are removed all together from the partner profile in the integration account.

But, removing them makes the decode action fail, since the decode action seems to look at the qualifiers (which makes sense) in the edifact message in order to determine sender and receiver.

**Edifact: Encode by identities**
![image](https://user-images.githubusercontent.com/26870936/122916609-5cf65980-d35d-11eb-9fd7-29b1b0fb0c75.png)

**Edifact: Decode**
![image](https://user-images.githubusercontent.com/26870936/122917090-ec9c0800-d35d-11eb-8d8d-4f04e8aa22ad.png)

When encoding an edifact message, it feels weird to be forced to store the qualifiers in a table to provide them as input to the service. I could just store the actual name of the agreement to use instead - but that  would defeat its purpose since I should be able to just send in the identifiers (as part of the business document).

**Comment by shailesh-agre** [comment]
@ mystiqu While using multiple identifies, to figure out agreement those specific values will be needed (or agreement needs to specified directly). Can you please elaborate the ask / requirement in more detail?

**Comment by shailesh-agre** [comment]
@mystiqu Once you provide more details about the requirement, we can take it forward. I will close the issue till then.

**Comment by mystiqu** [comment]
Hi

Really sorry for the lack of response, I've been on vacation and off the grid.
Is it possible to reopen this issue?

**Some additional details**:
When we receive an edifact message (if we have multiple identities for a partner), we need to provide the qualifiers for the decode step to successfully find a matching agreement. 

That require us to create a lookup table with partners and which qualifiers to use for the various identities.
But, this is what the partner section is for in the Integration Account - what good is that if I need to create an additional data store to store the same information?

The identifiers should be partner unique and this not be needed for the decode action - unless you have the unique situation where you have two partners with the same identifier but different qualifier - pretty rare I would say.
