### ISSUE TITLE
Add proper resubmit information in the portal and in the logic app instance

### ISSUE THREAD

**Issue by mystiqu** [Azure/logicapps#317]
When doing a resubmit for a specific logic app instance,, there is a lot if information missing - both from a portal perspective but also from within the logic app. This is crucial both from development perspective, but also from a maintenance/operations perspective.

This is basic functionality that really needs bigger attention and something that pretty much very other integration platform have had for the last decades.

**1) The portal**
The portal MUST show that a particular instance has been resubmitted, when and how many times
All resubmit should have the same "main instance id", while each resubmit gets a new instance id..

**2) Within a logic app execution**
It must be possible to detect a resubmit (during the execution) as well in case of situations when things cannot rolled back in case of an error, or if we just want to highlight (e.g. post a notification) that we have a resubmit.
Currently, we can only get the normal execution id via @{workflow()['run']['name']}

**Sample portal view**
![Microsoft Logic App resumit sample](https://user-images.githubusercontent.com/26870936/124171092-65126f80-daa8-11eb-82ec-28c73f18b791.png)

**Comment by shailesh-agre** [comment]
@mystiqu kindly request you to provide the feedback here - https://feedback.azure.com/forums/287593-logic-apps
Meanwhile, if you have a need for monitoring purpose, please have a look at the following blog - it provides APIs and logic to resubmit the runs. You may modify the code to suit your requirements.
https://techcommunity.microsoft.com/t5/integrations-on-azure/logic-app-utility-to-perform-bulk-operations-on-workflow-runs/ba-p/2258241
