### ISSUE TITLE
Open in Designer opens blank canvas if Logic App was just created

### ISSUE THREAD

**Issue by pierceboggan** [Azure/logicapps#319]
After creating a Logic App and opening it in the Visual Studio Code extension, Open in Designer opens a blank canvas, making it difficult for the user to know what to do next:
![image](https://user-images.githubusercontent.com/1091304/124058001-c45b7b80-d9e5-11eb-8eb7-850e7aa8b9e1.png)

Expectation: If Logic App is empty, I'm prompted to create a trigger (just like in the web designer in the Azure portal).
Reality: If Logic App is empty, blank canvas opens.

**Comment by colinrippeyfinarne** [comment]
I'm seeing the same thing. I see this blank screen behaviour if I create a new Logic App and also if I choose a Logic App I have previously created in the portal.

**Comment by vikash-anand** [comment]
@pierceboggan Can you check the logs and let us know if you notice any errors? You can view the logs in the output window i.e. view -> output and then select Azure logic Apps(Standard) on the dropdown.

@colinrippeyfinarne Can you do the same as above for local project? For the project created in portal, we make some api calls. Can you share the fiddler trace of the api calls? and let us know if you see any failures in the api calls?

**Comment by pacodelacruz** [comment]
@vikash-anand , what else can we do for troubleshooting when the designer opens a blank canvas with no functionality? 

I have had many attempts trying to make the designer work on my workstation, but I've had no luck. 
I have all the prerequisites in place and have followed all the instructions on [this page](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#set-up-visual-studio-code)
The local project was initialised using the VS Code extension. 

Below is what I get in the output logs. 

```
Azure Functions Core Tools
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
Function Runtime Version: 3.0.15828.0

[2021-07-22T00:55:57.743Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
For detailed output, run func with --verbose flag.
```

Not sure whether `No job functions found` is an issue at all or not? 

Are there any security or firewall configurations that must be in place? 

Any advice would be appreciated! 

Thanks,

**Comment by influential-eliot** [comment]
Sorry to add a note here, but this should be raised as a change somewhere, surely?

In the 'incident'-->'workaround' and 'problem'-->'fix' approach ... this is surely something that should be working without us having to look up this workaround online, no?
