### ISSUE TITLE
AS2 Decode: No MDN is generated when payload cannot be decoded

### ISSUE THREAD

**Issue by mystiqu** [Azure/logicapps#322]
If the payload cannot be decoded (but everything else is ok like headers, partners etc), no MDN is generated.
Since there is no "AS2 Generate MDN" action where you can add parameters like original message id, fault reason, parter information etc, the decode action needs to generate an MDN on failures as well since most partners expect an MDN to be generated and sent with status success or an error message.

Currently, this is not working using Azure Integration Account and the built-in AS2 decode action.
I would expect an MDN like below.

**MDN Sample**
```
--_fec6e8ce-7a75-4db3-8db9-027d84e8c402_
Content-Type: multipart/report;report-type="disposition-notification";boundary="_1a93f591-0423-4f66-9893-7a5ef0a02a15_"

--_1a93f591-0423-4f66-9893-7a5ef0a02a15_
The message could not be processed

--_1a93f591-0423-4f66-9893-7a5ef0a02a15_
Content-Type: message/disposition-notification

Final-Recipient: rfc822; <AS2RECEIVERIDENTIFIER>
Original-Message-ID: <RD0003FF7281F2_EDCFFCFF-B40A-452F-B846-E224109F1F8C>
Disposition: automatic-action/MDN-sent-automatically; processed/Error: Could not parse message

--_1a93f591-0423-4f66-9893-7a5ef0a02a15_--

--_fec6e8ce-7a75-4db3-8db9-027d84e8c402_
Content-Type: application/pkcs7-signature;name="smime.p7s"
Content-Transfer-Encoding: base64

MDN signature here....

--_fec6e8ce-7a75-4db3-8db9-027d84e8c402_--
```

**Comment by shailesh-agre** [comment]
@mystiqu For normal protocol errors, generally the MDN is returned. Can you please provide more details about the error message? Possibly sharing the output of the decode action.

**Comment by shailesh-agre** [comment]
@mystiqu Once you provide the error details, we can check further. Also this appears to be generic issue with AS2 connector. In case it is urgent, kindly request you to open support ticket with the Logic Apps team.
