### ISSUE TITLE
New logic app flow SQL execute stored procedure does not retreive parameters from stored procedure

### ISSUE THREAD

**Issue by gs9824** [Azure/logicapps#324]
Using the new logic apps runtime public preview 

When adding a Execute Stored Procedure step, parameters defined in the stored procedure are not retreived automatically. There is only 'Raw inputs'. In the previous version, parameters defined in the selected stored procedure were automatically retreived and listed.

The issue does not appear on the 'old' logic apps flow designer 

![image](https://user-images.githubusercontent.com/36197920/124743917-821ec680-df1e-11eb-9a8c-01f20cb30699.png)

**Comment by shailesh-agre** [comment]
@gs9824 I have tested this and it is working fine.
![image](https://user-images.githubusercontent.com/61179796/124877582-d9896900-dfe8-11eb-9f0b-806e4808723a.png)
Are you using portal or other client tools like VS?
The Standard Logic App is now GA. If using on portal directly, have you tried to create new GA version and test?

**Comment by gs9824** [comment]
@shailesh-agre

I can confirm it now works - could have been a temporary glitch

Closing the issue
