### ISSUE TITLE
source-pipeline-azure-devops

### ISSUE THREAD

**Issue by jaysson1710** [Azure/logicapps#326]
Hi, 
the link to azure devops example doesn't work, could you paste of pipeline example into current repository?
tnks

**Comment by shailesh-agre** [comment]
@jaysson1710 to be sure, can you please provide the exact document link and if applicable relevant section information?

**Comment by gcmlpfaltaher** [comment]
Running into the same issue.  The link the readme points to is: https://dev.azure.com/logicappsdemo/Logic%20Apps%20v2%20Sample/_build?view=folders

The file is the README.md for the azure-devops-sample project.  The line is referenced on is 118

**Comment by shailesh-agre** [comment]
Thanks @gcmlpfaltaher. So you are referring to https://github.com/Azure/logicapps/tree/master/azure-devops-sample
![lastandarddevopssample](https://user-images.githubusercontent.com/61179796/126741593-4022ab5c-add3-4925-9468-b3151c3783fa.png)
I will contact the owner and will provide updates.

**Comment by Bec-Lyons** [comment]
Hi folks, the link is updated and should look like so: https://dev.azure.com/liliankasem/Logic%20Apps%20v2%20Sample/_build?view=folders. Let me know if that works for you.
