### ISSUE TITLE
Logic Apps (Standard): how to enable Azure AD OAuth authentication?

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/logicapps#328]
I am using the new _single-tenant_ Logic Apps **(Standard)** resource type and I would like to enable [Azure AD OAuth authentication](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app?tabs=azure-portal#enable-azure-active-directory-open-authentication-azure-ad-oauth) (Azure Active Directory Open Authentication) for an incoming HTTP trigger configured on the workflows. This is already possible for the _multi-tenant_ (Consumption) resource type, but I cannot find a way to achieve the same for the _single-tenant_ resource type. How can I do this?

Related: https://github.com/MicrosoftDocs/azure-docs/issues/78262

**Comment by ecfan** [comment]
Hi @gastonmuijtjens, 

Azure AD OAuth is currently unavailable for inbound requests using the Logic Apps (Standard) resource type in single-tenant Azure Logic Apps. The docs are being updated to note this status.
