### ISSUE TITLE
WorkFlowActionCompleted has greater Time than WorkFlowRunCompleted

### ISSUE THREAD

**Issue by grik001** [Azure/logicapps#33]
Hi,

I am using the diagnostics setting that is pushing to EventHub. After pulling from EH using an Azure Function, I have noticed that some events are not in order(when I say not in order, I am referring to the time property not the actual order in the queue). For example WorkFlowActionCompleted has greater Time than WorkFlowRunCompleted.

Is this behavior by design?

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
