### ISSUE TITLE
nextPageLink cannot be null or undefined.

### ISSUE THREAD

**Issue by jiyongseong** [Azure/logicapps#332]
Does this occur consistently? Yes
Repro steps:

1. click "Load More" menu on the Visual Studio Code toolbar

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.1
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.58.1
Language: ko

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4633675
fulfilled extension.bundle.js:2:4632717
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by mbarqawi** [comment]
can you share Screenshot?

**Comment by jiyongseong** [comment]
![image](https://user-images.githubusercontent.com/17041566/125806902-58e41ad3-263c-4171-ab24-16008de61f3e.png)

**Comment by mbarqawi** [comment]
do you have this error for all subscriptions?
can you capture the fiddler trace? and open a support ticket 

the action that you need to search for is 
GET https://management.azure.com/subscriptions/00000/providers/Microsoft.Web/sites

**Comment by jiyongseong** [comment]
do you have this error for all subscriptions? > Yes

**Comment by cuntoulishifu** [comment]
I run into the same problem, any updates?
