### ISSUE TITLE
Allow chunked transfer-encoding for Request trigger

### ISSUE THREAD

**Issue by doggy8088** [Azure/logicapps#333]
Refere to https://github.com/dotnet/runtime/issues/55583 and https://feedback.azure.com/forums/287593-logic-apps/suggestions/33616297-implement-chunked-transfer-encoding-inside-logic-a

I'd like to suggest Azure Logic App's Request/HTTP trigger allow chunked transfer-encoding.

**Comment by karelz** [comment]
It looks like current Azure Logic App behavior is violating HTTP spec and therefore it can't be connected to by SDKs (e.g. .NET SDK).

**Comment by shailesh-agre** [comment]
@doggy8088 This is applicable in general for consumption and standard logic. PG has taken this feedback and work item in progress. However, as of today we do not have eta as such.
