### ISSUE TITLE
Logic App (Standard) Workflow Designer not loading. Azure Functions Core Tools reports 'provider' is null

### ISSUE THREAD

**Issue by duyn9uyen** [Azure/logicapps#334]
I'm trying to follow this guide so that I can play with the new Logic App (Standard) workflows in VS Code. https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code

I have _Azurite services_ running (tables, blobs, and queues) but I am unable to view my workflow in Designer. I get the following error from the Auzre Logic Apps (Standard) Output Window.

> 2:22:50 PM: Running command: "func host start --port 8000"...
> Azure Functions Core Tools
> Core Tools Version:       3.0.3477 Commit hash: 5fbb9a76fc00e4168f2cc90d6ff0afe5373afc6d  (64-bit)
> Function Runtime Version: 3.0.15584.0
> Value cannot be null. (Parameter 'provider')
> [2021-07-15T18:25:10.731Z] Host unavailable after check. Returning error.

Windows: 10 Buid: 19042.1110
VS Code: 1.58
VS Azure Logic App Standard extension: 0.22.0
VS Code Azurite extension: 3.13.1
Azure Functions Core Tools: 3.0.3477

**Comment by IainAdamsLabs** [comment]
I have the exact same problem. I am just trying to create my first standard logic app. Followed the tutorial and get the same error. The version of Azure Functions Core Tools is the same.

```
Azure Functions Core Tools
Core Tools Version:       3.0.3477 Commit hash: 5fbb9a76fc00e4168f2cc90d6ff0afe5373afc6d  (64-bit)
Function Runtime Version: 3.0.15584.0

[2021-07-28T22:38:06.602Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-07-28T22:38:06.602Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.
Value cannot be null. (Parameter 'provider')
[2021-07-28T22:40:21.191Z] Host unavailable after check. Returning error.
```
Mac OS X Catalina 10.15.7
VS Code: 1.58.2
VS Azure Logic App Standard extension: 1.0.2
VS Code Azurite extension: 3.14.0
Azure Functions Core Tools: 3.0.3477

**Comment by vikash-anand** [comment]
@duyn9uyen The function host is not starting on your machine. Logic App designer needs the function host to be running for the designer to load. Can you take a look at this issue: https://github.com/Azure/azure-functions-core-tools/issues/2232 There are some workarounds suggested to start the Function host.

Let us know if you are not able to fix this.
