### ISSUE TITLE
Logic Apps (Standard): cannot access query and path parameters from HTTP trigger outputs

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/logicapps#335]
I have a _single-tenant_ Logic App **(Standard)** with a HTTP request trigger. In a subsequent action I want to access the query parameters of the invoked URL from the request trigger. When I try to access the query parameters using `@triggerOutputs()['queries']` (as suggested by the designer) I'm getting the following error:

```
System.Private.CoreLib: Exception while executing function: Functions.WorkflowDispatcher. Microsoft.Azure.Workflows.Worker.Common: Unable to process template language expressions in action 'Initialize_variable' inputs at line '1' and column '1410'. Current flow run operation failed. Exception: '***sanitized***'.
```

Directly accessing `triggerOutputs()`variable only outputs headers.

My workflow.json definition:

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Initialize_variable": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "queryParameters",
                            "type": "string",
                            "value": "@{triggerOutputs()['queries']}"
                        }
                    ]
                },
                "runAfter": {}
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {},
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```

Is there any way to access query parameters (and path parameters) from a HTTP request trigger in a _single-tenant_ Logic App **(Standard)** workflow?

**Comment by shailesh-agre** [comment]
Is ['queries'] empty? you may use  question mark to avoid the error in case of empty values. 
"value": "@{triggerOutputs()?['queries']}"

**Comment by gastonmuijtjens** [comment]
@shailesh-agre My bad, I was assuming the predefined query parameters (i.e. `api-version`, `sp`, etc.) to be also present in the `queries` trigger outputs. Appending a custom query parameter actually does allow access from the trigger outputs, just verified. Thanks for your help, I will close this issue.
