### ISSUE TITLE
Logic Apps (Standard) manage API Connection access policy via Powershell?

### ISSUE THREAD

**Issue by originalRoze** [Azure/logicapps#337]
Hello,
We are planning rather complex Logic App (Standard)  "cluster", which will, possibly, contain up to couple hundred Logic Apps.
To avoid overcomplicating Access Policy Management, we are granting all the Logic Apps access to all API Connections via ARM Template. This is somewhat doable at the current "stage" (4 Logic Apps, 3 Storage Accounts, 2 ServiceBuses), but at larger scale this will be extremely painful to maintain. 
We have an idea, that similarly to "GenerateConnections.ps1", we would generate "Access Policies" for all resources within specific RG scopes via PowerShell script during IaC deployment. However cannot find any documentation, nor examples on how to grant Access for Microsoft.Web/connections. From UI, you simple add by supplying ObjectId, when trying to somewhat replicate this from shell with New-AzRoleAssignment, we are asked to provide "RoleDefinitionName", which is unclear for this type of resource.

Is it possible to add Access Policies for Logic App API Connections via Powershell?

P.S - Dont ask why or how we need this cluster.....

**Comment by originalRoze** [comment]
Just wanted to add, that after more testing, were able to create new Access Policy via this snippet. I am partial to ps scripting, so please be gentle:

        $Properties  = @{
            principal = @{
                type = "ActiveDirectory"
                identity = @{
                    tenantId = "{tenantId}"
                    objectId = "{objectId}"
            }
        }
    }
        $Name = "{APIConnectorName}/{objectId}"
 New-AzResource -Location "{location}" -ResourceGroup "{ResourceGroupName}" -ResourceType "Microsoft.Web/connections/accessPolicies" -ResourceName $Name -Properties $Properties

**Comment by shailesh-agre** [comment]
@ originalRoze Does that mean this issue is resolved now? or do you have further queries?

**Comment by originalRoze** [comment]
@shailesh-agre Yes, it can be considered as resolved. Maybe as future improvement official script could be also provided, same as for GenerateConnections.ps1.

Adding our simpleton [script ](https://github.com/originalRoze/LogicApps-Standard/blob/main/CreateAccessPolicies.ps1), in case someone needs it or wants to build on it.

**Comment by srih1rsh1** [comment]
Hello,
I have tried the PowerShell which you have mentioned 
when i am trying to use the resource Type or Azure Namespace "Microsoft.Web/connections/accessPolicies"
it is not working 

New-AzResource: {"message":"No HTTP resource was found that matches the request URI 'https://eastus.logic.azure.com/api/web/subscriptions/*********/resourceGroups/******/providers/Microsoft.Web/connections/***/accessPolicies?api-version=2016-06-01'."}

any help here to create the access policy on Azure api connection using powershell or az cli  or any DSL (ARM,Bicep)
