### ISSUE TITLE
Logic Apps (Standard): HTTP operation auth not supported

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/logicapps#338]
The built-in HTTP operation does not support auth like in Logic Apps v1. This is a blocker for Cx as we needed to be able to do auth to make requests to other Azure resources. This is especially a blocker because ManagedServiceIdentity is not yet supported in v2 (this later became a massive issue as the security team at Cx would only approve our request for Microsoft Graph permissions through something like a managed identity that was tied to the logic app, something not possible at the moment in v2).

### Repro steps
1. Create a HTTP built in operation in a logic app workflow
1. You will see that there is no dropdown option to add auth in the designer
1. Save and navigate to the code view, and update your HTTP operation to include the auth properties
```json
    "authentication": {
        "audience": "@appsetting('mediaServiceAudience')",
        "clientId": "@appsetting('aadServicePrincipalId')",
        "secret": "@appsetting('aadServicePrincipalSecret')",
        "tenant": "@appsetting('aadTenantId')",
        "type": "ActiveDirectoryOAuth"
    },
```
4. Run your logic app

**Actual Result**: You will see a HTTP 500 server error on this operation

**Expected Result**: HTTP request goes through without issues

### Workaround
The product group gave us a workaround for this which was to add this extension to host.json file. This fixed our issue, just logging for insights sake.

    "extensions": {
        "workflow": {
            "settings": {
                "Runtime.OAuth.DefaultAuthenticationAuthority": "https://login.microsoftonline.com/"
            }
        }
    },

<details><summary>Internal tracking</summary>#434824</details>

**Comment by ShreeDivyaMV** [comment]
Sorry for the delay in responding to this.
In the http built in action, there is an option to 'Add new parameter' and choose Authentication.
It gives option to choose AD auth and provide the auth parameters.
Could you verify this and let us know if it helps?
![image](https://user-images.githubusercontent.com/30790938/127148936-0d9c75d4-48de-4495-bfcd-016cd7690c51.png)

**Comment by brandonh-msft** [comment]
cc @liliankasem for input here

**Comment by liliankasem** [comment]
This was an issue from January 2021 when Logic Apps v2 was still in preview, seems to be fixed with them going GA so I think we can just close this.

**Comment by brandonh-msft** [comment]
+1 thanks!
