### ISSUE TITLE
Deleting all the files in a Standard Logic App in Azure creates an invalid hosts.json

### ISSUE THREAD

**Issue by probertdaniel** [Azure/logicapps#339]
This is a very minor bug, but...

When you delete all the files in the Logic App's wwwroot folder, a new _hosts.json_ file is created that has an invalid version reference to the _Microsoft.Azure.Functions.ExtensionBundle.Workflows_ file.

Steps to reproduce:
1) Create a new Logic App.
2) Create a workflow, or upload at least one workflow from VS Code
3) Get the Publish Profile settings, and FTP to the _/site/wwwroot_ folder.
4) Delete the entire contents of that folder
5) A new _hosts.json_ file will be created
6) This _hosts.json_ file has a reference to v2.x of the Workflows extension bundle, which doesn't (yet) exist.

The newly created _hosts.json_ file contains this:

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[2.*, 3.0.0)"
  }
}
```
i.e. load a v2.x bundle. However, the current version of the bundle (as of today's date) is v1.1.19 (in Azure) and v1.1.17 (in VS Code).
When you create a new Logic App (via the portal, or a new project via VS Code), the _hosts.json_ file looks like this:

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  }
}
```
Which correctly selects the v1.1.17/1.1.19 bundle.

If I download the App Content using the portal, open the project in VS Code, and attempt to debug, I get this error:
```
[2021-07-22T16:14:11.827Z] Bundle version matching the [2.*, 3.0.0) was not found
[2021-07-22T16:14:11.835Z] Unable to find or download extension bundle
[2021-07-22T16:14:12.765Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
For detailed output, run func with --verbose flag.
[2021-07-22T16:14:17.996Z] Host lock lease acquired by instance ID '0000000000000000000000008FC77954'.
```

I would argue that anyone who FTPs to their Logic App and deletes all the files, deserves any issues they find, but I thought I'd raise it just in case it causes issues for anyone.
I appreciate that this may also be by design.

Thanks!

**Comment by shailesh-agre** [comment]
@probertdaniel Thank you for reporting the issue. Product group is aware of this issue and this will get fixed.

**Comment by c8fcc946f0** [comment]
Thanks
