### ISSUE TITLE
Diagnostic Events LA to EH

### ISSUE THREAD

**Issue by grik001** [Azure/logicapps#34]
Hi,

Is it possible that LA are not posting all events to EH? I am still investigating this issue but its very hard to debug.

In my scenario I am sometimes missing the WorkFlowRunCompleted.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
