### ISSUE TITLE
Unable to see the map in the XML Transform dropdown

### ISSUE THREAD

**Issue by Nisha-D** [Azure/logicapps#343]
I am using Visual Studio Code, and created a new project. XSLT is created under Artifacts/Maps folder.

but when I try to select that map in the XML Transform action, it is not appearing in the dropdown. 

![image](https://user-images.githubusercontent.com/20060578/127116781-cb856c68-f5d4-4bd6-8bca-d439f666c2ab.png)

**Comment by ShreeDivyaMV** [comment]
Please use the extension as .xslt, for showing up in the dropdown.
The ,xsl file also works, if you click on "Enter custom value" and provide the value manually,

Please update us if any further questions

**Comment by Nisha-D** [comment]
Thank you. Using the extension as .xslt has worked.
