### ISSUE TITLE
Cannot debug using Logic Apps Extensions

### ISSUE THREAD

**Issue by Andrew-MS** [Azure/logicapps#348]
Does this occur consistently?

Yes
Repro steps:
Running debug on Logic APps 

Action: azureLogicAppsStandard.getDebugSymbolDll

Error type: ENOENT
Error Message: ENOENT: no such file or directory, scandir 'C:\Users\---\AppData\Local\Programs\Microsoft VS Code\%%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
Usage: func [context] [context] <action> [-\--options]

Contexts:
azure       Commands to log in to Azure and manage resources
durable     Commands for working with Durable Functions
extensions  Commands for installing extensions
function    Commands for creating and running functions locally
host        Commands for running the Functions host locally
kubernetes  Commands for working with Kubernetes and Azure Functions
settings    Commands for managing environment settings for the local Functions host
templates   Commands for listing available function templates

Actions: 
start   Launches the functions runtime host  
    --port [-p]        Local port to listen on. Default: 7071
    --cors             A comma separated list of CORS origins with no spaces. Example: https:\functions.azure.com,https:\functions-staging.azure.com
    --cors-credentials Allow cross-origin authenticated requests (i.e. cookies and the Authentication header)
    --timeout [-t]     Timeout for on the functions host to start in seconds. Default: 20 seconds.
    --useHttps         Bind to https:\localhost:{port} rather than http:\localhost:{port}. By default it creates and trusts a certificate.
    --cert             for use with --useHttps. The path to a pfx file that contains a private key
    --password         to use with --cert. Either the password, or a file that contains the password for the pfx file
    --language-worker  Arguments to configure the language worker.
    --no-build         Do no build current project before running. For dotnet projects only. Default is set to false.
    --enableAuth       Enable full authentication handling pipeline.
    --functions        A space seperated list of functions to load.
    --verbose          When false, hides system logs other than warnings and errors.

new     Create a new function from a template. Aliases: new, create
    --language [-l]  Template programming language, such as C#, F#, JavaScript, etc.
    --template [-t]  Template name
    --name [-n]      Function name
    --authlevel [-a] Authorization level is applicable to templates that use Http trigger, Allowed values: [function, anonymous, admin]. Authorization level is not enforced when running functions from core tools
    --csx            use old style csx dotnet functions

init    Create a new Function App in the current folder. Initializes git repo.  
    --source-control       Run git init. Default is false.
    --worker-runtime       Runtime framework for the functions. Options are: dotnet, node, python, powershell, custom
    --force                Force initializing
    --docker               Create a Dockerfile based on the selected worker runtime
    --docker-only          Adds a Dockerfile to an existing function app project. Will prompt for worker-runtime if not specified or set in local.settings.json
    --csx                  use csx dotnet functions
    --language             Initialize a language specific project. Currently supported when --worker-runtime set to node. Options are - "typescript" and "javascript"
    --managed-dependencies Installs managed dependencies. Currently, only the PowerShell worker runtime supports this functionality.

logs    Gets logs of Functions running on custom backends  
    --platform Hosting platform for the function app. Valid options: kubernetes
    --name     Function name\Microsoft.Azure.Functions.ExtensionBundle.Workflows'

Version: 1.0.2
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

**Comment by hongzli** [comment]
Hi @Andrew-MS , it looks like you're using an older Azure Functions Core Tools version. Can you try upgrading to version 3.0.3477 (https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.3477) or later, and then trying again?

**Comment by Andrew-MS** [comment]
That got me to this

> Executing task: C:\Program Files\dotnet\dotnet.exe C:\Users\Andrew\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.8.1\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll <

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-C:\Users\Andrew\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.8.1\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
The terminal process "C:\Program Files\dotnet\dotnet.exe 'C:\Users\Andrew\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.8.1\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.


Though I have the extension installed

**Comment by hongzli** [comment]
Can you try this:
1. Delete the folder C:\Users\Andrew.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.8.1
2. Open your workflow in designer
3. Run your workflow again

**Comment by Andrew-MS** [comment]
THat did the trick!
but its launching a earlier version ( I deleted both from folder) any reason for this, or any disadvantage with the older version?
C:\Program Files\dotnet\dotnet.exe C:\Users\Andrew\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.1.19\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll

**Comment by hongzli** [comment]
1.1.19 is actually our latest version, and I don't know where 1.8.1 came from, as we haven't released any version outside of the range 1.1.*. Do you have any ideas on where it could have come from? Did you download it manually by any chance, or did it get there automatically?

**Comment by Andrew-MS** [comment]
I only added from Extensions gallery. Thanks for the background though

**Comment by hongzli** [comment]
Might be a bug somewhere then. Closing this issue as it's now working for you.
