### ISSUE TITLE
Getting error while opening Standard Logic App in Designer mode in VS Code

### ISSUE THREAD

**Issue by AnaghBhatt-TomTom** [Azure/logicapps#349]
**Issue with opening Standard LA in Designer mode**

 Running command: "func host start --port 8000"...
'func' is not recognized as an internal or external command,
operable program or batch file.

Installed all the pre-requisites. Still Designer is not opening.

**Comment by hongzli** [comment]
Hi, it seems like "func", which comes from Azure Functions Core Tools, is not on your PATH variable. If you have successfully installed Functions Core Tools, then restarting your computer may help.

**Comment by AnaghBhatt-TomTom** [comment]
Thanks Hongzli. I already did  this and it worked like a charm.

**Comment by hongzli** [comment]
Great! Closing this issue.
