### ISSUE TITLE
Conflict between Azure Logic Apps (Standard) and Azure Functions VSCode extension - ECONNREFUSED 9091

### ISSUE THREAD

**Issue by HoLengZai** [Azure/logicapps#350]
Hi,

I go the latest version of vscode: 1.58.2
Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

with Azure Functions Core Tools version: 3.0.3477

I have the latest version of Azure Function extension and the new Azure Logic Apps (Standard) too:
(I also use Azurite latest version as I develop Durable Function, no issue with it)

Name: Azure Functions
Id: ms-azuretools.vscode-azurefunctions
Description: An Azure Functions extension for Visual Studio Code.
Version: 1.4.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions

Name: Azure Logic Apps (Standard)
Id: ms-azuretools.vscode-azurelogicapps
Description: Visual Studio Code extension for Azure Logic Apps (Standard)
Version: 1.0.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurelogicapps

Name: Azurite
Id: azurite.azurite
Description: An open source Azure Storage API compatible server
Version: 3.14.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Azurite.azurite

I noticed that if the Azure Logic Apps (Standard) extension is enabled
![vscode_extension_conflict](https://user-images.githubusercontent.com/20622767/127803313-f4f9f1ba-0099-4c10-b95e-75c51a54b1cf.gif)
I got an issue to debug the Azure Durable/ Functions.
Does it seem that the Azure Logic Apps (Standard) got a conflict with the Azure Function extension?
If I disabled the LA extension, no issue as you can see on the GIF.
It looks like that the LA extension detect my Durable Function as a Logic Apps code then ? (Same issue when I open an existing working Azure Function project if LA extension is enabled.
I have never got this issue before installing this new LA (Standard) extension.
When LA (Standard) extension is enabled, my Durable Function project cannot be debugged with an error ECONNREFUSED 9091.

To reproduce:
Install the 3 extensions (Azurite, Azure Function and Azure Logic Apps (Standard) and Azure Functions Core Tools
Enable all extensions
Run Azurite
Create a new Durable/Azure Function project from template.
Run
You will get the error ECONNREFUSED
Repeat the same process without Azure LA (Standard) extension and everything will work as expected

Thanks

Thanks

**Comment by horihiro** [comment]
I have a similar issue on debugging Node.js functions.
If both extensions for Azure Functions and Azure Logic Apps are enabled, the argument `--inspect=9229` is not passed to Node.js worker process when starting the debugger for Azure Function, then VSCode cannot attach the worker process.
If the extension for Azure Logic Apps is disabled, the debugger works normally.

**Comment by shailesh-agre** [comment]
Have you tried to use the latest extension? And does issue still reproduce?

**Comment by horihiro** [comment]
@shailesh-agre [my above issue](https://github.com/Azure/logicapps/issues/350#issuecomment-903032615) still happened even though both extensions are updated to the latest.

**Comment by shailesh-agre** [comment]
@horihiro Product group found some discrepancies with the extension. They  are working to fix it. Will update here.

**Comment by horihiro** [comment]
@shailesh-agre Thank you for letting me know this. I'm looking forward to a new release of this extension which is fixed.
