### ISSUE TITLE
[Unexpected Error: Failed to Fetch] Logic App (Standard) is not able to display the execution details from the run history for any steps.

### ISSUE THREAD

**Issue by ns616** [Azure/logicapps#351]
I have a Standard logic app workflow. It runs fine and is able to perform the work, However, when I try to check the run history all the steps show Unexpected Error: Failed to Fetch. How can this be resolved?

**Comment by mdeery** [comment]
Try adding * to Allowed Origins in the CORS tab and wait a few hours. I can't explain why this works though.

**Comment by ns616** [comment]
It seems like each Input and Output Information is obtained via API call. It can be observed from the browser DevTool too. In my case this was happening from my local machine which was not in the allowed network. Once I logged into the right VM, I was able to see the run history details. I think having a CORS * will let it get the history from anywhere, may be that's why it works.
