### ISSUE TITLE
Facing issue while deploying Logic app standard with Stateless plan

### ISSUE THREAD

**Issue by AnaghBhatt-TomTom** [Azure/logicapps#352]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.deploy
Error type: AccountNameInvalid
Error Message: --- is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.

Version: 1.0.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1743842
extension.bundle.js:2:1731676extension.bundle.js:2:1731676
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by VeeraMS** [comment]
Hi @AnaghBhatt-TomTom,

It seems to be an invalid storage account Name provided to create and deploy Logic App standard resource. 

Storage account must be alphanumeric and must be 3 to 24 chars long.  Please check this.

**Comment by VeeraMS** [comment]
Hi @AnaghBhatt-TomTom,

Could you let me know if the above answers your query. Or do you still see any issue?.
