### ISSUE TITLE
Relative path parameters not getting added to HTTP GET URL in Logic Apps Standard HTTP Request Trigger

### ISSUE THREAD

**Issue by j-d-harvey** [Azure/logicapps#354]
In multi-tenant logic apps relative path parameters are added to the URL:

https://zzzzz.logic.azure.com/workflows/f4c81150f98b4a0f9b506c94cbea46f0/triggers/manual/paths/invoke/{height}/{width}?api-version=2016-10-01&...

But when adding the same trigger to Logic Apps Standard with the same relative path parameter values they are not present:

https://zzzzzzz.azurewebsites.net:443/api/test/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&...

**Comment by shailesh-agre** [comment]
@j-d-harvey  Thank you for reporting this. Product group is aware of this issue. Will check the fix status and confirm.

**Comment by shailesh-agre** [comment]
@j-d-harvey product group is currently working on the fix - it will be deployed soon.

**Comment by rogfrich** [comment]
Hi, I am experiencing the same thing as described by @j-d-harvey - I'm working with a standard Logic App, adding a `relative path` parameter to the Request trigger and the `HTTP GET` url does not change even after pressing save.

**Comment by vinniejame** [comment]
Facing the same issue. Basically cant create any other methods than Post with logic app standard at the moment.

**Comment by shailesh-agre** [comment]
I suppose you will be still able to use the other methods at runtime - just that at design time the UI is not update. Please let me know if you are facing issues during runtime.
