### ISSUE TITLE
[QUERY]: Azure Storage needed for azure logic apps

### ISSUE THREAD

**Issue by jsquire** [Azure/logicapps#356]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET, [#23387](https://github.com/Azure/azure-sdk-for-net/issues/23387).

## Details

Hi, I was referred to this from the dapr team. I want to use azure logic apps locally without the requirement for azure storage to store the workflows. Is this possible? How do I get started with this?

**Comment by WillCasc** [comment]
Hi @stepro71 ,
Please check at https://docs.microsoft.com/en-us/azure/logic-apps/azure-arc-enabled-logic-apps-overview 
Here is also a quick guide: https://www.thomasmaurer.ch/2021/06/run-cloud-native-apps-on-azure-paas-anywhere/ 
Regards,
