### ISSUE TITLE
strange issue with Foreach loop (VSCode)

### ISSUE THREAD

**Issue by Nisha-D** [Azure/logicapps#359]
Code is in VSCode.

Upon clicking the foreach loop connector, I am unable to change the parameters. And once the foreach loop is clicked, any task that I click on later is unusable.

for each loop
![image](https://user-images.githubusercontent.com/20060578/130062717-78e5fddb-0e41-424c-9683-fb1f66755928.png)

for variable connector

![image](https://user-images.githubusercontent.com/20060578/130063116-ec009aea-0cb8-4b35-ba39-94cf2bc2076c.png)

![image](https://user-images.githubusercontent.com/20060578/130063164-5fc00e4a-ca23-448e-aae2-447e0d44e744.png)

**Comment by ShreeDivyaMV** [comment]
@Nisha-D, thanks for reporting this. We are working with the product group on this issue and I will update you with the findings.

**Comment by ShreeDivyaMV** [comment]
Tracking this issue at https://github.com/Azure/logicapps/issues/355, hence closing this thread.
