### ISSUE TITLE
Error while opening the designer

### ISSUE THREAD

**Issue by AnandBhopale** [Azure/logicapps#360]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.openDesigner
Error type: Error
Error Message: Webview is disposed

Version: 1.0.3
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.59.1
Language: en

<details>
<summary>Call Stack</summary>

```
r.assertNotDisposed extensionHostProcess.js:86:80325
r.get webview [as webview] extensionHostProcess.js:86:79131
OpenDesignerForAzureResource.<anonymous> extension.bundle.js:2:4464003
fulfilled extension.bundle.js:2:4461714
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by puspraj-repos** [comment]
@AnandBhopale, Can you please share repro steps. Also, can you make sure if you have all the prerequisites installed on your machine before creating new LA standard in VS code? you can find the prerequisites here : https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#prerequisites

**Comment by puspraj-repos** [comment]
@AnandBhopale , Just wanted to check, if you are still facing the issue ?  Follow the prerequisites, you should be able to create workflows successfully. Please update if you're still facing issue and provide repro steps.
