### ISSUE TITLE
 Unable to determine function project root folder.

### ISSUE THREAD

**Issue by jbishtkiwirail** [Azure/logicapps#365]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.openDesigner
Error type: Error
Error Message: Unable to determine function project root folder.

Version: 1.0.4
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.59.1
Language: en

<details>
<summary>Call Stack</summary>

```
OpenDesignerForLocalProject.<anonymous> extension.bundle.js:2:4521787
fulfilled extension.bundle.js:2:4520831
```

</details>

**Comment by mksa1** [comment]
Seeing the same. Did you manage to fix it?

**Comment by jbishtkiwirail** [comment]
You need to move one level up and open the designer from the folder which has the file workflow.json
Hope it helps.
