### ISSUE TITLE
Creating Azure Logic Apps from VS Code

### ISSUE THREAD

**Issue by Arextion** [Azure/logicapps#368]
Does this occur consistently? YES
Repro steps:
1. Under Azure Logic App (Standard) Extension, Create new project
2. Choose Statefull
3. Type name
4. Enter

Action: azureLogicAppsStandard.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureFunctions.suppressProject is not a registered configuration.

Version: 1.0.4
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.59.1
Language: en

<details>
<summary>Call Stack</summary>

```
E.toConfigurationEditingError workbench.desktop.main.js:1979:18781
E.validate workbench.desktop.main.js:1979:21573
E.doWriteConfiguration workbench.desktop.main.js:1979:15186
Object.factory workbench.desktop.main.js:1979:15020
d.consume workbench.desktop.main.js:68:16672
vscode-file:/workbench.desktop.main.js:68:16487
d.queue workbench.desktop.main.js:68:16411
E.writeConfiguration workbench.desktop.main.js:1979:15005
E.writeConfigurationValue workbench.desktop.main.js:1979:44591
vscode-file:/workbench.desktop.main.js:1979:30749
E.updateValue workbench.desktop.main.js:1979:30737
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by puspraj-repos** [comment]
@Arextion , can you please confirm if you have installed all the prerequisites mentioned in this DOC : https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#prerequisites

Make sure, when you're using either storage emulator or Azurite, you are running the services. **storage emulator** you can run by searching it in windows search bar 
![image](https://user-images.githubusercontent.com/85361569/134869127-452b6d8e-8ddf-4f91-b6c1-24885d3a871c.png)

For **Azurite**, you need to run it in VS code itself, press ctrl+shift+P and choose **Azurite: start** and press enter.

![image](https://user-images.githubusercontent.com/85361569/134873714-89ca9e67-9dc8-424a-93c5-510699a03b61.png)


Can you please confirm if you are still facing issue even after following above steps?

**Comment by odee79** [comment]
I am experiencing the same issue, Azurite is started, but impossible to create a new project. I followed the mention doc and installed all prerequisites. A colleague of mine experiences the same issue.

Action: azureLogicAppsStandard.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureFunctions.suppressProject is not a registered configuration.


Version: 1.0.6
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.60.2
Language: en

<details>
<summary>Call Stack</summary>

```
I.toConfigurationEditingError workbench.desktop.main.js:1935:18825
I.validate workbench.desktop.main.js:1935:21617
I.doWriteConfiguration workbench.desktop.main.js:1935:15186
Object.factory workbench.desktop.main.js:1935:15020
d.consume workbench.desktop.main.js:77:16583
vscode-file:/workbench.desktop.main.js:77:16398
d.queue workbench.desktop.main.js:77:16322
I.writeConfiguration workbench.desktop.main.js:1935:15005
I.writeConfigurationValue workbench.desktop.main.js:1935:44653
vscode-file:/workbench.desktop.main.js:1935:30793
I.updateValue workbench.desktop.main.js:1935:30781
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by Arextion** [comment]
I can't replicate this problem anymore, for some reason. But i did create my project in a different location after this problem and since installed all sorts of tools etc.

**Comment by joechung-msft** [comment]
I experienced this by not having the Azure Functions Core Tools installed before. I resolved it by installing the tools prior to creating the project.

**Comment by AvtsVivek** [comment]
Yes, Installed the following and it worked.

![image](https://user-images.githubusercontent.com/41255281/141312186-764ef3c5-44cc-4360-865f-1d2845d784ae.png)
