### ISSUE TITLE
Flat File decoding not available in standard logic apps

### ISSUE THREAD

**Issue by skyaddict** [Azure/logicapps#371]
I am able to include my flat-file schemas in my standard logic app but the flat file connector is not available. I would have expected that flat-file decoding to be available in standard logic apps.

**Comment by divyaswarnkar** [comment]
Hi @skyaddict , Flat File support decode/encode is not yet available in Standard. We have it in our backlog and should be available in few months

**Comment by vinniejame** [comment]
We have a requirement, where flat file decoder and encoder are required but since it is not available, we had to fall back to consumption.

**Comment by skyaddict** [comment]
@vinniejame I was able to create a consumption app that just does the encode and decode step. I then call that from my single-tenant app. for the time being that works.
