### ISSUE TITLE
Deleting Standard Logic App in Portal doesn't do cascade delete 

### ISSUE THREAD

**Issue by mdroogendijk** [Azure/logicapps#375]
Currently when you delete a standard logic app in the portal, it only deletes the logic app resource itself and not the workflows, parameters and connections within.

Steps to recreate:
1. Create a Standard Logic App
2. Populate with f.e. workflow, parameters and connections
3. Delete the Logic App in the Portal
4. Recreate the Logic App with the same name
5. The recreated Logic App is automatically populated with the sub-resources that were left-over from the previous app

This makes debugging and cleanup rather difficult. 
Sometimes you want to start of with a clean sheet and that's quite a lot of work right now.

**Comment by ShreeDivyaMV** [comment]
@mdroogendijk, I tried to repro the above scenario. Though deleting the logic app, doesn't  delete the file share in the Storage account, when we create a new logic app, it does create a new file share in the storage account to store the workflows and connections files. As highlighted below there are two file shares- one for the deleted Logic app and one for the new one.

Could you confirm if you have hardcoded the file share name in the ARM template while deploying the logic app?

I would also check with the dev team about the possibility of having a feature to clean delete from storage account as well.


![image](https://user-images.githubusercontent.com/30790938/133274371-f9c9d2f4-586a-42bf-a9a0-e8f03afd7363.png)
