### ISSUE TITLE
Logic Apps Standard does not allow to disable workflows

### ISSUE THREAD

**Issue by pacodelacruz** [Azure/logicapps#376]
While there is a `Disable` button on the workflows, I can't disable them. 

![image](https://user-images.githubusercontent.com/11328987/133031410-b84898e4-4da2-4fa5-b2a5-5be839b119ed.png)

This issue is present when I create workflows on the portal and also from an automated pipeline. 
I see this issue happening on multiple Logic Apps. 

I this a known bug?

**Comment by ShreeDivyaMV** [comment]
@pacodelacruz, thanks for bringing this up. I would check with the dev team and update on this.
Meanwhile, The disable option is available, when you open the workflow, if that helps your scenario.

![image](https://user-images.githubusercontent.com/30790938/133234505-2a373dbb-6500-4856-9b5c-a78e08e1b489.png)

**Comment by ShreeDivyaMV** [comment]
@pacodelacruz, the fix has been deployed and I verified that it is working fine. Please verify and let us know if you have any further questions.

**Comment by pacodelacruz** [comment]
That's great news @ShreeDivyaMV ! Many thanks for the prompt response and action!
