### ISSUE TITLE
Add filtering capabilities in the run history view for Logic Apps standard

### ISSUE THREAD

**Issue by pacodelacruz** [Azure/logicapps#377]
While the current Logic App standard run history view allows some sorting, it does not allow any filtering. 

![image](https://user-images.githubusercontent.com/11328987/133031968-4faa9d0f-9cdc-4274-9905-faee7f2a81a8.png)

It'd would be highly beneficial to offer the following filters
* Filter by status
* Filter by date range
* Filter by client tracking id

**Comment by rubenaster** [comment]
Yep, and the sorting doesn't help too much since it only sorts already loaded runs and you won't find runs that you'll find on later pages.

Same filters as in consumption-based Logic Apps would be great!
