### ISSUE TITLE
Nested logic app retries - parent throwing 504

### ISSUE THREAD

**Issue by Kruti-Joshi** [Azure/logicapps#379]
I have a nested logic app which takes some time for 4 retries in case of a failure. According to the documentation, the default HTTP timeout is 100 seconds. I'm able to increase the HTTP client timeout value in my code which triggers the parent logic app, but in case of a failure in the child logic app, it is retried 4 times and takes much longer. Meanwhile, the parent logic app responds with a 504 (gateway timeout).

E.g. - My nested logic app retried 4 times and failed after 4 minutes
![Failure](https://user-images.githubusercontent.com/10906811/133245266-ecb7b1a8-133e-4344-bc99-da2c34713769.png)
However, my code already receives a response of 504 after 2 minutes 9 seconds of triggering the parent logic app
![Error](https://user-images.githubusercontent.com/10906811/133245322-57f347f5-31c8-45f5-8f75-a4e01e816222.png)

The HTTP client which triggers the parent logic app has a timeout of 20 minutes. I verified that this timeout value is working, because without it, we were receiving the timeout reponse in 1 minute 40 seconds (100 seconds), which is default HTTP trigger timeout. I'm under the impression that if the nested logic app also doesn't respond within 100 seconds of being triggered, the parent throws a timeout because it didn't receive a response.

> If logic app doesn't get any response within 2 minutes the request will timeout

I tried setting the timeout for asynchronous pattern in the workflow action settings to PT8M, but it doesn't seem to help. I'm still receiving a 504.
 
![timeout](https://user-images.githubusercontent.com/10906811/133245794-6ecdb530-89e0-44c6-8039-73ea61fb434b.png)

How can I have a long running nested logic app?

**Comment by gcmlpfaltaher** [comment]
if your trigger is a HTTP request, try adding a response to the end of the parent logic app.  In the past, I was able to resolve this when I included a response action in a logic app with a HTTP request trigger.

**Comment by Kruti-Joshi** [comment]
@gcmlpfaltaher I laready have a response in both the child logic app and the parent logic app, but it's still failing.

**Comment by Kruti-Joshi** [comment]
FYI, The timeout was happening because logic app couldn't keep incoming http connections open for more than 2 minutes, so I switched to using the asynchronous polling pattern.
