### ISSUE TITLE
azureFunctions.suppressProject is not a registered configuration

### ISSUE THREAD

**Issue by sarabsandhu** [Azure/logicapps#380]
Does this occur consistently? 
Repro steps:

1.  install Visual Studio Code extension Azure Logic App (Standard) as extension
2. Create Stateless logic app project 

Action: azureLogicAppsStandard.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureFunctions.suppressProject is not a registered configuration.

Version: 1.0.4
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
E.toConfigurationEditingError workbench.desktop.main.js:1981:18781
E.validate workbench.desktop.main.js:1981:21573
E.doWriteConfiguration workbench.desktop.main.js:1981:15186
Object.factory workbench.desktop.main.js:1981:15020
d.consume workbench.desktop.main.js:68:16672
vscode-file:/workbench.desktop.main.js:68:16487
d.queue workbench.desktop.main.js:68:16411
E.writeConfiguration workbench.desktop.main.js:1981:15005
E.writeConfigurationValue workbench.desktop.main.js:1981:44591
vscode-file:/workbench.desktop.main.js:1981:30749
E.updateValue workbench.desktop.main.js:1981:30737
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shailesh-agre** [comment]
This is same as #368 
https://github.com/Azure/logicapps/issues/368
