### ISSUE TITLE
'Condition' Connector gives 'Error Loading Component' Error Message in Web Browser

### ISSUE THREAD

**Issue by claude-newcombe** [Azure/logicapps#381]
Hi, this is exactly the same issue as #355 however it is in the web portal. The project I'm working on was started in the web portal and hasn't been run locally.

Repro steps:
1. Start new logic app in web portal (standard & stateful)
2. Add a new work flow to the logic app
3. Add 'Condition' connector
4. the same error message as in #355 is displayed

![image](https://user-images.githubusercontent.com/57662969/133415151-00e10fb5-be55-4db3-8e23-ba819f8e507c.png)

**Comment by shailesh-agre** [comment]
@claude-newcombe I tried same thing on the portal - but it worked fine.
If it still repros for you, can you please provide more detailed steps / complete screen shot of workflow definition?

**Comment by wcc-markdavies** [comment]
I have the same problem editing existing apps I had created. Originally I got the same error message "error loading component" but that then disappeared and I would just get the "Please select a card to see the content" message.  The action would have red exclamation mark on its right hand side.

My browser versions are as follows:

CHROME:  Version 96.0.4664.93 (Official Build) (64-bit)
EDGE:    Version 96.0.1054.43 (Official build) (64-bit)
FIREFOX: 78.15.0esr (64-bit)

My steps to replicate:

1) Open Logic App
2) Choose EDIT
3) Click the (+) to Add a new action (doesn't matter where in the existing application this is created)
4) Select the CONTROL BUILT IN
5) Choose a CONDITION control action
6) It will load up the properties but after a second it the displays the text "Please select a card to see the content".  

This should have the parameters, settings, run after, about displayed along with the condition builder.  

To work around this I have to:

1) Select another existing action.  This displays the properties\settings for that action.  
2) Select the CONDITION control again and it then the settings are displayed as expected allowing the control to be configured.

**Comment by shailesh-agre** [comment]
@wcc-markdavies Based on the steps mentioned, looks like you are using Consumption Logic App and not Standard Logic App.
I tried the steps you mentioned and checked with few other colleagues also. But we could not reproduce the issue. So this appears to be specific to your machine or environment. It will be a good idea to open an incident with the support team as this may need some depth troubleshooting.
