### ISSUE TITLE
logicapp issue in vscode

### ISSUE THREAD

**Issue by mounirkam** [Azure/logicapps#382]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.loadMore
Error type: Error
Error Message: nextPageLink cannot be null or undefined.

Version: 1.0.4
OS: win32
OS Release: 10.0.22454
Product: Visual Studio Code
Product Version: 1.60.0
Language: en

<details>
<summary>Call Stack</summary>

```
Serializer.serialize extension.bundle.js:2:1745717
getOperationArgumentValueFromParameterPath extension.bundle.js:2:1766365
getOperationArgumentValueFromParameter extension.bundle.js:2:1765872
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:2:1762311
WebApps.listNext extension.bundle.js:2:553051
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:4640566
fulfilled extension.bundle.js:2:4639608
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by mbarqawi** [comment]
What the Extension (Standard or Consumption)

Can you share screenshot?

**Comment by shailesh-agre** [comment]
#332 Same issue
