### ISSUE TITLE
Error in codespaces

### ISSUE THREAD

**Issue by Martin-Carlsson** [Azure/logicapps#383]
Does this occur consistently? Yes
Repro steps:
1. Open codespaces
2. Install Azure Logic Apps for Visual Studio Code (Standard)
3. Create new project - following this guide: https://youtu.be/7k2CbsirDc0?t=1009

![image](https://user-images.githubusercontent.com/7769335/133615711-a28e75cd-d943-4c1f-b152-b05df4ce602d.png)

Action: azureLogicAppsStandard.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureFunctions.suppressProject is not a registered configuration.

Version: 1.0.4
OS: linux
OS Release: 5.4.0-1055-azure
Product: Visual Studio Code
Product Version: 1.60.1
Language: en-US

<details>
<summary>Call Stack</summary>

```
I.toConfigurationEditingError workbench.web.api.js:1916:18826
I.validate workbench.web.api.js:1916:21618
I.doWriteConfiguration workbench.web.api.js:1916:15187
Object.factory workbench.web.api.js:1916:15021
d.consume workbench.web.api.js:77:16016
https:/workbench.web.api.js:77:15831
d.queue workbench.web.api.js:77:15755
I.writeConfiguration workbench.web.api.js:1916:15006
I.writeConfigurationValue workbench.web.api.js:1916:44637
```

</details>

**Comment by shailesh-agre** [comment]
same as #368
