### ISSUE TITLE
Runs History Visual Display Incorrect

### ISSUE THREAD

**Issue by kirikintha** [Azure/logicapps#386]
Hello,

I have been modifying a logic app created before the new editor and I have been noticing a strange behavior when reviewing the run history for my logic app.

I am using a switch to run different data factory pipelines. All is working as intended, but the history looks odd to me. 

For example, in the following - at 16:00 hours the pipeline shows as a success and runs the appropriate action in ADF. However, the UI displays the case as "skipped" even though this not correct. The activity correctly displays "Succeeded".
![Screen Shot 2021-09-19 at 4 04 26 PM](https://user-images.githubusercontent.com/274575/133944759-48b97c40-610c-42d8-93ef-acddc439db44.png)

ADF Log is correct:
![Screen Shot 2021-09-19 at 4 20 00 PM](https://user-images.githubusercontent.com/274575/133944830-edef780c-9059-43c9-b7ac-80a270e27c0b.png)

What does show as a success is the "default" for the switch case. However, its action is showed as skipped.
![Screen Shot 2021-09-19 at 4 04 45 PM](https://user-images.githubusercontent.com/274575/133944885-2eb0d7f7-b41e-4c6b-b103-77f7a2b49d0d.png)

What I am expecting to see is that the default case is skipped and the "16:00" case is flagged as "Succeeded".

This is happening in the current version of logic apps on the azure portal site. Thank you.

**Comment by manoharpatel** [comment]
@kirikintha please let me know if you continue to see this behavior.

If so, could you please provide the below details for a repro?
- Resource id for your logic app.
-  One or more run ids where you observe this behavior.

**Comment by manoharpatel** [comment]
@kirikintha just wanted to follow up on the earlier request for details.

**Comment by kirikintha** [comment]
@manoharpatel - thanks for checking in, this looks correct now! Excellent Job!
