### ISSUE TITLE
Alerts for single tenant workflows

### ISSUE THREAD

**Issue by skyaddict** [Azure/logicapps#389]
Consumption logic apps have the ability to create azure alerts when a workflow fails more than 1 time in 15minutes. With Single-Tenant logic apps is there a way to select Runs Failed as the signal on an alert?

![image](https://user-images.githubusercontent.com/18058674/134206089-e8af1c6e-5f94-4e15-b484-dce57be21956.png)

AB#16033514

**Comment by shailesh-agre** [comment]
@skyaddict A few customers have reported this and Product Group will work to add this feature in the Standard Logic App as well.

**Comment by rubenaster** [comment]
@shailesh-agre what is the status here? We're currently using a pretty complex Kusto query (which costs more than a simple alert).

**Comment by rohithah** [comment]
@rubenaster - we are planning on making these metrics available by the end of the year. pls stay tuned on upcoming announcements.
