### ISSUE TITLE
Email content in logic app

### ISSUE THREAD

**Issue by riya-naico** [Azure/logicapps#39]
Hi,

I want to send an email using send grid through Logic App in Azure.My JSON object after parsing is 
{
    "properties": {
        "location": {
            "type": "string"
        }      
    },
    "required": [
        "location"
    ],
    "type": "object"
}

The location contains multiple value which are comma separated(example: {"location":"LAS Building,Recreation Center,Qatar Academy"}). I want to take each value from location to add in the email content under location heading.How can I separate the json value inside the email content.
Thanks!

**Comment by tomkerkhove** [comment]
You can dynamically compose the body of your email by using for each loop over your location field where you append it to a variable.

That variable is then used as the body of your email.

**Comment by riya-naico** [comment]
Hi, 
 <body onload="getValues()">

<script type ="text/javascript">
		function getValues()
		{
			var loc=@{triggerBody()['location']};
			var  obj=[]; 
			obj= loc.location.split(",");
			var locations = '';
			locations +='<ol>';
			foreach(var i in obj) {
				locations += '<li style="color:#3872AF";>'+obj[i]+'</li>';
			}
			locations +='</ol>';
			document.getElementById('locs').innerHTML = locations ;
			}
		</script>
		<div>
                <tr>
			<th style="width:25%; text-align: left; color:#000000;">Locations</th>
		</tr>
		<tr id="locs"></tr>
                </div>
</body>

This is how i did.Is there any issue with this code?
