### ISSUE TITLE
Dynamic content missing

### ISSUE THREAD

**Issue by mksa1** [Azure/logicapps#390]
We recently started using the Logic Apps extension for Visual Studio Code. Overall it works fine and great to be able it integrate with our CI/CD pipelines in DevOps.

We have however run into a problem with missing "Dynamic Content".

![image](https://user-images.githubusercontent.com/56736173/134467400-e3520438-97c5-4dbf-8c33-21bfde866ff7.png)

When selecting "Dynamic content" in the designer in Visual Studio Code we only see the "List of items" from the trigger action. If we do the same through the portal we also see a number of attributes from the SharePoint trigger action

![image](https://user-images.githubusercontent.com/56736173/134467644-35edc2bf-3cbe-4c64-b57c-641a9f0e1da8.png)

I'm suspecting this could be due to something wrongly configured with the connections locally. Any ideas are much appreciated.

**Comment by VeeraMS** [comment]
Hi @mksa1,

It looks like you have the multiple parameters configured in Azure portal for the Logic App. hence you are able to see many.

But it looks like your VS code parameters file doesn't have the all parameters details.

Go to Logic App in portal--> Parameters --> Copy all parameters in json format--> copy them in VS code project parameter file and save.

You can verify if the trigger shows all.

**Comment by mksa1** [comment]
Well spotted @VeeraMS . It was indeed a problem with the VS code parameters.

**Comment by VeeraMS** [comment]
@mksa1 , Glad to hear that!
