### ISSUE TITLE
Process messages sequentially from Service Bus Queues: Logic Apps Standard

### ISSUE THREAD

**Issue by Nisha-D** [Azure/logicapps#391]
On logic apps (standard), we have a requirement to process the messages sequentially from EventHub and service bus Queues (i.e, we want only one instance of the workflow running at a time). 

Below options have been tried:
1.	Adding the below configuration on the service bus trigger for queue: **Result**: no messages were getting picked from the queue.
              "runtimeConfiguration":{
              "concurrency":{"runs":1}
              }
2.	Added "operationOptions": "SingleInstance" on the service bus trigger for queue: **Result**: no messages were getting picked from the queue.
3.	set the Runtime.Trigger.MaximumRunConcurrency to 1 in the appsettings of the logic app: **Result**: multiple instances of the workflow were still created
4.	Added "operationOptions": "SingleInstance" in the appsettings of the logic app: **Result**: multiple instances of the workflow were still created
 
How we can achieve this using logic apps standard? Are these bugs or working as designed?

**Comment by KeerthikReddy** [comment]
Which SB trigger are you trying to use? 

Azure's Service bus connector (API connection type), "Runtime configuration" (concurrency and maximumWaitingRun) works and supported. 

Built-In Service bus connector (Service provider type)  "Runtime configuration" is not supported yet and throws validation error.

Support for "Runtime Configuration" in the built-in SB trigger is in pipeline would be released in future.

For sequential pattern, we'd suggest you to go with session enabled queue in Service Bus and follow below document to utilize SB message's sessions in Logic App.

https://docs.microsoft.com/en-us/azure/logic-apps/send-related-messages-sequential-convoy
