### ISSUE TITLE
Logic App (standard): VS Code can't open workflow in designer

### ISSUE THREAD

**Issue by Valerii-Poliakov** [Azure/logicapps#395]
Does this occur consistently? Yes
Repro steps:

1. Create Logic App (standard) project and push to Azure DevOps git
2. Clone from DevOps git on another laptop
3. Try open workflow in designer 
Actual: Error "Unable to determine function project root folder." Source: Azure Logic Apps (Standard) (Extension) 
Expected: workflow opened in designer

New Logic App (standard) project created in empty folder works fine and designer opened. 
New Logic App (standard) project created in the **empty folder within the cloned project** has the same problem - can't start designer.
.NET SDKs:
3.1.413 [C:\Program Files\dotnet\sdk]
5.0.401 [C:\Program Files\dotnet\sdk]
According to this guide https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code
global.json added to the project root folder but it doesn't helped

Action: azureLogicAppsStandard.openDesigner
Error type: Error
Error Message: Unable to determine function project root folder.

Version: 1.0.6
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.60.2
Language: en

<details>
<summary>Call Stack</summary>

```
OpenDesignerForLocalProject.<anonymous> extension.bundle.js:2:4521990
fulfilled extension.bundle.js:2:4521034
```

</details>

**Comment by hongzli** [comment]
Hi @Valerii-Poliakov , can you verify that the vscode on the non-working system is opened at the same folder level as the vscode project on the working machine? This could be due to not opening vscode at the correct folder level, and nested projects aren't supported.

**Comment by nareshnagpal06** [comment]
I am having the same issue. If I create workflow at the root level or inside one folder level, it works fine. But if I create another folder inside first level folder, the designer stops working.  

Root>LA works.
 Root->Folder1->LA works. 
 Root->Folder1->Subfolder1->LA does not work

**Comment by yoHasse** [comment]
Another workaround that only works for a single LA Standard project in a subfolder:  
* Open or add the file: ```<folderRoot>\.vscode\settings.json```
* Add the setting:
    ``` "azureLogicAppsStandard.projectSubpath": ".\\<Subfolder>\\<LA Standard Project Folder>",```
