### ISSUE TITLE
Logic App Operator role does not allow access to single tenant workflow list 

### ISSUE THREAD

**Issue by skyaddict** [Azure/logicapps#397]
I have added a role assignment "logic app operator" to a user. This role does not let them see a single-tenant logic app. I then added the Reader role to the user. Now they can see the logic app but not the workflows. In consumption apps they would be allowed to enable and disable the workflow. What I want to be able to do is allow a user to enable disable and run the workflows for the logic app. In consumption apps, I cloned the "Logic App Operator" role and added the following:
                    
                    "Microsoft.Logic/workflows/triggers/run/action",
                    "Microsoft.Logic/workflows/run/action",
                    "Microsoft.Logic/workflows/runs/read"
                    
Since these roles don't work with single-tenant apps i can't provide this level of security.

**Comment by ShreeDivyaMV** [comment]
@skyaddict , Currently these roles are applicable for Consumption Logic Apps 
For Standard Logic Apps, this feature would be available sometime in the next year
There is an option to provide Contributor Role on Function App level to access the Workflow Site. Role: 
https://docs.microsoft.com/en-us/azure/role-based-access-control/troubleshooting#azure-functions-and-write-access 

Please let us know if any further questions
