### ISSUE TITLE
VS Code Logic App Create New Project "Unable to write to Workspace Settings because azureFunctions.suppressProject is not a registered"

### ISSUE THREAD

**Issue by garthunwinAccelitas** [Azure/logicapps#399]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureFunctions.suppressProject is not a registered configuration.

Version: 1.0.6
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.61.0
Language: en

<details>
<summary>Call Stack</summary>

```
E.toConfigurationEditingError workbench.desktop.main.js:2002:18845
E.validate workbench.desktop.main.js:2002:21637
E.doWriteConfiguration workbench.desktop.main.js:2002:15206
Object.factory workbench.desktop.main.js:2002:15040
u.consume workbench.desktop.main.js:77:16613
vscode-file:/workbench.desktop.main.js:77:16428
u.queue workbench.desktop.main.js:77:16352
E.writeConfiguration workbench.desktop.main.js:2002:15025
E.writeConfigurationValue workbench.desktop.main.js:2002:44722
vscode-file:/workbench.desktop.main.js:2002:30814
E.updateValue workbench.desktop.main.js:2002:30802
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by puspraj-repos** [comment]
@garthunwinAccelitas , please install all prerequisites before creating new project. also this looks as same as this issue [368](https://github.com/Azure/logicapps/issues/368) .

**Comment by garthunwinAccelitas** [comment]
Thanks, Pooja, but I have no idea why you’re getting this message, or why you’re sending it to me, or even what it means.
Is there some context that I’m missing?

Thanks,
G


***@***.***

Garth Unwin  |  Sr. Software Engineer  |  M: 707-889-8532  |  accelitas.com<http://accelitas.com/>  |  Accelitas™

**Comment by puspraj-repos** [comment]
@garthunwinAccelitas , you are receiving this email because you were a part of a github issue. If you do not want to receive the email, please click on unsubscribe button on the right side of the page. 
Also, can you confirm if you are still facing the issue?
