### ISSUE TITLE
`converFromUtc` documentation wrong or function wrong?

### ISSUE THREAD

**Issue by erewok** [Azure/logicapps#40]
Hi all,

I'm unsure if this is the right place for this, but here goes. Within a logic app, I'm attempting to use the `converFromUtc` function and running into problems.

Here's my invocation:

```json
"Submission_Date": "@{convertFromUtc(triggerBody()?['DateTimeReceived'], '400')}",
```

This seems to conform to what the [documentation tells me](https://docs.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#convertFromUtc) on parameters:

`convertFromUtc('<timestamp>', '<destinationTimeZone>', '<format>'?)`

However, I get this run failure message:

>  InvalidTemplate. Unable to process template language expressions in action 'Insert_row' inputs at line '1' and column '3259': 'The template language function 'convertFromUtc' expects its second parameter to be a string that contains a UTC date time. The value was '2018-11-09T23:48:07.0000000+00:00'. Please see https://aka.ms/logicexpressions#ConvertFromUtc for usage details.'.

**2018-11-09T23:48:07.0000000+00:00** certainly looks to me to be a valid *ISO-8601* timestamp. (This is coming from gmail, by the way.)

Anyway, I had to do the following to get it to parse...

```json
convertFromUtc(concat(split(triggerBody()?['DateTimeReceived'], '+')[0], 'Z'), 'Pacific Standard Time')
```

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.

In this particular case, you can provide feedback on the documentation page using this link:
https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-workflow-definition-language#feedback
