### ISSUE TITLE
Stateful Workloads running on old code even after new code deployement 2 days back. The designer shows new code but the runs in the run history clearly proves that the logic app runs are happening with the old code.

### ISSUE THREAD

**Issue by SmrutiRanjanMishra** [Azure/logicapps#400]

**Comment by dtkaloust** [comment]
I have had this issue as well. In my inline code block I was referencing an upstream block. I then ended up changing that upstream block name, but did not update that reference in the inline code block. When saving it indicates that it saved correctly, but it actually does not and uses the old code. Once I changed that reference in the inline code, it would save successfully and deploy with the new code.

**Comment by Rajre** [comment]
Hi, For this actually we can navigate to your Logic App Standard blade --> Diagnose and solve Problems --> Runs and Triggers --> click on Workflow Validation Summary and check for the error to resolve it. Please see if this helps.

**Comment by SmrutiRanjanMishra** [comment]
> I'm having the same issue as you, but only when I add an inline code block. Do you have any in your code?

**Comment by SmrutiRanjanMishra** [comment]
> I'm having the same issue as you, but only when I add an inline code block. Do you have any in your code?

I do not have any inline code. And I am not able to reproduce the issue again.

**Comment by SmrutiRanjanMishra** [comment]
> I have had this issue as well. In my inline code block I was referencing an upstream block. I then ended up changing that upstream block name, but did not update that reference in the inline code block. When saving, it indicates that it saved correctly, but it actually does not and uses the old code instead. Once I changed that reference in the inline code, it saves successfully and deploys with the new code.
> 
> So, I think there is a bug here where the logic app is claiming to have saved successfully, but it actually fails some validation in the inline code block and does not save.

We are using CI CD for deploying logic app. So m not sure why it was behaving that way.

**Comment by SmrutiRanjanMishra** [comment]
> Hi, For this actually we can navigate to your Logic App Standard blade --> Diagnose and solve Problems --> Runs and Triggers --> click on Workflow Validation Summary and check for the error to resolve it. Please see if this helps.

Thanks for the tip. I will keep that in mind next time i encounter this issue.

**Comment by Rajre** [comment]
> > Hi, For this actually we can navigate to your Logic App Standard blade --> Diagnose and solve Problems --> Runs and Triggers --> click on Workflow Validation Summary and check for the error to resolve it. Please see if this helps.
> 
> Thanks for the tip. I will keep that in mind next time i encounter this issue.

Sure, Thank you!

**Comment by P1514** [comment]
This didn't work with me. There was no error being shown over there. I ended up talking with support and the issue was because the inline code. LogicApp was not configured as NodeJS and the inline code was javascript. 
If anyone else finds this issue, check this as well

**Comment by Rajre** [comment]
> This didn't work with me. There was no error being shown over there. I ended up talking with support and the issue was because the inline code. LogicApp was not configured as NodeJS and the inline code was javascript. If anyone else finds this issue, check this as well

Thanks for the update.
