### ISSUE TITLE
Resubmit action "Hangs" on trigger. And is submitting old workflow. 

### ISSUE THREAD

**Issue by terra819** [Azure/logicapps#401]
When resubmitting an old execution of a workflow, after making changes, the flow "hangs" on the trigger and the rest of the flow is showing as disabled, and the execution stays in "running" state until cancelled. Only the trigger is executed. And the workflow that shows in the details, is an old workflow.

**Comment by puspraj-repos** [comment]
@terra819 , can you ocnfirm if you are using **execute javascript code** action. In case you are using this action, please remove all the comments from javascript code and try running it.

**Comment by puspraj-repos** [comment]
@terra819 , One probable reason for this issue could be invalid workflow definition. even though you might be able to save the workflow but if the workflow does not pass validation check then it will not get loaded for execution, instead last valid workflow will be loaded. do you see any error messages while saving it?
