### ISSUE TITLE
Error ParameterNotDefined. Message: Parameter 'token:TenantId' is not allowed on the connection api to Azure SQL with Service Principal

### ISSUE THREAD

**Issue by aizefler** [Azure/logicapps#402]
Hi guys, I am having problems creating a MICROSOFT.WEB/CONNECTIONS for an Azure SQL database with the connection type based on Service Principal.

Connection via Portal:

![image](https://user-images.githubusercontent.com/2823190/136856100-d8578e70-88c9-4180-bf8a-b905546ac58c.png)

ARM Template:

       {
            "type": "MICROSOFT.WEB/CONNECTIONS",
            "apiVersion": "2016-06-01",
            "name": "[parameters('ConnectionDbSqlName')]",
            "location": "[parameters('Location')]",
            "properties": {
                "api": {
                    "id": "[concat(subscription().id, '/providers/Microsoft.Web/locations/', parameters('Location'), '/managedApis/', 'sql')]"
                },
                "displayName": "[parameters('ConnectionDbSqlName')]",
                "parameterValues": {
                    "token:TenantId": "[parameters('tokenTenantId')]",
                    "token:clientId": "[parameters('tokenClientId')]",
                    "token:clientSecret": "[parameters('tokenClientSecret')]",
                    "token:grantType": "client_credentials"
                }
            }
        }

Error message:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\"Code\":\"BadRequest\",\"Message\":\"Input parameters are invalid. See details for more information. Details:errorCode: ParameterNotDefined. Message: Parameter 'token:TenantId' is not allowed on the connection since it was not defined as a connection parameter when the API was registered..\",\"Target\":null,\"Details\":[{\"Message\":\"Input parameters are invalid. See details for more information. Details:errorCode: ParameterNotDefined. Message: Parameter 'token:TenantId' is not allowed on the connection since it was not defined as a connection parameter when the API was registered..\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"ExtendedCode\":\"14022\",\"MessageTemplate\":\"Input parameters are invalid. See details for more information. Details:{0}.\",\"Parameters\":[\"errorCode: ParameterNotDefined. Message: Parameter 'token:TenantId' is not allowed on the connection since it was not defined as a connection parameter when the API was registered.\"],\"Code\":\"BadRequest\",\"Message\":\"Input parameters are invalid. See details for more information. Details:errorCode: ParameterNotDefined. Message: Parameter 'token:TenantId' is not allowed on the connection since it was not defined as a connection parameter when the API was registered..\"}}],\"Innererror\":null}"}]}

**Comment by puspraj-repos** [comment]
@aizefler , When you are creating API connection using service principal for SQL connector, please refer to below template for creating same. let me know if you are still facing any issues. for more details about how to reference parameters using ARM template you can follow this doc : [Link](https://docs.microsoft.com/en-us/azure/logic-apps/set-up-devops-deployment-single-tenant-azure-logic-apps?tabs=github#find-api-connection-parameters)

`{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {},
    "resources": [{
        "type": "Microsoft.Web/connections",
        "apiVersion": "2018-07-01-preview",
        "name": "knightsqlsp",
        "location": "southeast asia",
        "properties": {
            "displayName": "connectionDisplayName",
            "api": {
                "id": "[concat(subscription().id, '/providers/Microsoft.Web/locations/', 'southeast asia', '/managedApis/', 'sql')]"
            },

            "parameterValueSet": {
                "name": "oauthSP",
                "values": {
                    "token:TenantId": {
                        "value": "tenant-id"
                    },
                    "token:clientId": {
                        "value": "client-id"
                    },
                    "token:clientSecret": {
                        "value": "client-secret"
                    }
                }
            }
        }
    }],
    "outputs": {}
}`
