### ISSUE TITLE
Disabling/rolling over SAP connector (NCo library) extended logs (on-premises data gateway)

### ISSUE THREAD

**Issue by abhinavcreed13** [Azure/logicapps#403]
Hey team,

In our non-production environment, there are times when we get many errors from SAP which results in noisy logging by the SAP connector (SAP NCo library) through

The logging is currently happening in `C:\Windows\ServiceProfiles\PBIEgwService\AppData\Local\Temp` folder inside the file `dev_nco_rfc.log`.

![image](https://user-images.githubusercontent.com/31875389/136894191-ca7907c4-b266-41d8-a961-7318a9a82393.png)

We have already disabled additional logging in the Diagnostics settings of the on-premises data gateway app and we are using the default logging level as Error only.

The logs keeps on growing due to intense SAP connector error logging and we haven't found a way to disable/rollover these logs.

We are wondering whether it is possible to:
- Rollover SAP NCo library logs after a maximum limit is reached (highly recommended solution)
- Disable SAP NCo library logs

Any suggestions?

**Comment by daviburg** [comment]
BTW I heard back from SAP support that this log file cannot be disabled by application devs. For further help, you will unfortunately need to raise a support ticket with SAP.
