### ISSUE TITLE
VS Code Create Connection to Azure - Sign In Method

### ISSUE THREAD

**Issue by anthonywhite** [Azure/logicapps#404]
I am working in VS Code and wish to create workflow connections to SharePoint. The Create Connection/Sign In panel that appears when adding an action forces this to redirect to my _default browser_ - which I don't want, as this is signed in to my corporate production tenant. I want to direct the Sign In through a different browser which is signed in to the dev tenant where the SharePoint service is.

Copying and pasting the generated URL from one browser to the other results in an error. How can we achieve Sign In to the correct tenant?

**Comment by puspraj-repos** [comment]
@anthonywhite , VS code will use default browser that is configured in your system. If you want to use different browser, please change the default browser ( in case of windows 10, open **"choose a default web browser"** and change the **"web browser"** . 
Once you configure this, VS code will use the newly configured browser for creating API connection.
