### ISSUE TITLE
Cannot trigger recurrence from HTTP trigger

### ISSUE THREAD

**Issue by AmitayStrijevski** [Azure/logicapps#41]
1. Create http trigger
2. Add next step -> Recurrence
3. Failed to save logic app ****. The request content is not valid and could not be deserialized: 'Could not find member 'recurrence' on object of type 'FlowTemplateAction'. Path 'properties.definition.actions.Recurrence.recurrence', line 1, position 583.'.

**Comment by tomkerkhove** [comment]
it should actually not be possible to use recurrence as a non-trigger or am I missing something here @kevinlam1?

**Comment by kevinlam1** [comment]
Correct you can't add the recurrence trigger as an action in a Logic App.  You should try to use Delay or Delay Until actions instead.
