### ISSUE TITLE
logic app vnet integration

### ISSUE THREAD

**Issue by dariuszbz** [Azure/logicapps#410]
Some connectors doesn't work with private endpoints as expected. example:
azure tables - the connector created is API not services provider.

Is there any road map available to check when it will be possible to user private networking for connectors (not only tables, but all)?

Are there are "walk around" patterns available and how to find them (don't answer: google, please)?

**Comment by kclaka** [comment]
@dariuszbz 

Not a roadmap but it speaks of new features coming to Logic Apps Fall 2021

https://techcommunity.microsoft.com/t5/azure-developer-community-blog/azure-logic-apps-announcement-fall-2021-release/ba-p/2911923

**Comment by puspraj-repos** [comment]
@dariuszbz , you can also share your feature request here : [Feedback-Logic apps](https://feedback.azure.com/d365community/forum/cb47c115-7926-ec11-b6e6-000d3a4f032c)
