### ISSUE TITLE
bool handling 

### ISSUE THREAD

**Issue by asos-andrewgoad** [Azure/logicapps#414]
Using the HTTP Trigger we have defined a schema which includes `"properties": {"isHtml":{"type":"boolean"}}` and our request is `{"isHtml": true}`

Which we can see on the output for the Trigger
![image](https://user-images.githubusercontent.com/42029884/139922917-7c2dd20a-d62a-41e8-884d-8a7be11f403c.png)

In it's raw form `@{triggerBody()?['isHtml']}` is shown as `True` so `true` has become `True`

![image](https://user-images.githubusercontent.com/42029884/139923052-86da0291-682c-4c63-8ce3-fbceca7d9b81.png)

If we apply the bool function `@{bool(triggerBody()?['isHtml']})` or `@{bool(string(triggerBody()?['isHtml']))}` it is shown as `True` but the [bool() document states]( https://docs.microsoft.com/en-us/azure/logic-apps/workflow-definition-language-functions-reference#bool) `true` & `false`

Cosmos expects `"isHtml": true` rather than `"isHtml": True`, so errors, unless we apply a (very very hacky) workaround of `@{toLower(string(triggerBody()?['isHtml']))}`

**Comment by puspraj-repos** [comment]
@asos-andrewgoad , I am trying to reproduce the scenario at my end, but I'm not facing any issues, every time I'm getting **true** with small case letter. Can you share more details on which action you are facing this issue, I tried this to extract the trigger value using this expression **@{triggerBody()?['isHtml']}** . I'm not seeing true with capital **T**.
