### ISSUE TITLE
Logic App Standard | Two workflows unable to communicate in the same Private Linked Logic App using HTTP Action

### ISSUE THREAD

**Issue by saffiali** [Azure/logicapps#415]
Description:
I have two workflows, one call the other over HTTP, enabled Private link , can call them from a VM (in the same vnet as private link)

Issue:
I am unable make them communicate over private link

Ask: How to make them communicate, with Private Link Enabled, as I am assuming since both are in the same Logic App Instance they both in the same VNet

**Comment by kclaka** [comment]
@saffiali 

Are both logic apps in different vnets ?

**Comment by HarisAbdulkareem** [comment]
@saffiali How do you verify that they are not communicating through the private endpoint?

**Comment by saffiali** [comment]
Update: Issue that HTTP doesn't work automatically with VNet. 

Resolution: Use Call Workflow Action not the HTTP Action
