### ISSUE TITLE
Is there any ARM templates how to include workflow.json definition file path in the standard plan of Azure Logic App?

### ISSUE THREAD

**Issue by Sahithi-Modak** [Azure/logicapps#416]
Hello Team,

We are trying to create an Azure Logic App with a standard SKU plan using terraform with a workflow.
But we couldn't find any ARM template where we can include workflow.json path.

Could you please help with ARM template where we can specify workflow.json?

**Comment by archidda** [comment]
HI @Sahithi-Modak, we currently don't have a way to upload workflow.json via ARM template. 

You can also use CLI to upload files to your logicapp standard. Here's a doc for that-https://docs.microsoft.com/en-us/azure/logic-apps/set-up-devops-deployment-single-tenant-azure-logic-apps?tabs=azure-cli#install-azure-logic-apps-standard-extension-for-azure-cli

You can use following commands-
Get the logicapp extension using-
az extension add --yes --source "https://aka.ms/logicapp-latest-py2.py3-none-any.whl"

Then you can create a logicapp using-
az logicapp create --name MyLogicAppName 
   --resource-group MyResourceGroupName --subscription MySubscription 
   --storage-account MyStorageAccount
   [--plan planName]

Plan is optional and can be workflowStandard or ASEv3 SKU.

To zip-deploy using CLI, refer to https://docs.microsoft.com/en-us/azure/logic-apps/set-up-devops-deployment-single-tenant-azure-logic-apps?tabs=azure-cli#deploy-logic-app

**Comment by Sahithi-Modak** [comment]
Please find attached zip file.








[X]<https://modak.com/>

Tekumalla Sahithi

Senior Software Engineer | Modak Analytics LLP

M: +91 9059004642

E: ***@***.******@***.***>

www.modak.com<http://www.modak.com/>

[X]<https://www.facebook.com/ModakData/>

[X]<https://twitter.com/ModakAnalytics>

[X]<https://www.linkedin.com/company/modak/about/>







________________________________

**Comment by grainerm** [comment]
Hello, 
is it planned in the future to be able to upload workflow.json via ARM template?

**Comment by archidda** [comment]
I do not have a concrete answer but it is one of the things we are discussing.
