### ISSUE TITLE
[CI/CD] Enable/Disable Logic apps standard workflows using powershell

### ISSUE THREAD

**Issue by GFPhillips** [Azure/logicapps#417]
I would like to disable workflows on our pipelines using powershell. I have tried to modify the "flowStaste" property using az rest , but the http methods for PATCH/PUT are not supported. Only GET works and can see the "flowstate" property

Commands tried

```powershell

az rest --method PUT --uri "https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resourcegroupname}/providers/Microsoft.Web/sites/{logicappname}/workflows/{workflowname}?api-version=2020-12-01" --body '{"properties":{"flowState":"Disabled"}}'

az rest --method PATCH --uri "https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resourcegroupname}/providers/Microsoft.Web/sites/{logicappname}/workflows/{workflowname}?api-version=2020-12-01" --body '{"properties":{"flowState":"Disabled"}}'

```
Error

``` powershell
Method Not Allowed(<Error><Message>The requested resource does not support http method 'PUT'.</Message></Error>)

Method Not Allowed(<Error><Message>The requested resource does not support http method 'PATCH'.</Message></Error>)
```

Debugging on the azure portal (for disabling workflow), i could see that it pulls the appsettings and does a POST using ALL the current appsettings pulled + new property to disable the workflow i.e. Workflows.{myworkflow}.FlowState: "Disabled"

I find this unnecessary complicated, so would like to avoid using the appsettings at all for this purpose.

Are there any other options or perhaps im using the wrong API version/commands for what im trying to achieve?

Thanks

**Comment by puspraj-repos** [comment]
@GFPhillips , for disabling the workflow in logic app standard, we can also use the PowerShell command to update the app settings. 
Currently you can use FuncitonApp sdk to achieve your goal, just replace the function app name with the logic app name.

When we disable the workflow, in the backend we update the app setting for that workflow. the app setting key would be **Workflows.{WorkflowName}.FlowState** and the value would be **Disabled** . For enabling, you can use **Enable** or remove the setting as well.

Example : **Update-AzFunctionAppSetting -Name "logicappprivate" -ResourceGroupName "la-v2" -AppSetting @{"Workflows.workflow2.FlowState"="Disabled"}**

For more details you can refer this : https://docs.microsoft.com/en-us/powershell/module/az.functions/update-azfunctionappsetting?view=azps-6.6.0#example-1--add-a-new-app-setting-in-a-function-app-

**Comment by puspraj-repos** [comment]
@GFPhillips , can you please update if you were able to test the above workaround?

**Comment by GFPhillips** [comment]
Thanks @puspraj-repos , this works. However, I would like to stay away from adding this on app settings, specially due to the fact that making changes to app settings restarts the logic app and affects other workflows. - Yes, we could separate into more logic apps, but we are aware of app density on the app service plans 

Would rather have this like we used to have on consumption tier where you could enable/disable from the ARM template

https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-azure-resource-manager-templates-overview#logic-app-resource-definition

 But if this is the only solution we have at the moment, then that will have to do. Unless there are works in the pipeline to improve this?

**Comment by puspraj-repos** [comment]
@GFPhillips , I agree the one we have at consumption tier is easier to implement. currently this is the only workaround it seems, we could use REST API's do achieve the same but more or less it would also add these app settings in the logic app.
