### ISSUE TITLE
Use principal on Azure AD Connector

### ISSUE THREAD

**Issue by ahmetsyildirim** [Azure/logicapps#418]
Currently, I cannot see that there is an option to use principal when using Azure AD Connector in Logic Apps.
It would be nice to have that feature available.
As an example, Azure Data Lake connector has that option.

**Comment by puspraj-repos** [comment]
@ahmetsyildirim , can you please use this link to give this feedback/idea https://feedback.azure.com/d365community/forum/cb47c115-7926-ec11-b6e6-000d3a4f032c

**Comment by ahmetsyildirim** [comment]
> @ahmetsyildirim , can you please use this link to give this feedback/idea https://feedback.azure.com/d365community/forum/cb47c115-7926-ec11-b6e6-000d3a4f032c

@puspraj-repos , thanks for sharing the feedback page.
I can see that the same feature request was already created 3 years ago. https://feedback.azure.com/d365community/idea/3109c510-8226-ec11-b6e6-000d3a4f0789?page=1

I guess it was not considered as a useful feature.
