### ISSUE TITLE
VSCode extension cannot show overview since version 1.0.7

### ISSUE THREAD

**Issue by kaylumah** [Azure/logicapps#420]
Hi,

We have a logic app that works perfectly well when deployed in Azure, but not in development with VSCode. (converted to dotnet style project with the plugin)
Everything was working with version `1.0.6` but in `1.0.7` and `1.0.8` when I want to see the overview on **any** workflow in the logicapp I get a message similar to 
> Workflow run history could not be loaded. Error: 'Could not establish connection to the host. Run your function project to view the run history. Failed to execute 'fetch' on 'Window': Failed to parse URL from http://localhost:undefined/runtime/webhooks/workflow/api/management/workflows/Stateful1/runs?api-version=2019-10-01-edge-preview'

I've justed tested and verified this after creating a new (nodejs) logicapp from the extension (v1.0.8) and I get the same result.

Can you look into this, since one of the selling points for my team was the local dev experience

**Comment by kennyMSFT** [comment]
@kaylumah  Thanks for bringing this to our attention. Could you also post a few screen shots so I can follow up on this ?

**Comment by kaylumah** [comment]
![001](https://user-images.githubusercontent.com/8428126/141169047-48f6e642-70d4-4062-86a8-1ffdac03476c.PNG)
![002](https://user-images.githubusercontent.com/8428126/141169062-89bb9259-c516-4aaa-9d06-0d95eff6bdc0.PNG)
![003](https://user-images.githubusercontent.com/8428126/141169074-14e9d527-830c-449d-ae63-01d1b733acef.PNG)
![004](https://user-images.githubusercontent.com/8428126/141169086-ffb25606-1494-46ba-ac0a-345c40f8c490.PNG)
![005](https://user-images.githubusercontent.com/8428126/141169100-77a8d04d-2c07-4fe2-a2f9-32641aa516d1.PNG)

Please let me know if you need anything else :)

**Comment by kennyMSFT** [comment]
Hello @kaylumah 

Thanks for the screenshots. I was able to reproduce this error myself.

Apparently this would only happen when your workflow is not running, which the error seems to indicate. If you run the workflow and try to open the overview it should work without errors.

Let me know if that works for you or if you have further questions.

Thanks

**Comment by kaylumah** [comment]
Hi @kennyMSFT 

![image](https://user-images.githubusercontent.com/8428126/141254588-a56c8988-602a-4b73-a8d1-358503b6ce97.png)

Normally that would mean a run button here (updated the new logic app to have webhook trigger)

On 1.0.6 the error is very different

Without logic app running:
![image](https://user-images.githubusercontent.com/8428126/141255008-e042cbc6-2801-4da4-b3a8-b5961788c162.png)

With logic app running (func host start)
![image](https://user-images.githubusercontent.com/8428126/141255196-4a561e21-b392-4b96-8d5f-b93c08b50463.png)

Please find attached the workflow as well

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Terminate": {
                "type": "Terminate",
                "inputs": {
                    "runStatus": "Failed"
                },
                "runAfter": {}
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```
its a very simple one, once the url gets called stop the workflow

**Comment by kaylumah** [comment]
Perhaps usefull information, we use vscode on Windows 🙂

**Comment by kennyMSFT** [comment]
Hello @kaylumah 

Please can you make me know the results when you follow the steps below

1. On the logic app standard window in vscode ensure that you Azurite running in the terminal. you can use `azurite -s -l .` to start it
2. Run your logic app standard by clicking  Run -> Start Debugging
3. Now try to open the overview and see if you get the same error

**Comment by kaylumah** [comment]
@kennyMSFT that seems to work for the one I generated for this issue, but not for my currently in use one.

Are you saying `func host start` is no longer a supported scenario?

**Comment by kennyMSFT** [comment]
Hello @kaylumah 

That is great to hear. `func host start` still works. 

But something I have noticed is I have to run the Logic App first by clicking Run -> Start Debugging/Run without Debugging. After that first run I am then able to use `func host start` to run the logic app and view the overview.

I am not sure why that behaviour and will let the team know.

Thanks
