### ISSUE TITLE
Is there an option/way to deploy a workflow independently in Standard Logicapps?

### ISSUE THREAD

**Issue by pchandramouli** [Azure/logicapps#421]
Most of the Azure Devops documentation / samples explain how to deploy the Logicapps as a zip (both Devops and CLI).  In the [documentation ](https://docs.microsoft.com/en-us/azure/logic-apps/set-up-devops-deployment-single-tenant-azure-logic-apps?tabs=azure-cli) too, this note is present:

> Make sure that your zip file contains your project's artifacts at the root level. These artifacts include all workflow folders, configuration files such as host.json, connections.json, and any other related files. Don't add any extra folders nor put any artifacts into folders that don't already exist in your project structure. 

Is there any way to deploy a workflow independently in Standard Logicapp instance without disturbing the existing workflows?

**Comment by ShreeDivyaMV** [comment]
One option would be do a PUT call to the management URI as below and passing the workflow.json content in the body
https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<RGName>/providers/Microsoft.Web/sites/<LAName>/hostruntime/admin/vfs/<WorkflowName>/workflow.json?api-version=2018-11-01&relativepath=1

**Comment by ShreeDivyaMV** [comment]
@pchandramouli, Please let us know if any further questions on this query.

**Comment by pchandramouli** [comment]
Couldn't find that management URL in the Logicapp documentation: https://docs.microsoft.com/en-us/rest/api/logic/ . Particularly, I'm not sure what should come after the `/vfs/` part in the management URL you've suggested. 

I found a forum post on how to upload maps/schemas within Logicapps Standard SKU: https://docs.microsoft.com/en-us/answers/questions/510039/powershell-script-for-uploading-map-and-schemasart.html  But even here, I couldn't get the exact syntax.

**Comment by ShreeDivyaMV** [comment]
Sorry, I missed to get back on this thread. The URL wasn't copied properly earlier.

https://management.azure.com/subscriptions/<SubscriptionName>/resourceGroups/<ResourceGroupName>/providers/Microsoft.Web/sites/<LogicAppName>/hostruntime/admin/vfs/<WorkflowName>/workflow.json?api-version=2018-11-01&relativepath=1

**Comment by ShreeDivyaMV** [comment]
@pchandramouli, Please let us know if any further questions on this query.
