### ISSUE TITLE
Single-tenant Logic Apps (Standard) not working with Azure Function Core Tools 4.x

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/logicapps#424]
After I upgraded my Azure Function Core Tools from version 3.x to 4.0.3971 my single-tenant Logic App (Standard) no longer works when running locally. Are single-tenant Logic Apps (Standard) already compatible with version 4.x of the Azure Function Core Tools? [According to the documentation](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#tools) the latest version x.x is required.

I tried to generate a fresh new Logic App (Standard) project using Visual Studio Code, but that does not work either.

The following scenario works:
- Azure Function Core Tools version 3.0.3904 installed

The following scenarios do **not** work:
- Azure Function Core Tools version 4.0.3971 installed
- Both Azure Function Core tools version 3.0.3904 _and_ 4.0.3971 installed

System:
- Azure Function Core Tools 4.0.3971
- .NET (Core) SDK 3.1.415 & 6.0.100
- Visual Studio Code 1.62.2 with Azure Logic Apps (Standard) 1.0.8 extension
- macOS 12.0.1

**Comment by kennyMSFT** [comment]
Hello @gastonmuijtjens 

We are aware some customers are experiencing issues when using the latest version of Azure Function core tools 4.x. For now, please keep using Azure Function Core Tools version 3.0.3904.

Thanks

**Comment by gastonmuijtjens** [comment]
Hi @kennyMSFT, thanks for your answer. Since our project contains both Azure Functions (for which we would like to use the latest 4.0 runtime) and single-tenant Logic Apps it is not really convenient to have two interfering versions installed of the Azure Function Core Tools
