### ISSUE TITLE
connections.json problem with azure connector when trying to use app settings

### ISSUE THREAD

**Issue by hugogirard** [Azure/logicapps#427]
Hi,

I have a simple workflow,  that call a pipeline run in Azure Data Factory

![image](https://user-images.githubusercontent.com/64166891/142491733-8b45e64c-cce6-4670-bd9e-f1fda79884e0.png)

This create the proper api connection in connections.json file but I will like to not have the subscription ID or resource group name saved there and leverage the appsetting.

I want to do something like this

![image](https://user-images.githubusercontent.com/64166891/142496626-4e286a1c-512f-47e9-936a-26c59c531b24.png)

But when I do this my Azure connector doesn't work anymore

![image](https://user-images.githubusercontent.com/64166891/142496697-2cbc82bf-ab5c-4a44-8006-1693f0e42a88.png)

**Comment by RemiDLWR** [comment]
I've had the same issue. 
It's some kind of bug in the new update of Azure Logic Apps (Standard) extension. For now I'm solving it by reverting the version to v1.0.7.

**Comment by mirzaciri** [comment]
Handling these types of different connectors with LAS is a major drawback of using LAS.
Using only Built-In connectors works fine, and can be deployed with DevOps easily, but if you want to use any of the other connectors (ServiceNow, Salesforce, etc.) then you are in for big deep dive of a rabbit hole which is not fun to solve.

It goes to show how immature LAS is for now unfortently.

**Comment by shailesh-agre** [comment]
This is a known issue as Designer has problems with change in parameters. This is currently in pipeline and will be addressed sometime this semester.

**Comment by rubenaster** [comment]
So we deploy a LogicApp with the Azure SFTP connector and the connection JSON looks as follows:

`{
    "managedApiConnections": {
        "sftpwithssh_2": {
            "api": {
                "id": "@appsetting('SFTP_CONNECTION_API_ID')"
            },
            "authentication": {
                "type": "ManagedServiceIdentity"
            },
            "connection": {
                "id": "@appsetting('SFTP_CONNECTION_RESOURCE_ID')"
            },
            "connectionRuntimeUrl": "@appsetting('SFTP_CONNECTION_RUNTIME_URL')"
        }
    }
}`

When saving the Logic App we always get a validation error on the connection. This leads the designer to save but the Logic App doesn't work anyways (I guess it can't compile the design).

![image](https://user-images.githubusercontent.com/3841725/151231842-9ae17146-c277-43e5-884e-c230d724e6a1.png)

All AppSettings are set up properly and when we insert the values directly into the connections JSON the Logic App can be saved and gets validated.

**Is our problem related to this issue?**
