### ISSUE TITLE
Unable to create Logic Apps Standard workflows using VS Code

### ISSUE THREAD

**Issue by AnaghaPirangute** [Azure/logicapps#428]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.createCodeless
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 1.0.8
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:2:4784037
Object.<anonymous> extension.bundle.js:2:4799857
fulfilled extension.bundle.js:2:4799033
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by kennyMSFT** [comment]
Hello @AnaghaPirangute the repro steps are missing from your initial post.

However, can you confirm you have Azure Functions Ver (3.0.3904) installed ?

Thanks

**Comment by AnaghaPirangute** [comment]
Yes Kenny it's up-to-date

**Comment by puspraj-repos** [comment]
@AnaghaPirangute , can you please check [this](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code) link and confirm if you followed all prerequisites.
