### ISSUE TITLE
command 'azureLogicAppsStandard.createNewProject' not found

### ISSUE THREAD

**Issue by aferland1** [Azure/logicapps#430]
I just installed the extension (and its pre-requisites (Azurite, Azure Functions Core Tools v 3.0.3442) and when I try to create a new project from the extension, 

![image](https://user-images.githubusercontent.com/73231351/143260427-b6df3f4e-dcb8-4f84-91ee-4fc935c8f240.png)

I get the exception "command 'azureLogicAppsStandard.createNewProject' not found"

**Comment by swakMS** [comment]
Have you tried to remove and add this Extensions again and check if this works

**Comment by aferland1** [comment]
Yes I did it many times and restarted VSCode many times

**Comment by mbarqawi** [comment]
can you share the extension version and the OS 
also can you disable the Azure function extension  if you have it

**Comment by aferland1** [comment]
Hello, the Azure Logic Apps (Standard) extension version is v1.0.8, the OS is Windows 10 Enterprise.

The Azure Functions Extensions is not installed.

**Comment by swakMS** [comment]
Please confirm if you have the below installed
Azure Account extension, C# for Visual Studio Code extension, Azure Functions Core Tools - 3.x version(func-cli-3.0.3904-xxx.msi)

**Comment by aferland1** [comment]
Yes the following extensions are installed 
Azure Account extension, C# for Visual Studio Code extension, Azure Functions Core Tools - 3.x version(func-cli-3.0.3904-xxx.msi)

**Comment by swakMS** [comment]
Seems you have all required pr-requisites installed. I would suggest to raise a case with MS support to troubleshoot on this.
