### ISSUE TITLE
Actions in Stateless Workflows fail to validate with Testing (preview) feature

### ISSUE THREAD

**Issue by rubenaster** [Azure/logicapps#437]
So we have a Stateless Workflow and enabled the Testing feature on e.g. the "Parse JSON"-Action:

![image](https://user-images.githubusercontent.com/3841725/146192197-33c4396f-00e9-4b33-87bb-2952b291e46a.png)

Saving this Workflows leads to the following error:

> Workflow saved successfully. Workflow validation failed for the workflow 'TestFeature'. The request content is not valid and could not be deserialized: 'Required property 'code' not found in JSON. Path 'properties.definition.staticResults.Parse_JSON0.error', line 1, position 514.'.

Alright, Stateless Workflows don't seem to be ready for that preview feature yet so turned the Testing feature off again. But still I got the error when saving the Workflow.

The reason is that enabling the Testing feature added the "runtimeConfiguration" property to the Code of the Action which isn't removed when turning off the Testing feature again. So validation still fails.

![image](https://user-images.githubusercontent.com/3841725/146192864-4e255ee7-ceb4-44cf-8a55-66ef09e3bf91.png)

**Comment by shailesh-agre** [comment]
Thank you for reporting - checking at our end.

**Comment by julietlutalo-abic** [comment]
> Thank you for reporting - checking at our end.

Is there an ETA or update on this? I am encountering the same issue.
