### ISSUE TITLE
Improvement: Logic App Standard Connections overview should have loading indicator

### ISSUE THREAD

**Issue by rubenaster** [Azure/logicapps#438]
When switching to the Connections menu in a Logic App Standard, the overview first looks like there're no connections at all:

![image](https://user-images.githubusercontent.com/3841725/146193721-600ff670-5b69-4dd8-ac27-7d19bfd3e551.png)

A few seconds later the Connections appear:

![image](https://user-images.githubusercontent.com/3841725/146193795-495569d3-837f-40b1-b372-e008569ccb15.png)

What seems like a small issue can easily confuse developers, especially if they're new to Logic Apps and try to figure out why something isn't working. Sometimes loading the Connections takes pretty long and it looks like you're missing something.

A loading indicator would help to indicate that Azure portal is still loading if there are any Connections.

**Comment by shailesh-agre** [comment]
It looks like App is not ready and taking time to load the artifact. Soft restart takes time - which can be caused because of configuration changes. Passing the feedback to the product group.
