### ISSUE TITLE
Undocumented "operationOptions": "FailWhenLimitsReached" for Until

### ISSUE THREAD

**Issue by bartbovendeerdt** [Azure/logicapps#439]
Not sure if this is undocumented by design but when using the Until action it is quite handy to have subsequent actions differ depending on the outcome of the Until. By default the Until never fails or has a timeout (unless it's child actions fail). Even when the explicit timeout is exceeded the Until action block exits with `Succeeded`. 

Using "operationOptions": "FailWhenLimitsReached" as an additional property on the action sets the outcome of the Until to `Timed out`. This then enables alternative flow after the Until block based on `Succeeded` or `Timed out`.

If this is a feature that is meant to stay in, I highly recommend documenting it. Also, enable setting it using the UI.

With "operationOptions": "FailWhenLimitsReached"

![image](https://user-images.githubusercontent.com/7485108/146362739-b61f51e4-877d-46f6-8a9f-048335576813.png)

Without "operationOptions": "FailWhenLimitsReached"

![image](https://user-images.githubusercontent.com/7485108/146363655-a973729a-97ed-41e9-8dcc-3c08fdfcc855.png)

**Comment by OmarAbuArisheh** [comment]
Hi Bart,

Thank you for reaching out on this issue. Kindly note that I have a Blog Post on this issue in our Official Integration Blog, and you are correct, it is not documented in the official Logic App Documentation, but our Integration Blog contains many articles on some "hidden" features, workarounds, and some other great "how-tos".

Please have a look at my article regarding this issue and let me know if it answers your inquiry:

"Changing the behavior of Until Loop when the loop limit is reached"

https://techcommunity.microsoft.com/t5/integrations-on-azure-blog/changing-the-behavior-of-until-loop-when-the-loop-limit-is/ba-p/1986229
