### ISSUE TITLE
Can't connect to CosmosDb if the database name contains a space

### ISSUE THREAD

**Issue by JesseDeBruijne** [Azure/logicapps#44]
I created a Stored Procedure in my CosmosDb database to delete a number of files in the collection based on a property. The structure of the database looks like this:

    Database Test
    | - Collection
      | - Documents
      | - Stored Procedures
        | - CleanupByProperty

I then created a Logic App, that executes this Stored Procedure. I connected via the Portal to the Cosmos database, using the Read/Write Primary Key. When creating the connector in the Logic App, it couldn't read the collections from my database server, giving the following error:

[![Error message][1]][1]

> Could not retrieve values. The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used.

If I manually filled in the fields for `Collection ID` and `Sproc ID`, and ran the Logic App, it returned `Unauthorized` on the action.

[![Unauthorized][2]][2]

When I repeat the exact same scenario, but with the database name `Database-Test`, everything works as expected, and I'm able to select the Collection and Stored Procedure correctly

  [1]: https://i.stack.imgur.com/4rOvh.png
  [2]: https://i.stack.imgur.com/uadE2.png

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
