### ISSUE TITLE
Designer not saving when two workflows calling each other

### ISSUE THREAD

**Issue by Manigandan-R** [Azure/logicapps#441]
Have a project with two workflows, need to call the first workflow in second and vice versa.
Zip deployed successfully  but designer not saving and throwing below error.

Error:
Workflow saved successfully. Workflow validation failed for the workflow 'JobCreate'. The 'inputs' of workflow run action 'job' of type 'Workflow' is not valid. Property 'host.workflow' is missing.

Any help how to achieve this?

**Comment by mbarqawi** [comment]
can you elaborate if the 2 logic app are stateful or stateless ?
