### ISSUE TITLE
Logic App Standard Storage Account action through Private Endpoint gives 403

### ISSUE THREAD

**Issue by rubenaster** [Azure/logicapps#442]
We have a Virtual Network that has three subnets.
- X.X.X.1 for API Management
- X.X.X.2 for Logic App outbound / App Service Plan
- X.X.X.3 for Private Endpoints

A storage account is created and secured using a Private Endpoints. Access is set to be available through X.X.X.2 subnet.

A Logic App Standard is created and outbound traffic is set to go through X.X.X.2. Also its App Service Plan is connected to X.X.X.2.

A workflow is created that uses the Azure-action "Create blob (v2)" and the Storage Account is connected.

Now when I run this Logic App I always get a 403 Forbidden. Only if I give access from all networks on the Storage Account the access from the action works.

What am I doing wrong? Do I missunderstand any concept?

**Comment by mbarqawi** [comment]
the Azure will not work , you need to use the Built-in action 
![image](https://user-images.githubusercontent.com/891607/146667066-230ce96c-4f12-46f7-a00e-b6f4ef08f409.png)

**Comment by rubenaster** [comment]
Yeah, that's what I was afraid of. Unfortunately lots of triggers and actions currently don't exist for Built-In. For example look-peek on Message Queue or any Key Vault action.

Thanks for clarification.
