### ISSUE TITLE
LogicApps connectors remove Content-Range from header for all requests

### ISSUE THREAD

**Issue by narcisradoi** [Azure/logicapps#443]
trying to use the Graph API to upload a file larger than 4mb requires creating an upload session as per
https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-handle-large-messages#upload-content-in-chunks

however the subsequent requests require a content-range value to be supplied which is impossible since all logic apps remove the content-range from the header.
https://docs.microsoft.com/en-us/azure/connectors/connectors-native-http#known-issues

I've tried to create a custom connector and it removes the header as well - can we get this allowed at least for custom connectors?

**Comment by zhangadreedom** [comment]
Hi @narcisradoi Looks like the doc is incorrect. The header will be removed. Have a try : using APIM to add those headers.
The flow looks like: Logic App Http call => Azure APIM (adding header: Content-Range, replace the URL point to Graph again) => Graph API

**Comment by narcisradoi** [comment]
I understand the Content-Range header will be removed from all logicapps - this is the issue, it should not be removed when doing an HTTP request since you cannot send a file upload to Graph API from logicapps without external setup.
