### ISSUE TITLE
Functions host is no longer running error in vscode

### ISSUE THREAD

**Issue by soma-s** [Azure/logicapps#444]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 1.0.10
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:4444435extension.bundle.js:2:4444435
fulfilled extension.bundle.js:2:4441026
```

</details>

**Comment by zhangadreedom** [comment]
Hi @soma-s, can you restart Function host and try again. Please provide more information or screenshot
