### ISSUE TITLE
Deploying Logic App onto Arc enabled AKS through VS Code is failing with 404

### ISSUE THREAD

**Issue by monojit18** [Azure/logicapps#446]
Does this occur consistently? YES
Repro steps:

1. Create AKS cluster with Azure Arc extension ([Set up an Azure Arc-enabled Kubernetes cluster to run App Service, Functions, and Logic Apps](https://docs.microsoft.com/en-us/azure/app-service/manage-create-arc-environment?tabs=bash))

2. Create a Logic App resource in the Portal ([Create Logic app through Portal](https://docs.microsoft.com/en-us/azure/logic-apps/azure-arc-enabled-logic-apps-create-deploy-workflows?tabs=azure-portal#create-and-deploy-logic-apps))

3. Select Custom Location as region
<img width="586" alt="Screenshot 2022-01-03 at 10 10 19 AM" src="https://user-images.githubusercontent.com/2395966/147900137-07368577-6ad0-4119-a4f6-c7a724c51a00.png">

4. Create a new Logic App project through VS Code

5. Open workflow designer

6. Add some workflow e.g. Http Request/Response

7. Right Click in the empty area in the workspace and Select menu option to Convert to Nuget project ([Enable built-in connector authoring](https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#enable-built-in-connector-authoring))

8. Right Click in the empty area in the workspace and Select menu option to Deploy Logic App

9. Deployment fails with below message (PFA)
<img width="1122" alt="Screenshot 2022-01-03 at 9 24 21 AM" src="https://user-images.githubusercontent.com/2395966/147898708-6920adbd-1f4a-4437-81e4-4971d80f4be8.png">

Action: azureLogicAppsStandard.deploy
Error type: 404
Error Message: Failed with code "404".

Version: 1.0.10
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1743842
extension.bundle.js:2:1731676extension.bundle.js:2:1731676
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by mbarqawi** [comment]
did it work if you tried to deploy using normal project structure (not nuget)?

Can you browse the portal created LA from the VS code machine?
