### ISSUE TITLE
Error with Logic Apps (Standard) Extension for vscode

### ISSUE THREAD

**Issue by jcetina** [Azure/logicapps#450]
I'm using VSCode on Mac OS Big Sur.

Whenever I try to create a logic app project using the aforementioned extension, I get the following error:

`You must have the .NET Core SDK installed to perform this operation. See here for supported versions.`

I've tried using both .NET Core 5 and 6 (uninstalling the other version each time), and it's always the same error. The error comes when I select the type of workflow (Stateful or Stateless) in the `Create New Project` dialogs.

**Comment by jcetina** [comment]
Figured it out. I didn't realize that I needed .NET version 3. Works fine now.

**Comment by Rajre** [comment]
Thanks for the update and confirmation Jason.
