### ISSUE TITLE
Liquid maps: Slice doesn't support arrays

### ISSUE THREAD

**Issue by chriswatsonaus** [Azure/logicapps#451]
In Liquid Maps, the Slice filter doesn't support array inputs, only strings. 
This is a known issue in DotLiquid - https://github.com/dotliquid/dotliquid/issues/455 
Please ensure the update is included as soon as it has been completed in DotLiquid.

Example: 
"My first birthday" | Slice: 0,1    --> "My"  - OK
"My first birthday" | Split " " | Slice: 0,1 --> Error (String[] not supported input), expected: ["My","first"]

AB#15957678

**Comment by mbarqawi** [comment]
are you facing this in logic app standard or the consumption?

**Comment by Prafulkapse** [comment]
I have tried in the consumption, it does not work. The Slice or Split currently is not performing.
Also I can see the latest version of the DOT Liquid is 2.2.656 and Logic app is still using DotLiquid 2.0.
Kindly update the version.

**Comment by rohithah** [comment]
We are currently using Liquid 2.0.361.0 and I have added this to our backlog to update this to the latest version.
