### ISSUE TITLE
Child workflows cannot be invoked by providing parameter as workflow's name

### ISSUE THREAD

**Issue by WenovateAA** [Azure/logicapps#452]
Although Logic App standard workflows allow to specify name inside variables or by other indirect ways, when saving such workflow error pops up: 

_Workflow saved successfully. Workflow validation failed for the workflow 'Debug'. The provided workflow name '@variables('workflow')' has these invalid characters '@'''. The name can only be a letter, digit, '-', '.', '(', ')' or '_'._

Repro steps: 
* create a variable and set child workflow name as value. 
* create new workflow operation action
* action allows to specify custom name instead of choosing from existing ones by choosing Enter custom value from drop-down menu:
![image](https://user-images.githubusercontent.com/97520510/148934160-9d555efb-f02c-4871-a4f9-b25b77ac0701.png)

Code:
````
{
    "inputs": {
        "host": {
            "workflow": {
                "id": "@variables('workflow')"
            }
        }
    }
}
````
It seems that it's only possible to use the action using hard-coded values of workflows. This makes it difficult to parameterize workflow names and invoke them with single action without switch or if-else constructions.

**Comment by shailesh-agre** [comment]
The action needs to validate if workflow exists or not. If you provide random custom hardcoded name which does not exist in the app, while saving it will throw an error
![image](https://user-images.githubusercontent.com/61179796/149267174-b8662f21-145c-421c-9ae3-d1eb1decf478.png)
Hence dynamic values will not work.
If you want to call workflow dynamically, you may use HTTP Post action instead to call workflows having HTTP request trigger.

**Comment by WenovateAA** [comment]
Wrong custom value for workflow could be provided in other ways: editing JSON code (and because of huge amount limitation with Designed you have to edit directly a lot!), removing workflow after it was added or similar hacks. Preventing doing this through Designed doesn't provide a lot of protection but forces to use hard-coding values that in general is a bad idea.  Parameters could be used in many other actions (tables in Azure Storages, etc) and inside connections.json. This is a way to keep code dynamic and I don't see why it's not the case for workflows too. I guess, it was done indeliberate, because Designer doesn't prevent of specifying custom value as I showed.

Specifying URL of a workflow inside HTTP post action is a bad idea and I see many developers are making such mistake. Main reason is, it contains SAS token that is not available for Reader role otherwise. Therefore, having URL allows to run workflow for readers from anywhere and posses security issue. Additionally, when storing LA code in repo for CI/CD would then put secret SAS value to this repository too. This is again security issue and proper way would be use any kind of key vault instead. Which is very much overhead for such task.

**Comment by shailesh-agre** [comment]
@WenovateAA let me take this with  the product group and see if they have any further comments.
Also, you can put this ask as a feature request here
https://feedback.azure.com/d365community/forum/cb47c115-7926-ec11-b6e6-000d3a4f032c
which will is monitored by the product group.

**Comment by shailesh-agre** [comment]
@WenovateAA Here are points after checking with the product group:
What is the main scenario you have? Calling one workflow from set of available workflows that are predefined?
(please note, if using this action you can call workflow which is part of the same Logic App).
In Standard Logic Apps, the requirement of the workflow name being static is not just coming from designer, but from a runtime point of view as well. When we are processing the workflow we need to know all the child workflows that parent workflow is calling for processing purposes. And changing this behavior could result in significant work.

On side note, to use http action, you may keep the url in the app setting and refer it in the http action. That way, read only users will not be able to see SAS urls.

**Comment by WenovateAA** [comment]
@shailesh-agre Our use-case is to use workflows as object methods rather than independent workflow. That is, in parameters we define object 
{
"obj1": {
"get": "LA-workflow1"},
"obj2": {
"get": "LA-workflow2"}
}

Then in code we would be able to specify `@parameters('obj1')?['get']` as child workflow name without need to perform If-Else or Switch flows. Also, that would allow to add-remove or rename (yes, renaming is possible through FTPS and I never found statements that it is not supported) of workflows - you then change its name in parameters - without affecting others.

Hope it makes sense

**Comment by venkyrs** [comment]
I would like to see this feature. Please reopen this issue.

**Comment by hartra344** [comment]
@venkyrs we're using this Github to monitor for bug reports but no so much feature requests, if you would like to see this as a feature, I would recommend going to https://feedback.azure.com/d365community/forum/cb47c115-7926-ec11-b6e6-000d3a4f032c as mentioned above.
