### ISSUE TITLE
Unable to deploy logic app from vs code.

### ISSUE THREAD

**Issue by Kalyan-Modak** [Azure/logicapps#453]
While deploying logic app from vs code, getting following error.

The remote runtime "undefined" for logic app "logicapp-test" must be node or dotnet.

**Comment by Kalyan-Modak** [comment]
I have converted it to Nuget project and when I tried to deploy.

Observed above mentioned issue.


Thanks
________________________________

**Comment by zhangadreedom** [comment]
Hi @Kalyan-Modak May I know where you see above error message? is that pop-up in VSCode or you see it in Output (switch to "Logic app standard")? If you could provide the deploy log or screenshot, it will be great

**Comment by Kalyan-Modak** [comment]
Hello,

It is a pop-up shown in VSCode

Please find screenshot,



***@***.***


Thanks,
Kalyan
________________________________

**Comment by zhangadreedom** [comment]
Hi @Kalyan-Modak , when I deploy Logic app standard to Azure( right click), VScode will pop-up to let you choose a subscription, target logic app or creating a new if no one available.... step by step, may I know which steps you are failing?
If you failed in first step, looks like it is a VScode environment issue, it should be better to reinstall all required extension (see https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code) and try create a new logic app standard.

**Comment by zhangadreedom** [comment]
or you can raise a support ticket to Azure Logic app support team for further investigation. Cheers

**Comment by Kalyan-Modak** [comment]
Hey Ziyu Zhang,

I’m able to select subscription , resource group and logic app.
But when I click on deploy to logic app, i’m facing this issue.

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by zhangadreedom** [comment]
Hello @Kalyan-Modak please check Logic app application settings whether FUNCTIONS_WORKER_RUNTIME has a correct value? (Valid values are: dotnet, node, java, powershell and python.)
![image](https://user-images.githubusercontent.com/69228696/150948593-9cc0e5ce-2927-4d31-91fe-574914963e39.png)
