### ISSUE TITLE
LA Standard | Runtime.Trigger.MaximumRunConcurrency not working for ServiceBus built-in trigger

### ISSUE THREAD

**Issue by robin-parker** [Azure/logicapps#455]
The Runtime.Trigger.MaximumRunConcurrency setting is not working for the Service Bus built-in ServiceProvider trigger.
I want to use this setting to throttle the number of parallel workflows consuming downstream resources.

I have tried configuring as indicated in the latest version of the [reference docs for host settings](https://docs.microsoft.com/EN-US/azure/logic-apps/edit-app-settings-host-settings?tabs=visual-studio-code#reference-for-host-settings---hostjson), but the settign is not observed too many parallel workflows are running flooding downstream resources.

Is there an error in the docs, or is the feature not yet available? This issue is preventing me migrating from Managed to Built-in/ServiceProvider connectors.

host.json is configured as below:
```json
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
        "version": "[1.*, 2.0.0)"
    },
    "extensions": {
        "workflow": {
            "settings": {
                "Runtime.Trigger.MaximumRunConcurrency": "5"
            }
        }
    },
}
```

**Comment by ShreeDivyaMV** [comment]
@robin-parker, Sorry for the delay in answering this. The concurrency setting is currently not supported for Built-in Connectors. We would take this feedback to the development team. Thank you.

**Comment by diogonborges** [comment]
Is it _still_ not supported?
