### ISSUE TITLE
Failed to save workflow - Definition contains invalid parameters !

### ISSUE THREAD

**Issue by fao001** [Azure/logicapps#456]
I can't save my workflow, this message appear when I click to save. but the problem is, i don't know where the issue is... the error don't give me information about the parameter.

I'm using azure portal directly to create the workflow and standard tier.

anybody can help?

some idea in how to debug that?

**Comment by fao001** [comment]
Resolve, by deleting whole workflow and created it again.....at the end i can save the workflow that before i can't.

**Comment by AnaghBhatt-TomTom** [comment]
Hi all
I also faced the same issue, when i deploy Standard Logic app via Git Action's . I cannot save the workflow.
![image](https://user-images.githubusercontent.com/83761186/163787841-ea135767-5ba9-4bd6-8b10-72ca3c7c78be.png)

**Comment by jeffwessling** [comment]
I'm also experiencing this issue and I don't know what's causing it. It seems there should be more information given here to help identify where the invalid parameter is being defined. If not, users are forced to discard recent work to get back to a working state and slowly re-add actions and save to find the culprit. If I'm on a role I may go longer than I should before saving the workflow, having to back code out to find an 'invalid parameter' is maddening. There has to be a better way. 

I'd love to see more descriptive messages for invalid parameters (like in what Action it is occurring) and/or the ability to disable Actions so they aren't validated. That could help with this sort of troubleshooting as well.

There's a good thread over in the VS Code Logic App Extension Github forum around this that doesn't look like it made it into the core Logic Apps forum... https://github.com/microsoft/vscode-azurelogicapps/issues/223

**Comment by serkanozkul** [comment]
Lots of people are still hitting this error which does not provide any detail. As per the comment above, there is a separate thread with more information.
https://github.com/microsoft/vscode-azurelogicapps/issues/223

Moreover, I get the "Definition contains invalid parameters" error when I try to save the workflow via the Designer panel in Azure Portal (Standard Logic App) but saving works when I use the "Code" panel.

**Comment by infosecrk** [comment]
We are having this issue again, will share more details
