### ISSUE TITLE
How to set private key in sftp connection using programmatically in azure logic app.

### ISSUE THREAD

**Issue by katherdx** [Azure/logicapps#46]
I am using logic app for connecting sftp server. Connection and everything working fine.
I want to set private key to sftp connection using  programmatically instead of copy/paste directly.  I kept my private-key in keyvault.  Can you please advise, how I can achieve this requirement.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
