### ISSUE TITLE
When do Built-In Key Vault Actions arrive?

### ISSUE THREAD

**Issue by rubenaster** [Azure/logicapps#461]
Dear LA-Team,

currently managed Connectors in Standard Logic Apps really have troubles, especially when it comes to CI/CD. In my opinion the preferred option would be to have as many Built-In Connectors/Actions as possible.

Actions that are used pretty often are related to Key Vault and I guess that it wouldn't be too hard to implement those as Built-In. I know that it can also be achieved pretty easy by using HTTP Request Actions but our customers prefere to have dedicated Actions, which I can understand.

**Is there any plan when Key Vault Actions will be supported as Built-In?**

**Comment by ShreeDivyaMV** [comment]
@rubenaster, Key vault built-in connectors are planned to be available in the first half of 2022. 
Could you please provide more details on the issues with managed connectors in CI/CD?

**Comment by ShreeDivyaMV** [comment]
@rubenaster could you please let us know if any further questions on this?

**Comment by rubenaster** [comment]
> @rubenaster could you please let us know if any further questions on this?

Nope, all good. Waiting patiently :)
