### ISSUE TITLE
Logic Apps Standard built in trigger pricing query

### ISSUE THREAD

**Issue by daverobinson64** [Azure/logicapps#462]
I'm using the service bus trigger from the built-in triggers rather than the Azure triggers. It seems that the built in trigger doesn't have any notion of recurrence so therefore I would assume that messages arriving on a topic will be consumed immediately so near real time? I'm trying to understand the statement below from the link https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-pricing#standard-operations - 

_Note: Some managed connector operations are also available as built-in operations. While built-in operations are free, the Standard model still meters and bills managed connector operations using the same Standard or Enterprise connector pricing as the Consumption model._

I'm assuming this means that if I'm using the built-in service bus trigger, which picks up messages immediately, that there won't be a charge. If I was using the managed service bus connector and I was polling every 1 second then I may be amassing action executions of around $320 even if there was no messages in the topic.

Please confirm the statement above as I'm a little confused (which is easy) as to the meaning.

Thanks

**Comment by HarisAbdulkareem** [comment]
@daverobinson64 : Yes, the trigger works as a listener and messages would be picked up (near) real time.
Your above understanding about billing is correct. Built-in operations in standard logic apps are free which managed (Azure) connections (trigger and actions) will be charged same as consumption and even the skipped trigger will be considered as an execution. Hope this is clear.
