### ISSUE TITLE
Unable run workflows

### ISSUE THREAD

**Issue by Kalyan-Modak** [Azure/logicapps#466]
While saving workflow getting following error.

**Workflow saved successfully. Workflow validation failed for the workflow 'testworkflow'.**

**Comment by AbodeSaafan** [comment]
Hey @Kalyan-Modak Can you provide more information about this workflow? 

Is this for LA standard? 
Is this happening locally or on portal? 
Can you provide the logs for this app? Locally, you would see them when running the workflow in the "output" of VSCode, on portal you would get these by heading to the "Advanced tools" blade, to open "kudu" and then get them from the file system by using the CMD there to navigate to "LogFiles". 

Do not post the logs here in case of any PII, but if you can see the error in the logs and confirm that it does not include PII, please paste that here.
