### ISSUE TITLE
Support for table value parameter logic app to azure sql server stored procedure

### ISSUE THREAD

**Issue by esvinae** [Azure/logicapps#47]
i would like to send csv table content to a stored procedure created in azure sql server in logic app 
Is this possible ?

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
