### ISSUE TITLE
Relatively small amount of workflows (20-30) makes LA Standard Designer very slow when using invoke workflow built-in action

### ISSUE THREAD

**Issue by WenovateAA** [Azure/logicapps#472]
Scenario: you have somewhere 20+ workflows in your LA Standard. You want to invoke some of them from another using built-in workflow action.
There are huge delays when trying to configure workflow actions or watch workflow history during this. Delays could be somewhere 20-30 seconds (for overall amount of workflows 20-30). 
So you sit and watch Designer loading information about all workflows every time you open workflow:

![image](https://user-images.githubusercontent.com/97520510/153184591-b7a3697f-d063-4b11-bb91-e680caeeef41.png)

Reason is ChildWorkflow.js function reads all workflows synchronously each call taking 500-1000ms:

 
![image](https://user-images.githubusercontent.com/97520510/153184950-30a7411d-b3cc-41a4-9d32-e08d5be7c4a4.png)

Similar issue for run history, delays up to 30 seconds. It's unclear for me why not to query just a single workflow and not all of them at least when your watch run history. 
Overall, build-in Invoke Workflow action is designed in a way it makes it difficult to use in production workload. Idea to use some workflows as functions for others therefore is difficult to implement on practice. See my other opened issues regarding child workflows. These issues force to use HTTP action but hiding SAS signatures in URLs adds additional complexity a simple built-in action could have solved.

**Comment by atroiano-glue** [comment]
Hi @WenovateAA ,

I have encountered the same issue in our configuration.
Wandering which underlying App Service Plan you are using. I'm experiencing it with S1.

Thanks
