### ISSUE TITLE
send email from logic app

### ISSUE THREAD

**Issue by manasimahajann** [Azure/logicapps#473]
I am trying to convert html file to pdf and attaching the filecontent in "Send an email(V2)" - it sends a file out with gibberish characters - ���Ok�����~

1. initialize a variable - string - HTML context in the Value
2. Create file - OneDrive for business - file content from above variable
3. Convert file - File is Id and target type PDF
4. Send an email(V2) - Attachment name-1 = FileContent or body('Convert_file')

Same thing works well in power automate.

**Comment by mbarqawi** [comment]
Do you have screenshots of the wrong characters

**Comment by manasimahajann** [comment]
Here is the attachment screenshot and the screenshot when we hover over the attachment
![2022-02-23 11_23_54-Inbox](https://user-images.githubusercontent.com/22528585/155362377-67bec287-1ef4-4800-9a2f-c76d33009c7f.png)


![2022-02-23 11_24_16-](https://user-images.githubusercontent.com/22528585/155362179-c267081a-6a67-45f4-846b-44f916e5cc7d.png)
