### ISSUE TITLE
cant create workflow 

### ISSUE THREAD

**Issue by dariuszbz** [Azure/logicapps#474]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.createCodeless
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 1.0.10
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:2:4784273
Object.<anonymous> extension.bundle.js:2:4800093
fulfilled extension.bundle.js:2:4799269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by ShreeDivyaMV** [comment]
@dariuszbz, Could you please verify the project language setting at workspace setting in VS code as shown in below image?
![image](https://user-images.githubusercontent.com/30790938/155310754-f5e90ba0-c9cf-408d-9d11-9447c3ef9cc6.png)

**Comment by dariuszbz** [comment]
![image](https://user-images.githubusercontent.com/19564162/158982083-099d33fc-dc05-419d-9a6e-c9be5239f0ee.png)


it's empty value. I can select:
![image](https://user-images.githubusercontent.com/19564162/158982173-d5c00452-3c9e-42de-8bdc-06fc55f1cca3.png)

**Comment by ShreeDivyaMV** [comment]
@dariuszbz, could you choose 'javascript' in this setting and let us know if the issue persists?
