### ISSUE TITLE
Error deploying parameterized connections.json

### ISSUE THREAD

**Issue by sven5** [Azure/logicapps#475]
Does this occur consistently? Yes

1. create entry in **connections.json**

```
"managedApiConnections": {
    "azurefile": {
        "api": {
            "id": "/subscriptions/@parameters('SubscriptionId')/providers/Microsoft.Web/locations/germanywestcentral/managedApis/azurefile"
        },
        "authentication": {
            "parameter": "@appsetting('BMVSTORAGE_KEY')",
            "scheme": "Key",
            "type": "Raw"
        },
        "connection": {
            "id": "/subscriptions/@parameters('SubscriptionId')/resourceGroups/xxx-stage/providers/Microsoft.Web/connections/azurefile"
        },
        "connectionRuntimeUrl": "https://sss.03.common.logic-germanywestcentral.azure-apihub.net/apim/azurefile/xxx",
        "displayName": "storage1"
    }
  },
```

Action: azureLogicAppsStandard.deploy
Error type: Error
Error Message: Error in creating access policy for connection in reference - 'azurefile'. Error: Error in getting connection - /subscriptions/@parameters('SubscriptionId')/resourceGroups/---/providers/Microsoft.Web/connections/azurefile. Error: The provided subscription identifier '@parameters('SubscriptionId')' is malformed or invalid.

Version: 1.0.12
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.64.2
Language: de

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:4376961extension.bundle.js:2:4376961
rejected extension.bundle.js:2:4372108
processTicksAndRejections task_queues.js:93:5
```

</details>

The same works when editing connections.json in Azure portal.

**Comment by ShreeDivyaMV** [comment]
@sven5, The error looks like the parameter value for subscription ID is not loaded. Could you provide more details on how you are providing the value to the parameter and how are you deploying the connection?

**Comment by ShreeDivyaMV** [comment]
@Sven5, Sorry for the delay in getting back on this.  Currently we have an issue with transitive reference of app settings in Parameters. The product group is working on the fix. 
As of now, the template doesn't work if,
1. A Param in parameters.json which reads value from app-settings using @appsetting() expression
2. Referring the above param in connections.json file using @parameters()

We would update this thread once it is fixed. Meanwhile please check if the app setting can be directly used in the template for this requirement.

**Comment by PratikT29** [comment]
@sven5 I was facing exactly same issue, referencing subscription and resource group from app settings directly works fine in connections.json

This works fine:
"connection": {
                "id": "/subscriptions/@appsetting('AzSubscription')/resourceGroups/@appsetting('AzResourceGroup')/providers/Microsoft.Web/connections/azuredatafactory"
            },

While referencing subscription as @{appsetting('AzSubscription')} doesn't work.

**Comment by ShreeDivyaMV** [comment]
@sven5, could you please let usknow if any further questions on this?

**Comment by lrf85** [comment]
Any update on this issue? I'm facing the same issue. Using a parameters for the connection ->id  is giving problems (invalid connections). No problems when I use a parameter for the connectionRuntimeUrl for example.

Things I've tried:

@appsetting('ResourceGroup')
@{appsetting('ResourceGroup')}
@parameters('ResourceGroup') -> and reference in the parameters json to the appsetting

I've also added the full URL as parameter, without success.

Any other suggestions?

It's absolutely crucial that we can parameterize these values.

A workaround could be maintaining seperate connections.json files per environment and replace them in the pipeline, but this is not my preferred solution.

**Comment by nikhilbattula9** [comment]
My logic app is in switzerland north region .I got the same error tried using both ways without using curly braces @appsetting('subscription_id') and with curly braces @{appsetting('subscription_id')} . app setting parameter values is'nt reflecting into the connections.json file. Could u guys pls let me know if you found any work around (except creating mutliple files for each environment)
