### ISSUE TITLE
Logic Apps (Standard) extension breaks debugging for Node function apps in vs code

### ISSUE THREAD

**Issue by jkewley** [Azure/logicapps#478]
As [noted here](https://github.com/microsoft/vscode-azurefunctions/issues/3043), the Logic Apps standard extension breaks the ability to debug Node-based function apps. The functions will run, but the debugger won't attach to the process. Disabling the logic app standard extension fixes the issue.

**Comment by nturinski** [comment]
Seems like others have run into this issue as well:
https://github.com/Azure/logicapps/issues/350
