### ISSUE TITLE
Problems inserting document with Mongodb and Logic Apps

### ISSUE THREAD

**Issue by brunorodmoreira** [Azure/logicapps#48]
My logic app collects data from an api rest and inserts into a cosmosdb mongodb. The process occurs successfully, but when performing a query using Data Explorer the following error occurs:

`Error while fetching page of documents: {"code":400,"body":"Command find failed: Unknown server error occurred when processing this request."}`

Here is an example of a call that reproduces the error:

```
"Create_or_update_document": {
                "inputs": {
                    "body": {
                        "id": "11111",
                        "name": "john",
                        "surname": "doe"
                    },
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['documentdb']['connectionId']"
                        }
                    },
                    "method": "post",
                    "path": "/dbs/@{encodeURIComponent('cockpit')}/colls/@{encodeURIComponent('target-collection')}/docs"
                },
                "runAfter": {
                    "HTTP_2": [
                        "Succeeded"
                    ]
                },
                "type": "ApiConnection"
            }
```

Example input:
```
{
  "id": "11111",
  "name": "john",
  "surname": "doe"
}
```

What I've been exploring is something related to the creation of the ObjectId. Does anyone know a solution?

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
