### ISSUE TITLE
In VS Code: Built-In Operations list is empty and throws error "Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by gabrieletassoni** [Azure/logicapps#481]
# Local dev machine
```
VS Code Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-19-generic
```

## Devcontainer:

Based on: `mcr.microsoft.com/vscode/devcontainers/base:0-hirsute`

```bash
vscode ➜ /workspaces/FR-Comparator/src/Stateful1 (master ✗) $ node -v
v12.22.10
vscode ➜ /workspaces/FR-Comparator/src/Stateful1 (master ✗) $ npm -v
6.14.16
vscode ➜ /workspaces/FR-Comparator/src/Stateful1 (master ✗) $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.416
 Commit:    8d3765c609

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.416/

Host (useful for support):
  Version: 3.1.22
  Commit:  35fa579a30

.NET Core SDKs installed:
  3.1.416 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
vscode ➜ /workspaces/FR-Comparator/src/Stateful1 (master ✗) $ COLUMNS=132 dpkg -l | grep azure-functions-core-tools-3
ii  azure-functions-core-tools-3   3.0.3904-1                        amd64        Azure Function Core Tools v3
```

Whenever I try to add a trigger or Operation from Built-In tab of the Designer for a workflow.json, it throws me the following error (actually making impossible to add a Built-In trigger):

![ErrorBuiltIn](https://user-images.githubusercontent.com/11076471/155103636-b8697e0f-6cde-4794-b16d-1ea1ab80e2e8.png)

Operations from Azure tab are correctly shown and selectable:

![AzureOperations](https://user-images.githubusercontent.com/11076471/155104028-098fae84-c0ba-43ad-b003-9169a34aa098.png)

If I add the triggers or operations from Azure designer on the online resource, it works, I can copy and paste the generated workflow on the localdev one and from that moment onwards, I can configure the operations and triggers from VS Code.

**Comment by rubenaster** [comment]
@gabrieletassoni do you maybe have actions or triggers in your workflow that use a colon in the name? We had some issues with actions that had a colon in the name and got the same error message when viewing actions inside a run.

**Comment by gabrieletassoni** [comment]
Hi, the workflow.json was without actions or triggers, just the initial "skeleton" of the workflow.json as created by the extension.

**Comment by gabrieletassoni** [comment]
Could it maybe related to the fact that I'm working in a [Dev Container](https://code.visualstudio.com/docs/remote/containers)? Maybe the builtin list makes a request on a port not exported by the dev container, failing to get the list and instead obtaining an unparsable (by json) html error page?

Here is a screenshot of the ports section in my VS code while using the configuration posted in the initial bug report:

![Screenshot from 2022-02-24 16-46-32](https://user-images.githubusercontent.com/11076471/155558287-90efb3b5-5dc8-4891-b739-d4fb0092eaeb.png)

**Comment by cschar** [comment]
having same issue...
