### ISSUE TITLE
Unable to access storage account and getting 403 error

### ISSUE THREAD

**Issue by Kalyan-D** [Azure/logicapps#482]
I have enabled VNet integration and trying to access a storage account that has private endpoint.

From kudu application logs observed 403 error.

Could you please help me how to resolve this?

**Comment by mbarqawi** [comment]
can you check this post 
https://techcommunity.microsoft.com/t5/integrations-on-azure-blog/deploying-standard-logic-app-to-storage-account-behind-firewall/ba-p/2626286

**Comment by Kalyan-D** [comment]
@mbarqawi ,

I tried the above method and created a logic app, but I still get a 403 error.

**Comment by brandonros** [comment]
Is there a way to create logic app without storage account? Like from linux Docker container?

**Comment by mbarqawi** [comment]
@Kalyan-D 
If you have virtual appliances or NSG make sure that you have access to the storage account for the ports 445 and 443 
to test that I prefer to do the ping  and the NSlookup from VM on the same LA subnet 

@brandonros 
For testing you can use https://github.com/Azure/Azurite 
also there is iption to use SQL as database insted of Storage account
