### ISSUE TITLE
Renew lock token in logic app using Service Bus peek-lock trigger

### ISSUE THREAD

**Issue by cuongdq19** [Azure/logicapps#484]
Hi,
I'm running a logic app using Service Bus peek-lock trigger. The Service Bus queue has 5 minutes of message lock duration, which is the maximum time to set.
![image](https://user-images.githubusercontent.com/54937481/155478810-5a0d0772-afd5-45e5-8b25-c262c206ee87.png)
There is an issue when the processes take more than 5 minutes, then when I make a "Complete the message in a queue" after processing the logic, it returns a Bad Request.
![image](https://user-images.githubusercontent.com/54937481/155479346-61a072ec-00da-4b90-bd64-55bf5838d2a6.png)
There is a logic app action of "Renew the lock token of the session". But I haven't found any solutions to achieve this so that the lock token is renewed if the instance is running for more than 5 minutes.
If you have any solution, don't be afraid to raise and discuss it together. Thanks for your help.

**Comment by SahinOzdemir** [comment]
Interesting question. If an action before the complete takes more than 5 minutes, than it will become difficult to renew the token. If you're doing consequent actions, e.g. in a loop, just renew the token at each iteration, that way it doesn't expire.

Another thing that you could do try is to swap the lock token version of the sb action for an auto complete one. So it will retrieve and complete when the message arrives in the logic app. Downside is that you won't be able to have control over when to complete, defer or deadletter.
