### ISSUE TITLE
VS Code: Executed Terminate in stateless workflow means no run history

### ISSUE THREAD

**Issue by John-Bosch** [Azure/logicapps#488]
While using VS Code to run a **stateless** logic app locally (with run history enabled), having a Terminate action executed in the run means there is no run history displayed. This very simple workflow shows what I mean;

![image](https://user-images.githubusercontent.com/5135377/156104796-11168b08-c67f-4efd-b2b0-744410cc71bb.png)

The Terminate is set to return as a success, and the response returns 200, so the workflow appears to run correctly when I use Postman to run it, but no run history is displayed other than the opening request action.

If I make a slightly more complex workflow where I can conditionally execute the Terminate or not, I see the two following results;

![image](https://user-images.githubusercontent.com/5135377/156104959-ec2c0d71-aa7c-4420-9e63-5cb04e049f8b.png)

![image](https://user-images.githubusercontent.com/5135377/156104975-791272cf-7d8f-4712-bba7-a473fe001801.png)

In the first, the condition returns false and the Terminate action is processed. In the second the Terminate is bypassed as the condition returns true and the logic app completes normally.

Ignore the scopes, they are there purely as I initially thought it may only be Terminates within Scopes. However, the first screenshot shows this to not be the case.

**Comment by hongzli** [comment]
Thanks for reporting this -- we have identified it as a bug. The immediate workaround is to change the "AzureFunctionsJobHost__extensionBundle__version" app setting to have value "[1.1.26, 1.1.27)". We are working on a fix that should be deployed within 4-6 weeks, at which point the app setting value change can be reverted.

**Comment by John-Bosch** [comment]
No worries. Thanks for providing the workaround.

**Comment by mark-abrams** [comment]
Hi, is there any update for when this issue will be fixed?
