### ISSUE TITLE
Logic Apps Standard pricing query

### ISSUE THREAD

**Issue by daverobinson64** [Azure/logicapps#492]
I'm just trying to clarify the pricing (and also the terminology used in the pricing calculator) and it's not clear to me from the documentation. When I create a Logic App Standard and I assign it to a app service plan, e.g. WS1, if I then create another Logic App Standard also in the same plan I will then have 2 Apps running in that WS1 app service plan. Assuming it's running for 1 month then WS1 is around $180. However if I have two instances of Logic App Standard running, even in the same app service plan, do I get charged for 2x$180?

So I guess the questions is, am I charged for the number of instances of Logic App Standard running, or just instances of the App Service Plan (so multiple instances can share one app service plan and only receive one cost)?

Thanks

**Comment by SahinOzdemir** [comment]
You pay for the app Service plan and how you scale them up and down.
Pricing should be pretty clear. Consumption based you pay for the actions and connectors in the logic apl, while at standard you pay for the app Service (cpu/memory) as described here:
https://azure.microsoft.com/en-us/pricing/details/logic-apps/
