### ISSUE TITLE
HTTP Trigger not returning 400 for BadRequest

### ISSUE THREAD

**Issue by robin-parker** [Azure/logicapps#495]
I have enabled schema validation on a stateless workflow in a single-tenant logic app, when the trigger reports a `BadRequest` it does not return a 400, see screenshot.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/4507581/157646347-f3f0d1a9-c879-4512-bfb7-25433b60aadc.png">

The guide at https://docs.microsoft.com/en-us/azure/connectors/connectors-native-reqres#add-request-trigger, point 4 states it should return a 400.

**Comment by jackiefong** [comment]
I am facing the same exact issue.
