### ISSUE TITLE
Information request on Generate-Connections.ps1

### ISSUE THREAD

**Issue by PingPongSet** [Azure/logicapps#497]
Could anyone explain the purpose of this file below?
https://github.com/Azure/logicapps/blob/master/azure-devops-sample/.pipelines/scripts/Generate-Connections.ps1

I found some comments on the file, but still don't understand fully how it works and what the final file, Connections.json, looks like?

Does it replace API connection on Connections.json with below only?

`            "authentication": {
                "type": "ManagedServiceIdentity"
            }`

What other functions?

**Comment by ShreeDivyaMV** [comment]
@PingPongSet, this script would update the authentication to managedServiceIdentity and also retrieve the connection runtime URL from the  API connections deployed in Azure.

**Comment by ShreeDivyaMV** [comment]
@PingPongSet , Please let us know if any further questions on this?
