### ISSUE TITLE
Unable to create Logic App Consumption project using VS Code

### ISSUE THREAD

**Issue by thomasgauvin** [Azure/logicapps#498]
Creating a project using the Azure Logic App (Consumption) VS Code extension does not produce anything. The notification `Creating project...` pops up but does not complete & no files are created locally.

![image](https://user-images.githubusercontent.com/35609369/158233566-87750dd6-3c09-4327-bdf4-c9c80746505c.png)

Any help would be appreciated

**Comment by joechung-msft** [comment]
Creating a Consumption project just designates a folder as a Visual Studio Code workspace where you can add Logic Apps.

After you have created the project, you can add Logic Apps to the workspace by right-clicking the Logic App in the Azure explorer.

![image](https://user-images.githubusercontent.com/26208574/161162493-d6f29a77-6933-46a5-8a7f-d0a6cbf41e8a.png)

Once you have done this, two files should appear in your project, one for the definition template and one for the parameters template.

![image](https://user-images.githubusercontent.com/26208574/161162567-692f471a-6807-4c83-beac-c5106eb9f475.png)
