### ISSUE TITLE
Up Logic App concurrency control to 500?

### ISSUE THREAD

**Issue by Runamok81** [Azure/logicapps#50]
Do we know if the Logic Apps team is considering lifting the hard cap of 50 for the trigger concurrency control?  Perhaps to something like 500?
https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-workflow-actions-triggers#change-trigger-concurrency

I ask because our organization makes heavy use of Logic Apps.  Our Logic Apps are ingesting data from an occasionally “spikey” data source and then inserts it into an Azure SQL database.
The concurrency control helps us smooth those spikes and protect the downstream Azure SQL database. 
But – for our purposes - a hard limit of 50 concurrent LAs isn’t enough throughput to fully saturate a P6 or P11 Azure SQL database.
The 50 limit is a bottleneck for us.

Would the team ever consider raising the cap and giving customers more choice?   
If so, that would prevent my organization from having to re-architect this solution away from Logic Apps as we scale.  

@joechung-msft

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.

**Comment by joechung-msft** [comment]
@kevinlam1 and @derek1ee for PM visibility.

**Comment by kevinlam1** [comment]
@Runamok81 you can use a pattern to accomplish the throttling you desire.
Essentially you will create 3 sets of Logic Apps:
1. Interface Logic App - this has a request trigger that has no concurrency constraints and calls 1 of 10 copies of a "throttled" logic app which can be accomplished with a "rand(1, 10)" expression and a switch statement that has a case for each value between 1 and 10, where each case calls a different copy of the "throttled" logic app.
2. Throttled Logic Apps - create 10 copies of this logic app that has a request trigger with concurrency set to it's max limit (50). This logic app then calls the "Do Work" logic app.
3. Do Work Logic App - a single definition with a request trigger that has no concurrency control configured that handles all of the business logic.

**Comment by ssachde5** [comment]
@TroyWitthoeft  Looks like Kevinlam1 comment  to create multiple copy of logic app could be a solution till microsoft does the enhacnemnet at their end . please vote -  https://feedback.azure.com/forums/287593-logic-apps/suggestions/42360637-increase-logic-app-event-hub-connector-concurrency
