### ISSUE TITLE
Visual Studio Code Deploy to Logic App Error

### ISSUE THREAD

**Issue by cfraschettigwrr** [Azure/logicapps#500]
Does this occur consistently? Yes
Repro steps:

1. Download Visual Studio Logic App project from portal, after creating one.
2. Click the Deploy to Logic App and pick a logic app to deploy 

Action: azureLogicAppsStandard.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 1.0.12
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:2:4795306
Object.<anonymous> extension.bundle.js:2:4811126
fulfilled extension.bundle.js:2:4810302
```

</details>

**Comment by ShreeDivyaMV** [comment]
@cfraschettigwrr , Could you please try updating the project language setting in the Extensions settings(from the settings blade) as below.
![image](https://user-images.githubusercontent.com/30790938/162155151-0970d6bc-3cd6-44d9-9745-1d9b81920e73.png)

**Comment by cfraschettigwrr** [comment]
I found this setting and tried to add it explicitly.  The error was showing a deep python packages error.  This ended up being a problem with versioning of tools.  I update both Node JS (16.14.2) and Azure CLI (2.34.1). I believe it was the version of Azure CLI that I was using that was the culprit.  Thank you.
