### ISSUE TITLE
ECONNRESET when deploying single-tenant logic app to Azure from company VDI

### ISSUE THREAD

**Issue by akidd97** [Azure/logicapps#501]
Does this occur consistently? Yes from VSCode in Citrix VDI not from laptop when onsite.
Repro steps:

1. Deploy Standard Single-Tenant logic app from VSCode from company Citrix VDI.
2. Wondering if there is a port closed or company security is trying to decrypt/encrypt payload

Action: azureLogicAppsStandard.deploy
Error type: ECONNRESET
Error Message: request to https://---.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 1.0.12
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:3783067
ClientRequest.emit events.js:327:22
ClientRequest.EventEmitter.emit domain.js:467:12
TLSSocket.socketErrorListener _http_client.js:469:9
TLSSocket.emit events.js:315:20
TLSSocket.EventEmitter.emit domain.js:467:12
emitErrorNT destroy.js:106:8
emitErrorCloseNT destroy.js:74:3
processTicksAndRejections task_queues.js:80:21
```

</details>

**Comment by sven5** [comment]
It seems your VDI or firewall is blocking traffic. Nothing that can be handled by logic apps.
Ask you IT administrator for help.
