### ISSUE TITLE
Keep being prompted to choose project language when creating new logic app workflow. On choosing C# get this error

### ISSUE THREAD

**Issue by swalkeybirm** [Azure/logicapps#502]
Does this occur consistently? No, only with one specific project.
Repro steps:

1. Using the Azure Logic App plugin, click on the button to create a new (logic app) project.
2. The main project heading dialog prompts for 'project language'.
3. On choosing one from the drop down (i.e. C#) you get this error in the Output and the project create action does not happen.
4. On pressing the button again you are prompred to choose the language again and cannot progress passed this loop of 1 to 3.

Action: azureLogicAppsStandard.createCodeless
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 1.0.12
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:2:4795306
Object.<anonymous> extension.bundle.js:2:4811126
fulfilled extension.bundle.js:2:4810302
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by ShreeDivyaMV** [comment]
@swalkeybirm, Could you please try updating the project language setting in the Extensions settings(from the settings blade) as below.
![image](https://user-images.githubusercontent.com/30790938/161010562-c119dde9-1e15-40fb-9f4a-493eafb8bda8.png)

**Comment by ShreeDivyaMV** [comment]
@swalkeybirm, could you please let me know if any further questions on this?
