### ISSUE TITLE
Cannot get extension to run on M1 Mac

### ISSUE THREAD

**Issue by yobyot** [Azure/logicapps#504]
On an M1 Mac, every time I try to create a project with a new Logic App (Standard) in VS Code, I receive the following error:

`You must have the [.NET Core SDK](https://aka.ms/AA4ac70) installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions.`

This link takes you to the requirements for the Functions extension, which works fine.

Here's the output of `dotnet --list-sdks` from the `/users/local/share/dotnet/x64` directory:

```
1:47:16 PM callisto /usr/local/share/dotnet/x64> arch
i386
1:47:18 PM callisto /usr/local/share/dotnet/x64> ./dotnet --list-sdks
3.1.417 [/usr/local/share/dotnet/x64/sdk]
5.0.406 [/usr/local/share/dotnet/x64/sdk]
6.0.201 [/usr/local/share/dotnet/x64/sdk]
1:47:27 PM callisto /usr/local/share/dotnet/x64>
```

Here's the output of `dotnet --list-sdks` from `/user/local/share/dotnet' (the ARM directory):
```
1:49:17 PM callisto /usr/local/share/dotnet> arch
arm64
1:49:19 PM callisto /usr/local/share/dotnet> dotnet --list-sdks
6.0.201 [/usr/local/share/dotnet/sdk]
1:49:30 PM callisto /usr/local/share/dotnet>
```

I've tried:
- Opening VS Code in Rosetta
- Altering VS Code's dotnet path settings as follows:
```
    "dotnetAcquisitionExtension.existingDotnetPath": [
    
        {
            "extensionId": "msazurermtools.azurerm-vscode-tools",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-azuretools.vscode-bicep",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "ms-azuretools.vscode-azurefunctions",
            "path": "/usr/local/share/dotnet/x64/dotnet"
        },
        {
            "extensionId": "ms-azuretools.vscode-azurelogicapps",
            "path": "/usr/local/share/dotnet/x64/dotnet"
        },
    ]
```
Note that `ms-azuretools.vscode-azurefunction` _is_ able to find and use the x64 installed SDK and create projects.

Does anyone have any suggestions of what I might have missed or workarounds?

**Comment by bradshaw84nz** [comment]
Which versions of the Functions Tool have you got installed? it does not support V4.x and you have to run using V3.x

**Comment by yobyot** [comment]
Thanks, @bradshaw84nz.

I believe I have the right version of the functions app installed and specified in the extension's settings. 
![2022-04-04_09-02-37](https://user-images.githubusercontent.com/14332263/161549747-cf81be32-f2b9-456e-93ad-135b91d46351.png)

**Comment by bradshaw84nz** [comment]
`	"dotnetAcquisitionExtension.existingDotnetPath": [
		{
			"extensionId": "msazurermtools.azurerm-vscode-tools",
			"path": "/usr/local/share/dotnet/dotnet"
		},
		{
			"extensionId": "ms-azuretools.vscode-bicep",
			"path": "/usr/local/share/dotnet/dotnet"
		  }
	],
	  // The name of the Python virtual environment used for your project. A virtual environment is required to debug and deploy Python functions.
	"azureLogicAppsStandard.pythonVenv": "~3",`
	
My VSCode Settings, it complains about 3.1 SDK not being there but everything appears to still run correctly at the moment, I have not done any heavy lifting with it yet though.

**Comment by yobyot** [comment]
Thanks, @bradshaw84nz. But, as you can see, if I set my `dotnetAcquisitionExtension.existingDotnetPath` to match yours, the Logic Apps extension still fails. But set as I indicated above _or_ as you have it, the Function extension can successfully create a project.

![logicapp](https://user-images.githubusercontent.com/14332263/161650873-9503ecdd-5a7d-4bee-a81a-7bd7d3f33794.gif)
