### ISSUE TITLE
socket hangup when deploying Logic App (standard) via VS code

### ISSUE THREAD

**Issue by rathna121** [Azure/logicapps#507]
Does this occur consistently? Yes
Repro steps:

 Added a new workflow in Logic App(standard) created in VS code. Tried deploying using VS code  into Azure portal but it takes a long time to deploy and hangs up.  Using Azure event grid as trigger.

Action: azureLogicAppsStandard.deploy
Error type: ECONNRESET
Error Message: request to https://---.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 1.0.12
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.66.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:3783067
```

</details>

**Comment by cokiochoa3** [comment]
Dealing with this issue too. This is the Logic App that I previously successfully locally tested based on: https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#debugging-fails-to-start

2:08:56 PM logicapp-http-email-vscode-2: Starting deployment...
2:09:02 PM logicapp-http-email-vscode-2: Creating zip package...
2:09:12 PM logicapp-http-email-vscode-2: Zip package size: 33.1 MB
2:25:03 PM: Error: request to https://logicapp-http-email-vscode-2.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

**Comment by masakawa527** [comment]
I have the same problem. When will this problem be corrected?
The Functions side of the issue is said to be resolved in this Issue.

https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1111435719

It would be great if you could fix the VSCode downgrade as it is not possible.

**Comment by nareshnagpal06** [comment]
I am also having same issue.  Error comes after 15 minutes of clicking on deploy and keeps going until below error is thrown

 **failed, reason: socket hang up**

It was working fine earlier but not sure if its due to VS code upgrade or something else. 

I have 4 workflows in logic app. If I delete 2 workflows and just deploy 2, it works fine. Very annoying. 


Resolution: I had June 2022 version of VS code and I started downgrading from may till Feb. And Feb Version worked.

**Comment by johan-burman** [comment]
Same issue here. This issue just appeared out of the blue, and only affected some standard logic apps.

After downgrading (from July to Feb), deploy is working again.

**Comment by onurmicoogullari** [comment]
I'm having the same problem with error "**failed, reason: socket hang up**" during deployment. Tried downgrading VS Code to February 2022 (version 1.65) as stated in above comments, but now I can't run my Logic App locally. I'm getting the following error when i try:

![image](https://user-images.githubusercontent.com/69526842/184532677-4a1c35f3-2daa-4dff-9a8d-d239825297c0.png)



I'm running Logic App (Standard) extension v. 1.0.25. Anyone else having the same problem?
