### ISSUE TITLE
Logic resume work flow after web hook call or multiple HTTP Request

### ISSUE THREAD

**Issue by pranavdhundhia** [Azure/logicapps#51]
I am setting up a work flow with web hook URL.

Following are the steps we have configured.
1) Http Request is received.
2) Send Email with Gmail plugin
3) Response 200
4) WebHook Call back to Application
5) **Resume WorkFlow to continue other operations ( Ex.  Send Email With outlook configuration)**

Do have faced problem to resume work flow after web-hook URL is successfully executed.

![image](https://user-images.githubusercontent.com/3126366/53809565-017ce380-3f7b-11e9-920e-191a86bbf4a5.png)

![image](https://user-images.githubusercontent.com/3126366/53861727-08533700-400b-11e9-901e-2123b0754080.png)

Image shows request still in request state after web-hook URL Called.  Unable to resume logic app workflow after webhook URL.

Please lets me any workaround to resolve this issue.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
