### ISSUE TITLE
New Logic App Fails - Could not load file or assembly Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by Garyljackson** [Azure/logicapps#516]
When I create a new Azure Logic App, add a work flow, then try open the designer I get the following error in the Output window for the "Azure Logic Apps (Standard)" VS Code extension.

```
4:44:16 AM: Running command: "func host start --port 8000"...

Azure Functions Core Tools
Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0

[2022-04-19T04:44:21.463Z] A host error has occurred during startup operation 'e3e7df04-9092-4133-b672-434135af3450'.
[2022-04-19T04:44:21.463Z] System.Private.CoreLib: Exception has been thrown by the target of an invocation. Microsoft.Azure.Workflows.ServiceProviders.ServiceBus: Could not load file or assembly 'Microsoft.Azure.ServiceBus, Version=4.2.1.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c'. The system cannot find the file specified.
[2022-04-19T04:44:21.463Z] .
Value cannot be null. (Parameter 'provider')

```

If I start Azurite, and try run the app, I get this error:

```
5:18:27 AM: Running command: "func GetExtensionBundlePath"...
5:18:29 AM: Extension bundle path: "/home/vscode/.azure-functions-core-tools/Functions/ExtensionBundles/"...
5:18:29 AM: Error: ENOENT: no such file or directory, scandir '/home/vscode/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows'
```

### Versions:  
.NET Core SDK version: `3.1.416`

```
Azure Functions Core Tools
Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0
```

## Prerequisites 
- Visual Studio Code
- Docker Desktop
- VS Code - Remote Containers Extension ("ms-vscode-remote.remote-containers")

## Quick Example:
Here is an example app that I built using a VS Code dev container - just clone the app, and open using a dev container in VSCode
https://github.com/Garyljackson/azure-logic-app-example/tree/example-app

If you want just the dev container (which also includes all the required VS Code extensions) then that's on the main branch
https://github.com/Garyljackson/azure-logic-app-example

The dev container used is the standard Microsoft provided `Azure Functions & C# - .NET Core 3.1` dev container.  

![image](https://user-images.githubusercontent.com/5189408/163923268-eb7ee70a-3a6e-42de-9f19-e2d2881c6f31.png)

## Manual Steps:
- Open Visual Studio Code in a folder
- Using the remote container ext: "Add Development Container Configuration Files"
- Select the `Azure Functions & C# - .NET Core 3.1` dev container
- Edit `devcontainer.json` extensions section to: 

```
	"extensions": [
		"ms-azuretools.vscode-azurefunctions",
		"ms-dotnettools.csharp",
		"ms-azuretools.vscode-azurelogicapps",
		"ms-azuretools.vscode-docker",
		"ms-vscode.azure-account",
		"Azurite.azurite"
	],
```
- Using the remote container ext: `Open Folder in Container`
- Wait for container to build, and for extensions to install
- In VSCode, select the Azure Extension, and then the `Logic Apps (Standard)` section
- Click the "Create New Project" button
- Accept the default folder
- Select `Stateful Workflow`
- Name workflow `Stateful1`
- Go back to the explorer view, right click on the `Workflow.json` and select `Open in Designer` (it will fail)
- Go to the `OUTPUT` tab and view the output for `Azure Login App (Standard)` - Error above

The same error occurs irrespective of whether I start Azurite or not

If you want to try run the App:
- Start Azureite
- F5

**Comment by AshirwadSatapathi** [comment]
I'm getting the same error while working with a stateless workflow. My project was working file till yesterday but since today morning it's throwing up this error.

**Comment by axellundh** [comment]
I am experiencing the same issue.

```
Azure Functions Core Tools
Core Tools Version:       3.0.4425 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.4.2.0

[2022-04-19T10:27:19.300Z] A host error has occurred during startup operation '0fdf7dcd-8d17-4cf6-8c5e-531d15b0a45b'.
[2022-04-19T10:27:19.300Z] System.Private.CoreLib: Exception has been thrown by the target of an invocation. Microsoft.Azure.Workflows.ServiceProviders.ServiceBus: Could not load file or assembly 'Microsoft.Azure.ServiceBus, Version=4.2.1.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
```

**Comment by ruuddrummen** [comment]
Same issue with same logs here reproduced on three separate environments. Was working fine last Friday.

Built a clean environment this morning with just
- .NET Core v3.1.418 x64
- Azure Functions Core Tools v3.0.4484 x64
- VS Code with Azure Functions and Azure Logic Apps (Standard) extensions

Created a fresh logic app project and tried opening the designer:
```
[2022-04-19T10:40:12.571Z] A host error has occurred during startup operation 'f934548c-b7e6-4fcc-8705-2f6ff52b4074'.
[2022-04-19T10:40:12.571Z] System.Private.CoreLib: Exception has been thrown by the target of an invocation. Microsoft.Azure.Workflows.ServiceProviders.ServiceBus: Could not load file or assembly 'Microsoft.Azure.ServiceBus, Version=4.2.1.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
```

**Comment by leighchilcott** [comment]
Getting exactly the same, everything was working fine last week, but today I cannot open the designer for any workflow

**Comment by john-long2** [comment]
Same error for me.  

I installed the updates below this weekend, not sure if anyone else has installed these are they the issue?

![Capture](https://user-images.githubusercontent.com/104009538/164013075-0c6392f9-03ff-42b9-9377-20407299af20.PNG)

**Comment by koenloyens** [comment]
The file Microsoft.Azure.ServiceBus.dll is missing in my folder bin where version 1.1.54132173 has been installed.
when I copy the file from the version 1.1.32 and run func host start --port 8001 --verbose 
I get error : 
A host error has occurred during startup operation
Microsoft.WindowsAzure.Storage: Value cannot be null. (Parameter 'connectionString')
Initializing Warmup Extension.
There was an error performing a read operation on 
the Blob Storage Secret Repository. Please ensure the 'AzureWebJobsStorage' connection string is valid.
Value cannot be null. (Parameter 'provider')

**Comment by yusufzerdazi** [comment]
Copying `Microsoft.Azure.ServiceBus.dll` from the previous version of the Extension Bundle seems to fix this.

I copied it from 
`C:\Users\<UserName>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.1.32\bin`
to
`C:\Users\<UserName>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.1.54132173\bin`

and the designer opened fine.

**Comment by alexkarcher-msft** [comment]
We have rolled back the release on our side and you all should see your bundles updated locally in the next hour or so (11:30am PDT expected resolution). No change is needed on your side. VS Code should downgrade the package automatically to 1.1.32.

**Comment by Garyljackson** [comment]
> We have rolled back the release on our side and you all should see your bundles updated locally in the next hour or so (11:30am PDT expected resolution). No change is needed on your side. VS Code should downgrade the package automatically to 1.1.32.

Thanks Alex, will give it another try today

**Comment by Garyljackson** [comment]
> We have rolled back the release on our side and you all should see your bundles updated locally in the next hour or so (11:30am PDT expected resolution). No change is needed on your side. VS Code should downgrade the package automatically to 1.1.32.

Hi @alexkarcher-msft 

Can you please confirm which repo had the change that was rolled back?
It doesn't appear to be part of this one.

Thanks

**Comment by alexkarcher-msft** [comment]
These packages are built from a private repository. We're still in the midst of a root cause analysis, so for the time being we've just re-deployed the previous version of our extension.

**Comment by Garyljackson** [comment]
> These packages are built from a private repository. We're still in the midst of a root cause analysis, so for the time being we've just re-deployed the previous version of our extension.

Thanks @alexkarcher-msft would you like me to leave this issue open for the root cause analysis result or close it?

**Comment by alexkarcher-msft** [comment]
Feel free to close it. We have our own internal incident we're using to track the underlying cause. So long as you're seeing the issue fixed on your side I'd say this is fully resolved. We'll fix whatever is wrong before pushing a new release.

**Comment by Garyljackson** [comment]
> Feel free to close it. We have our own internal incident we're using to track the underlying cause. So long as you're seeing the issue fixed on your side I'd say this is fully resolved. We'll fix whatever is wrong before pushing a new release.

Okay, will do, I've progressed further now, but have encountered a new issue - I'll create a new issue with the details.

Thanks
