### ISSUE TITLE
Can't obtain worfkflow history and callback url with designer

### ISSUE THREAD

**Issue by milicevica23** [Azure/logicapps#517]
After creating a new project and workflow with http triger i was not able to get callback url and workflow history

![image](https://user-images.githubusercontent.com/46800472/164092761-dc34bc1f-8400-448a-b7f7-e7562593b4bc.png)

![image](https://user-images.githubusercontent.com/46800472/164091355-43e38dc3-8c7b-4f66-8ee0-a41394c06f6a.png)

There is a problem with the url which is send to the logic app (port -> undefined) i also tried with the port 7071 and got respose with the history. 

Can i provide port number to the logic app extension?

Could you provide how can i obtain callback url from the workflow with a rest api call? 

```
Azure Functions Core Tools
Core Tools Version:       3.0.4484 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.4.2.0
```
Logic app (Standard)

AB#15957676

**Comment by enhendrickson** [comment]
I'm having similar issues when I try to run multiple logic apps where one of them is running on a non-standard port; the overview doesn't work.

**Comment by hartra344** [comment]
We are currently unable to support running on a non standard port. Tracking this as a feature request as we work on updating our VSCode experience.

**Comment by ccastrotrejo** [comment]
Hi @milicevica23  can you state which version of the extension you are using?

**Comment by ccastrotrejo** [comment]
Hi @enhendrickson as a workaround you can run multiple logic apps in standard ports and use overview, by specifying the port in the .vscode/tasks.json file 
<img width="599" alt="Screenshot 2022-11-08 at 3 34 52 PM" src="https://user-images.githubusercontent.com/102700317/200699234-7a8531bd-7cbf-4f12-8dbd-1037b402b3a5.png">
