### ISSUE TITLE
New Logic App - Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Garyljackson** [Azure/logicapps#518]
## Overview
When I create a new Logic App, define workflow and then try run it, it produces the following error

### Error Popup
![image](https://user-images.githubusercontent.com/5189408/164117717-e60ebd4a-358b-4745-9cc7-b1f7347e6c4e.png)

### Extension Output Window Message
```
11:30:43 PM: Running command: "func GetExtensionBundlePath"...
11:30:43 PM: Extension bundle path: "/home/vscode/.azure-functions-core-tools/Functions/ExtensionBundles/"...
11:30:43 PM: Error: ENOENT: no such file or directory, scandir '/home/vscode/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows'
```

### Versions
.NET SDK  
```
vscode@7bd6c6f89c76:/workspaces/azure-logic-app-example$ dotnet --list-sdks
3.1.416 [/usr/share/dotnet/sdk]
```

Azure Functions Core Tools  
```
Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0
```
## How to reproduce
I've used a Visual Studio Code dev container to reduce machine specific configuration differences as much as possible.  

### Prerequisites
 - Visual Studio Code
 - WSL (Windows Subsystem for Linux)
 - Docker Desktop
 - VS Code - Remote Containers Extension ("ms-vscode-remote.remote-containers")
 

This example uses the standard Microsoft provided dev container named: `Azure Functions & C# - .NET Core 3.1`  
The only difference is I've updated the `devcontainer.json` extensions section to include the prerequisite logic app extensions
```
	"extensions": [
		"ms-azuretools.vscode-azurefunctions",
		"ms-dotnettools.csharp",
		"ms-azuretools.vscode-azurelogicapps",
		"ms-azuretools.vscode-docker",
		"ms-vscode.azure-account",
		"Azurite.azurite"
	],
```

### Sample App Steps:
- Clone the repo: https://github.com/Garyljackson/azure-logic-app-example/tree/example-app-2 
- Visual Studio Code: Open Folder In Container
- Visual Studio Code Command palette: `Azurite: Start`
- Run App: F5
- Visual Studio shows the error popup (shown above) and the error is visible in the `Azure Logic App (Standard)` OUTPUT window (also above)

### Manual Steps
- Start a new Visual Studio Code instance
- Create a dev container using the `Azure Functions & C# - .NET Core 3.1`  definition
- Add the required extensions (listed above)
- Add a new statefull logic app
- Right click on the workflow and select `Open in Designer`
- Enable Connectors in Azure: select  `Skip for now`
- Update the workflow (see below)
- Start Azurite
- Run (F5)

### Workflow Screenshot
![image](https://user-images.githubusercontent.com/5189408/164117172-e460b3b5-faf1-43aa-b5ae-d177f0fb868e.png)

### Workflow Raw JSON
```
{
  "definition": {
      "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
      "actions": {
          "Response": {
              "type": "Response",
              "kind": "http",
              "inputs": {
                  "statusCode": 200,
                  "body": "Hidi ho"
              },
              "runAfter": {}
          }
      },
      "triggers": {
          "manual": {
              "type": "Request",
              "kind": "Http",
              "inputs": {}
          }
      },
      "contentVersion": "1.0.0.0",
      "outputs": {}
  },
  "kind": "Stateful"
}
```

## Workaround
I have discovered that if I comment out the `generate Debug Symbols` in the `.vscode/tasks.json` file I can get the project to run - but I guess that means I won't be able to debug.

```
{
  "version": "2.0.0",
  "tasks": [
    // {
    //   "label": "generateDebugSymbols",
    //   "command": "dotnet",
    //   "args": [
    //     "${input:getDebugSymbolDll}"
    //   ],
    //   "type": "process",
    //   "problemMatcher": "$msCompile"
    // },
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true
    }
  ],
  "inputs": [
    {
      "id": "getDebugSymbolDll",
      "type": "command",
      "command": "azureLogicAppsStandard.getDebugSymbolDll"
    }
  ]
}

```

**Comment by Garyljackson** [comment]
Hi Guys

Any thoughts on this?

**Comment by cuntoulishifu** [comment]
run into the same problem...

**Comment by Garyljackson** [comment]
> run into the same problem...

Yeah, still an issue for me too
