### ISSUE TITLE
VS code Depoy to Logic Apps error

### ISSUE THREAD

**Issue by scleynen** [Azure/logicapps#519]
Does this occur consistently? yess
Repro steps:

1. Deploy workflow from vs code

Action: azureLogicAppsStandard.deploy
Error type: 400
Error Message: 400.0 BadRequest

Version: 1.0.14
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1743760
extension.bundle.js:2:1731594extension.bundle.js:2:1731594
```

</details>

**Comment by john-long2** [comment]
I have also started experiencing issues deploying from vs code.  This is happening on new and existing Logic App projects.

![image](https://user-images.githubusercontent.com/104009538/164417851-09e55caa-39b3-4cc3-84d5-7914d8024103.png)

**Comment by daverobinson64** [comment]
I'm also getting this on a project I'm working on and it started happening about 1 week ago. Exactly same error as john above.

**Comment by MrJGrav** [comment]
I am seeing exactly the same issue.

**Comment by Asit777** [comment]
I'm also getting this same error
