### ISSUE TITLE
Multiple trigger in single work flow

### ISSUE THREAD

**Issue by pranavdhundhia** [Azure/logicapps#52]
How is it possible have multiple trigger call's in single work flow ? 

Eg:
Step1:  HttpTrigger  leave approval (Mail sending context)
Step2:  Send leave request mail for approval to applier and Approver
Step3:  HttpTrigger  leave accepted (Mail sending context)
Step4: Send leave accepted mail 

if you have found a way ,somehow to mitigate the issue, please let me know. Thank you

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
