### ISSUE TITLE
Cannot edit LA standard workflows in Portal that were originally developed in VS Code

### ISSUE THREAD

**Issue by daverobinson64** [Azure/logicapps#520]
Apologies if this is raised elsewhere but I cannot find anything.

If I develop a Logic App standard workflow in VS Code when I deploy to Azure and attempt to edit in the portal it will not let me save it and I get the following error

Failed to save workflow
ajaxExtended call failed

From what I've seen in the documentation I should be able to edit it, but have I missed something here?

Point 4 of the following links suggests you should be able to
- https://docs.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#manage-deployed-logic-apps-in-the-portal

**Comment by rob-thijssen** [comment]
I am facing the same issue here. with LogicApp standard (west-europe). In the past I was able to edit the LogicApp workfl;ow that was originally deployed with Azure DevOps (zip deployment).
Now it is not possible anymore, with the exception message described in the topic start. 
What was changed that introduced this (unwanted, unexpected(?)) behaviour?
Thanks in advance!

**Comment by rob-thijssen** [comment]
@daverobinson64,
I found out what was wrong with our LogicApps at our side. Due to a change in our deployment pipelines, the WEBSITE_RUN_FROM_PACKAGE was set to 1.
This caused the behaviour that we couldn't edit the logicApp workflows in the portal. 
After fixing the pipeline back to the original settings, the WEBSITE_RUN_FROM_PACKAGE now is deleted again before deployment. 
Maybe this setting is also present at your configuration settings? Set it to 0, or delete it, and you will be able to edit the LogicApps in the portal again.

**Comment by anjani40612000** [comment]
Is there any resolution for this one, I am facing similar issue. 
If I develop a Logic App standard workflow in VS Code when deploy to Azure and attempt to edit in the portal giving the following error. 
Failed to save workflow
ajaxExtended call failed

After updating  WEBSITE_RUN_FROM_PACKAGE:0 all the workflow gone.

**Comment by hartra344** [comment]
This is by design if the Logic App is getting deployed as run from package. Here is the documentation: https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package

**Comment by anjani40612000** [comment]
Is there any workaround , don't want to deploy logic app manually.

**Comment by hartra344** [comment]
As a general rule of thumb, if you’re developing locally and using CICD to deploy then you should not be editing in portal as well. You should use VsCode and your local environment for development. Doing both would go against advised best practices.
