### ISSUE TITLE
Logic app standard - local development in vscode parametrization of connections.json

### ISSUE THREAD

**Issue by ykursav** [Azure/logicapps#527]
Hi all,

I have parametrized connections.json in the root directory of project. When you try to open with designer in vscode it throws below error: (It is same like issue https://github.com/Azure/logicapps/issues/463 but in local development environment.)

I tried multiple options like putting parameters instead of appsettings etc. nothing works.

![image](https://user-images.githubusercontent.com/13722374/165713969-adbece9e-7a08-4c3b-a99d-bc45d955b94a.png)

It would be nice to be able to use same parametrized connections.json file for local development and deploying to azure.

AB#16030165

**Comment by erwinkramer** [comment]
What works for me: 

Don't reference to appsettings directly, instead; reference to the parameters.json first like:
`@{parameters('WORKFLOWS_SUBSCRIPTION_ID')}
`

Then reference to your appsettings inside your parameters.json like:
`@{appsetting('WORKFLOWS_SUBSCRIPTION_ID')}`

**Comment by erwinkramer** [comment]
Please re open

**Comment by ccastrotrejo** [comment]
Hey all, 
Support for parameterization in local without burly braces was made in Sep 7th (from 1.0.40 version). Meaning that connections.json can support both types of parameterization: 
`@{parameters('WORKFLOWS_SUBSCRIPTION_ID')}` & `@parameters('WORKFLOWS_SUBSCRIPTION_ID')`

As for now Portal does **only** support parameterization **with** curly braces. Meaning that connections.json can only support:
`@{appsetting('WORKFLOWS_SUBSCRIPTION_ID')}`
