### ISSUE TITLE
400.0 BadRequest while deploying Logic Apps

### ISSUE THREAD

**Issue by Asit777** [Azure/logicapps#531]
Does this occur consistently? Yes 
Repro steps:
1. Deploy logic app from VS Code

Action: azureLogicAppsStandard.deploy
Error type: 400
Error Message: 400.0 BadRequest

Version: 1.0.19
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1743760
extension.bundle.js:2:1731594extension.bundle.js:2:1731594
```

</details>

**Comment by ppanchal-mobiz** [comment]
I am facing the same issue #563. Were you able to fix it or any workaround?
