### ISSUE TITLE
Logic Apps (Standard) - Service Bus Connector not deserializing contentType application/json; charset=utf-8

### ISSUE THREAD

**Issue by asos-chrishimsworth** [Azure/logicapps#536]
When using the below workflow, if a message is processed with a `contentType` of 
`application/json; charset=utf-8`, then when the sub-workflow is invoked, the contents of the message are not passed through as JSON. 
The raw input just shows as:
`   
 "body": {
        "$content-type": "application/json; charset=utf-8",
        "$content": "eyJ0b........"
    }`    

 If I manually re-submit the same message, but change the `contentType` to be just `application/json` the message is processed as expected and the contents are passed to the sub-workflow as JSON.
The raw input shows correctly as JSON:
`"body": {
        "topic": "...",
        "subject": "..."      
    }`

The source of the Service Bus message is an Event Grid Subscription to Service Bus, so I cannot control the message being published. 

![image](https://user-images.githubusercontent.com/79143631/166960027-21285b59-1bf3-46ed-8911-9c56b17c2333.png)

The workflow action is:
`{
    "inputs": {
        "host": {
            "workflow": {
                "id": "EventGridProcessor"
            }
        },
        "body": "@items('For_each_message')?['contentData']"
    }
}`

**Comment by apranaseth** [comment]
Thanks Chris for reporting this. We will be fixing this.
