### ISSUE TITLE
Error while opening designer from vscode

### ISSUE THREAD

**Issue by suryawanshi-rakesh** [Azure/logicapps#542]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.openDesigner
Error type: Error
Error Message: Error in determining project root. Please confirm project structure is correct.

Version: 1.0.19
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.67.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:4260062
fulfilled extension.bundle.js:2:4259287
```

</details>

**Comment by ccastrotrejo** [comment]
Hey @suryawanshi-rakesh , please install the new 1.0.34 version of the extension. If this still happens, please let me know. Otherwise, I will close this issue by 9/15. Thanks

**Comment by hartra344** [comment]
The answer can also be found here: #619
