### ISSUE TITLE
Deployment fails from VSCode

### ISSUE THREAD

**Issue by tshabeer** [Azure/logicapps#544]
Does this occur consistently? 
Repro steps:

1.Deploy to Logic App
2.00:50:19 las-01-smrint-genric-dev: Starting deployment...
00:50:20 las-01-smrint-genric-dev: Creating zip package...
00:50:20 las-01-smrint-genric-dev: Zip package size: 12.7 kB
00:51:16: Error: 400.0 BadRequest

Action: azureLogicAppsStandard.deploy
Error type: 400
Error Message: 400.0 BadRequest

Version: 1.0.19
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1743760
extension.bundle.js:2:1731594extension.bundle.js:2:1731594
```

</details>

**Comment by ppanchal-mobiz** [comment]
I am facing the same issue #563. Were you able to fix it or any workaround?
