### ISSUE TITLE
Logic App Standard - "Backups" option is disabled

### ISSUE THREAD

**Issue by mhireholi** [Azure/logicapps#546]
@divyaswarnkar 

Do you know why the "Backups" option in the logic app standard is disabled? 

![image](https://user-images.githubusercontent.com/40304643/168690767-72660b79-c428-4cd9-a68d-a882548a8c52.png)

**Comment by divyaswarnkar** [comment]
@mhireholi the backup capability is not available on Logic Apps. How important is that for you ? What is your use case for backup.

**Comment by mhireholi** [comment]
> @mhireholi the backup capability is not available on Logic Apps. How important is that for you? What is your use case for backup.

@divyaswarnkar : backups and disaster recovery are very important for BCDR especially when everything is running in the cloud.
