### ISSUE TITLE
Run into error when debugging azure logic apps locally in vscode

### ISSUE THREAD

**Issue by cuntoulishifu** [Azure/logicapps#549]
error : Could not find path to extension bundle.

**Comment by cuntoulishifu** [comment]
**here is the output content :**
3:27:35 PM: Running command: "func GetExtensionBundlePath"...
3:29:16 PM: Could not find path to extension bundle
3:29:16 PM: {"status":1,"signal":null,"output":[null,"","Unable to locate extension bundle.\r\n"],"pid":33832,"stdout":"","stderr":"Unable to locate extension bundle.\r\n"}
3:29:16 PM: Error: Could not find path to extension bundle.
3:29:17 PM: Running command: "func GetExtensionBundlePath"...
3:31:02 PM: Could not find path to extension bundle
3:31:02 PM: {"status":1,"signal":null,"output":[null,"","Unable to locate extension bundle.\r\n"],"pid":35260,"stdout":"","stderr":"Unable to locate extension bundle.\r\n"}
3:31:02 PM: Error: Could not find path to extension bundle.

**the same time I run 'func GetExtensionBundlePath' in TERMINAL, I got :**
PS C:\Work\test-logicapp> func GetExtensionBundlePath
C:\Users\xxxxxxx\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.1.35

**Comment by jstenlund** [comment]
I'm experiencing exactly the same issue now since a couple of days back. Before that, I have never seen this error.

@cuntoulishifu Were you able to work around it somehow?

**Comment by jstenlund** [comment]
> I'm experiencing exactly the same issue now since a couple of days back. Before that, I have never seen this error.
> 
> @cuntoulishifu Were you able to work around it somehow?

Suddenly, everything started to work for me again... To my knowledge, I did not do anything to fix it.

**Comment by ccastrotrejo** [comment]
Hey @cuntoulishifu and @jstenlund , please install the new 1.0.34 version of the extension. If this still happens, please let me know. Otherwise, I will close this issue by 9/15. Thanks
