### ISSUE TITLE
VSCode - Can't see workflow run history since version 1.0.6

### ISSUE THREAD

**Issue by asos-yusufzerdazi** [Azure/logicapps#551]
*Does this occur consistently?* Yes

*Repro steps:*

1. Create new logic app project locally
2. Run the project
3. Right click workflow and click "Overview"
4. Run history is not shown. The following error appears
![image](https://user-images.githubusercontent.com/84977594/169262870-ad33b6c7-2ba8-448f-8135-bf003be1eb23.png)

After downgrading to version 1.0.6, the issue no longer happens and the run history is shown.

AB#16572343

**Comment by asos-yusufzerdazi** [comment]
This is not resolved, we still have to manually update the JS file for each new version

**Comment by NitashaV** [comment]
Re-Opening the issue for investigation

**Comment by ccastrotrejo** [comment]
Hi @asos-yusufzerdazi, I am looking at this issue and I can only replicate it when I don't debug the app. I can tell by your first screenshot that it seems that you are not debugging it as the Debug bar isn't in it.
![Screenshot 2022-12-12 at 10 55 13 AM](https://user-images.githubusercontent.com/102700317/207106241-599f03db-2fd3-4b3a-b0d7-28c97199fae7.png)

Could you please try to debug the app by pressing `F5` or by going to the `Run and Debug` view in the activity bar and click in the green run button. If you are already doing this, please let me know, to do a further investigation.
During this step of debugging the app, we get the port from the azurite server.

**Comment by asos-yusufzerdazi** [comment]
@ccastrotrejo This is happening only when debugging is running. When it's not running, I just get "Failed to fetch" 
![image](https://user-images.githubusercontent.com/84977594/207595444-9f2c24d6-c425-44fb-b024-997b9958959f.png)

We have had to manually replace the token ${I.ext.workflowRuntimePort} in "extension.bundle.js" with "7071" in order to be able to view the run history.

**Comment by ccastrotrejo** [comment]
@asos-yusufzerdazi Thanks for replying. I have been trying to repro your issue when running the app, still dont be able to repro.
Could you please state the version of azurite, azure functions core tools and .NET installed in your computer?
Does the IDE turns orange when you press `F5` as a sign of running the app?

For what I can see is that the application is not picking up the running server port.  Please make sure that the `.vscode/launch.json` and `.vscode/tasks.json` files aren't manipulated/updated as that config has an important role in this process.
