### ISSUE TITLE
User-Assigned identity support for HTTP connector action in LA Standard

### ISSUE THREAD

**Issue by erwinkramer** [Azure/logicapps#566]
When will user-assigned identities be supported for the HTTP connector, i'm currently getting a false error where it's assuming i have a system assigned identity (which i don't have):
`
User identity is not supported when Logic App has system assigned managed identity enabled.
`

**Comment by zhangadreedom** [comment]
Hello @erwinkramer you can have a look here to see if System assigned identity is enable or not.
![image](https://user-images.githubusercontent.com/69228696/172541364-61e646b1-2bd7-4ece-8b18-57d96d8491a5.png)

**Comment by erwinkramer** [comment]
> Hello @erwinkramer you can have a look here to see if System assigned identity is enable or not. ![image](https://user-images.githubusercontent.com/69228696/172541469-a2a0826a-9883-4a32-a9c1-912abd48ad47.png)

I don't have it enabled but I'm also running locally so it shouldn't check in Azure
