### ISSUE TITLE
Unable to deploy Logic Apps Standard with Zone Redundancy enabled

### ISSUE THREAD

**Issue by novenera** [Azure/logicapps#567]
My customer was trying to deploy Logic Apps Standard with Zone redundancy in Australia East region. However, they reported getting an error, saying: 

![image](https://user-images.githubusercontent.com/16081468/172504603-598a9516-292e-4740-bdd4-fc77ef2fe072.png)

There is some confusion as to whether:

- AZ has already been enabled for Logic Apps in general (whether in Public Preview or GA)
- AZ enabled for Consumption only
- AZ enabled for Standard only 
- AZ has been enabled on Logic Apps in general but on some AZ datacentres (given that its under the [list of Mainstream services that support AZ](https://docs.microsoft.com/en-us/azure/availability-zones/az-region#azure-regions-with-availability-zones#) list)

There was a blog post on it last March 2022 ([Logic Apps Availability zone support (microsoft.com)](https://techcommunity.microsoft.com/t5/integrations-on-azure-blog/azure-logic-apps-availability-zone-support-is-coming-soon/ba-p/3254456)) saying that its on the roadmap, however there was no other official doc on whether that has come out as Public Preview at the very least.  **_We would just like some clarification if AZ has already enabled in Australia East (at the very least), and if yes is it on GA or Public Preview only?_**

**Comment by zhangadreedom** [comment]
@noemi616  Thanks for this issue. I tried this in my own account and faced the similar error: "Requested features are not supported in region. Please try another region.". I will report this to the product team.

**Comment by zhangadreedom** [comment]
@noemi616 

Azure Logic Apps currently supports the option to enable availability zones only for **new Consumption logic app workflows that run in multi-tenant Azure Logic Apps.**
This option is available only when you create a Consumption logic app using the Azure portal. No programmatic tool support, such as Azure PowerShell or Azure CLI, currently exists to enable availability zones.
This option is unavailable for existing Consumption logic app workflows and for **any Standard logic app workflows.**
ref: https://docs.microsoft.com/en-us/azure/logic-apps/set-up-zone-redundancy-availability-zones

**Comment by zhangadreedom** [comment]
> @noemi616
> 
> Azure Logic Apps currently supports the option to enable availability zones only for **new Consumption logic app workflows that run in multi-tenant Azure Logic Apps.** This option is available only when you create a Consumption logic app using the Azure portal. No programmatic tool support, such as Azure PowerShell or Azure CLI, currently exists to enable availability zones. This option is unavailable for existing Consumption logic app workflows and for **any Standard logic app workflows.** ref: https://docs.microsoft.com/en-us/azure/logic-apps/set-up-zone-redundancy-availability-zones

Looks like the doc is updating, Standard version is supported now, I try to deploy a new Logic App standard (WS2 plan) with zone redundancy in Australia East, it works today but yesterday not. Please have a try agan today.

**Comment by abatishchev** [comment]
@zhangadreedom can you share an example of ARM template for AZ-enabled LA standard?
