### ISSUE TITLE
VS Code Logic app designer. Error in determining project root. Please confirm project structure is correct.

### ISSUE THREAD

**Issue by mmarif2020** [Azure/logicapps#568]
Does this occur consistently? <yes>
Repro steps:

1. create a new branch in the repo from main branch
2. open vs code
3. open the workspace. navigate to the logic app files
4. open the workflow.json file in code view
5. right click workflow.json file and click 'Open in designer'

Expected : Logic app designer is opened
Actual : Logic  app designer is not opened and I get below error.
![image](https://user-images.githubusercontent.com/55423730/173475339-59644e56-fbc0-4f1e-a57d-d298cecca4d2.png)

Action: azureLogicAppsStandard.openDesigner
Error type: Error
Error Message: Error in determining project root. Please confirm project structure is correct.

Version: 1.0.19
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.68.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:4260062
fulfilled extension.bundle.js:2:4259287
```

</details>

**Comment by hartra344** [comment]
The answer to this problem can be found here: #619

**Comment by patelamit06** [comment]
this does not solve my problem ? any other solution.
