### ISSUE TITLE
Logic apps unable to upload more than 94.3 MB to share point using CreateFile action

### ISSUE THREAD

**Issue by eegasai** [Azure/logicapps#569]
We are using Logic apps stateful workflow to transfer .csv file from Azure Blob storage to Share point using SharePoint connector Create File action. When I try to upload a file with 103MB size I got an error 
{
  "status": "413",
  "message": "The request is larger than 94371840 bytes."
}

Chunk mode is already enabled for the transfer . 

Is there any limitation on the fie size even when chunking is enabled ? If yes, is there any workaround to achieve larger file uploads.

Also I have one observation, when i open run history for CreateFile action even though chunking is enabled its showing as disabled. 
Attached screenshots showing chunk mode enabled from Designer and chunk mode disabled from Run history.
![ChunkMode-RunHistory-Disabled](https://user-images.githubusercontent.com/13637810/173574308-078adf36-fb08-487f-81db-b07860b3bfe4.PNG)
![ChunkMode-Designer](https://user-images.githubusercontent.com/13637810/173574314-e019fafb-e605-4d32-b1d9-4fb042e4e739.PNG)

**Comment by sarthak-mnscorp** [comment]
We are facing the same issue issue with similar workflow.

**Comment by aholmis** [comment]
I would like a solution to this issue. Reopening.
