### ISSUE TITLE
I cannot deploy my logic app more than here

### ISSUE THREAD

**Issue by guillemhs** [Azure/logicapps#571]
Does this occur consistently? 
Repro steps:

1. Deploy logic app from Visual Studio code Mac
2. Follow the instructions until the project Language

Action: azureLogicAppsStandard.deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null, undefined, nor empty: projectLanguage

Version: 1.0.19
OS: darwin
OS Release: 21.5.0
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullOrEmptyValue extension.bundle.js:2:4374917
Object.<anonymous> extension.bundle.js:2:4388527
fulfilled extension.bundle.js:2:4387703
```

</details>

**Comment by ccastrotrejo** [comment]
Hello guillemhs, I wasn't able to replicate this issue in the VS Code extension. Do you mind sharing some screenshots or/and more repro steps?

**Comment by ccastrotrejo** [comment]
Hey @guillemhs, please install the new 1.0.34 version of the extension. If this still happens, please let me know. Otherwise, I will close this issue by 9/15. Thanks
