### ISSUE TITLE
retryPolicy of type "default" is not valid and unable to deploy

### ISSUE THREAD

**Issue by it-vandojo** [Azure/logicapps#577]
[The documentation](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-exception-handling?tabs=consumption#retry-policies) shows "default" as a possible value for the type property of a retryPolicy in an action or trigger.

When deploying a bicep template that has "default" defined as the type in a retryPolicy for an HTTP action, the deployment fails, stating the following:
The retry policy provided at line '1' and column '6419' in action 'Some_Redacted_Action' is not valid. The value provided: 'default' for the property: 'type' is not a valid 'RetryType'.

**Comment by hartra344** [comment]
default means that it will behave that way if there's nothing defined at all or the property isn't there.
