### ISSUE TITLE
Deployment using Visual Studio logic-app executes app

### ISSUE THREAD

**Issue by Imar** [Azure/logicapps#58]
I am using the Logic App add-in for VS 2019. Using it, I created an app with a schedule to run at at 3AM in the morning. When I deploy the app, it got executed immediately. This is an issue for many other apps I intend to build as they cannot run until the specified time. Is this a bug in the add-in? 

Also, to mitigate this issue, is it possible to create an app in the disabled state?

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
