### ISSUE TITLE
Update the Microsoft.Web/connections schema

### ISSUE THREAD

**Issue by mcollier** [Azure/logicapps#583]
Are there plans to publish an updated version of the Microsoft.Web/connections swagger?  As far as I can tell, the current version is 2016-06-01.  

When creating an API connection for a Logic App, there is a need to set the `kind` property to "V2" in order to get the `connectionRuntimeUrl` output property.  The Bicep linter in VSCode produces a warning that `kind` and `connectionRuntimeUrl` are not defined in the resource definition.

If I'm understanding the process correctly, a schema update would resolve this issue.  There are two open issues in the Azure Bicep repo on GitHub related to this:
- Azure/bicep/issues/3494
- Azure/bicep/issues/3512

Additionally, there doesn't seem to be a published schema for `Microsoft.Web/connections/accessPolicies`.  This makes the Bicep authoring experience in VSCode more challenging as the developer doesn't know if what they're writing is structurally correct.

**acceessPolicies**
![image](https://user-images.githubusercontent.com/1142273/176711716-7aeccb57-ad8f-4b10-a273-4ea201d4c7bb.png)

**connectionRuntimeUrl**
![image](https://user-images.githubusercontent.com/1142273/176711897-8073ed0c-f80e-4fad-ab22-72482c8262ed.png)

AB#15956455

**Comment by alexkarcher-msft** [comment]
This is on our roadmap for the next release of the Microsoft.Web definition. We have just updated the definition to include /workflows routes a few weeks ago and we are targeting to have the /connections schemas added by the end of the year.

**Comment by johnbilliris** [comment]
@alexkarcher-msft  @hartra344 Could you please provide an update to the schema release date?
(And please re-open as it is still an issue)

**Comment by ranasabih** [comment]
Any update on this?

**Comment by mcollier** [comment]
@wsilveiranz Please reopen.
