### ISSUE TITLE
unable to deploye Logic App Standard from VSCode

### ISSUE THREAD

**Issue by DeepakkSHAW** [Azure/logicapps#595]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.deploy
Error type: ECONNRESET
Error Message: request to https://---.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 1.0.25
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.69.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:5513566
```

</details>

**Comment by Thomas-Bailey** [comment]
@DeepakkSHAW product error - just so you know, if you use v1.65 it works fine.

**Comment by TWolverson** [comment]
Confirmed that downgrading to 1.65.2 fixes the problem.

**Comment by kritollm** [comment]
> Confirmed that downgrading to 1.65.2 from 1.69.2 fixes the problem for me.

**Comment by ccastrotrejo** [comment]
Hey @DeepakkSHAW , please install the new 1.0.34 version of the extension. If this still happens, please let me know. Otherwise, I will close this issue by 9/15. Thanks
