### ISSUE TITLE
Trying to create  new standard logic app project

### ISSUE THREAD

**Issue by aabdulrahi** [Azure/logicapps#599]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.createNewProject
Error type: Error
Error Message: Unable to write to Workspace Settings because azureFunctions.suppressProject is not a registered configuration.

Version: 1.0.25
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

<details>
<summary>Call Stack</summary>

```
T.toConfigurationEditingError workbench.desktop.main.js:2685:6467
T.validate workbench.desktop.main.js:2685:9488
T.doWriteConfiguration workbench.desktop.main.js:2685:2796
Object.factory workbench.desktop.main.js:2685:2652
y.consume workbench.desktop.main.js:86:16053
vscode-file:/workbench.desktop.main.js:86:15868
y.queue workbench.desktop.main.js:86:15792
T.writeConfiguration workbench.desktop.main.js:2685:2621
x.writeConfigurationValue workbench.desktop.main.js:2685:36613
vscode-file:/workbench.desktop.main.js:2685:20733
x.updateValue workbench.desktop.main.js:2685:20721
```

</details>

**Comment by msitsoftware** [comment]
Which version of Azure Functions Core Tools do you installed?
