### ISSUE TITLE
Unable to download or open logic apps inside Visual Studio 2019 Enterpise

### ISSUE THREAD

**Issue by tjones0808** [Azure/logicapps#60]
Visual Studio 2019, the option to download / open in editor is completely missing.

![error file](https://user-images.githubusercontent.com/10042391/56374241-b2a8a780-61d0-11e9-81e2-91eb6ceb6aab.PNG)

**Comment by tomkerkhove** [comment]
Just checking but did you install the new extension for VS2019?

**Comment by tjones0808** [comment]
yeah, looks like i missed the fact that microsoft says it doesn't work in 2019 yet... sorry!

**Comment by tomkerkhove** [comment]
In fact, VS2019 extension was released this week - https://azure.microsoft.com/en-us/updates/azure-logic-apps-tools-for-visual-studio-2019/

**Comment by tjones0808** [comment]
oh dang... hm, wasn't opening the editor for me in 2019... downloaded the latest yesterday.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.

I'll pass this feedback along to the engineering team which works on the Visual Studio extension.
