### ISSUE TITLE
Error while converting to nuget-based logic app project

### ISSUE THREAD

**Issue by nareshnagpal06** [Azure/logicapps#600]
Does this occur consistently? 
Repro steps:

1.Created a new Logic app Standard project in VS code
2.Created a stateful workflow
3. Click on "convert to nuget-based logic app project".

Action: azureLogicAppsStandard.switchToDotnetProject
Error type: Error
Error Message: **options object is required**

<img width="419" alt="image" src="https://user-images.githubusercontent.com/33876096/181821733-52100fc6-0a42-4a1e-94cc-7eef29c09465.png">

Version: 1.0.25
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

<details>
<summary>Call Stack</summary>

```
WebResource.prepare extension.bundle.js:2:1779137
Object.<anonymous> extension.bundle.js:2:4383166
fulfilled extension.bundle.js:2:4381203
```

</details>

**Comment by klawrawkz** [comment]
I'm experiencing this too.

- Azure Functions
v1.7.4

- Azure Logic Apps (Standard)
v1.0.25

![image](https://user-images.githubusercontent.com/48074223/182467107-33daa5e0-30f7-40b7-8cc1-118bd6bc0093.png)

**Comment by TommiBK** [comment]
Same here.

Azure Functions
-v1.6.0

Azure Logic Apps (Standard)
-v1.0.19

Version: 1.69.2 (system setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by TonnyWildeman** [comment]
see https://github.com/Azure/logicapps/issues/608#issuecomment-1231780096 for solution

**Comment by ccastrotrejo** [comment]
Hey  @nareshnagpal06  extension version 1.0.34 should have fixed the issue. Please try it out.
