### ISSUE TITLE
VS Code Error Logic Apps Standard Workflow Convert to Nuget-based Logic App project Error

### ISSUE THREAD

**Issue by svinjimoorrtiorg** [Azure/logicapps#604]
Does this occur consistently?  Yes
Repro steps:

1.In the Explorer pane, at your project's root, move your mouse pointer over any blank area below all the other files and folders, open the shortcut menu, and select Convert to Nuget-based Logic App project
2.getting the below error

Action: azureLogicAppsStandard.switchToDotnetProject
Error type: Error
Error Message: options object is required
![image](https://user-images.githubusercontent.com/104835629/184347153-1e48ffd4-b654-4e6d-a9ab-bf4a7728085c.png)

Version: 1.0.25
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.70.1
Language: en

<details>
<summary>Call Stack</summary>

```
WebResource.prepare extension.bundle.js:2:1779137
Object.<anonymous> extension.bundle.js:2:4383166
fulfilled extension.bundle.js:2:4381203
```

</details>

**Comment by TommiBK** [comment]
I'm having the same issue.

Azure Functions
-v1.6.0

Azure Logic Apps (Standard)
-v1.0.19

Version: 1.69.2 (system setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by klawrawkz** [comment]
Hi all,

Query if this is the same as or related to _**[this issue](https://github.com/Azure/logicapps/issues/600#issuecomment-1213225764)**_.

At least we've still got Bowie:

![image](https://user-images.githubusercontent.com/48074223/186977117-5c368cda-926c-4af6-ab03-4861af3b7765.png)

> Ground Control to MLAT (Microsoft Logic App Team) 
> Your circuit's dead, there's something wrong
> Can you hear me, MLAT?
> Can you hear me, MLAT?
> Can you hear me, MLAT?
> Can you...

So on and so forth....

klaw

**Comment by TonnyWildeman** [comment]
see https://github.com/Azure/logicapps/issues/608#issuecomment-1231780096 for solution

**Comment by ccastrotrejo** [comment]
Hey @svinjimoorrtiorg , extension version 1.0.34 should have fixed the issue. Please try it out.
