### ISSUE TITLE
object error while converting to Nuget based project

### ISSUE THREAD

**Issue by quilter-SudhanshuSharma** [Azure/logicapps#606]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.switchToDotnetProject
Error type: Error
Error Message: options object is required

Version: 1.0.25
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
WebResource.prepare extension.bundle.js:2:1779137
Object.<anonymous> extension.bundle.js:2:4383166
fulfilled extension.bundle.js:2:4381203
```

</details>

**Comment by TonnyWildeman** [comment]
see https://github.com/Azure/logicapps/issues/608#issuecomment-1231780096 for solution

**Comment by ccastrotrejo** [comment]
Hey @quilter-SudhanshuSharma  extension version 1.0.34 should have fixed the issue. Please try it out.

**Comment by ccastrotrejo** [comment]
Closing issue as version 1.0.34 fixed it.
