### ISSUE TITLE
"options object is required" Error while converting the standard logic app to Nuget based project

### ISSUE THREAD

**Issue by nnikita** [Azure/logicapps#608]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.switchToDotnetProject
Error type: Error
Error Message: options object is required

Version: 1.0.25
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.70.2
Language: en

"options object is required" Error while converting the standard logic app to Nuget based project

```
WebResource.prepare extension.bundle.js:2:1779137
Object.<anonymous> extension.bundle.js:2:4383166
fulfilled extension.bundle.js:2:4381203
```

</details>

**Comment by TonnyWildeman** [comment]
So, I went a bit down the rabbit hole here in figuring out where the extension went bleugh. I unminified the extension bundle and added yield b.ext.ui.showWarningMessage("you are here", c.dialogResponses.yes); And did some google fu and logical thinking.

These are the steps I ended up taking to ""fix"" it...

- download the latest **release** template bundle from the template feed: https://functionscdn.azureedge.net/public/cli-feed-v4.json
- find the highest **release** 3.xx.xx number and the referenced template url. You must check that at the top of the json feed.  
At moment of writing the template url is "https://functionscdn.azureedge.net/public/TemplatesApi/3.1.1648.zip"  
- create a folder in your workspace /resources/backupTemplates and unzip the contents in there.  
Should have three folders: bindings, resources and templates. Thus looking like /resources/backupTemplate/bindings, /resources/backupTemplates/resources and /resources/backupTemplates/templates
- comment out the line  "q = yield z.getLatestTemplates(e, a);" using /*.....*/ in your applogic vscode extension.bundle.js. Somewhere in and around %userprofile%/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-1.0.25/dist/extension.bundle.js 2:4140807 (that's 4 million 140 thousand 807)

Restart vscode completely and do the conversion.

there is a bug in the getLatestTemplate function in the Azure Functions Template library: https://github.com/microsoft/vscode-azurefunctions/tree/6106a9d7a8f91162086dddfd2b648db6e1ce9520/src/templates

**Comment by ccastrotrejo** [comment]
Hey @nnikita @TonnyWildeman, newest version 1.0.34 should have fixed the issue. Please try it out.

**Comment by TonnyWildeman** [comment]
@ccastrotrejo can confirm that the conversion works from the latest version.

**Comment by ccastrotrejo** [comment]
Closing issue therefore
