### ISSUE TITLE
Reading from Service Bus Queue requires Manage rights to work properly

### ISSUE THREAD

**Issue by ericloeliger** [Azure/logicapps#61]
This is possibly related to https://github.com/Azure/azure-functions-host/issues/1048

When creating a Logic App which reads from a Service Bus queue, my intent was to only grant the LA 'Listen' permissions on the queue.  However, that returns the following error:
![image](https://user-images.githubusercontent.com/12478449/56843717-4716a800-686a-11e9-91c9-5fe0843a6fbc.png)
It appears this is needed to list the available Queue Names. 

When I change the Service Bus SharedAccessPolicy to have Manage permissions, it works just fine.  This is OK for me now because I am the owner of the queue, but if I wanted to read from an external queue, where I'd be unlikely to be granted Manage permissions, it would be an issue.

**Comment by tomkerkhove** [comment]
Agreed

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.

I'll pass this feedback along to the engineering team who developed the Service Bus connector.
