### ISSUE TITLE
Calling HTTP with Azure AD with Asynchronous Pattern enabled fails with 401 when Location is returned

### ISSUE THREAD

**Issue by hajekj** [Azure/logicapps#611]
I have a following scenario:

Logic App calls Azure Resource Manager API PATCH operation which results with HTTP 202 and Location header returned. When I have asynchronous pattern enabled, the first request (PATCH) succeeds and returns Location header (pointing to ARM API) and Retry-After (10) which fails with 401 error:

```xml
{
  "error": {
    "code": "AuthenticationFailed",
    "message": "Authentication failed. The 'Authorization' header is missing."
  }
}
```

The issue is that when the connector follows the Location it omits the Authorization header and the overall operation fails. The workaround (from case 2209090010001308) is to disable Asynchronous Pattern and follow the requests manually via Until loop, which adds to complexity of the Logic App.

Is this desired behavior (I suppose it should be documented then) or is it a bug? I would classify it as a bug since when I have AAD protected API, I expect to protect all endpoints with it, even the endpoint from Location header.

AB#15942596

**Comment by hajekj** [comment]
Bump

**Comment by hajekj** [comment]
Bump

**Comment by rohithah** [comment]
@hajekj - are you using the ARM connector in this case or HTTP action?

if the latter, we use the authentication specified on the action on any follow-up calls made on the url returned in the location header. For example, if you use MI on the HTTP action, then it will the MI backed tokens on any subsequent calls. If its a connector, then connector may have a specific behavior and we need to look into it.

**Comment by hajekj** [comment]
Yes, it is ARM Connector. Authenticated via interactive user authentication.

**Comment by rohithah** [comment]
This is a bug in the ARM connector that we will be fixing. Rough ETA is end of March. Hopefully, you can workaround this using the HTTP action until we have the fix in place.

**Comment by amirhancheg** [comment]
Hi @hajekj Could you please share repro runid or action raw intpus/outputs?

**Comment by hajekj** [comment]
The full run is: https://preview.portal.azure.com/#view/Microsoft_Azure_EMA/LogicAppsMonitorBlade/runid/%2Fsubscriptions%2F63dd3a98-6ad8-47ae-ae7f-568e9b3104a8%2FresourceGroups%2Fhajekj-frontdoortest%2Fproviders%2FMicrosoft.Logic%2Fworkflows%2Fgithub-logicapps-issues-611%2Fruns%2F08585262011232141435512064818CU138
