### ISSUE TITLE
problem with unicode symbols in username

### ISSUE THREAD

**Issue by gwuhm** [Azure/logicapps#612]
Does this occur consistently? Yes
Repro steps:

1. Hit F5 in vscode to run Logic App
2. Error shows

Looks like problem with unicode symbols in username

Action: azureLogicAppsStandard.getDebugSymbolDll
Error type: ENOENT
Error Message: ENOENT: no such file or directory, scandir 'C:\Users\xxxl�pste\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows'

Folder path is C:\Users\xxxlápště\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows
exists with subfolder named 1.2.11

Version: 1.0.34
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.71.0
Language: en

AB#15956271

**Comment by daviburg** [comment]
Try as a workaround this command from command prompt:
`taskkill /IM "func.exe" /F`
