### ISSUE TITLE
VS Code: LA Standard Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureLogicAppsStandard.pickProcessTimeout" setting

### ISSUE THREAD

**Issue by svinjimoorrtiorg** [Azure/logicapps#616]
Does this occur consistently? 
Repro steps:
![AQzure Standard Logic apps workflowProcessTimeOutError](https://user-images.githubusercontent.com/104835629/190678168-2ec9ac2e-658c-4fbc-bf0d-8e6e3969ba82.JPG)

1. While selecting debug option  for local workflow project thru VS Code

Action: azureLogicAppsStandard.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureLogicAppsStandard.pickProcessTimeout" setting.

Version: 1.0.34
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.71.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:6195412extension.bundle.js:2:6195412
fulfilled extension.bundle.js:2:6191665
```

</details>

**Comment by hartra344** [comment]
This is a setting that you can increase in your VSCode settings. You may need to increase it if your app is taking a while to start up. 

<img width="1319" alt="CleanShot 2022-10-21 at 18 10 57@2x" src="https://user-images.githubusercontent.com/13208452/197309835-ec5d4d80-41de-4917-b686-601e8c4960e5.png">
