### ISSUE TITLE
Error adding a second workflow to VS Code project

### ISSUE THREAD

**Issue by RussSmi** [Azure/logicapps#618]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.createCodeless
Error type: Error
Error Message: Functions version "~4" not supported. Only version "~2" is currently supported for Codeless.

Version: 1.0.34
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:6091591extension.bundle.js:2:6091591
fulfilled extension.bundle.js:2:6089417
```

</details>

**Comment by yoHasse** [comment]
If you're developing a Logic App Standard:  
Only function runtime ~3 is supported, for now.

[Read more here](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#tools)

```
Azure Functions Core Tools - 3.x versionby using the Microsoft Installer (MSI) version, which is func-cli-X.X.XXXX-x*.msi. 
Don't install the 4.x version, which isn't supported and won't work.
```

**Comment by RussSmi** [comment]
Thanks, @yoHasse.  Any idea when this is going to be fixed?  We are already seeing warnings about function runtime ~3 being retired.

**Comment by yoHasse** [comment]
Sorry, I only know what says in that wiki page. Hopefully they'll update that soon. 

Did it work after you switched the projectruntime?

**Comment by RussSmi** [comment]
@yoHasse Yes it did thanks, I've now added the second workflow into the project successfully.
