### ISSUE TITLE
Error in determining project root. Please confirm project structure is correct.

### ISSUE THREAD

**Issue by san360** [Azure/logicapps#619]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.openDesigner
Error type: Error
Error Message: Error in determining project root. Please confirm project structure is correct.

Version: 1.0.34
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:6446590extension.bundle.js:2:6446590
fulfilled extension.bundle.js:2:6445548
```

</details>

**Comment by yoHasse** [comment]
If the logic app doesn't exist in the root project folder the designer will not work.

A workaround is to add a project subpath in the settings file

```

root
└─── LogicApps
     └─── LogicApp1
          └─── Stateless
                  workflow.json

```

* Open or add the file: ```<folderRoot>\.vscode\settings.json```
* Add the setting:
    ``` "azureLogicAppsStandard.projectSubpath": ".\\LogicApps\\LogicApp1"```

**Comment by yoHasse** [comment]
@san360 

Have you been able to test my suggestion?

**Comment by hartra344** [comment]
Thanks for taking the time to answer @yoHasse . Going to close this since there was no response.

**Comment by VTVishwanath** [comment]
This really helps, Thanks for the answer :).

**Comment by coldeli** [comment]
This solution is not working for me, have the settings structured changed since this post?

**Comment by yoHasse** [comment]
> This solution is not working for me, have the settings structured changed since this post?

Depends! Yes and no, it has changed when creating a workspace but other than that it should work as usual, tested this 3 weeks ago.

Can you explain/show your structure? 

Or create a new issue to make sure that you'll get faster help 🙌🏼

**Comment by RobBowman** [comment]
@yoHasse are you able to provide a link to any guidance for a multi-root workspace file and logic app standard please? I'm getting the "Error in determining project root. Please confirm project structure is correct." error with the following workspace file:

```
{
  "folders": [
    {
      "name": "Functions",
      "path": "./src/Function"
    },
    {
      "name": "LogicApp",
      "path": "./src/LogicApp"
    },
    {
      "name": "Deploy",
      "path": "./deploy"
    }
  ]
}
```

**Comment by arnaudluti** [comment]
Hello
Same here, tried with @yoHasse suggestion, doesnt, work for me, my directory tree is like,
`
root
-- | logicapps
---- | myworkflow1
------ | workflow.json
---- | myworkflow2
------ | workflow.json
.vscode
-- | settings.json
`
and the settings.json,
`
{
    "azureLogicAppsStandard.projectSubpath": ".\\LogicApps\\"
}
`

![Image](https://github.com/user-attachments/assets/4c868e57-0ad9-4104-8b37-3a9f5b3ded9a)
Thanks for the help
