### ISSUE TITLE
OpenAPI custom connectors does not work correctly for file output

### ISSUE THREAD

**Issue by Cloudmersive** [Azure/logicapps#62]
I imported this OpenAPI spec as a custom connector into logic apps:

https://api.cloudmersive.com/swagger/api/image

I am trying to use /image/face/crop/first

It takes a file as input, and produces a file as output.  I want to take files in from Azure Storage, crop them to the face, and then store them back into Azure Storage.

Simple, right?  Unfortunately it's not working because the output of the face crop first operation does not appear as a pill for me to select in Create Blob in the Expression Builder.

Does anyone have any ideas on how to get this working?  As far as I can tell it is a bug in Azure Logic apps and how it handles file responses from OpenAPI 2.0 specs.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
