### ISSUE TITLE
Creating LogicApp using  Visual Studio Code gives error that .NET Core missing

### ISSUE THREAD

**Issue by rkhan1971** [Azure/logicapps#620]
Does this occur consistently? 
Repro steps:

1. Open VSCode 1.71.2 and sign into Azure Subscriptions
2. Right click on a subscription in the Logic App(Standard) window and click "Create Logic App in Azure .."
3. Select Entered a globally unique name and press Enter
4. Location used EastUS2
5. Hosting: Windows standard and created new App Service Plan
6. Selected WS1
7. Zone redundancy Enabled
8. Specified Resources Group
9. Selected Storage Account in EastUS2 region
10. No SQL Storage for Logic App
11. Skip Application Insights
12. Pop up windows shows up and fails at Step 2/3
13. Error below

Action: azureLogicAppsStandard.createFunctionApp
Error type: BadRequest
Error Message: Requested features are not supported in region. Please try another region.

Version: 1.0.34
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:2791052
deserializeResponseBody extension.bundle.js:2:2791777
```

</details>

AB#15956135

**Comment by hartra344** [comment]
Zone redundancy doesn't appear to be available in East US 2 for Logic Apps. @ccastrotrejo  can you take a look at why ZR is being shown as an option for this region?

**Comment by ccastrotrejo** [comment]
Zone redundancy feature will be updated in the future. No ETA for now.
