### ISSUE TITLE
Logic App Standard never triggers locally for some triggers

### ISSUE THREAD

**Issue by yoHasse** [Azure/logicapps#621]
Steps to reproduce:
* Create a new project, local only with a stateful workflow. 
* Add recurrance trigger and some other things you want.
* Start debugging.
* Watch and wait as the recurrance never triggers.

It works great when using HTTP request trigger.

Logic App (Standard) - VS Code extension.
Version: 1.0.34

Azure Functions Core Tools
Core Tools Version:       3.0.4753 Commit hash: N/A  (64-bit)  
Function Runtime Version: 3.12.1.0  

Azurite (Installed separately, no extension): 
v3.19.0

host.json

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  }
}

```

**Comment by ppanchal-mobiz** [comment]
Was this working earlier?
My Azure Queue trigger workflows were not firing and the following always solved it for me.
1. Stop Azurite
2. Clear Azurite data by deleting the generated folder. _(Please note, that this step will also change your HTTP trigger URLs and remove all the run history)_
3. Start Azurite

**Comment by yoHasse** [comment]
> Was this working earlier?
> My Azure Queue trigger workflows were not firing and the following always solved it for me.
> 1. Stop Azurite
> 2. Clear Azurite data by deleting the generated folder. _(Please note, that this step will also change your HTTP trigger URLs and remove all the run history)_
> 3. Start Azurite

I actually have to clear the azurite folder between runs because of another bug. I can't remember ever getting this to work.

Could be something that throws an error during the trigger tries to fire but I can't troubleshoot if I don't get any information that somethings gone wrong 😟
