### ISSUE TITLE
Message showing in Azure portal: "(.....) . Value of "AzureWebJobsStorage" app setting is invalid. (...)"

### ISSUE THREAD

**Issue by rob-thijssen** [Azure/logicapps#622]
The following message shows up after the weekend for all LogicApp Standard resources:

`Unable to retrieve diagnostics and error information for your function app. Value of "AzureWebJobsStorage" app setting is invalid. Keyvault references are not supported`

We did not change anything to the configuration. We use the settings for months already, and the error message was never shown berore.

After some googling for this error message I ended up at these links:
https://azdochistory.aimless.jp/updates-of-azure-at-2022-09-05/
https://learn.microsoft.com/en-us/azure/azure-functions/errors-diagnostics/diagnostic-events/azfd0002?WT.mc_id=AZ-MVP-5003408
https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?toc=%2Fazure%2Fazure-functions%2Ftoc.json&tabs=azure-cli#considerations-for-azure-files-mounting

The last link mentions that the validation message can be surpressed by adding an extra configuration settings
`WEBSITE_SKIP_CONTENTSHARE_VALIDATION = 1`

I added the setting, but the validation message is still showing in the Azure Logicapps Standard overview page
![image](https://user-images.githubusercontent.com/98831650/191010480-cfebfc11-a0e6-44e2-bc2b-c034f68d868f.png)

![image](https://user-images.githubusercontent.com/98831650/191011234-1082c9e0-b62c-446e-a532-e3bd74cf05ff.png)

**Comment by marcelkieser** [comment]
Having the same issue

**Comment by rob-thijssen** [comment]
Starting yesterday the error message automagically disappeared. Not showing anymore in the portal.
I think the Azure team fixed something in the back-end?

**Comment by StefanPuntNL** [comment]
> Starting yesterday the error message automagically disappeared. Not showing anymore in the portal. I think the Azure team fixed something in the back-end?

You know what they say about problems that go away by themselves right? ;)
