### ISSUE TITLE
Logic App Standard - HTTP Action fail when adding query

### ISSUE THREAD

**Issue by yoHasse** [Azure/logicapps#624]
When adding a query to an HTTP Action that should trigger another logic app having HTTP trigger the workflow fails.

If I remove the queries it works without any problem.

The query is a simple string having:
name: filename 
value: test

I get the following errors:

```
{
  "error": {
    "code": "MissingApiVersionParameter",
    "message": "The api-version query parameter (?api-version=) is required for all requests."
  }
}

```

After adding the api-version (which already exists in the URI)

```
{
  "error": {
    "code": "DirectApiAuthorizationRequired",
    "message": "The request must be authenticated only by Shared Access scheme."
  }
}
```

Http raw input (changed base url and token for security reasons)

```
{
    "uri": "https://prod-33.westeurope.logic.azure.com:443/workflows/<workflowId>/triggers/manual/paths/invoke?api-version=2017-07-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=y-<token>",
    "method": "POST",
    "queries": {
        "filename": "test"
    }
}
```

AB#15942616

**Comment by rohithah** [comment]
The queries specified in the http action's inputs definition will replace any queries specified in in the request uri. One possible solution for you is to move all of the query string parameters into the queries section of the input. for example
"queries":{
"filename": "test",
"api-version":"..."

}

**Comment by yoHasse** [comment]
Already tried this and received an error as mentioned in the issue.: "After adding the api-version (which already exists in the URI)..."
