### ISSUE TITLE
Logic app standard designer view error

### ISSUE THREAD

**Issue by azcertfree** [Azure/logicapps#626]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.openDesigner
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED redacted:id

Version: 1.0.40
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RequestError extension.bundle.js:2:5852707
Request.callback extension.bundle.js:2:5854674
Request.RP$callback [as _callback] extension.bundle.js:2:5854120
b._callback.b.callback.b.callback extension.bundle.js:2:5878549
Request.onRequestError extension.bundle.js:2:5887742
```

</details>

**Comment by hartra344** [comment]
Need more info to triage
