### ISSUE TITLE
Element with id /subscriptions/xxxxxxx is already registered

### ISSUE THREAD

**Issue by dbzowkakpmguk** [Azure/logicapps#632]
I cant browse across nodes

**Comment by joechung-msft** [comment]
Related issue for the Consumption extension linked.

There are explorer tree node ID conflicts between the Logic Apps extensions (both Standard and Consumption) and one or more of the extensions included in the Azure Tools extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-node-azure-pack).

**Comment by hartra344** [comment]
Closing as a duplicate

**Comment by joechung-msft** [comment]
@hartra344 Can you link to the duplicate issue where this was fixed? Thanks.
