### ISSUE TITLE
VS Code (Logic App Standard Extension) - Unable to create any Azure Resource 

### ISSUE THREAD

**Issue by petitcz** [Azure/logicapps#637]
Since some time I can't create any Workflow / Project in my VS Code Studio using the LOGIC APP Standard Extension.

The "to" argument must be of type string. Received an instance of SubscriptionTreeItem.
Source: Azure Logic Apps (Standard) (Extension)

![image](https://user-images.githubusercontent.com/31005597/194747547-c81390a8-cd50-4164-b28c-95e34bfaaab3.png)

Would you have an idea how to resolve this?

**Comment by Salamipizza27** [comment]
same for me. Only the end of the error changes, if I select the subscription, logic app or empty Workflow section and then click on "Create Workflow...". So seems to be a generall issue. After restarting I can't re-established the connection to the subscription (keeps loading without login window or error etc. popping up), so overall not a well desinged extension yet.

Workflow section:
The "to" argument must be of type string. Received an instance of RemoteWorkflowsTreeItem

Logic app:
The "to" argument must be of type string. Received an instance of ProductionSlotTreeItem

subscription:
The "to" argument must be of type string. Received an instance of SubscriptionTreeItem

**Comment by jeffwessling** [comment]
I am having this issue too

**Comment by hartra344** [comment]
Closing in favor of tracking to: #639
