### ISSUE TITLE
cannot create workflow

### ISSUE THREAD

**Issue by ohahyo** [Azure/logicapps#639]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureLogicAppsStandard.createNewProject
Error type: ERR_INVALID_ARG_TYPE
Error Message: The "to" argument must be of type string. Received an instance of SubscriptionTreeItem

Version: 1.0.40
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.72.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.isPathEqual extension.bundle.js:2:6666800
extension.bundle.js:2:6682970extension.bundle.js:2:6682970
getContainingWorkspace extension.bundle.js:2:6682959
FolderListStep.setProjectPath extension.bundle.js:2:6212618
extension.bundle.js:2:6227328extension.bundle.js:2:6227328
fulfilled extension.bundle.js:2:6226292
```

</details>

**Comment by petitcz** [comment]
I have had the same problem. With no result. 
https://github.com/Azure/logicapps/issues/637

**Comment by jeffwessling** [comment]
I have this problem too. Seems to be several issues reported here for this error.

**Comment by Salamipizza27** [comment]
I think I have a solution:
-	Installed „Azure Logic Apps (Standard)” extension in visual studio code
-	Installed “Azure Resources” extension in visual studio code
-	Installed “C#” extension in visual studio code. Source: https://www.youtube.com/watch?v=hlDN0o9tBAc
-	Also the “.NET Core SDK” is required, when selecting if the logic app should be stateful / stateless
         o	The extension also checks if you have .NET Core 3.1 installed. 
         o	Seems that LA Standard doesn't support Functions runtime 4 / .NET 6 at this moment. 
         o	Source: https://stackoverflow.com/questions/73084113/error-from-visual-studio-code-logic-apps-you-must-have-the-net-core-sdk-insta

-	Set the “project language” to “C#”, else it will fail when selecting the language manually in the workflow creation process
-	Set the “Project Subpath” to the folder where your bicep files are located. My repo name is “API_Platform” and first folder on lowest level is \bicep\...

Here my "extension settings" of the Azure Logic Apps (Standard) extension:
![image](https://user-images.githubusercontent.com/73077208/195461517-44884365-7a90-418f-aa83-b058849f13dd.png)

**Comment by ccastrotrejo** [comment]
Hello everyone, thank you very much for raising the issue. We've isolated it issue and are working on a fix

**Comment by hartra344** [comment]
We just uploaded a new VSIX with a fix to this issue. This should be fixed.
