### ISSUE TITLE
can't start new project from VS Code extension

### ISSUE THREAD

**Issue by aktapaz** [Azure/logicapps#641]
Does this occur consistently? Yes
Repro steps:

1.open the azure extension in VS Code
2.Klick on "create new project" or "create workflow"
3. Voilà
![Bild_2022-10-11_104954782](https://user-images.githubusercontent.com/88380135/195044143-d663a09d-4899-41fe-aa4c-cbdd365ed3d4.png)

Action: azureLogicAppsStandard.createNewProject
Error type: ERR_INVALID_ARG_TYPE
Error Message: The "to" argument must be of type string. Received an instance of SubscriptionTreeItem

Version: 1.0.40
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.72.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.isPathEqual extension.bundle.js:2:6666800
extension.bundle.js:2:6682970extension.bundle.js:2:6682970
getContainingWorkspace extension.bundle.js:2:6682959
FolderListStep.setProjectPath extension.bundle.js:2:6212618
extension.bundle.js:2:6227328extension.bundle.js:2:6227328
fulfilled extension.bundle.js:2:6226292
```

</details>

**Comment by jeffwessling** [comment]
Yes! This is the exact problem I am having when I try to create new Logic App (Standard) projects in VS Code. If I could upvote this issue I would.

**Comment by hartra344** [comment]
Closing in favor of keeping things on #639
