### ISSUE TITLE
On Create New Project: The "to" argument must be of type string. Received an instance of SubscriptionTreeItem

### ISSUE THREAD

**Issue by jeffwessling** [Azure/logicapps#642]
I wanted to create a logic app (standard) and be able to store it in an Azure DevOps Git repo. To this end I...
1) Created a new Git repo in Azure DevOps 'fooLogicApp' , main branch
2) Cloned the main branch using the 'Clone to VS Code' button in Azure DevOps
3) Selected the local desktop folder I wanted the repo to clone to
4) Opened the Azure Cloud Explorer in VS Code, (Azure subscriptions loaded appropriately)
5) Clicked the 'Create New Project' button to create a new Logic App (Standard) and received the error in the title with a link to 'Report an Issue' here

      The "to" argument must be of type string. Received an instance of SubscriptionTreeItem

For whatever reason I have found it exceptionally difficult to get my Logic App (Standard) code into source control. Any help understanding how to resolve the above error and get things working would be appreciated. 

If the above resonates with you as "Well, that's not the way I would do it" let me know how you would do it. The internet seems to be lacking in how to make Logic Apps (Standard) work with all this.

Thanks,
   Jeff

**Comment by conradascott** [comment]
Had the same issue. Resolved by updating the version of the "Azure Logic Apps (Standard)" extension to previous versions until one worked. Got it working on version 1.0.25.

**Comment by AFeser1963** [comment]
Hi all,
the changing of the version did not work for me until I was tired to click on my target subscription.
Now it makes sense to me what the "to" argument is: 
Without marking the target (after the reload), there is no "to" and I do not get the error anymore.
(Until I would mark anything in the azure tree ...)

Hope this hint helps to fix that issue.

Kind regards,
Achim

**Comment by hartra344** [comment]
This is a known issue we're working on. Closing this one though to keep discussion on #639
