### ISSUE TITLE
Cannot read properties of undefined (reading 'createPanel')

### ISSUE THREAD

**Issue by eashi** [Azure/logicapps#645]
I keep getting this error message whenever I tried to open a workflow in a designer.

Does this occur consistently? yes
Repro steps:

1. Open a Logic App project from the root its root folder
2. Open a workflow.json file
3. Run the command: "Azure Logic Apps: Open in Designer
4. I get the message "Cannot read properties of undefined (reading 'createPanel')

Action: azureLogicAppsStandard.openDesigner
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createPanel')

Version: 1.0.40
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.72.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:6398085
extension.bundle.js:2:6397712
_ extension.bundle.js:2:6397398
openDesigner extension.bundle.js:2:6397894
extension.bundle.js:2:4194631
extension.bundle.js:2:4171389
extension.bundle.js:2:4170207
_ extension.bundle.js:2:4169893
callWithTelemetryAndErrorHandling extension.bundle.js:2:4171296
extension.bundle.js:2:4194349
extension.bundle.js:2:4193885
_ extension.bundle.js:2:4193571
extension.bundle.js:2:4194160
n._executeContributedCommand extensionHostProcess.js:90:111324
n.$executeContributedCommand extensionHostProcess.js:90:112028
i._doInvokeHandler extensionHostProcess.js:100:13680
i._invokeHandler extensionHostProcess.js:100:13362
i._receiveRequest extensionHostProcess.js:100:12132
i._receiveOneMessage extensionHostProcess.js:100:10834
extensionHostProcess.js:100:8941
p.invoke extensionHostProcess.js:61:145
v.deliver extensionHostProcess.js:61:2266
b.fire extensionHostProcess.js:61:1844
c.fire extensionHostProcess.js:69:19049
extensionHostProcess.js:116:17106
p.invoke extensionHostProcess.js:61:145
v.deliver extensionHostProcess.js:61:2266
b.fire extensionHostProcess.js:61:1844
c.fire extensionHostProcess.js:69:19049
s._receiveMessage extensionHostProcess.js:69:23861
extensionHostProcess.js:69:21304
p.invoke extensionHostProcess.js:61:145
v.deliver extensionHostProcess.js:61:2266
b.fire extensionHostProcess.js:61:1844
b.acceptChunk extensionHostProcess.js:69:15880
extensionHostProcess.js:69:15010
Socket.d extensionHostProcess.js:69:27128
```

</details>

AB#15942577

**Comment by ccastrotrejo** [comment]
Hey @eashi, thank you for raising this issue. Will work on solving it.

**Comment by ccastrotrejo** [comment]
Hi @eashi. This issue will be solved in the next version of the extension. In the meantime, you can also run that command by doing right click in the `workflow.json` file and click in `Open in Desinger` option.
