### ISSUE TITLE
The custom connector's service principal cannot be setup for redirects to an http:// URL

### ISSUE THREAD

**Issue by amang2205** [Azure/logicapps#65]
That's no longer supported. Hence, the URL of the newly created service principal doesn't match the redirect URL configured in the app.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
