### ISSUE TITLE
Could not find path to extension bundle

### ISSUE THREAD

**Issue by ZarKoBraMa** [Azure/logicapps#655]
### VSCode Dump

Does this occur consistently?  Yes 
Repro steps:

1. Open Application folder with Visual Studio Code
2. Press F5

Action: azureLogicAppsStandard.getDebugSymbolDll
Error type: Error
Error Message: Could not find path to extension bundle.

Version: 1.0.34
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.72.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:6296338extension.bundle.js:2:6296338
extension.bundle.js:2:6295377extension.bundle.js:2:6295377
P extension.bundle.js:2:6295063
getExtensionBundleFolder extension.bundle.js:2:6295969
extension.bundle.js:2:6296593extension.bundle.js:2:6296593
extension.bundle.js:2:6295377extension.bundle.js:2:6295377
P extension.bundle.js:2:6295063
getDebugSymbolDll extension.bundle.js:2:6295878
extension.bundle.js:2:4136498extension.bundle.js:2:4136498
extension.bundle.js:2:4113256extension.bundle.js:2:4113256
extension.bundle.js:2:4112074extension.bundle.js:2:4112074
P extension.bundle.js:2:4111760
callWithTelemetryAndErrorHandling extension.bundle.js:2:4113163
extension.bundle.js:2:4136216extension.bundle.js:2:4136216
extension.bundle.js:2:4135752extension.bundle.js:2:4135752
P extension.bundle.js:2:4135438
extension.bundle.js:2:4136027extension.bundle.js:2:4136027
n._executeContributedCommand extensionHostProcess.js:90:111324
n.$executeContributedCommand extensionHostProcess.js:90:112028
i._doInvokeHandler extensionHostProcess.js:100:13680
i._invokeHandler extensionHostProcess.js:100:13362
i._receiveRequest extensionHostProcess.js:100:12132
i._receiveOneMessage extensionHostProcess.js:100:11033
extensionHostProcess.js:100:8941extensionHostProcess.js:100:8941
p.invoke extensionHostProcess.js:61:145
v.deliver extensionHostProcess.js:61:2266
b.fire extensionHostProcess.js:61:1844
c.fire extensionHostProcess.js:69:19049
extensionHostProcess.js:116:17106extensionHostProcess.js:116:17106
p.invoke extensionHostProcess.js:61:145
v.deliver extensionHostProcess.js:61:2266
b.fire extensionHostProcess.js:61:1844
c.fire extensionHostProcess.js:69:19049
s._receiveMessage extensionHostProcess.js:69:23861
extensionHostProcess.js:69:21304extensionHostProcess.js:69:21304
p.invoke extensionHostProcess.js:61:145
v.deliver extensionHostProcess.js:61:2266
b.fire extensionHostProcess.js:61:1844
b.acceptChunk extensionHostProcess.js:69:15880
extensionHostProcess.js:69:15010extensionHostProcess.js:69:15010
Socket.d extensionHostProcess.js:69:27128
```

</details>

### Steps to Reproduce the Bug or Issue

1. Open Azure Logic App Standard Application with Visual Studio Code (previously Logic App Standard App work fine)
2. Press F5
3. Error shown: Could not find path to extension bundle. Source: Azure Logic App Standard Extension

What I saw is that Azure Logic App Standard Extension is updated 6 hours ago, I try to revert to previous version but same issue happened. Application can not start locally, and designer also can not open for the workflows. 

AB#15943509

Side effect: Right click on workflow in Azure Logic App Standard and choose Open in Designer. Designer will never open, and popup error message with next output:
8:42:02 AM: Running command: "func GetExtensionBundlePath"...
8:42:04 AM: Could not find path to extension bundle
8:42:04 AM: {"status":1,"signal":null,"output":[null,"","Unable to locate extension bundle.\r\n"],"pid":47560,"stdout":"","stderr":"Unable to locate extension bundle.\r\n"}
8:42:04 AM: Error: Could not find path to extension bundle.
8:46:50 AM: Running command: "func GetExtensionBundlePath"...
8:46:51 AM: Could not find path to extension bundle
8:46:51 AM: {"status":1,"signal":null,"output":[null,"","Unable to locate extension bundle.\r\n"],"pid":119524,"stdout":"","stderr":"Unable to locate extension bundle.\r\n"}
8:46:51 AM: Error: Could not find path to extension bundle.
9:32:17 AM: Running command: "func GetExtensionBundlePath"...
9:32:17 AM: Could not find path to extension bundle
9:32:17 AM: {"status":1,"signal":null,"output":[null,"","Unable to locate extension bundle.\r\n"],"pid":85008,"stdout":"","stderr":"Unable to locate extension bundle.\r\n"}
9:32:17 AM: Error: Could not find path to extension bundle.
9:41:14 AM: Running command: "func host start --port 8000"...

Azure Functions Core Tools
Core Tools Version:       3.0.4585 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.7.1.0

[2022-10-21T07:41:16.429Z] Error fetching version information for extension bundle Microsoft.Azure.Functions.ExtensionBundle.Workflows
[2022-10-21T07:41:16.433Z] Unable to find or download extension bundle
[2022-10-21T07:41:16.934Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
For detailed output, run func with --verbose flag.
[2022-10-21T07:41:21.904Z] Host lock lease acquired by instance ID '0000000000000000000000001668EE14'.
9:43:43 AM: Running command: "func host start --port 8000"...
Port 8000 is unavailable. Close the process using that port, or specify another port using --port [-p].
9:48:06 AM: Error: 404 - undefined

---------------------------------------
This could be also useful info: when I start: func host start --verbose:
![Capture](https://user-images.githubusercontent.com/58488815/197148985-0784532d-41ec-4693-8a41-acde715a3e00.JPG)

**Comment by IMeeus** [comment]
Our entire development team has the same issue.

**Comment by IMeeus** [comment]
We found a workaround by converting to a NuGet package-based project.

1. Remove from `host.json`

![image](https://user-images.githubusercontent.com/48489532/197161840-d56e8d32-8238-4cbb-a0a0-7c67332f1bca.png)

2. Add file `Properties > launchsettings.json`

```json
{
    "profiles": {
        "Workflows": {
            "commandName": "Project",
            "commandLineArgs": "--port 7275",
            "launchBrowser": false
        }
    }
}
```

3. Set in `local.settings.json` FUNCTIONS_WORKER_RUNTIME to dotnet

4. Add file `Workflows.csproj`:

```dotnet
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<AzureFunctionsVersion>v3</AzureFunctionsVersion>
		<RootNamespace>...</RootNamespace>
		<MSBuildWarningsAsMessages>MSB3246;$(MSBuildWarningsAsMessages)</MSBuildWarningsAsMessages>
		<StartDevelopmentStorage>False</StartDevelopmentStorage>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
		<PackageReference Include="Microsoft.Azure.Workflows.WebJobs.Extension" Version="1.2.7" />
	</ItemGroup>
	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
		<None Update="connections.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="parameters.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Artifacts\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="**\workflow.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
```

**Comment by IMeeus** [comment]
I've debugged a little bit further.

![image](https://user-images.githubusercontent.com/48489532/197176084-32fe74e5-6d19-461f-b0b2-721c01abcded.png)
The issue occurs when fetching information on extension bundle versions on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/index.json

Although, when I browse to this url, it sais `ResourceNotFound`. Has this resource been removed?

**Comment by tilicon** [comment]
We have the same issue. Stopped working today, was working fine yesterday.

Tried reverting back to version 1.0.40, but it still doesn't work so @IMeeus comment above seems to be the issue.

**Comment by ZarKoBraMa** [comment]
Guys, seem is start working again :).

**Comment by ZarKoBraMa** [comment]
I don't think that we can prevent this at any way. As @IMeeus mentioned there wasn't resource on location https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/index.json where extension bundle shoul be pulled from. Now, on this location there is a list of bundle versions:

[
"1.1.0",
"1.1.1",
"1.1.2",
"1.1.3",
"1.1.4",
"1.1.5",
"1.1.6",
"1.1.7",
"1.1.8",
"1.1.9",
"1.1.12",
"1.1.14",
"1.1.15",
"1.1.16",
"1.1.17",
"1.1.19",
"1.1.20",
"1.1.24",
"1.1.26",
"1.1.30",
"1.1.32",
"1.1.33",
"1.1.35",
"1.2.9",
"1.2.11"
]

**Comment by IMeeus** [comment]
If this error occurs again in the future, you can convert your workflow-designtime to run on dotnet instead of node.

<details>
<summary>How to</summary>

Create/Change the following files in workflow-designtime folder:

`host.json`:

```json
{
  "version": "2.0",
  "extensions": {
    "workflow": {
      "settings": {
        "Runtime.WorkflowOperationDiscoveryHostMode": "true"
      }
    }
  }
}
```

`local.settings.json`:

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsSecretStorageType": "Files",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

`workflow-designtime.csproj`:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<AzureFunctionsVersion>v3</AzureFunctionsVersion>
		<MSBuildWarningsAsMessages>MSB3246;$(MSBuildWarningsAsMessages)</MSBuildWarningsAsMessages>
		<StartDevelopmentStorage>False</StartDevelopmentStorage>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
		<PackageReference Include="Microsoft.Azure.Workflows.WebJobs.Extension" Version="1.2.7" />
	</ItemGroup>
	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
```

</details>

**Comment by ShruthiNatesh** [comment]
Hi Team, I am unable to open Logic Apps Standard in designer mode in VS Code, I see the following in the output window 

"No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)."

Followed the above steps mentioned but it not work: 
1.  Changed the host.json file in workflow-designtime folder 
2. Also changed local.settings.json
3. Added  workflow-designtime.csproj

But I still see the same issue
