### ISSUE TITLE
Logic App Standard deploying issue from VS code,Unable to verify the first certificate

### ISSUE THREAD

**Issue by vkop20** [Azure/logicapps#666]
### Describe the Bug

While deploying logic app standard from VS code to Azure, getting the following error "Unable to verify the first certificate"

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1)Create Sample Logic App standard project from VS code
2)Create a stateful work flow
3)Right click on Logic App standard project created and Select on Deploy to Logic App option

AB#16096596

**Comment by ccastrotrejo** [comment]
Hi @vkop20 can you state which version of the extension you are using?

**Comment by ccastrotrejo** [comment]
Let me know if this is still happening, I couldn't repro with the 1.0.43 version.
