### ISSUE TITLE
Azure Logic App Step Fail Monitoring with Alerts 

### ISSUE THREAD

**Issue by ketaanhshah** [Azure/logicapps#67]
We have a logic app little complex and it has a step in whcih we Create a File and Upload it, this step can fail sometimes.

What we would like to do is Monitor this step over a period of 3 hour and if this step fails like more than 10 times in that 3 hour period we would like to send an alert to a team.

Unfortunately I have not been able to find out a way to perform this. One thing I thought was every failure of this step should be recorded in Log Analytics workspace and may be we can query that workspace for such errors and then generate alert from it.

Anyone aware of how we can monitor a STEP in Azure Logic Apps for failure over a 3 hour period and then generate an alert? All this has to be done with out of the box Azure and not looking for any third party paid solutions.

Thank you,

**Comment by tomkerkhove** [comment]
You can create an alert on `ActionsFailed` metric (https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftlogicworkflows) for > 10 over 3 hours, but unfortunately it does not give you more information.

Would be great if the metric would have a dimension which contains the name of the action.

**Comment by ketaanhshah** [comment]
@tomkerkhove Thank you Tom, but thats the issue as the workflow as so many steps and we want to only monitor 1 step and get a count of failure above 10 lets say in 3 hour period. Also another issue I saw that was AGGREGATION GRANULARITY is 1hr, 6hr, 12hr , 24hr and no way to specify 3hr even if we were to get total count of ActionsFailed. Do you think we may have to do this Alert thru Powershell or ARM Template to get custom 3hr Aggregation Granularity?

**Comment by tomkerkhove** [comment]
I have not tried this but I'm afraid that won't be possible, but that's an assumption

**Comment by ketaanhshah** [comment]
We were looking for Monitoring soln and finally we got this query and an Alert out of it to make it work for our requirement:-

`AzureDiagnostics
| where
 status_s == "Failed"and
 tags_displayName_s =="My Logic Apps Name"and
 resource_actionName_s in ("For_each_file_in_blob_copy_it_to_sftp_server","Create_file_on_SFMC_SFTP_folder")
| summarizecount()by resource_runId_s, resource_actionName_s, tags_displayName_s, status_s
`
Using the above Query we created a New Alert and this currently works for our monitoring requirement.
