### ISSUE TITLE
NullReferenceException when using Azure Table Storage v2 builtin actions

### ISSUE THREAD

**Issue by dxv0421** [Azure/logicapps#686]
### Describe the Bug

While executing many workflows using Built-in Azure Table Storage v2 actions (2 tables and 4 updates total) updating steps in similar places.  Usually fails using the upsertEntity operation w/ failIfEntityExists = true (used for de-duplication).  Once fails for one workflow, it fails continuously on all following workflows.  It also gets treated as a timeout so it will do that for several minutes.

exception='System.NullReferenceException: Object reference not set to an instance of an object. at
Microsoft.Azure.Workflows.ServiceProviders.Abstractions.LimitedCapacityAsyncCache`2.ReferenceCountingCacheItem.Release() at
Microsoft.Azure.Workflows.ServiceProviders.Abstractions.LimitedCapacityAsyncCache`2.GetCacheItem(TKey key, Func`2 valueFactory) at

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Build workflow using Built-In Azure Table Insert or Merge step, w/ fail on conflict
2. Execute workflow repeatedly
3. Once exception occurs on any 

### Workflow JSON

```json
{
    "inputs": {
        "parameters": {
            "tableName": "transactionRequests",
            "entity": {
                "PartitionKey": "@{workflow()['run']['name']}",
                "RequestType": "type-of-workflow-being-run",
                "RowKey": "@{variables('TransactionId')}",
                "Status": "NEW"
            },
            "failIfEntityExists": true
        },
        "serviceProviderConfiguration": {
            "connectionName": "azureTables",
            "operationId": "upsertEntity",
            "serviceProviderId": "/serviceProviders/azureTables"
        }
    }
}
```

AB#16456324

**Comment by rarayudu** [comment]
Thanks for reporting the issue. The fix for this is already checked-in and will be deployed in 7-10 days to all regions.

**Comment by dxv0421** [comment]
@rarayudu Thanks for the quick reply. Do you happen to know the rough timeline for GA of the built-in features?

**Comment by rarayudu** [comment]
We are looking around Q1 of next year - Rough timeline would be around end of Jan to early Fed for the most built-in connectors to be GA.

**Comment by dxv0421** [comment]
Thanks for the responses! Pleasure working with you.
