### ISSUE TITLE
Logic Apps and Java

### ISSUE THREAD

**Issue by ketaanhshah** [Azure/logicapps#69]
Hi All,
One of my customers has a Java based application (build using ANT) which generates excel document, my cutomer wants to know if this app can be somehow used in a Logic App, so that the excel gets generated using existing java app and logic app can email it or save it to some location on a scheduled basis. Do we have any way to hos this Java app in the Logic App?

Thanks
K

**Comment by tomkerkhove** [comment]
You cannot host the java app in Logic Apps, but it can work based on the outputted Excel file.

You can run your app on Azure Functions - https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven

**Comment by ketaanhshah** [comment]
@tomkerkhove Thank you Tom! Perfect then we will host that Java based app into Azure and then use Logic app.

**Comment by ketaanhshah** [comment]
@tomkerkhove Hey Tom in case if we need to get a daily extract some records from POSTGRES SQL database hosted in Azure and send it across as an email to identified stakeholders (as an excel file). Do we have anything in Logic App that we can use to create it entirely from logic app instead of using the Java based app as all it is doing is talking with postgres sql and creating the excel file which I think can be recreated easily..just not sure if Logic App has a step for that.

**Comment by tomkerkhove** [comment]
Logic Apps has a ton of connectors that it supports - https://docs.microsoft.com/en-gb/connectors/

It has Postgres SQL in preview with several actions, but I'm not sure where your data is stored and how the hybrid support is for that connector - https://docs.microsoft.com/en-gb/connectors/postgresql/#actions

But in theory your scenario should be supported.
