### ISSUE TITLE
Logic App on AKS "Function Host is not running" whereas same image works on Docker Container Locally

### ISSUE THREAD

**Issue by 4KkU** [Azure/logicapps#691]
### Describe the Bug

Developed a simple HTTP Request and Response Logic App on VSCode.
It works perfectly on Docker Container locally, but when deployed to AKS, when i check the IP , it says "Function Host is not running"
![tempsnip](https://user-images.githubusercontent.com/31247325/207834971-3c24049d-be0e-44ef-9d48-ecb497eebb89.png)

_Using .NET  3.1 and .NET 6 Versions_
 
I have tried it with both **v3** and **v4** Func Core Tool Runtime

Also tried with both below images:
1. mcr.microsoft.com/azure-functions/node:3.0
2. mcr.microsoft.com/azure-functions/node:4-node16

I have used below reference 
[https://www.c-sharpcorner.com/article/create-docker-image-of-azure-logic-app-standard-and-deploy-in-azure-kubernetes-s/](https://www.c-sharpcorner.com/article/create-docker-image-of-azure-logic-app-standard-and-deploy-in-azure-kubernetes-s/)
Still on AKS it doesn't run,

**on Docker Container Locally it does run** 
![image](https://user-images.githubusercontent.com/31247325/207836431-dd204afe-f4fc-44ab-b052-b3f374d08768.png)

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Followed this to create project:
(https://www.c-sharpcorner.com/article/create-docker-image-of-azure-logic-app-standard-and-deploy-in-azure-kubernetes-s/)

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "http",
                "inputs": {
                    "statusCode": 200,
                    "body": "HTTP Request Received"
                },
                "runAfter": {}
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```

### Additional context

Dockerfile as below:

FROM mcr.microsoft.com/azure-functions/node:3.0

ENV AzureWebJobsStorage=***********
ENV AzureWebJobsScriptRoot=/home/site/wwwroot 
ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true
ENV AZUREFUNCTIONS_SQLBINDINGS_TELEMETRY_OPTOUT=1
ENV AZURE_FUNCTIONS_ENVIRONMENT=Development  
ENV FUNCTIONS_V2_COMPATIBILITY_MODE=true
ENV WEBSITE_HOSTNAME=localhost
ENV WEBSITE_SITE_NAME=httpTrigger

COPY . /home/site/wwwroot
RUN cd /home/site/wwwroot 

AB#16609118

**Comment by rohithah** [comment]
@4KkU - would you be able to capture logs from the function host and share any errors you are seeing?

**Comment by vinicinbgs** [comment]
How did you fix it?
