### ISSUE TITLE
VS Code Extension Azure Logic App Standard Latest Version (1.0.44) doesn't works with .NET 7

### ISSUE THREAD

**Issue by 4KkU** [Azure/logicapps#692]
### Describe the Bug

While trying to create a Logic App project with .NET 7 and .NET 3 both installed in VS Code (Using v4 Func Core Tools)
with 1.0.44 i.e Latest Version of Azure Logic App Standard Extension, it fails stating below

![image](https://user-images.githubusercontent.com/31247325/207839481-46da93da-aff5-40a6-8470-e3ad31bde9f9.png)

Same if i use 1.0.43 version, I am able to create the project

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Have .NET 7 installed
2. Have Azure Logic App Standard Extension VS Code v.1.0.44 installed
3. Try to create any type of Logic App Standard workflow

AB#16609174

**Comment by hartra344** [comment]
@4KkU we current support .NET 6 with the Azure Function Tools v4

@rohithah  do you know if there would be an issue adding .NET 7 to the allow list locally? Any breaking changes we would need to worry about there?

**Comment by 4KkU** [comment]
@hartra344 But it works with .NET 7 but only with **v.1.0.43** Extension of VS Code AZ Logic App Standard, at least locally.
The issue is when we use **v.1.0.44** i.e. latest version of VS Code extension, it gives error.

**Comment by rohithah** [comment]
Azure functions does not yet support .NET 7 in-proc (only available support is for out-of-proc). But having NET 7 installed shouldnt result in any failures as long as you have .NET 6 also installed.
