### ISSUE TITLE
SFTP action in Logic Apps "List files in folder" 

### ISSUE THREAD

**Issue by Prafulkapse** [Azure/logicapps#701]
### Describe the Enhancements

Below are the two enhancement request
1) SFTP action "List files in folder" also lists subdirectory. It would be good if it looks into subdirectory and list the file and not the name of the subdirectory
2) SFTP Trigger : There is no "File masks" in trigger.  Adding a file mask will reduce number of actions in Logic apps. 

### Plan Type

Consumption

### Steps to Reproduce the Bug or Issue

Create a new logic app
Add a SFTP trigger. In parameters there is not file masks option.
Add List files in folder action
Add a subdirectory on SFTP site
Once you run it will list the sub directory name in the output.

### Screenshots or Videos

<img width="353" alt="image" src="https://user-images.githubusercontent.com/45224624/210250472-753d41ce-bbbd-4a30-b105-3599d9a9a6b6.png">

AB#16691955

**Comment by praveensri** [comment]
Putting these feature requests in our backlog, we will triage and update here.
