### ISSUE TITLE
Not possible to disable Logic App specific logging

### ISSUE THREAD

**Issue by timjansenortec** [Azure/logicapps#702]
### Describe the Bug

I am trying to reduce Application Insights logging that is generated by my Logic App Standard.
I am doing this to reduce costs.
The most logging entries are created in the AppDependencies and AppTraces tables

I am using the following host.json:
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        },
        "logLevel": {
            "default": "Warning"
        }
    }
}
```
(I am using a NuGet based logic app, so extensionBundle is not in here)

This disables all 'Information' logging in the AppTraces tables.
example categories that are not logged anymore:
- Host.Triggers.Workflows
- Function.WorkflowNodeWorker
- Function.WorkflowDispatcher
- Host.Startup

Logging to AppDependencies is reduced as well, but the following remains:
entries with category 'Host.Results' that are still logged:
- POST <storage account>/flow<some id>runs (table target)
- POST <storage account>/flow<some id>jobtriggers00 (queue target)

entries with category 'Host.Workflow' that are still logged:
- PUT <storage account>/flow<some id>histories
- GET <storage account>/flow<some id>flowruntimecontext
- POST <storage account>/$batch
These entries do not have a LogLevel property.

I think logging that is generated by the Function App is influenced by host.json.
Bug the logging that is generated by the LogicApp extension is not.
Is there any way to influence this logging?

This documentation page does not mention anything about logging:
https://learn.microsoft.com/en-us/azure/logic-apps/edit-app-settings-host-settings?tabs=azure-portal

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a Logic App Standard with host.json that is mentioned in
2. Connect the Logic App to Application Insights
3. Create a simple stateful flow that does something trivial.
4. Observe that the AppDependencies table still contains successful POST/GET/PUT calls to the storage account

When using this configuration:
```
        "logLevel": {
            "default": "Warning"
        }
```
I expect that only failed dependencies are logged to the AppDependencies table.

AB#16717788

**Comment by hartra344** [comment]
@rohithah ?

**Comment by rohithah** [comment]
@timjansenortec - we will be soon releasing set of enhancements for application insight integration for logic apps and enabling user to reduce amount logs is one of the key goals including ability to set filters.  we plan to make these enhancements available within few weeks. If you are interested, please fill out this [form ](https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR8AP83lLZxJFteJHpAUUPclUOUk3R0hTTkQ3UU9KRjBDQklOV1JGNk5UNC4u) and we can get you early access.
