### ISSUE TITLE
VS code for Logic app standard

### ISSUE THREAD

**Issue by SRGuptha** [Azure/logicapps#724]
### VSCode Dump

when i click to create the logic app it 

### Steps to Reproduce the Bug or Issue

click on the logic app creation icon
it prompts me "Initialize project for use the VS code?" Yes
it asks me select the project language , what ever I select it is not working.

AB#17019344

**Comment by ccastrotrejo** [comment]
Hi @SRGuptha, does this keep happening with the newest version? The languages that we support to initialize are Javascript and C# (with the csproj file). Please use those, upcoming version will not have other options.  A workaround is to initialize manually by adding the following line in the settings.json inside the .vscode folder:
`"azureLogicAppsStandard.projectLanguage": "JavaScript"`
