### ISSUE TITLE
New UI Performance

### ISSUE THREAD

**Issue by SteveTe** [Azure/logicapps#727]
### Describe the Bug

Hi All, 
Whenever I view a logic app run history in the new UI designer, it shows a white screen for 30 or more seconds.

Then when it finally renders the run and you click on the individual items the right fly our window takes again ages to respond. The form is blank, and you need to click on the input or output.

The overall performance with complex logic apps is also terrible.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Open a complex logic app (> 200 steps)
wait for the screen to load
try to view the first or second step
Click expand button for fly out window. 
Blank form shown ....eventually

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "CRM_Auth_And_Option_Set": {
                "actions": {
                    "GetCrmAuthToken": {
                        "inputs": {
                            "body": "@concat('grant_type=client_credentials&client_id=',parameters('crmClientId'),'&client_secret=',encodeUriComponent(parameters('crmClientSecret')),'&resource=https%3A%2F%2F',parameters('crmEnvURL'))",
                            "headers": {
                                "Content-type": "application/x-www-form-urlencoded"
                            },
                            "method": "POST",
                            "uri": "@{concat('https://login.microsoftonline.com/',parameters('subscriptionTenantId'),'/oauth2/token')}"
                        },
                        "runAfter": {},
                        "type": "Http"
                    },
                    "GlobalOptionSetDef-ContractEvent": {
                        "description": "gcp_eventtype = EventType Metadataid = DEV/QA/UAT/PROD: 49158d6d-7e1f-ed11-b83d-00224891e294",
```

### Screenshots or Videos

![Screenshot 2023-02-09 142311](https://user-images.githubusercontent.com/44633256/217710159-005819da-fe7e-4cdc-bd49-c56a87db2809.png)
![Screenshot 2023-02-09 142443](https://user-images.githubusercontent.com/44633256/217710163-38fd86a1-8448-45fc-bfc2-9919f962cd08.png)

AB#17092145

**Comment by hartra344** [comment]
@SteveTe sorry for the slow response. Have you tried the preview designer? You should have a “Try Preview” button on the command bar of the designer. We specifically set out to help with this problem.

**Comment by SteveTe** [comment]
Hi @Travis Harris,

I wish I could say that the experience is better using the "Try Preview", but it performs even worse.

Happy to get on a screen share of it helps understand my frustration.

By the way I have split out the original logic app into two, which has improved the experience, but only on the normal UI, not the "Try Preview"

Regards,

Steve

**Comment by hartra344** [comment]
Send me an email at travisharris@microsoft.com with a email to send the invite to and your availability. Would be happy to hop onto a call to see what problems you’re having with the preview Designer.

**Comment by WCMV** [comment]
I can confirm that UI performance in Logic Apps seems abysmal compared to elsewhere in Azure. 30 second+ wait after hitting refresh, or needing to reload the page entirely just to see the run history, and then the delay when opening a run and it loads the actions. Preview designer connector listing is at least much better than GA designer, but overall I feel I spend more time waiting for LA to render itself than I do actually building workflows.

**Comment by mohit-jagtiani** [comment]
I agree, performance of designer is very bad. Run history, connectors, entire experience is not at par with any workflow builder tool. Something must be done about it.
