### ISSUE TITLE
Azure LogicApp recurrence schedule first of month specific time not saved to JSON file

### ISSUE THREAD

**Issue by MWielen** [Azure/logicapps#73]
Hi,

I want to set recurrence schedule to 1st of month starting at 03:00 AM
When I try to save the following JSON only monthDays is saved but hours and minutes is lost when saving.

"triggers": {
"Recurrence": {
"recurrence": {
"frequency": "Month",
"interval": 1,
"schedule": {
"minutes":[0],
"hours":[3],
"monthDays": [
1
]
},
"startTime": "2019-08-01T03:00:00Z",
"timeZone": "UTC"
},
"type": "Recurrence"
}
}

Result after saving:

"triggers": {
"Recurrence": {
"recurrence": {
"frequency": "Month",
"interval": 1,
"schedule": {
"monthDays": [
1
]
},
"startTime": "2019-08-01T03:00:00Z",
"timeZone": "UTC"
},
"type": "Recurrence"
}
}

What should I do? Thanks!

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
