### ISSUE TITLE
Azure Government |  Export Logic App continues to spin

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/logicapps#730]
### VSCode Dump

Export logic app feature in VS code with an Azure Government (Fairfax) account will continue to spin why trying to query the subscription. Based on a Fiddler trace the response is trying to authenticate against Azure Commercial tenant (login.microsoftonline.com instead of .us). 

![image](https://user-images.githubusercontent.com/18233035/218864914-6abcf0cd-e262-4ebc-852e-950d49840273.png)

{"error":"invalid_grant","error_description":"AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (2) is specified.\r\nTrace ID: 8a9a16ef-3ddc-4d43-8f50-fb5080dd0400\r\nCorrelation ID: b71f8e09-57c2-4f50-bef3-954f4908e0d6\r\nTimestamp: 2023-02-14 21:18:19Z","error_codes":[90051],"timestamp":"2023-02-14 21:18:19Z","trace_id":"8a9a16ef-3ddc-4d43-8f50-fb5080dd0400","correlation_id":"b71f8e09-57c2-4f50-bef3-954f4908e0d6"}

![image](https://user-images.githubusercontent.com/18233035/218865151-b3127a3c-9e72-4eb8-9cb9-0d796efe9924.png)

### Steps to Reproduce the Bug or Issue

1. Log into VS Code Azure extension with a Government account
2. Navigate to the Logic App Standard view 
3. Export Logic App

The wheel will continue to spin. 

AB#17177894

**Comment by ccastrotrejo** [comment]
Hi @jcbrooks92 thank you for raising this issue, the fix for it will be released soon with a new extension version.
