### ISSUE TITLE
Built-in Service Bus trigger converts datetime values in JSON payload

### ISSUE THREAD

**Issue by johnstrand** [Azure/logicapps#734]
### Describe the Bug

I have a solution where one Logic App sends a message to a Service Bus queue, and another Logic App, using the "When messages are available in a queue"-trigger, processes them. The problem occurs when sending a JSON object with a property containing a datetime value without time zone indicator.

As a reduced example, I sent:
```
{
  "date": "2023-01-01T00:00:00"
}
```
to the queue, but on the receiving end, my message looks like this:
```
{
  "date": "2022-12-31T23:00:00Z"
}
```

So, somewhere along the way, the datetime value gets implicitly treated as UTC and then serialized with the Z-suffix. I fully expect that data sent to a queue should be received in an identical state, and this kind of mangling has a potential for causing issues.

As an experiment, I used the C# SDK to retrieve the same message from the same queue, and that time the message had the expected, original content.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Create a workflow that sends a message to Service Bus
Ensure that the workflow sends a property containing a datetime value without time zone indicator
Create a workflow that receives a message from Service Bus
Trigger the first workflow
Observe the mangled data

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Compose": {
                "type": "Compose",
                "inputs": "@triggerOutputs()?['body']?['contentData']",
                "runAfter": {}
            }
        },
        "triggers": {
            "When_messages_are_available_in_a_queue": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "queueName": "queue1",
                        "isSessionsEnabled": false
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "serviceBus",
                        "operationId": "receiveQueueMessages",
                        "serviceProviderId": "/serviceProviders/serviceBus"
                    }
                },
                "splitOn": "@triggerOutputs()?['body']"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```

AB#17312327

**Comment by saroja-sattigeri** [comment]
@johnstrand, Could you please test the same scenario via service bus explorer?

**Comment by jdelforno** [comment]
We've run into this issue and for the past week, have been trying to narrow it down.

The old connector doesn't have this issue so we're unsure as to why the new connector is converting timestamps.

**Comment by saroja-sattigeri** [comment]
@johnstrand, Thanks for your response could you please test the same scenario via service bus explorer and let me know if you see same behavior there also?

**Comment by johnstrand** [comment]
@saroja-sattigeri When fetching the data via Service Bus Explorer, or using the SDK in LINQPad, the message is retrieved correctly

**Comment by jdelforno** [comment]
> ### Describe the Bug
> 
> I have a solution where one Logic App sends a message to a Service Bus queue, and another Logic App, using the "When messages are available in a queue"-trigger, processes them. The problem occurs when sending a JSON object with a property containing a datetime value without time zone indicator.
> 
> As a reduced example, I sent:
> 
> ```
> {
>   "date": "2023-01-01T00:00:00"
> }
> ```
> 
> to the queue, but on the receiving end, my message looks like this:
> 
> ```
> {
>   "date": "2022-12-31T23:00:00Z"
> }
> ```
> 
> So, somewhere along the way, the datetime value gets implicitly treated as UTC and then serialized with the Z-suffix. I fully expect that data sent to a queue should be received in an identical state, and this kind of mangling has a potential for causing issues.
> 
> As an experiment, I used the C# SDK to retrieve the same message from the same queue, and that time the message had the expected, original content.
> ### Plan Type
> 
> Standard
> ### Steps to Reproduce the Bug or Issue
> 
> Create a workflow that sends a message to Service Bus Ensure that the workflow sends a property containing a datetime value without time zone indicator Create a workflow that receives a message from Service Bus Trigger the first workflow Observe the mangled data
> ### Workflow JSON
> 
> ```json
> {
>     "definition": {
>         "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
>         "actions": {
>             "Compose": {
>                 "type": "Compose",
>                 "inputs": "@triggerOutputs()?['body']?['contentData']",
>                 "runAfter": {}
>             }
>         },
>         "triggers": {
>             "When_messages_are_available_in_a_queue": {
>                 "type": "ServiceProvider",
>                 "inputs": {
>                     "parameters": {
>                         "queueName": "queue1",
>                         "isSessionsEnabled": false
>                     },
>                     "serviceProviderConfiguration": {
>                         "connectionName": "serviceBus",
>                         "operationId": "receiveQueueMessages",
>                         "serviceProviderId": "/serviceProviders/serviceBus"
>                     }
>                 },
>                 "splitOn": "@triggerOutputs()?['body']"
>             }
>         },
>         "contentVersion": "1.0.0.0",
>         "outputs": {}
>     },
>     "kind": "Stateful"
> }
> ```
> 
> ### Screenshots or Videos
> 
> _No response_
> ### Additional context
> 
> _No response_
> 
> [AB#17312327](https://msazure.visualstudio.com/One/_workitems/edit/17312327/)

Please refer to https://github.com/dotnet/runtime/issues/1566 as I believe it's the upstream issue. 

We've resolved the problem it seems by setting the WEBSITE_TIME_ZONE to "UTC". Whilst not ideal.. it's working and not converting time zones.

**Comment by jdelforno** [comment]
MSFT Support team have confirmed that this is an issue via MSFT Ticket: 2306210030002343 and are investigating potential options.

**Comment by saroja-sattigeri** [comment]
Thanks for the update @jdelforno

**Comment by saroja-sattigeri** [comment]
Hi @jdelforno, As product group is looking into other options for above behavior in MS ticket just wanted to check if we can close this Github issue?
