### ISSUE TITLE
Office 365 Approval mail action does not work with logic app standard deployed on an ASEv3

### ISSUE THREAD

**Issue by Gabriel123N** [Azure/logicapps#736]
### Describe the Bug

When trying to use the action "Send an approval mail" on a stateless logic app running on an ASE, it is impossible to progress as using any action results in an error.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a new logic app standard on an ASE
2. Create a new workflow stateless
3. Create the approval mail task for office 365
4. When receiving the mail, click on accept

When accepting from the mail dialog, it will say that an unexpected error happened.

When approving from the mail's html or with a confirmation through the browser, it will redirect to a page with the following error:

`An error occured while recording your response. Please try again later!`

### Additional context

My guess is that the error happens because whatever is doing the confirmation cannot reach the logic app (since it is inside an ASE with no public endpoints).

However, being able to use approval flows such as this one on fully private logic apps is something that shouldn't be blocked by such a limitation since many others Azure service are able to  keep working correctly once a resource is inside a private endpoint.

A user approving the mail from inside the private network should as well be able to bypass this limitation if it exists.

**Comment by saroja-sattigeri** [comment]
Hi @Gabriel123N, Since logic app standard is hosted in an internal ASE(where public IPs are denied) and outlook connector is being Azure connector which flows through public Azure data center(which would be having public IP address) responding from public network would not be available.

**Comment by saroja-sattigeri** [comment]
Hi @Gabriel123N, Just wanted to check if any concerns on shared details.
