### ISSUE TITLE
App settings do not retrieve latest Key Vault secret

### ISSUE THREAD

**Issue by floriandldlw** [Azure/logicapps#740]
### Describe the Bug

I have a Logic App standard, that has an app setting subscription_key which references to the keyvault secret that stores my subscription key.
![2023-03-02 10 35 07 portal azure com bf5c50f8d913](https://user-images.githubusercontent.com/82218711/222389553-539edd65-2098-41aa-bfc2-e2fa3b1b0419.png)

Inside my workflow, I reference the appsetting to retrieve the value and use the subscription key in my HTTP call.
![2023-03-02 10 38 09 portal azure com 86e0069ea36f](https://user-images.githubusercontent.com/82218711/222390303-4dc67edd-a30a-42cb-977a-417f4cd13157.png)

In my keyvault I have 2 versions of the secret:

![Untitled](https://user-images.githubusercontent.com/82218711/222391377-59019765-a8de-4301-a172-4bec319aa62f.png)

I deploy this Logic App standard and the appsettings via DevOps. 
I notice that after the pipelines have ran, my Logic App workflow retrieves the old keyvault secret value as this subscription key is outdated. Hence why I created a new one.

![2023-03-02 10 43 21 portal azure com 484b2aca1b6b](https://user-images.githubusercontent.com/82218711/222391600-99df2aaf-7e4c-4687-979b-2f0fdce13db1.png)

When I restart the Logic App Standard, the appsettings are refreshed and I takes the latest secret version. The flow works again:
![2023-03-02 10 44 46 portal azure com bf7d986b530c](https://user-images.githubusercontent.com/82218711/222391982-d07053fd-d6b0-4ae0-97b1-09c0c9562bca.png)
When I disable the older version, it also works and I don't have to restart the Logic App Standard.

It seems like the Logic App standard is not restarting automatically after a deployment of app settings is done. This was the case in the past otherwise I would have had these errors a lot more.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create keyvault secret
2. create 2 secret versions
3. reference this keyvault secret in the app setting of the logic app standard
4. deploy your app settings with a devops pipeline and ARM/Bicep
5. use the app setting in your workflow
6. the workflow will use the oldest active version secret
7. restart the logic app standard
8. the workflow will use the newest active version of the secret
8. disable the secret version and the workflow will use the oldest active version which in this case is the new secret version

AB#17401904

**Comment by axiomitdavid** [comment]
App settings can take up to 24 hours to reflect and changes.  You have to restart the function/logic app to have them used immediately

**Comment by mark-abrams** [comment]
Referencing Key Vault secrets from a Logic App is a feature that is provided by the Azure App Service platform, it is not a feature specific to Logic Apps. The App Service [documentation ](https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#rotation)describes how keys are rotated within a 24 hour period. You can't control this period, or know when the last refresh was, so the only way to force the refresh is to restart the Logic App, i.e. the App Service.

It would be really nice if the user experience for App Service settings was similar to Named Values in APIM. With Named Values that are linked to Key Vault secrets, you can see the last refresh date/time and there is an option to force the refresh of individual named values, without triggering a "restart" of APIM. It would be good if App Service offered the same feature for settings that are linked to Key Vault.

@floriandldlw , you should close this issue if you are happy with the responses.

**Comment by VeeraMS** [comment]
Hi @floriandldlw

If a version is not specified in the reference, then the app will use the latest version that exists in the key vault. When newer versions become available, such as with a rotation event, the app will automatically update and begin using the latest version within 24 hours. The delay is because App Service caches the values of the key vault references and refetches it every 24 hours. Any configuration changes to the app that results in a site restart causes an immediate refetch of all referenced secrets.

https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#rotation
