### ISSUE TITLE
setting up containerized ARC enabled logic apps fails to deploy, function host not running. advapi32.dll

### ISSUE THREAD

**Issue by gijsebaert** [Azure/logicapps#741]
### Describe the Bug

When trying to launch the logic app in a containerized enviroment I get the following error.

Microsoft.WindowsAzure.ResourceStack: Unable to load shared library 'advapi32.dll' or one of its dependencies. In order to help diagnose loading problems, considering setting the LD_DEBUG enviroment variable: libadvapi32.dll: cannot open shared object file: No such file or directory.

![image](https://user-images.githubusercontent.com/71766951/222406050-31675e38-de9c-4cba-a629-19b65c33f70a.png)

The app can be reached trough this link and shows that the function host is not running.
[https://arc-enabled-la.kubernetes-clust-99wpj3f.westeurope.k4apps.io/](https://arc-enabled-la.kubernetes-clust-99wpj3f.westeurope.k4apps.io/)

![image](https://user-images.githubusercontent.com/71766951/222405747-c1e9c8c6-dc72-4a8b-aaf1-cec6dbe0bab5.png)

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. follow the guide over [here](https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-portal?tabs=azure-cli). Without deploying the application
2.  Make the cluster ARC enabled by following this guide. [Connect an Azure Kubernetes Service cluster to Azure Arc in AKS hybrid - AKS hybrid | Microsoft Learn](https://learn.microsoft.com/en-us/azure/aks/hybrid/connect-to-arc)
3. prepare your cluster for the logic app deployment over [here](https://learn.microsoft.com/en-us/azure/app-service/manage-create-arc-environment?tabs=powershell).
4. deploy the logic app als following. [Azure arc enabled create and deploy logic Apps](https://learn.microsoft.com/en-us/azure/logic-apps/azure-arc-enabled-logic-apps-create-deploy-workflows?tabs=azure-cli)
5. The error will occur when the logic app is created.

AB#17402089

**Comment by VeeraMS** [comment]
Hi @gisebaert,

We have fixed it in the latest Workflow extension bundle, could you please check.

**Comment by gijsebaert** [comment]
@VeeraMS this is now no longer an issue, however. We currently face the following dll related error.

![image](https://user-images.githubusercontent.com/71766951/233987663-04d49732-7fc9-4434-b70c-8540609744fa.png)

**Comment by VeeraMS** [comment]
Hi @gijsebaert ,

I am checking on this. Could you help me with the values of the App settings configured for the extension bundle version and runtime version.

**Comment by gijsebaert** [comment]
Ofcourse I can, reffering to the screenshot down below. I think these are all the values needed?

![image](https://user-images.githubusercontent.com/71766951/234256006-6de984ac-50d8-4595-9f14-df12ea49798c.png)
![image](https://user-images.githubusercontent.com/71766951/234256430-f2d7a67b-f6c3-40eb-990d-f7eb22f038c1.png)
