### ISSUE TITLE
VSCode custom location Logic App deployment

### ISSUE THREAD

**Issue by gijsebaert** [Azure/logicapps#743]
### VSCode Dump

The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 'extendedLocation', line 1, position 327.'.

Source: Azure Logic Apps (Standard) (Extension)

### Steps to Reproduce the Bug or Issue

When creating a Logic app via the AZ Logic App extension GUI interface I face the following error. Since I run ARC enabled Kubernetes I want this resource to run on a custom location (my kubernetes cluster). The custom location is visible in the options when choosing my resource location. As seen below. However on creation it fails with the following error. What could be the cause of this error?

![image](https://user-images.githubusercontent.com/71766951/223692526-674e1d71-3512-4277-9062-00e11c2ad343.png)
![image](https://user-images.githubusercontent.com/71766951/223693444-fd630c4d-caad-4be6-9b60-282602ffe5a9.png)

When creating the Logic app via the CLI interface it appears in VSCode, however I cannot manage it and find the authentication token anywhere. Not on the Azure site, nor the VSCode overview pane. As you can see when I expand my workflows I don't see any after I did my VSCode deployment to the LA with custom location. Is there another source where I can find the URL for my workflow?

![image](https://user-images.githubusercontent.com/71766951/223693304-38d302fc-1d14-49cb-8522-ccc219070b8d.png)

I already checked configurations but they are identical. I don't see why the workflows don't appear when the LA isn't created in VSCode and why the deployment of a LA fails with a custom location specified. Many thanks for checking in on this!

AB#17470694

**Comment by ccastrotrejo** [comment]
Hi @gijsebaert sorry for the late response. Does this keep happening? I am looking for why the first issues happens, however for the second issue. Does your Logic app project in the Azure portal doesn't show any workflows?

**Comment by ccastrotrejo** [comment]
@gijsebaert Thanks for letting me know! Glad you found the solution.
