### ISSUE TITLE
macOS x64 - VSCode Debugger starts and immediately terminates - Function Core Runtime V4

### ISSUE THREAD

**Issue by axiomitdavid** [Azure/logicapps#745]
### Describe the Bug

Working with a new Logic App Standard Workflow

Press F5 to start Debug, See debug symbol generation take place and the Func Host Start
You see the Logic App startup, the VSCode status bar turns orange briefly and then you are returned back to the terminal.

No error messages shown

Azure Function Core Tools V4 installed using HomeBrew

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create new logic and and stateful workflow
2. Start Azurite
3. Start Debugging (F5)

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "http",
                "inputs": {
                    "statusCode": 200
                },
                "runAfter": {}
            }
        },
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {}
    },
    "kind": "Stateful"
}
```

### Additional context

Azure Function Extension / Project Runtime Version is set to ~4

AB#17517537

**Comment by ccastrotrejo** [comment]
Hi @axiomitdavid I tried to replicate it but couldn't get the same behavior. Can you please check if you have the latest Azure Function Core Tools V4 version? Are you running azurite with the Azurite extension?

**Comment by axiomitdavid** [comment]
I just re-installed Azure-Functions-Core-Tools@4 using HomeBrew.  Same issue occurs.

![image](https://user-images.githubusercontent.com/41350688/229034878-2dffa7b7-27ba-42f7-9d20-72baece1154a.png)

**Comment by hartra344** [comment]
@rohithah

**Comment by axiomitdavid** [comment]
I had been following https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cmacos%2Ccsharp%2Cportal%2Cbash. and installing Azure Functions Core Tools V4 using Hoebrew.

Re-installed tools using NPM and it is now working.
