### ISSUE TITLE
Service Bus Topic trigger with Managed Identity fails as Unauthorized for no good reason

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/logicapps#747]
### Describe the Bug

When templating the creation of a Logic App using the Service Bus topic subscription trigger with Managed Identity, some Logic Apps intermittently enter a state where their trigger invocations fail with Unauthorized for no reason. 

The Managed Identity is granted Service Bus Data Owner via a Group, and it displays these RBAC permissions in its own permissions dialog:

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/94133561/226693798-c9bf3d90-067e-4102-9f67-be575944e59e.png">

This approach works for numerous other Logic Apps included through repeated deployments. We run the group assignment through the Azure CLI on each deployment, which we were expecting to be idempotent although this raises errors that the group assignment already exists, which we believe is safe to ignore. The emergence of this issue the most recent time does not coincide with running this script. We have seen one other occasion of this with a different Logic App which resolved itself with no further action after a period of over 12 hours of continuous failures. This time it was resolved by:
- disabling and re-enabling the Logic App, after which we continued to see Failed triggers
- assigning the trigger a different API connection, one that is working, and then assigning it back to the original one, after which point the trigger entries started to be logged as Skipped instead of Failed. We have no messages to handle at the moment so Skipped is expected

### Plan Type

Consumption

### Steps to Reproduce the Bug or Issue

Deploy a Logic App and Service Bus API connection configured for Managed Identity via ARM templates
At random, the trigger stops working after deployment
Entries in the Trigger history appear as Failed and their Code is Unauthorized, with no other information provided

AB#17624914

**Comment by TWolverson** [comment]
This issue appears to be as described here in the FAQ: https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/managed-identities-faq#are-managed-identities-tokens-cached

This is a really poor user experience; _Why_ do we have to wait so long? This basically makes automatically provisioning new resources with managed identities unviable since it'll take the best part of a day for them to be able to access anything.
