### ISSUE TITLE
JavaScript Inline Connector never saves properly

### ISSUE THREAD

**Issue by mohit-jagtiani** [Azure/logicapps#751]
### Describe the Bug

Workflow saved successfully. Workflow validation failed for the workflow 'test-get-document-list'. {"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null}

Connector code view

{
  "type": "JavaScriptCode",
  "inputs": {
    "code": ""
  },
  "runAfter": {
    "Initialize_variable": [
      "SUCCEEDED"
    ]
  }
}

No relevant error in Kudu to share

### Steps to Reproduce the Bug or Issue

add inline js script action at any stage and save workflow
try code var a=1; in js script to retry and save

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Initialize_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "data",
                            "type": "string"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            },
            "Sort" : {
  "type": "JavaScriptCode",
  "inputs": {
    "code": "var a =1;"
  },
  "runAfter": {
    "Initialize_variable": [
      "SUCCEEDED"
    ]
  }
}
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "Recurrence": {
                "recurrence": {
                    "frequency": "Minute",
                    "interval": 1
                },
                "type": "Recurrence"
            }
        }
    },
    "kind": "Stateful",
    "parameters": {
        "efsApiPassword": {
            "type": "String",
            "value": "@{appsetting('efsPassword')}"
        },
        "efsApiUsername": {
            "type": "String",
            "value": "@{appsetting('efsUsername')}"
        }
    }
}
```

### Expected behavior

working connector action or relevant error

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/64312140/228370526-53c31c80-b41e-4b14-991c-f74b9b5ce5d8.png)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Firefox

AB#17784415

**Comment by mohit-jagtiani** [comment]
i think my configuration are correct according to blog

![image](https://user-images.githubusercontent.com/64312140/229929200-38b418f4-cb37-4bdc-b0eb-d4626afdde81.png)

**Comment by mohit-jagtiani** [comment]
Okay, reason we used dotnet was because we also nuget package based custom connector, does that mean we cant use that connector and inline java script connector in same logic app, even in different workflows?

**Comment by hartra344** [comment]
@rohithah  to help answer

**Comment by sudhalalwani** [comment]
Hi All, 
I am facing the same issue. 
Error I am getting is :

Workflow validation failed for the workflow 'PRIMUS-Test001'. {"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null}


Code :-

var t = "Hello World!"
return t;

I checked configuration and 
FUNCTIONS_WORKER_RUNTIME is set to  node and WEBSITE_NODE_DEFAULT_VERSION to ~18

Can someone please help me to understand why this is happening.

**Comment by timjansenortec** [comment]
node 18 is not supported yet for logic app standard
see https://github.com/MicrosoftDocs/azure-docs/issues/111387

see here about which FUNCTIONS_WORKER_RUNTIME to use:
https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/logic-apps/create-single-tenant-workflows-visual-studio-code.md#set-up-the-forwarding-url-in-your-app-settings
If your project is NuGet package-based (.NET), not extension bundle-based (Node.js), "FUNCTIONS_WORKER_RUNTIME" is set to "dotnet". However, to use Inline Code Operations, you must have "FUNCTIONS_WORKER_RUNTIME" set to "node"
