### ISSUE TITLE
Service Bus trigger does not pull data from dead letter queue

### ISSUE THREAD

**Issue by rohit3d2003** [Azure/logicapps#754]
### Describe the Bug

We our using Logic App (Standard) deployed on a App Service Plan using Functions runtime (node v4). In our logic app we have couple of workflows hooked to a Service Bus Topic to read message from **Dead Letter** queue on topic subscription. Service Bus topic has session enabled. While debugging the workflow, we realized that the message payload does not contain 'DeadLetterReason' & 'DeadLetterErrorDescription' attribute although the trigger configuration specifically has 'DeadLetter' subscription type instead of 'Main' queue. Not sure what is causing it and appreciate any help on this.

![Screenshot 2023-04-08 at 1 50 59 PM](https://user-images.githubusercontent.com/16943885/230742105-cc1e4d6c-6586-4aef-a12d-a95f98a9dcf1.jpg)

Message payload:

{
  "MessageType": "abc",
  "x-correlation-id": "a20b7f10-4b6b-4673-be91-f0beaab2af29",
  "Source": "xyz",
  "X-Forwarded-For": "10.249.251.241",
  "Request-Id": "|3af82256-4f293c5d3d436d29.3af82257_",
  "Request-Context": "appId=cid-v1:392a4616-5619-4cfd-9996-2e65f3954ed8",
  "CorrelationId": "a20b7f10-4b6b-4673-be91-f0beaab2af29",
  "DeliveryCount": "1",
  "EnqueuedSequenceNumber": "141",
  "EnqueuedTimeUtc": "2023-04-07T16:34:42Z",
  "ExpiresAtUtc": "2023-04-21T16:34:42Z",
  "Label": "xyz",
  "LockedUntilUtc": "9999-12-31T23:59:59Z",
  "LockToken": "5ae499e3-882a-49e7-8178-9c5e52970026",
  "MessageId": "Order9238",
  "ScheduledEnqueueTimeUtc": "0001-01-01T00:00:00Z",
  "SequenceNumber": "10696049115005069",
  "SessionId": "Order123",
  "Size": "3352",
  "State": "Active",
  "TimeToLive": "12096000000000"
}

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a workflow and add trigger 'When a message is received in a topic subscription (peek-lock)'
2. Set topic, subscription and subscription type to 'DeadLetter'
3. Put a message on subscription and set expiration to 1 sec.
4. Message will land on dead letter queue (Assuming subscription is configuration to move messages on dead letter queue upon expiration).
5. logic app workflow is triggered but it received message from 'Main' subscription type instead of 'DeadLetter'

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_message_is_received_in_a_topic_subscription_(peek-lock)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "servicebus"
                        }
                    },
                    "method": "get",
                    "path": "/@{encodeURIComponent(encodeURIComponent('topic-name'))}/subscriptions/@{encodeURIComponent('subscription-name')}/messages/head/peek",
                    "queries": {
                        "sessionId": "Next Available",
                        "subscriptionType": "DeadLetter"
                    }
                },
                "recurrence": {
                    "frequency": "Second",
                    "interval": 15
                },
                "type": "ApiConnection"
            }
        }
    },
    "kind": "Stateful"
}
```

AB#17896990

**Comment by rarayudu** [comment]
Picking up messages using sessions from dead letter queue is not supported by service bus. Please provide the session id as None to pick up messages from a dead letter queue. And also, I noticed you are using Shared connector from Logic Apps Standard. Would suggest look into using the built-in service bus as they has the performance benifits of running with-in the app and able to connect to service bus namespaces with network restrictions.

**Comment by rohit3d2003** [comment]
Appreciate your response. The built-in connector does not have an option to read from dead letter queue on topic subscription, hence I was using Azure connector

**Comment by apranaseth** [comment]
The built-in "when messages are available in a queue" or peek-lock trigger can be used to get messages from a dead-letter queue as any other queue. There is a default deadletter queue for both the queue or the topic subscription itself. The dead-letter queue name should be used like below as the queue name on the trigger
<queue path>/$deadletterqueue
<topic path>/Subscriptions/<subscription path>/$deadletterqueue

Refer https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#path-to-the-dead-letter-queue service bus documentation for details.
