### ISSUE TITLE
VSCode workflow cannot be maintained

### ISSUE THREAD

**Issue by PeterSchults** [Azure/logicapps#757]
### Describe the Bug

I want to adjust an existing workflow but workflow keeps "loading" .
Tried to rebuild from scratch, same problem....

### Plan Type

standard

### Steps to Reproduce the Bug or Issue

open VSC
Select Repo
Open Workflow

### Screenshots or Videos

![Schermafbeelding 2023-04-12 171605](https://user-images.githubusercontent.com/16748614/231960718-0b4fcec6-2c59-40f3-9493-afef80ec6374.png)

AB#17968730

**Comment by hartra344** [comment]
You’ve opened this bug 3 times now giving us no new information at all. I posted over here #1934  asking for some more information. Please keep the conversation to a single issue
