### ISSUE TITLE
Visual Studio Code Run Overview no longer showing input and output properties of actions in a loop

### ISSUE THREAD

**Issue by AndyN345** [Azure/logicapps#762]
### Describe the Bug

Visual Studio Code Editor is no longer showing the input and outputs of actions that are within a loop, which makes local debugging almost impossible.

View run history from Portal

![image](https://user-images.githubusercontent.com/99191002/233331924-a1275b52-b07a-4919-8c20-6f632c16eb7c.png)

View of run history from Visual Studio Code

![image](https://user-images.githubusercontent.com/99191002/233332214-91451807-1305-4da5-adb6-5018a01ea6d3.png)

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. In visual studio code view run history and select any action in a loop
2. Inputs and outputs not shown only properties

### Additional context

Extension version 2.5.1

**Comment by ccastrotrejo** [comment]
Hi @AndyN345 thanks for raising this issue. Is there any chance you can share the workflow.json with us, so we can replicate it?
