### ISSUE TITLE
VSCode designer resets contentVersion to 1.0.0.0

### ISSUE THREAD

**Issue by niphlod** [Azure/logicapps#786]
### Describe the Bug

When opening a previously saved workflow, on saving VS code resets the contentVersion tag to 1.0.0.0.

It'd be beneficial to leave it as it is, as it's a good usecase to know what specific version is deployed on each running environment.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

- Open any workflow.json
- Save it with contentVersion "2.0.0.0"
- Close the designer
- Reopen it
- Save it
- contentVersion is reset to "1.0.0.0"

AB#24124356

**Comment by pellitteris** [comment]
This also happens if you edit the workflow from the azure portal.

**Comment by niphlod** [comment]
don't know if this bug was looked into but it seems resolved now both on VS Code and in the online designer

**Comment by niphlod** [comment]
fixed as of [2.28.4](https://github.com/Azure/LogicAppsUX/compare/v2.28.3...v2.28.4)
