### ISSUE TITLE
Azure Storage Table doesn't support tables.

### ISSUE THREAD

**Issue by bobbytreed** [Azure/logicapps#79]
I've been writing to my one storage account with table storage connectors for months, and it's still active. I added one blob operation to a logic app and now all table storage connectors fail.

{
  "message": "The provided storage account does not support table operations.",
  "error": {
    "reason": "BadRequest",
    "message": "The provided storage account does not support table operations.",
    "innerError": {
      "code": 501,
      "reason": "Not Implemented",
    }
  }
}

**Comment by bobbytreed** [comment]
And yet on the Get Entities drop down it even shows me all the tables I can write to

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
