### ISSUE TITLE
Zip file getting corrupted upon Upload blob to storage container

### ISSUE THREAD

**Issue by nahimmedvent** [Azure/logicapps#794]
### Describe the Bug with repro steps

1. Get a zip file as an attachment in an email
2. Use the Azure Blob Storage built-in connector "Upload blob to storage container" to extract dynamic content "Attachments content" from the Outlook connector.
3. Try and open the uploaded file from the storage account, it will be corrupted (invalid)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Workflow JSON

```json
{
  "type": "ServiceProvider",
  "inputs": {
    "parameters": {
      "containerName": "xxxx",
      "blobName": "@variables('file_name_i')",
      "content": "@item()?['contentBytes']",
      "overrideIfExists": "True"
    },
    "serviceProviderConfiguration": {
      "connectionName": "AzureBlob-3",
      "operationId": "uploadBlob",
      "serviceProviderId": "/serviceProviders/AzureBlob"
    }
  },
  "runAfter": {
    "Set_variable_3": [
      "Succeeded"
    ]
  }
}
```

### Browser

Edge

### Additional context

This connector works fine with other types of attachments, the problem is only with zip files. I have also used the managed connection connetor (Create Blob V2) with the very same files with no issue, but I specifically need to use the built-in connector per company policies. 

AB#24145483

**Comment by samaea** [comment]
+ 1 same issue as above. Was a resolution ever found using the built-in connector "Upload blob to storage container"? Using "Create Blob V2" works too, but cannot be used with my customer due to vnet connectivity.
