### ISSUE TITLE
Teams Connector says it failed but message sent

### ISSUE THREAD

**Issue by bobbytreed** [Azure/logicapps#80]
The Teams connector says that it is failing every time with a badRequest, yet messages are sending just fine.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
