### ISSUE TITLE
SQL Based_SQL Action: Before adding long running scenario query, the workflow is succeeded.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/logicapps#802]
### Describe the Bug with repro steps

1.Create a project and add Stateful workflow in VS code.
2.Convert your workflow in SQL Based.
3.Open Designer and add http trigger and sql_Execute query_EXEC wait2;
4.Save and Debug the workflow.

**Expected:** The workflow should be failed after 2 minutes.

**Actual:** The workflow is succeeded after 2 minutes.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/c9de2078-3dfe-45c5-af7a-2653741f7896)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Browser

VS Code

### Additional context

**Vendor Testing**

VS Code extension - ​[vscode-azurelogicapps-2.15.10.vsix](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Au%3A%2Ft%2FLogicApps%2FEfFwik7TWPhDt6mLfCHxuroB4sWsRX8rJ3eaB21le9f2oQ%3Fe%3DbqyntL&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ai5RL0TcKC%2FztWGWL57RDgQfsN%2FfvDXgGrzpY1THyWE%3D&reserved=0)
NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzcyNDMyOTY3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.19.4.nupkg&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8rOfv%2F1U8FoD4NAccsyyHJnvk6h6LcmWterenDfUM20%3D&reserved=0)
Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X68ajYSgK%2BNa2gqT4XCZZTy%2Bu1Oqlg8%2BFvD2OUamhmo%3D&reserved=0)
Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.19.4/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.19.4%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.19.4_any-any.zip&data=05%7C01%7Cv-prakumar%40microsoft.com%7C98af4a71672d4c13dabe08db5061781d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192151876278076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lhzZGusR0OY2fFZq342r%2BiR8%2F6JBiGb0wvf2EI4yFdw%3D&reserved=0)

AB#24182121

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in VSIX : 2.24.3

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in vsix 2.28.3

**Comment by v-prakumar** [comment]
@ccastrotrejo Issue is repro in the vsix 2.55.1

**Comment by vgouth** [comment]
Issue repro in the latest request.

1.VS Code extension - vscode-azurelogicapps-2.58.0.vsix
2.NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc4MzA5NDU2L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.36.3.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YbUQGX1JIg4zw8dJj3tXaSQ1UvYGHZoesH4PqdR3ir0%3D&reserved=0)
3.Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iTF28R1F1CAdbvqFM1XoCLdADsc09X7HLH2v22QsIpc%3D&reserved=0)
4.Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.36.3/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.36.3%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.36.3_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd70348ec768743faf20508dba21b21b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638282009696249548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HnqMsrbHp0z5Arf04tfU0ktLF%2FIFr2p48GDG0%2FVDs6s%3D&reserved=0)

![image](https://github.com/Azure/logicapps/assets/113517384/51edda46-ce29-4cd5-adbc-1fa676259112)

**Comment by vgouth** [comment]
Issue repro in the latest VS code request

1. **VS Code extension** -  [ vscode-azurelogicapps-2.63.3.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EZqLPbe1WcBImD7iTJtkJcUB2XzuY0npAYSBrz3t9VzjAg?e=JLTViK&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218MzZjZGIyM2QzYWYwNDgyODgxZGIwOGRiYWY3ZDViYTN8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODI5NjcyNTI1Mzc3OTM0NnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=cFFqeE9NdWxDYjlqelRuNTh0NDhUQUE2dDBkMmNGTWlPUFA4Z0dpWjlxZz0%3d) 
2. **NuGet package:** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc5MjQ0MDM5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.38.2.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzc5MjQ0MDM5L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.38.2.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GFclQ81vlVvol1jJN%2FOrQpXJQIh9UQsiD%2FBSqm0mwRE%3D&reserved=0)
3. **Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t38EnCXtrvwpoMOdkKBpkUGcMssK%2B5JsTxCUiun62Ls%3D&reserved=0)
4. **Extension Bundle (Direct Download):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.38.2/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.38.2_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.38.2%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.38.2_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7C98cd3820f24a4770f31208dbaf01c3ad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638296194454108856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bq4GFeOnQoVNkZazW%2BEzVnBOBTzjoLKqxfzlmBHj1D4%3D&reserved=0)


![image](https://github.com/Azure/logicapps/assets/113517384/b84f764d-516e-4aa8-b611-2cc9c41b234b)
![image](https://github.com/Azure/logicapps/assets/113517384/4bc75211-109a-4c12-9568-26d23bc3a372)

**Workflow.Json:**

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Execute_query": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "query": "EXEC wait2;"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "sql-2",
                        "operationId": "executeQuery",
                        "serviceProviderId": "/serviceProviders/sql"
                    }
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        },
        "parameters": {}
    },
    "kind": "Stateful"
}

**Comment by vgouth** [comment]
Issue repro in the latest request 

**1. VS Code extension** -  [ vscode-azurelogicapps-2.69.0.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EeRUYYoqyrZPtK9ZvXk0xcQBG35zXPOj8q8xsyuAvEOuTw?e=H37L8f&xsdata=MDV8MDF8di1nb3Z1YmlsaXNoQG1pY3Jvc29mdC5jb218ZThkYzI1YTUzNTE0NGJkMWZmZDAwOGRiYmRlOTM1YTd8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODMxMjU4MTU5NTMwODcxMXxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=Wkx0VCtEbGhRL1JrTy9SakxIQXAzenBYdUxwTFRYSld3Tml5QnJaV2dTQT0%3d) 
**2. NuGet package:**  [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgwMDY5MTEwL2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.41.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce8dc25a535144bd1ffd008dbbde935a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638312581595308711%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xOkEsFCnkKCBSFtQv1WzMkFnDNMVIPN%2F3DRV7NOji2c%3D&reserved=0)
**3. Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce8dc25a535144bd1ffd008dbbde935a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638312581595308711%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xDK2PS2HVLVPoDaoqXQLv0NAXtbvBNNEQFDSV%2BXCvhg%3D&reserved=0)
**4. Extension Bundle (Direct Download):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.41.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip</p](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.41.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.41.1_any-any.zip%253c%2Fp&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ce8dc25a535144bd1ffd008dbbde935a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638312581595308711%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wPNdM8JE8fs1gZ0TMknatdNlM%2Fxvo%2BtABD%2B9scUVmsU%3D&reserved=0)

![image](https://github.com/Azure/logicapps/assets/113517384/9f4a4fe1-212e-47d1-a8ad-7d96f4fc728f)

**Workflow.Json:**
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Execute_query": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "query": "EXEC wait2;"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "sql",
                        "operationId": "executeQuery",
                        "serviceProviderId": "/serviceProviders/sql"
                    }
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        },
        "parameters": {}
    },
    "kind": "Stateful"
}

**Comment by vgouth** [comment]
@ccastrotrejo , @AbodeSaafan

Issue **not** repro in the latest request but there is an error in the terminal. Is the error expected?

**1.VS Code extension** - ​​vsix icon[ vscode-azurelogicapps-2.72.1.vsix](https://microsoft.sharepoint.com/:u:/t/LogicApps/EfKWqLA0W0ZEvopnY8wo_tkBY9WSkRtgWk-niBfAd47iPw?e=ohFYeL&xsdata=MDV8MDF8di1pdHJhbXlhQG1pY3Jvc29mdC5jb218MWY4ZWNjOWQwMTMwNGI2N2E0ZGYwOGRiY2YzN2ZhZGF8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODMzMTYxMTgxMjIxOTAyMnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=VUxqbU9kQ1VKV2ZmbFgvbFhnMExMUHVnQlE4TE1mVHRmYjdmOXhGNG5tVT0%3d)

**2.NuGet package:** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg&data=05%7C01%7Cv-itramya%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241613333478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=whaLLdJIMjsic5AHmCk6Xb4GDEnNzQdbhbmd7AYE66o%3D&reserved=0)

**3.Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-itramya%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241613343570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p0LTFBnMqK0OtC0tKtfn3DUiGfH9UT6wd0kzurKV1po%3D&reserved=0)

**4.Extension Bundle (Direct Download):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.44.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.44.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1_any-any.zip&data=05%7C01%7Cv-itramya%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241613350230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xir1h2Cqma1OrxIQHPS7EZ5mrVoth9%2BjUtVWPAH1auQ%3D&reserved=0)

![image](https://github.com/Azure/logicapps/assets/113517384/0d1d61ef-7af8-4bc2-a1a0-45ba93d6225b)

**Error message in terminal:**

[2023-10-18T13:41:43.354Z] Error message: correlationId='ae091658-ad43-4f2f-b9fe-64931d26b338', operationName='sql.SqlServiceOperationsProvider.ExecuteQueryAsync', message='A severe error occurred on the current command.  The results, if any, should be discarded.
[2023-10-18T13:41:43.355Z] Operation cancelled by user.', exception='Microsoft.Data.SqlClient.SqlException (0x80131904): A severe error occurred on the current command.  The results, if any, should be discarded.
[2023-10-18T13:41:43.356Z] Operation cancelled by user.
[2023-10-18T13:41:43.357Z]    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[2023-10-18T13:41:43.358Z]    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[2023-10-18T13:41:43.358Z]    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
[2023-10-18T13:41:43.359Z]    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
[2023-10-18T13:41:43.360Z]    at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
[2023-10-18T13:41:43.361Z]    at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
[2023-10-18T13:41:43.362Z]    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
[2023-10-18T13:41:43.365Z]    at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
[2023-10-18T13:41:43.367Z]    at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
[2023-10-18T13:41:43.368Z]    at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
[2023-10-18T13:41:43.369Z]    at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
[2023-10-18T13:41:43.371Z]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[2023-10-18T13:41:43.372Z] --- End of stack trace from previous location ---
[2023-10-18T13:41:43.373Z]    at Microsoft.Azure.Workflows.ServiceProviders.Sql.Utilities.SqlExecutor.GetSqlDataReader(SqlCommand command, CommandBehavior commandBehavior, CancellationToken cancellationToken)
[2023-10-18T13:41:43.373Z]    at Microsoft.Azure.Workflows.ServiceProviders.Sql.Utilities.SqlExecutor.ExecuteQueryAndGetResult(SqlCommand command, CommandBehavior commandBehavior, CancellationToken cancellationToken, String callerName)
[2023-10-18T13:41:43.374Z]    at Microsoft.Azure.Workflows.ServiceProviders.Sql.Utilities.SqlExecutor.ExecuteQueryAsync(ConnectionProperties connectionProperties, IDictionary`2 queryParameters, String query, CommandBehavior commandBehavior)
[2023-10-18T13:41:43.375Z] ClientConnectionId:3a204b1d-2cf4-4511-817b-ac082dbec2fd', organizationId='', activityVector='IN.03', additionalProperties='{"ParentActivityId":"00-21c16d5a7735661095bb3ddd707d3f49-581b3b61829e3115-00"}', extensionVersion='1.44.1.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='b154c40d-a808-45cf-97ed-906ce7b26c74'.
[2023-10-18T13:41:43.437Z] Executed 'Functions.WorkflowDispatcher' (Succeeded, Id=131fff88-8bb6-404a-8a31-5fab02426731, Duration=120475ms)
