### ISSUE TITLE
Chunking : InvalidContentRangeHeader 

### ISSUE THREAD

**Issue by grik001** [Azure/logicapps#81]
Hi, 

I am facing an issue when enabling chunking in my LogicApps. After the request hits my Patch endpoint I keep getting an InvalidContentRangeHeader error.

I have tried setting both:

response.Headers "Range" : "bytes 0-xxx/len"
response.Content.Headers "Content-Range" : "bytes 0-xxx/len"

No matter what I set I keep getting this error. Is chunking fully supported at the moment or am I missing something in my implementation? 

Full Error:

InvalidContentRangeHeader. The response to partial content upload request was not valid. The returned range header value '<null>' is not in the expected range of '0-137725638' with unit set to 'bytes'.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
