### ISSUE TITLE
Mooncake + Logic App + Azure Blob Storage V2 can't create a connection using service principal, I see the global endpoint("error_uri":"https://login.microsoftonline.com/error?code=90002") in error message 

### ISSUE THREAD

**Issue by MeihuaWang** [Azure/logicapps#813]
### Describe the Bug with repro steps

1. just add a Azure Blob Storage V2's action, such as create blob,
2. next you will be promted to create a connection, pls check service principal in "Authentication Type".

in both Consumption and Standard

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![1 uyi](https://github.com/Azure/LogicAppsUX/assets/95485003/8b40de43-cf4e-4cdf-88a9-7defac2eb721)

### Browser

Chrome latest version

AB#24187921

AB#24333332

**Comment by MeihuaWang** [comment]
so when this bug can be fixed? can I get the ETA ? thank you.

**Comment by rllyy97** [comment]
@meihua I reached out to our backend team to see if this is a bug or expected behavior, I have not heard back yet but I just wanted to let you know I am still looking into this for you

**Comment by rllyy97** [comment]
@meihua To help us investigate this could you collect and send a network trace to us?
You can find steps to do so here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file
And once you have the `.har` you can send it to me at rileyevans@microsoft.com

**Comment by MeihuaWang** [comment]
> @meihua To help us investigate this could you collect and send a network trace to us? You can find steps to do so here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file And once you have the `.har` you can send it to me at [rileyevans@microsoft.com](mailto:rileyevans@microsoft.com)

I've sent the har to [rileyevans@microsoft.com](mailto:rileyevans@microsoft.com), pls be aware of that.

**Comment by rllyy97** [comment]
@meihua I looked through your network trace and didn't find anything out of the ordinary,  I also tried reproducing your issue and was unable to.  Just to confirm, you're getting the service principal `Client ID` and `Tenant ID` for the connection from these values marked with yellow correct?

![image](https://github.com/Azure/logicapps/assets/25409734/087a5429-12ce-4fc5-94e2-6cb6040f9ab5)

![image](https://github.com/Azure/logicapps/assets/25409734/5b4cb74a-f609-46c6-94cb-00b525c8cdc3)

**Comment by MeihuaWang** [comment]
> @meihua I looked through your network trace and didn't find anything out of the ordinary, I also tried reproducing your issue and was unable to. Just to confirm, you're getting the service principal `Client ID` and `Tenant ID` for the connection from these values marked with yellow correct?
> 
> ![image](https://user-images.githubusercontent.com/25409734/251253111-087a5429-12ce-4fc5-94e2-6cb6040f9ab5.png)
> 
> ![image](https://user-images.githubusercontent.com/25409734/251254607-5b4cb74a-f609-46c6-94cb-00b525c8cdc3.png)

@rllyy97， I'm 100% sure that the client id and tenant id are correct, the issue here is we met this issue in Mooncake portal not Global portal, but we saw the global endpoint "error_uri":"https://login.microsoftonline.com/error?code=90002" in the error message, normally if we met this kind of error messages when invoking SDK, we knew we needed to change cloud enviroment, base url and credential scopes, but we can do nothing in portal , pls reproduce this in Mooncake portal.

**Comment by rllyy97** [comment]
@MeihuaWang I've been notified that a fix has been implemented and should be deployed by July 27th.
Thank you for your patience and cooperation while we got this fixed!

**Comment by MeihuaWang** [comment]
@rllyy97 it works now, thank you very much.

**Comment by rllyy97** [comment]
Great!  Glad we could finally get it working for you
