### ISSUE TITLE
Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by lhq2100** [Azure/logicapps#818]
AB#24351928

**Comment by j-chao** [comment]
I can replicate this issue as well.

**Comment by ccastrotrejo** [comment]
Hi @j-chao, can you give it a try by updating the Azurite and Azure Logic Apps (Standard) to the latest versions? 
Also, could you please follow the 1-4 steps from [here](https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#run-test-and-debug-locally) to properly run, test and debug locally the logic app project. Please, if this keeps happening let me know. Also, if there are any console errors could you please attach them as well?

**Comment by AbodeSaafan** [comment]
Hey,

For the latest stack trace, I see that the runtime isn't able to connect to the emulator, can you confirm your storage setting and that the emulator azurite is running fine

'Workflow runtime could not connect to the configured storage emulator. Please ensure storage emulator is installed and running.',
