### ISSUE TITLE
Update the Microsoft.Web/connections@2016-06-01 schema

### ISSUE THREAD

**Issue by coolhome** [Azure/logicapps#826]
### Describe the Bug

Re-opening https://github.com/Azure/logicapps/issues/583

When will `Microsoft.Web/connections@2016-06-01` and `Microsoft.Web/Connections@2018-07-01-preview` have the schema published or a new version of the API with a fully typed schema be available? There is a lot of holes in this implementation that require a lot of digging. It is almost not worth to choose this platform from a DevOps standpoint.

I have also aggregated related tickets about this schema issue that has not received any attention.
* https://github.com/Azure/azure-rest-api-specs/issues/19459
* https://github.com/Azure/azure-rest-api-specs/issues/20851
* https://github.com/Azure/bicep-types-az/issues/1490
* https://github.com/Azure/bicep-types-az/issues/1501
* https://github.com/Azure/bicep-types-az/issues/1671
* https://github.com/Azure/bicep-types-az/issues/1662
* https://github.com/Azure/bicep-types-az/issues/1812

### Plan Type

Standard & Consumption

### Steps to Reproduce the Bug or Issue

Using Bicep try to provision `Microsoft.Web/Connections` with Kind V1 and V2 have zero types and missing a lot of properties. 

AB#24479433

**Comment by aristosvo** [comment]
Please, anyone who can explain why the definitions are lacking features for a few years already, especially `Kind=V2` functionality?

**Comment by orgads** [comment]
This is still relevant. Please reopen.

Another link:
- https://github.com/hashicorp/terraform-provider-azurerm/issues/23064

**Comment by vjraitila** [comment]
Indeed. Why is this issue being systematically ignored? Proper CI/CD with Azure Logic Apps Standard in combination with managed connectors is a pain due to lack V2 support in the Azure API. 

Documentation for the various parameter schemas expected by the connectors are also non-existent. How are people supposed to know what they are?

**Comment by alanrroberts** [comment]
+1, please reopen this issue

**Comment by JoakimNylundOP** [comment]
+1, issue still valid!
