### ISSUE TITLE
Replication Tasks and Peeklock : Unable to peek messages for Dead-letter the message/Abandon the message/Complete the message actions from one servicebus queue to other queue dead-letter.

### ISSUE THREAD

**Issue by vgouth** [Azure/logicapps#828]
### Describe the Bug with repro steps

**Prerequisites:**
Create a service bus namespace with two queues.
Create an event hub instance with two hubs.

1.Create a new Stateless logic app in standard, open the designer.
2.Add a service bus "When messages are available in a queue (peek-lock)" trigger.
3.In the trigger, enter the queue name of your first service bus queue in "Queue name". In the trigger settings disable Split **On.**
4. Add a For each action and select Messages from the dynamic content as its input parameter.
5. Within the for each loop add the action "Dead-letter the message/Abandon the message" from service bus. In the Message ID field select "Message ID" from the dynamic content popup. 
6. Save the workflow.
7. Open the service bus queue attached to your trigger and then open the service bus explorer. Create a test message of content type text and send it to that queue.
8. Open the service bus queue attached to your replicate messages action and then open the service bus explorer. Open the peek tab, select the DeadLetter queue and click "peek".

**Expected:** After clicking peek you should see your message displayed below. Open it and verify that the contents match what you sent earlier.

**Actual:** Unable to peek messages for Dead-letter the message/Abandon the message actions from one servicebus queue to other queue dead-letter.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/ffbe641d-f604-48ab-a149-3606fc2ff0be)
![image](https://github.com/Azure/LogicAppsUX/assets/113517384/dfe6bcd8-f037-4e47-8d33-86ddf13b6bbd)

### Browser

Edge

### Additional context

**Environment Details:**

**URL:** https://aka.ms/emastaging-flowstip1
**Version:** 2.30508.1.2

AB#24283754

AB#24494142

**Comment by vgouth** [comment]
Issue repro in the latest request,

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C22eca00d05414450524c08db8c1dbdfd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638257831648260657%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Spc48TAD7oGuAs8oPmFAqnCllLZpAdhrd%2BkWGMT78Vo%3D&reserved=0)
**Version:** 2.30717.1.1

**Comment by vgouth** [comment]
Issue repro in the latest request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C25ee41df62d44438790c08db937727d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638265912263218130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ExdI18ub8D3V7ulDw4BDJPTB28t6zLoS8UczXvO%2FLFw%3D&reserved=0)
**Version:** 2.30731.1.4

**Comment by vgouth** [comment]
Issue repro in the latest request 

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ca913e3ff33294e1163d608db9db5f11a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638277177033505326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MKfEmdMGq%2BLkG6Dt%2Bs8o2wQO8nicOL75f4AcxCeQnZA%3D&reserved=0)
**Version:** 2.30814.1.1

**Comment by vgouth** [comment]
@AbodeSaafan As this issue is migrated to be a backend issue, requesting you to have a look into it.
 
Issue repro in the latest request
**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C18a8b542b1764bd310b408dba93133ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638289801129729358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wver%2BsKkXAoPcJFkMT%2FOj9%2FZg9i4gj8Sa%2FF8mmTQgTA%3D&reserved=0)
**Version:** 2.30828.1.2

![image](https://github.com/Azure/logicapps/assets/113517384/f1736508-1dae-4ea3-b87d-516df08a6cbb)
![image](https://github.com/Azure/logicapps/assets/113517384/a3205cad-4c71-4845-9451-9d73acdc8214)

**Comment by AbodeSaafan** [comment]
@vgouth can you check with Aprana on this since it's service bus to confirm if this is a bug or incorrect configuration

**Comment by vgouth** [comment]
@apranaseth Requesting you to have a look into this issue and let us know if this is a bug or incorrect configuration or changes to be done in test case..

**Comment by apranaseth** [comment]
@vgouth  can you reach out to Alex Karcher for replication task question.

**Comment by alexkarcher-msft** [comment]
Hi @vgouth . Can you share a screenshot and your workflow.json for the workflow that is driving this behavior? I'd like to see whether any actions are failing and see what queues are being targeted by that workflow.

**Comment by vgouth** [comment]
Hi @alexkarcher-msft, please find the attached workflow. Json code. All the screenshots are attached above including the test case, the issue one as well.  

{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "For_each": {
        "type": "Foreach",
        "foreach": "@triggerBody()",
        "actions": {
          "Complete_the_message": {
            "type": "ServiceProvider",
            "inputs": {
              "parameters": {
                "messageId": "@items('For_each')?['messageId']"
              },
              "serviceProviderConfiguration": {
                "connectionName": "serviceBus",
                "operationId": "completeMessage",
                "serviceProviderId": "/serviceProviders/serviceBus"
              }
            }
          }
        },
        "runAfter": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_messages_are_available_in_a_queue_(peek-lock)": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "queueName": "test3",
            "isSessionsEnabled": false
          },
          "serviceProviderConfiguration": {
            "connectionName": "serviceBus",
            "operationId": "peekLockQueueMessages",
            "serviceProviderId": "/serviceProviders/serviceBus"
          }
        }
      }
    }
  },
  "connectionReferences": {
    "serviceBus": {
      "connection": {
        "id": "/serviceProviders/serviceBus/connections/serviceBus"
      },
      "connectionName": "abc",
      "api": {
        "id": "/serviceProviders/serviceBus"
      }
    }
  },
  "parameters": {}
}

**Comment by vgouth** [comment]
@alexkarcher-msft . Thank you for quick connect. As per the updated the test case the issue is **not repro**, As of now closing this bug.
