### ISSUE TITLE
Critical: Logic app is using variable value of the first foreach iteration

### ISSUE THREAD

**Issue by brolifen** [Azure/logicapps#831]
### Describe the Bug

A foreach loop goes through all items in an array. For each item a variable is set in the iteration and used in a HTTP request. Here is the setup:

![image](https://github.com/Azure/logicapps/assets/20615514/1da06e89-097f-4308-b966-a56979941dfc)

As you can see the connectionIdentifier variable is set first and then used within the condition block. 

However in practise what I see is that the variable value of the previous iteration is used when processing the second item in the array.

![image](https://github.com/Azure/logicapps/assets/20615514/f0875bdb-56ec-4c4a-b929-b163391d5a0e)

![image](https://github.com/Azure/logicapps/assets/20615514/316ce15b-b3ee-40d8-97df-1e5633d9c019)

Am I doing something wrong here? What did the reference get the value of the previous iteration?

Some more testing I did:
- This issue is also 100% reproducible see the below shared workflow. 
- Same issue can be reproduced on two completely different subscriptions linked to completely different Entra ID tenants
- The same workflow on the Power Automate platform works as expected.
- Tried in both Eest US as West Europe region it seems to be present in all regions.
- The Issue ONLY occurs in a Foreach Loop, a Do Untill loop works as expected

### Plan Type

consumption

### Steps to Reproduce the Bug or Issue

1. Create a new consumption based Logic App in West Europe
2. Copy and paste the workflow JSON
3. Run the Workflow
4. Notice the variable value is not respected when called in the condition in the foreach iteration 

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "For_each": {
                "actions": {
                    "Set_userName_value": {
                        "inputs": {
                            "name": "userName",
                            "value": "@{item()?['name']}"
                        },
                        "runAfter": {},
                        "type": "SetVariable"
                    },
                    "Show_userName_value": {
                        "inputs": "@variables('userName')",
                        "runAfter": {
                            "Set_userName_value": [
                                "Succeeded"
                            ]
                        },
                        "type": "Compose"
                    }
                },
                "foreach": "@variables('UserArray')",
                "runAfter": {
                    "Initialize_UserArray_variable": [
                        "Succeeded"
                    ]
                },
                "type": "Foreach"
            },
            "Initialize_UserArray_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "UserArray",
                            "type": "array",
                            "value": [
                                {
                                    "name": "Alice",
                                    "number": "46374"
                                },
                                {
                                    "name": "Bob",
                                    "number": "65378"
                                },
                                {
                                    "name": "John",
                                    "number": "22654"
                                }
                            ]
                        }
                    ]
                },
                "runAfter": {
                    "Initialize_userName_variable": [
                        "Succeeded"
                    ]
                },
                "type": "InitializeVariable"
            },
            "Initialize_userName_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "userName",
                            "type": "string"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "manual": {
                "inputs": {},
                "kind": "Http",
                "operationOptions": "IncludeAuthorizationHeadersInOutputs",
                "type": "Request"
            }
        }
    },
    "parameters": {}
}
```

### Additional context

This is ONLY affecting the foreach loop. The do until loop respects the variable value correctly.

AB#24543921

**Comment by brolifen** [comment]
Has been over a day now without a response?

**Comment by rllyy97** [comment]
Hi @brolifen, I saw you closed the issue, are you still able to reproduce it or did you reach some sort of resolution?

**Comment by brunoscota** [comment]
try to use it in sequential mode

https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-control-flow-loops?tabs=consumption#for-each-run-sequentially
