### ISSUE TITLE
LogicApp APIM Connector fails to save when connecting to Consumption Plan APIM

### ISSUE THREAD

**Issue by ehuggz** [Azure/logicapps#84]
Connecting to API Management from a Logic App works fine if the APIM instance is either Developer or Standard SKU. The error below is generated after selecting a Consumption Plan APIM instance and API and then trying to save the changes. The error appears when saving.
 

> Failed to save logic app S-RREZ-GET-AppServiceSpace-LA01. The API Management service hosting the API '/subscriptions/<subscriptionID>/resourceGroups/S-RREZ-SYSTEMTOOLS-RG01/providers/Microsoft.ApiManagement/service/S-RREZ-SYSTEMAPI-APIM-01/apis/s-rrez-sysmon-fa-01' could not be found. 
> 

The error only occurs when targeting a Consumer API Management Sku using the standard APIM Connector. Standard and Dev Skus save successfully.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
