### ISSUE TITLE
Logic App Standard issues with Azurite 3.25

### ISSUE THREAD

**Issue by timjansenortec** [Azure/logicapps#841]
### Describe the Bug

There seem to be issues when running logic app standard locally together with Azurite 3.25

When running logic apps locally, the management API does not return runs anymore.
API: /runtime/webhooks/workflow/api/management/workflows/{workflowName}/runs
also see https://stackoverflow.com/questions/76758903/vs-code-has-suddenly-stopped-displaying-logic-app-standard-run-history

It seems that nothing can be read from storage anymore.
I have a step in a workflow that is giving secured output: when accessing the output in a next step it gives this error: 
'System.InvalidOperationException: The referenced action '<actionName>' with sequencer Id '<some id>' is not completed successfully

Reverting to Azurite 3.24 solved the issue for me.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Create a new flow locally in VSCode
2. Start the flow
3. History stays empty

AB#24639567

**Comment by mark-abrams** [comment]
I have exactly the same issue, and downgrading Azurite to 3.24.0 also solved the problem.

**Comment by ccastrotrejo** [comment]
Hi all, please downgrade and use the 3.24.0 version as a workaround for now. Thanks for raising this issue

**Comment by ccastrotrejo** [comment]
Hi all, a new azurite version was released (3.25.1) please update to that version. This version should work as expected, if not please let me know
