### ISSUE TITLE
Be able to disable an action and run the Logic App

### ISSUE THREAD

**Issue by Splaxi** [Azure/logicapps#87]
Image that I have a Logic App where I'm working with several actions and I need to disable one or more actions, to test how things behave.

I want to disable the http action (1). The second json parse (2) is dependent on the http action. 
![image](https://user-images.githubusercontent.com/8750181/82556694-8b0dd680-9b6a-11ea-9adc-23d2ed6a7569.png)

The Logic App designer already now blocks us from deleting actions that successor actions depend on. Using the same capability and logic, you shouldn't be allowed to disable an action, if a successor action is depending on it. So I would have to disable the second json parse (2), before being able to disable the http action (1).

I would expect the parser to, on save, to have to "calculate" the valid route of actions, almost like it does now. It could something like the "runAfter" should be split into "designedRunAfter" and "runAfter". That way the designer would still be able to show the flow of actions and keep the disabled actions in the correct spot of the design. When we are saving the Logic App, it would then calculate what actions that are valid and map the "runAfter".

Let me know what you think of the idea.

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.

**Comment by Splaxi** [comment]
Hi,

@clemensv asked me directly to post my suggestion after a session during the build conference.

This is NOT a question, but a suggestion for the product to improve. If feel that the feedback belongs to the ideas portal instead, I'm fine with that.

**Comment by joechung-msft** [comment]
I would suggest posting this in the User Voice then:
https://feedback.azure.com/forums/287593-logic-apps

It looks like there is a post similar to what you are proposing:
https://feedback.azure.com/forums/287593-logic-apps/suggestions/18410386-disable-enable-an-action-in-the-logicapp-workflo
