### ISSUE TITLE
Issue when using Transform XML Action (Error: Undefined. Undefined.)

### ISSUE THREAD

**Issue by msitsoftware** [Azure/logicapps#873]
### Describe the Bug

With no changes in codebase or no new deployments we are getting an error in Transform XML Action. Error Message is "Undefined. Undefined."

We were able to recreate it locally and we fixed it with an additional Config-Property: 
`"AzureWebJobsFeatureFlags": "EnableMultiLanguageWorker"`
But this does not work in production Environment.

The XSLT is plain without ExtensionObjects and is running in a node worker (version ~18)

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Execute Workflow with Transform XML action.

### Screenshots or Videos

![image](https://github.com/Azure/logicapps/assets/69357066/c18a2193-d36c-49aa-a6d9-d16530086c3b)

AB#25107263

**Comment by Viktorh89** [comment]
You can (usually) find a clearer error in App Insights, check for traces/exceptions for that runid with
operation_name == "XsltNetFxLanguageWorkerFunction"

**Comment by msitsoftware** [comment]
> You can (usually) find a clearer error in App Insights, check for traces/exceptions for that runid with operation_name == "XsltNetFxLanguageWorkerFunction"

{"error":{"code":"BadRequest","message":"The .NET framework worker could not be found."}}
