### ISSUE TITLE
Inline code not Supported in GOV Virginia or Arizona

### ISSUE THREAD

**Issue by fdellagr** [Azure/logicapps#881]
### Describe the Bug with repro steps

Inline code not Supported in GOV Virginia or Arizona

Workflow validation failed for the workflow ''. {"error":{"code":"InlineCodeNotSupported","message":"The inline code action of type 'JavaScriptCode' is not supported in this region."}}

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
Workflow validation failed for the workflow ''. {"error":{"code":"InlineCodeNotSupported","message":"The inline code action of type 'JavaScriptCode' is not supported in this region."}}
```

### Browser

chrome

AB#25182294

AB#25193027

**Comment by Eric-B-Wu** [comment]
Hi @fdellagr, thanks for reporting this issue. This is a backend issue, so will be transferring there for visibility and investigation.
