### ISSUE TITLE
Trigger condition not working for SQL connector in Logic app Standard.

### ISSUE THREAD

**Issue by sunnymehra10** [Azure/logicapps#882]
### Describe the Bug with repro steps

I am using a Logic app (standard) with SQL trigger connector.
I want to invoke operation when a rows are inserted or updated in a given table . 
So i have two workflow one for "When Rows are Inserted" and other for "When Rows are updated".
This works fine but if rows are inserted then update workflow is also triggered, but with Empty data.
Hence, I want to put a Trigger condition but it is not working.
I have used below trigger condition, but it is not working.
"@greater(length(triggerBody()),0)"

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP": {
                "inputs": {
                    "body": "@triggerBody()",
                    "method": "POST",
                    "uri": "https://webhook.site/2e789f41-1ea6-47d4-b425-3838407838ff"
                },
                "runAfter": {},
                "type": "Http"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_row_is_inserted": {
                "conditions": [
                    {
                        "expression": "@greater(length(triggerBody()),0)"
                    }
                ],
                "inputs": {
                    "parameters": {
                        "tableName": "[dbo].[test2]"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "sql",
                        "operationId": "whenARowIsInserted",
                        "serviceProviderId": "/serviceProviders/sql"
                    }
                },
                "type": "ServiceProvider"
            }
        }
    },
    "kind": "Stateless"
}
```

### Browser

Chrome

AB#25192878

AB#25193612

**Comment by Eric-B-Wu** [comment]
transferring to backend team for further investigation
