### ISSUE TITLE
Logic app not able to get column value from an inserted row

### ISSUE THREAD

**Issue by AmitAnajwala** [Azure/logicapps#883]
### Describe the Bug with repro steps

Create logic app.
Add workflow.
Add trigger when a row is inserted in sql server.
Add an action to call a function app.

It is working fine.

**Issue:**

If I want to trigger a function app, when value of event_type column is 'dataload' in an inserted row, then it is not working.

I gave trigger condition.
I also tried using condition control.
Here is the condition.
@equals(triggerBody()?['event_type'],'dataload')

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Microsoft Edge

AB#25179617

AB#25193669

**Comment by Eric-B-Wu** [comment]
Seems like its same issue as https://github.com/Azure/logicapps/issues/882, transferring to backend to investigate

**Comment by AmitAnajwala** [comment]
Hi,
I found solution for this.
Create Stateful workflow in Logic App.
Go to workflow designer and add When an item is created (V2) sql trigger.
Split On should be enabled for “When an item is created (V2)”.

Then I was able to use Condition control or Trigger condition in "When an item is created (V2)" and put condition based on inserted row's column value.

Regards,
Amit.
