### ISSUE TITLE
Logic app New Design not update the code when deploy it from Azure Devops

### ISSUE THREAD

**Issue by AllisonLi1230** [Azure/logicapps#888]
### Describe the Bug with repro steps

Changes reflected in the code view and designer view but runtime is not picking up the latest change and always picking the older version of the code even though we are able to see the latest change in the designer view and code view.
1. Update the logic app zip file, deploy it via devops:
![image](https://github.com/Azure/LogicAppsUX/assets/145325914/eb0c329b-8e1d-4639-98e1-3fc455d74ea4)

after deployed into the logic app, the logic app shows the new code view
Example code view:
 
![image](https://github.com/Azure/LogicAppsUX/assets/145325914/438c9f22-0bc9-45fe-a819-ff3484f55bd9)

3. However when run the logic app, it shown the error and the code view is the old one:
RunIDs:
08585074419552364038062287482CU00

runtime reflecting old code:
![image](https://github.com/Azure/LogicAppsUX/assets/145325914/5209db85-d363-4664-b404-0442aa9d7f0e)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge and Chrome

AB#25194126

AB#25223245

**Comment by mgmm13** [comment]
hi, would like to ask if there's an appropriate step for this. I'm also encountering the same issue where designer is updated and code has been deployed through pipeline but when I trigger run it's not picking up the new version deployed.
