### ISSUE TITLE
Service Principal Connection into Azure Container Instances unable to authenticate due to missing Authorization Header

### ISSUE THREAD

**Issue by MidnightTechnologies** [Azure/logicapps#89]
![image](https://user-images.githubusercontent.com/13490165/82616359-d1226480-9b81-11ea-881f-cb1c6e4a40f6.png)

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
