### ISSUE TITLE
Logic App/China North3 can't sign in to outlook.com connector

### ISSUE THREAD

**Issue by MeihuaWang** [Azure/logicapps#897]
### Describe the Bug

In Azure China's China North3, we encountered this error "invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application." when signing in to outlook.com connector, but in China East2, we could successfully sign in to it.

url:https://login.live.com/oauth20_authorize.srf?client_id=d4881a17-1c3b-4b0b-b022-46e75e3e4a1c&scope=https%3a%2f%2foutlook.office.com%2fmail.readwrite+https%3a%2f%2foutlook.office.com%2fmail.send+https%3a%2f%2foutlook.office.com%2fcontacts.readwrite+https%3a%2f%2foutlook.office.com%2fcalendars.readwrite+offline_access&redirect_uri=https%3a%2f%2flogic-apis-chinanorth3.consent.azure-apihub.cn%2fredirect&response_type=code&state=1bcb6ba5-ef33-44ef-9ae9-f7dfd950f6d2_logic-chinanorth3-001_azure-apihub.cn&response_mode=query&prompt=select_account&uaid=4dff3d94cc294d3fa62ac2f41d8459da&msproxy=1&issuer=mso&tenant=consumers&ui_locales=zh-CN&epct=PAQABAAEAAAAtyolDObpQQ5VtlI4uGjEPyBcwn_KFSkBsfzWNS-Lwuyb8lRbnZbtv08OghU5_NQDrfdot7uIXQde0vYfi8RLzoLNYWsBcEnu5D2Y_njhtgn1mfL2ApeuvoN9pnIVaClP9MNVdQzSEAJiZ3ZLetm7Na1Hpy6VQhlajVyY6U6VK2Xb91KgwWfKOcFfA8_Vv0j8DEw9gj5KJzTg2h4cyZSAKNyuERmoeK3vSvF47x9ogriAA&jshs=0#
error screenshot:
![Weixin Image_20231010113008](https://github.com/Azure/logicapps/assets/95485003/e7cdebc8-c828-4634-82d4-f1823b99d008)

pls help fix this bug ASAP, our customer needs to use this feature In Azure China, thank you.

### Plan Type

all

### Steps to Reproduce the Bug or Issue

1. open/create a logic app in China North3.
2. add an outlook.com connector trigger in workflow designer page and click "sign in", you'll be promoted to this error page.

AB#25411967

**Comment by hartra344** [comment]
@meihuawang are you able to open a support case or ICM for this. If this specific to a region then it’s not a UX issue and not something my team is able to do much with. If it’s blocking the customer, an ICM/support case would be the better way to get quick traction.

**Comment by MeihuaWang** [comment]
we've learned internally there's already one ICM created before I raised this ticket, we will follow up the case in that ICM, thank you
