### ISSUE TITLE
Stale Operation ID when choosing Delete Queue Message

### ISSUE THREAD

**Issue by MidnightTechnologies** [Azure/logicapps#90]
![image](https://user-images.githubusercontent.com/13490165/82616496-35ddbf00-9b82-11ea-9f60-7f39741c80c7.png)

**Comment by joechung-msft** [comment]
If you have questions about Logic Apps, please visit the [MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurelogicapps).  The Issues section here is for questions about the artifacts in this GitHub repository.
