### ISSUE TITLE
Designer - Not showing all In-App actions in Browse View

### ISSUE THREAD

**Issue by ccastrotrejo** [Azure/logicapps#901]
#### `Azure Function Operations` only shows up in `In-App` action when user search it in the search bar

1. Add any trigger
2. Click on add action
3. Filter actions by `In-App` actions
4. Look for `Azure Function Operations`
5. Search for `Azure Function Operations`

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

#### Search view
<img width="800" alt="Screenshot 2023-09-11 at 9 18 18 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/c75ee9ca-de40-4f26-8437-e841823cb024">

#### Browse view
<img width="800" alt="Screenshot 2023-09-11 at 9 18 23 AM" src="https://github.com/Azure/LogicAppsUX/assets/102700317/cc84725b-9c55-46af-9664-184a3ad50b3e">

### Browser

Edge

AB#25194462

AB#25511214

**Comment by vgouth** [comment]
Issue repro in the latest VS code request. 

When tried to apply filter in runtime with **In-App**, we could not see the **Azure Functions Operations** action even though the action is tagged with In-App tag. But when we type functions/azure we could see **Azure Functions Operations** action without selecting the filter.

1. VS Code extension -   vscode-azurelogicapps-2.72.1.vsix
2. NuGet package: [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2FMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fartprodeussu2.artifacts.visualstudio.com%2FA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2Fb32aa71e-8ed2-41b2-9d77-5bc261222004%2F_apis%2Fartifact%2FcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2Fcontent%3Fformat%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241498159266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kGeAv0T2RBttFD4AwbFxVa29hRDOCwSt0n4CgpbePao%3D&reserved=0)
3. Extension Bundle (CDN URL): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241498168940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DPy3Y2MXVbh4rP7zB5UzUxFWreLne2Q2wPpYm0xX7nU%3D&reserved=0)
4. Extension Bundle (Direct Download): [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.44.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1_any-any.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnforlogicappsv2.blob.core.windows.net%2Flogicapps-vendortesting%2FExtensionBundles%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2F1.44.1%2FMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1_any-any.zip&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cae053676d4a4467f085308dbcee1c051%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638331241498174991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tdW4JfakBqgWG%2FYik7vebsTkJNqI%2BEb94VIhBYB3SFo%3D&reserved=0)


![image](https://github.com/Azure/logicapps/assets/113517384/dcc698b5-bd49-423c-b94c-799f2e9af292)
![image](https://github.com/Azure/logicapps/assets/113517384/4eb0c164-b52f-42e1-8617-2f0f385c7c8c)

**Comment by vgouth** [comment]
Issue repro in the latest request

**Environmental Details:**
**Version:** 2.31023.1.1
![image](https://github.com/Azure/logicapps/assets/113517384/81754107-42bf-4aed-a876-a39d05455dda)

**Comment by vgouth** [comment]
Issue repro in the latest Vs Code request.

1.**VS Code extension** -​2.81.0

**Comment by vgouth** [comment]
Issue repro in the latest request.

**Environmental Details:**
**Version:** 2.31108.1.1
![image](https://github.com/Azure/logicapps/assets/113517384/caf03e5e-dde1-4005-8f86-a6b81c40b6eb)
![image](https://github.com/Azure/logicapps/assets/113517384/a3ebccea-07a5-44d9-971a-cbe26d4200df)

**Comment by ramya894** [comment]
Issue repro in the latest version.
Version: 2.40109.1.1
![image](https://github.com/Azure/logicapps/assets/52390408/003f83e4-2eff-4ead-8d35-089ada02b65a)

**Comment by ramya894** [comment]
Issue repro in the latest version.
Version: 2.40122.1.1
![image](https://github.com/Azure/logicapps/assets/52390408/fa08d642-a282-484f-a180-645c22fbb97d)

**Comment by ramya894** [comment]
Issue repro in the both latest VScode and portal versions.

VScode version:2.108.0
Portal version:2.40205.1.1

![image](https://github.com/Azure/logicapps/assets/52390408/e78525a1-6bab-4452-9aa1-01897a22fbb0)

**Comment by ramya894** [comment]
Issue repro in the latest VS code version.:2.113.1

![image](https://github.com/Azure/logicapps/assets/52390408/a57fc9d5-8f40-4b68-9ebe-b789c2888ae1)

**Comment by ramya894** [comment]
Issue repro in the latest standard portal version: 2.40311.1.4

![image](https://github.com/Azure/logicapps/assets/52390408/2ef3c321-de43-49e7-8af1-a7a0e1cfcc3e)

**Comment by ramya894** [comment]
Issue repro in the latest Vscode version 3.0.0
![image](https://github.com/Azure/logicapps/assets/52390408/1578883a-5041-4cb3-932d-c52b936c2d63)

**Comment by AbodeSaafan** [comment]
Will be fixed in the next major release (ETA july 24). The actions are still usable and can be searched for. When the fix comes out, you will see them in the browse view without any search needed.

**Comment by ramya894** [comment]
Issue repro in the latest VScode version: 4.31.1

![image](https://github.com/Azure/logicapps/assets/52390408/74f92fa7-df45-48a9-beb9-ce3cd7806480)

**Comment by vgouth** [comment]
Issue repro in the latest VScode version: 4.31.5

**Comment by vgouth** [comment]
Issue repro in standard portal.
Portal version:2.40722.1.1

![image](https://github.com/user-attachments/assets/9d65c3f2-fe4d-49e3-b9b4-24d4d504b9db)
![image](https://github.com/user-attachments/assets/e23c3dda-ba27-4756-aa3e-a4af707d63af)

**Comment by vgouth** [comment]
Issue repro in standard portal.
Sometimes when we filter with In-app action all the actions are not poping up 
This issue is seen intermittent.
**Version:** 2.40813.1.2

**Comment by vgouth** [comment]
Issue repro in Vs code request
Sometimes when we filter with In-app action all the actions are not poping up
This issue is seen intermittent.
Version: 4.57.3

![image](https://github.com/user-attachments/assets/9bc5733d-c07a-47c6-867c-dab3c8761731)

**Comment by vgouth** [comment]
Issue repro in Portal request
Sometimes when we filter with In-app action all the actions are not poping up
This issue is seen intermittent.
Version: 2.40826.1.3

**Comment by ccastrotrejo** [comment]
This works fine for vscode and portal
