### ISSUE TITLE
Logic App standard mapping fails: Used by another process?

### ISSUE THREAD

**Issue by JoakimNylundOP** [Azure/logicapps#916]
### Describe the Bug

We have an issue in multiple logic app standard workflows that are using XSLT mappings. Occasionally, this happens:
<img width="254" alt="image" src="https://github.com/Azure/logicapps/assets/139443452/b0bba651-3ccf-49c0-b6db-35b4f0f5d2ac">
<img width="473" alt="image" src="https://github.com/Azure/logicapps/assets/139443452/27d81b1c-7e07-4c6a-bacb-8edc48503e92">

My theory is that another workflow run is "occupying" the mapping. What is strange is that this error does not happen frequently, it happens perhaps 1 or 2 out of 300 runs.
Most of the time, we have multiple runs simultaneously without issues.
We are not calling any external assemblies in the mappings. We are however using inline C# code in them.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

1. Use an XSLT mapping in a Standard workflow. 
2. Run multiple workflow runs.
3. See if the error can be reproduced.

AB#25946984

**Comment by Viktorh89** [comment]
we are having exact same issue - but we do use external assemblies being called from the xslt
