### ISSUE TITLE
When deploying a LogicApp consumption to the Standard LogicApp, the expression outputs('compose') is changed to a string

### ISSUE THREAD

**Issue by Hemanthjs10** [Azure/logicapps#919]
### Describe the Bug with repro steps

we are migrating the logic consumption to standard.
workflow is working fine in consumption but when it is migrated/deployed as standard logic app it is failing.
 
when I checked I got to know that the file path is getting changed after migration.

 
cx is using VS code deployment / migration and follows the below article
 
https://learn.microsoft.com/en-us/azure/logic-apps/export-from-ise-to-standard-logic-app#group-logic-apps-for-export

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

chrome

AB#25843773

AB#25969661

**Comment by ccastrotrejo** [comment]
@Hemanthjs10 is there any chance you can share with us the original consumption workflow structure?  You can send it to me to ccastrotrejo@microsoft.com

**Comment by Hemanthjs10** [comment]
> @Hemanthjs10 is there any chance you can share with us the original consumption workflow structure? You can send it to me to [ccastrotrejo@microsoft.com](mailto:ccastrotrejo@microsoft.com)

I have shared the information, please check. Thank you
