### ISSUE TITLE
`XML transform` action - missing `transform options` input in Standard

### ISSUE THREAD

**Issue by prijeshramani** [Azure/logicapps#926]
### Describe the Bug with repro steps

While using the Standard Logic app, I am not able to see the Transform option in the XML transform. 
I have to apply "transformOptions": "applyXsltOutputAttributes" but I am not finding that option on the shape.

I had to add that line explicitly in the code view. Can you please fix this in new designer of Standard logic App.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

MS Edge

AB#24383621

AB#26009411

**Comment by prijeshramani** [comment]
Hi Team,
Any update

**Comment by rllyy97** [comment]
Hi @prijeshramani, I just checked the `Transform XML` action for both the `Transform options` parameter and option you specified, and I am seeing both on this action.
Are you still having issues with the action?

![image](https://github.com/Azure/logicapps/assets/25409734/1d59863d-54f0-4132-9b27-d247f8198b08)
