### ISSUE TITLE
Change kind from Stateful to Stateless

### ISSUE THREAD

**Issue by brad302** [Azure/logicapps#928]
### Describe the Bug

Not so much a bug but I assume there is some guidance on how to overcome the following ...

> Workflow 'Graph_Initialise_HTTP_Parameters' validation and creation failed. Error: 'The existing workflow 'Graph_Initialise_HTTP_Parameters' cannot be changed from 'Stateful' to 'Stateless' kind.'

In an attempt to improve the performance of my Workflows, I have changed, in particular, a flow from Stateful to Stateless.

Does guidance exist on how to enable this change?

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Simply change the "kind" property in a Workflow from "Stateful" to "Stateless".

### Workflow JSON

```json
N/A
```

### Additional context

Naturally, I receive an error both locally and in the cloud once the app is deployed.

Did come across this ... https://github.com/Azure/logicapps/issues/206 ... but it's quite old.  I "cleared" Azurite locally but that didn't fix it and didn't want to blow away storage entries in case I damaged things beyond repair.

AB#26064981

**Comment by brad302** [comment]
@ccastrotrejo / @hartra344 was thinking maybe you guys have some insight on this one and the both of you are typically quite responsive which is highly appreciated.  It may be a simple matter of "Nup, you have to recreate the workflow with a new name." ... am hoping there is a process though.

**Comment by hartra344** [comment]
Yep, unfortunately you do have the recreate the workflow. The workflow is first created, there are some things that happen with stateful workflows in storage to make it stateful. This is difficult to do after the fact. We do know this is a pain point though and is something we may be able to fix in the future but we don’t have concrete plans I can share right now.

**Comment by brad302** [comment]
@hartra344 ok, thanks. Before I do this though, do I need to give it a different name or do I just need to delete it and recreate it?

**Comment by hartra344** [comment]
Deleting it and recreating it should work just fine.
