### ISSUE TITLE
Additional .NET WorkflowActionTrigger Functions not registering

### ISSUE THREAD

**Issue by brad302** [Azure/logicapps#932]
### Describe the Bug with repro steps

I can't guarantee steps for being able to reproduce, I can merely demonstrate.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/14899088/e0ae6666-6920-44e7-8186-b9a5c513bda2)

### Browser

Chrome

### Additional context

Originally, when I was creating the WorkflowTrigger functions, they would appear in the list and able to be selected from.

After compilation, restarting VS Code, changing the affected workflow, clearing the lib folder, etc. etc. ... new functions won't appear in the list to be selected from.  This also results in a lack of clarity on the parameters.

I workaround it by specifying manually but it's just not ideal.

AB#26105047

**Comment by ccastrotrejo** [comment]
Hi @brad302 I talked with the BE team, in order to confirm this is a bug and keep forward with the investigation could you please send us the code and function.json from the functions that are not showing up in the dropdown selector? So far `AppendArrayToAnotherArray` and `ConvertObjectArrayToSinglePropertyPrimitiveArray` are the ones I can identify. 

Please send the files to my email. ccastrotrejo@microsoft.com

**Comment by brad302** [comment]
@ccastrotrejo email sent, thanks again for the prompt replies (@hartra344) ...!  I'm really liking the product so far, have been dealing with consumption for years but the additional features of standard make it a great product.  Keep up the good work.

**Comment by swghimire** [comment]
@brad302 thank you for sending over the zip file of your project! I was able to get all of the functions to appear when I ran it on my end. One thing I noticed is you have a function.sln in your project that solutions file can cause conflicts with the workspace. Another thing I would do is copy the full file path from right clicking the \LogicApp folder so something like "C:\\Users\\<Name>\\long-service-leave\\Workspace\\LogicApp". Then replace the` ProjectDirectory` value in your workflow-designtime\local.settings.json just to help with locating the functions better in case ProjectDirectory attribute was misgenerated.

Make sure the file path has double backslashes but it should looks something like this:
```

{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsSecretStorageType": "Files",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "ProjectDirectoryPath": "C:\\Users\\name\\long-service-leave\\Workspace\\LogicApp",
  }
}
```
Let me know if you need any help or if that did not resolve your issue! 
![Screenshot 2023-12-19 145503](https://github.com/Azure/logicapps/assets/111014793/243e3c98-576b-4da1-baf8-b5a4b51f1a93)

**Comment by brad302** [comment]
YES!!!  Thanks for the help, it was the path in the `local.settings.json` that you mentioned.  It was pointing to an old folder.  A trap for young players.  I'll keep that in mind if it ever happens again,

Once again, thanks for your help @swghimire and @ccastrotrejo ...!

**Comment by brad302** [comment]
@swghimire ... this may be one of interest to you as well ... it's been sitting open for a while now ... https://github.com/Azure/logicapps/issues/937
