### ISSUE TITLE
IBM Host File Actions: "Generate Host File Contents" getting content not found error after invoking the triger

### ISSUE THREAD

**Issue by ramya894** [Azure/logicapps#934]
### Describe the Bug with repro steps

 "Workflows.WebhookRedirectHostUri": "https://af12-2405-201-c022-b193-7031-a01a-daeb-557f.ngrok.io"

1.Create a new workflow app using VS Code.

2.Create a stateful workflow

3.Add a HTTP trigger to the workflow and save the workflow

4.Add a "Generate Host File Contents" (from the IBM Host File SP) Action after the trigger

5.The Connection Parameters can (should) be left unchanged - or, if you like: 37 and unchecked.

6.For the first 2 parameters of the Action, enter: redefines.hidx (for the HIDX Name), "CUSTOMER_FILE_ROW" (for the Schema Name).

7.Open the attachment named InputJson.txt, copy the contents. In VS Code - the third Parameter Rows, has a button on the right enabling you to fill out all Input as a single value, click this. Delete the contents of the text box ("[ null ]" or similar) and then paste in the copied Input.Json contents.

InputJson.txt (1K)
8.Add a "Parse Host File Contents" Action, and fill out the first 2 Parameters as above (step 6). For the "Binary Contents" select the Dynamic content "Binary Contents" (which is the output of the previous step).

9.Add a response action as well - Http Response - for the Body, use the Dynamic content "Rows" (the output from the previous step).

10.Click on  "Artifacts/Maps", right click - reveal in file explorer. Download the attachment "Redefines.hidx" into that directory.
Redefines.hidx (6K)
11.Press F5/Run the Workflow

12.Get the trigger URL by going to the "overview" page for the workflow

13.Run failed with the error "Generate Host File Contents" getting content not found error after invoking the triger

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200,
                    "body": "@body('Parse_Host_File_Contents')?['rows']"
                },
                "runAfter": {
                    "Parse_Host_File_Contents": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Generate_Host_File_Contents": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "hidx": "redefines.hidx",
                        "schema": "CUSTOMER_FILE_ROW",
                        "rows": [
                            {
                                "CUSTOMER_TYPE": "B",
                                "SIMPLE_REDEFINITION1": {
                                    "BUSINESS": {
                                        "NAME": "ABC"
                                    }
                                }
                            },
                            {
                                "CUSTOMER_TYPE": "P",
                                "SIMPLE_REDEFINITION1": {
                                    "PERSONAL": {
                                        "NAME": {
                                            "FIRST_NAME": "Rob",
                                            "LAST_NAME": "BEA"
                                        }
                                    }
                                }
                            }
                        ]
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "hostfile",
                        "operationId": "generateFileContents",
                        "serviceProviderId": "/serviceProviders/hostfile"
                    }
                },
                "runAfter": {}
            },
            "Parse_Host_File_Contents": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "hidx": "redefines.hidx",
                        "schema": "CUSTOMER_FILE_ROW",
                        "contents": "@body('Generate_Host_File_Contents')?['contents']"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "hostfile",
                        "operationId": "parseFileContents",
                        "serviceProviderId": "/serviceProviders/hostfile"
                    }
                },
                "runAfter": {
                    "Generate_Host_File_Contents": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/52390408/7b7bcb2a-1b84-47ae-ab17-38b0f26fe930)

### Browser

VScode version: ---2.86.0

AB#26124958

**Comment by ramya894** [comment]
HI @ccastrotrejo received the error below after updating code changes:
 "Generate_Host_File_Contents": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "hidx": "Redefines.hidx",

![image](https://github.com/Azure/logicapps/assets/52390408/20e4c85e-2600-4840-9294-c24c678e652c)

**Comment by ramya894** [comment]
Issue repro in latest vscode version

Bundle version: 1.55.1

![image](https://github.com/Azure/logicapps/assets/52390408/74567a5e-8c46-4160-867b-26c5cf167422)

**Comment by rob-beardsworth** [comment]
The workflow.json shows that the actions are expecting a Connection called "hostfile" - but the error message is indicating that there is no such connection.

**Comment by ramya894** [comment]
Closing the issue as it resolved.
