### ISSUE TITLE
Azure function activity sometimes fails with "BadRequest - Http request failed: the content was not a valid JSON."

### ISSUE THREAD

**Issue by mclad** [Azure/logicapps#944]
### Describe the Bug with repro steps

Unfortunately, I wasn't able to reproduce this in dev nor my personal account and this doesn't happen all the time...
We have a logic app with a "Call an Azure function" activity.
The Azure function is written in Python and returns plain text. It ends with: ```return func.HttpResponse(f"Successfully Splitted {filename}")```
Sometimes the "Call an Azure function" activity runs successfully, sometimes it fails with
```
BadRequest
Http request failed: the content was not a valid JSON. Error while parsing JSON: 'Unexpected character encountered while parsing value: S. Path '', line 0, position 0.'
```

I'm at a loss as to what could be causing the issue, especially since it doesn't happen every run.
I'd also be curious if there's a way to get more details on the faillure. Ideally, I'd be able to see the full http response (similar to what we get when the activity succeeds) so I could at least confirm if the issue is on the Azure function or on the Logic app side.

Here are screenshots of two different runs. One successfull with its OUTPUTS section, and a failure (no OUTPUTS section available). Nothing changed in the Azure function or in the logic app between these two runs.
![Capture d’écran 2023-12-27 112232](https://github.com/Azure/LogicAppsUX/assets/145580899/522ee5a7-765d-4319-b50a-635c87288b4f)
![Capture d’écran 2023-12-27 112400](https://github.com/Azure/LogicAppsUX/assets/145580899/020ca7b6-ea7c-4d38-ad2d-dfa14c086436)

Thank you very much!
Any help is appreciated!

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

**Comment by Eric-B-Wu** [comment]
also I would suggest creating a support ticket https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request to expedite this process, as this is connector-specific logic and that way it can be properly be transferred to the right owning team

**Comment by mclad** [comment]
Thank you Travis for moving this issue!

Thank you Eric for pointing me in the right direction. Unfortunatly, I don't have the "Support Request Contributor" permissions in my org so it seems I can't create a support request. I'll look into it again once the people that can grant me that permission are back from vacation.

But FYI, it's not an urgent issue for us. Despite the reported failure, the Azure function runs successfully and accomplishes what it needs to accomplish. It's just a small annoyance because we send emails and notify the on-call on each failure.

Thanks!

**Comment by mclad** [comment]
@Nandini-Sirasani 
Unfortunately I did not resolve this issue. I moved from Azure to another solution.
