### ISSUE TITLE
Connecting to host storage with an identity does not work (bypassing AzureWebJobsStorage connection string)

### ISSUE THREAD

**Issue by erwinkramer** [Azure/logicapps#949]
### Describe the Bug

The following specifies how one can reach the host storage with an identity: https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob&pivots=programming-language-csharp#connecting-to-host-storage-with-an-identity

I've tested this on Function Apps and obviously it works fine. Now Logic Apps Standard has a function runtime as well, but it doesn't seem to work as expected. If i leave `AzureWebJobsStorage` out of the app settings, i get the message `Microsoft.WindowsAzure.Storage: Value cannot be null. (Parameter 'connectionString').`. If i put it back in, my Logic App works fine.

I assume the following text in the docs counts for Logic Apps Standard at this time: `Make sure that all uses of AzureWebJobsStorage are able to use the identity-based connection format before changing this connection from a connection string.`. I'm also wondering if a NuGet-based workflow also suffers from this, does it handle differenty? I didn't test that one. 

I'm on runtime `4.28.3.21820`.

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Make a Logic App Standard with at least the following app settings:

``` json
[
  {
    "name": "APP_KIND",
    "value": "workflowApp",
    "slotSetting": false
  },
  {
    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "value": "YOURSTRING",
    "slotSetting": false
  },
  {
    "name": "AzureFunctionsJobHost__extensionBundle__id",
    "value": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "slotSetting": false
  },
  {
    "name": "AzureFunctionsJobHost__extensionBundle__version",
    "value": "[1.*, 2.0.0)",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__blobServiceUri",
    "value": "https://YOURSTORAGE.blob.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__queueServiceUri",
    "value": "https://YOURSTORAGE.queue.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__tableServiceUri",
    "value": "https://YOURSTORAGE.table.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~4",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "node",
    "slotSetting": false
  },
  {
    "name": "MANAGED_IDENTITY_ID",
    "value": "MYID",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTOVERVNET",
    "value": "1",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_NODE_DEFAULT_VERSION",
    "value": "~18",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE",
    "value": "1",
    "slotSetting": false
  },
  {
    "name": "WORKFLOWS_LOGICAPP_NAME",
    "value": "MYNAME",
    "slotSetting": false
  },
  {
    "name": "WORKFLOWS_RESOURCE_GROUP_NAME",
    "value": "RG-NAME",
    "slotSetting": false
  },
  {
    "name": "WORKFLOWS_SUBSCRIPTION_ID",
    "value": "ONETWO",
    "slotSetting": false
  }
]
```

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "inputs": {
                    "body": {
                        "Hello": "WORLD"
                    },
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {},
                "type": "Response"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

**Comment by erwinkramer** [comment]
Open

**Comment by hybridtechie** [comment]
Still valid issue

**Comment by JoakimNylundOP** [comment]
Still an issue

**Comment by erwinkramer** [comment]
@spplante that's great! Thanks for pointing this out,

**Comment by arnfinneide** [comment]
Great, now us using the WS1 plan, will just have to wait for them to support it :-)

In reference to the need to enable both IDs I found that you can add a reference to the user assigned id in JSON-view tab in the _Connections_ menu to make the connections use the correct ID. That way you don't need to enable the system assigned ID


            "authentication": {
                "identity": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx/resourcegroups/MyResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/My-ManagedIdentity",
                "type": "ManagedServiceIdentity"

**Comment by spplante** [comment]
@arnfinneide You are right, adding the **identity** property to the authentication indeed works for **managed api connections** (azure connectors), however it does not work for **service provider connections** (built-in connectors).

In my case I had the built-in Blob Storage connector and it didn't work, and after digging in MS documentation it confirmed my fear:

![Screenshot](https://i.ibb.co/PmMW031/Image1.png)

https://learn.microsoft.com/en-us/azure/logic-apps/authenticate-with-managed-identity?tabs=standard#where-you-can-use-a-managed-identity

I guess you could get away with a single user-assigned managed identity if you don't have any service provider connections, in my case I decided to enable both identity in order to cover all scenarios. The day they start supporting user-assigned identities in built-in connectors then I will go all the way UMI hehe.
