### ISSUE TITLE
Built-In Decode X12 Action is messed up - see details below

### ISSUE THREAD

**Issue by git-manjunath** [Azure/logicapps#963]
### Describe the Bug

- The sender ID in the incoming EDI is treated as the host partner ID while trying to retrieve the X12 agreement from the integration account instead of the guest partner ID.

- Integration account allows the qualifier 2-SCAC but the EDI file coming in with 02-SCAC fails in the built-in X12 decode action. The x12 qualifier 2 - SCAC is the same as 02 - SCAC

### Plan Type

Standard

### Steps to Reproduce the Bug or Issue

Create an X12 agreement
Create a workflow and use DecodeX12 action

**Comment by git-manjunath** [comment]
These values are swapped in the library. SENDER should be GUEST and RECEIVER should be HOST
Please fix it

![image](https://github.com/Azure/logicapps/assets/116526137/e0328efa-5fdb-43af-afe0-54c579acbcb0)

**Comment by divyaswarnkar** [comment]
Hi @git-manjunath - we have fixed this issue and the fix is getting deployed. Please try out early next week and let us know if you this is resolved.

**Comment by git-manjunath** [comment]
@divyaswarnkar - thanks. Any idea when this X12 connector be GA? 
Also, the output structure of the built in X12 decode is different from the shared X12.

**Comment by git-manjunath** [comment]
@divyaswarnkar 
The Host and Guest partner issue has been fixed. However, the X12 decode isn't functioning the way it should. 
I tried decoding an EDI file with multiple ST/SE (Transactions) and only one gets decoded. 

Generated Acknowledgement doesn't give all the AK segments. It just gives AK1 and AK9

Please take a look.

@kewear for visibility
