### ISSUE TITLE
base64ToBinary output produces corrupted PDF or image file

### ISSUE THREAD

**Issue by jhakulin** [Azure/logicapps#968]
### Describe the Bug with repro steps

1. I created a Logic App to trigger to HTTP requests and where in request I send a pdf file inside multipart/form-data and where file content is binary form as specified by application/octet-stream. Below is the actual Python code I used to send the HTTP request.
```
        file_name = os.path.basename(file_path)
        with open(file_path, 'rb') as file:
            file_content = file.read()

        files = {
            'file_content': (file_name, file_content, 'application/octet-stream')
        }

        response = requests.post(logic_app_url, files=files)
```
2. In Logic app, the HTTP request gets triggered and data is received as expected (that I can see). After trigger, I use Sharepoint connector to create a file. For getting the content of the PDF file I use the following expression
```
base64ToBinary(triggerBody()?['$multipart']?[0]?['body']?['$content'])
```

3. The file is created to the Sharepoint, however the data is corrupted in the PDF. 
- The PDF opens but it is blank.
- When I inspect the created PDF file, some characters are not correct when comparing to original PDF file.

To me it looks like problem is in base64ToBinary function and conversion from base64 encoded string.

Let me know what information you need to help me further? I attached the original and corrupted pdf for inspection

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

[corrupted_pdf.pdf](https://github.com/Azure/LogicAppsUX/files/14073260/corrupted_pdf.pdf)
[original_pdf.pdf](https://github.com/Azure/LogicAppsUX/files/14073261/original_pdf.pdf)

### Browser

Edge

### Additional context

Here is the raw output of body from the HTTP trigger

```
    "body": {
        "$content-type": "multipart/form-data; boundary=17d2fbd65b268c5f0383c18eaeafbfea",
        "$content": "LS0xN2QyZmJkNjViMjY4YzVmMDM4M2MxOGVhZWFmYmZlYQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJmaWxlX2NvbnRlbnQiOyBmaWx.....YzE4ZWFlYWZiZmVhLS0NCg==",
        "$multipart": [
            {
                "headers": {
                    "Content-Disposition": "form-data; name=\"file_content\"; filename=\"original_pdf.pdf\"",
                    "Content-Type": "application/octet-stream"
                },
                "body": {
                    "$content-type": "application/octet-stream",
                    "$content": "JVBERi0xLjQKJazcIKu6CjEgMCBvYmoKPDwgL1BhZ2VzIDIgMCBSIC9UeXBlIC9DYXRhbG9nID4......CnN0YXJ0eHJlZgoxNTkyMgolJUVPRgo="
                }
            }
        ]
    }
```
_No response_

AB#26989020

**Comment by BillingtonRWG** [comment]
1. I am experiencing the same issue. In a logic app, for the attachment content-field if you put in a formula for base64toBinary with the base64 content as the input, the logic app will function.  But, after weeks of use, the formula is removed.  Something about how the logic app is "compiled" or checked when saved will remove this function--even though it will continue to work and produce different output than if you never put it there in the first place.  Furthermore, the PDF files that do get saved after being converted to binary work in acrobat.  But, PDF files that get saved only as base64 will open if using the "open-with" in the UI and selecting chrome to open it.     So, to reproduce this:   1. Create a Logic app where the input is a base64 content of a pdf file, 2. Put the base64 content directly into the attachment field or a onedrive field.  3. Run the logic app and see that PDF is unopenable in acrobat, but can be opened with chrome/edge, 4. add the formula for base64tobinary  in the attachment content box, 5. Save, 6, Run your program and see that the pdf files are now openable in acrobat, 7. Look at the code in a 1 week and notice that the base64tobinary statements have been removed from the logic app--though continuing to function most of the time.  I now have a program that produces intermittent results: sometimes converting to binary and sometimes not.     The workaround I am now attempting is to use a separate "compose" step with base64tobinary  and using the compose output as the input for the file content.

**Comment by tbcashy** [comment]
@jhakulin Could you find a solution? I have the same issue.

**Comment by thewisenerd** [comment]
had a similar issue with the Azure Blob Storage connector's "[Create Blob (V2)][1]"

switching the body formatting to something similar to "[Other content types][2]" worked for me;

from,

```json
{
    "body": "@{base64ToBinary(item()?['contentBytes'])}"
}
```

to,

```json
{
    "body": {
        "$content": "@{item()?['contentBytes']}",
        "$content-type": "@{item()['contentType']}"
    }
}
```

[1] https://learn.microsoft.com/en-us/connectors/azureblob/#create-blob-(v2)
[2] https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-content-type#other-content-types
