### ISSUE TITLE
App Insights Exception Logging: 'Request' Table marking the exception as 'Information' instead of 'Error' in the action category which makes tracking not possible.

### ISSUE THREAD

**Issue by MohamedEliyas-A** [Azure/logicapps#979]
### Describe the Bug with repro steps

I have a question regarding a scenario in my business requirements. My objective is to log  into App Insights with custom tracking data only when there is an error. This approach is aimed at limiting the storage usage for writing into App Insights.

The challenge I'm encountering is that when an action fails, the 'request' table marks it as 'Information' and not as an 'Error'.This makes impossible to track the failed workflow runs in the 'request' table when I have the host json file filtering with an error. I've attached a screenshot for your reference to provide a clearer picture of the issue.

I've observed that failed requests are traceable in the exception table. However, the drawback is that no custom tracking data is available in the exception table.

I'd greatly appreciate any insights or suggestions you might have on how to address this issue. Your expertise would be invaluable in finding a suitable solution.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Catch": {
                "actions": {
                    "Response_1": {
                        "inputs": {
                            "body": "Error Occured",
                            "statusCode": 200
                        },
                        "kind": "Http",
                        "type": "Response"
                    },
                    "ThrowException1": {
                        "inputs": "@div(10,0)",
                        "runAfter": {
                            "Response_1": [
                                "SUCCEEDED"
                            ]
                        },
                        "type": "Compose"
                    }
                },
                "runAfter": {
                    "Try": [
                        "TIMEDOUT",
                        "SKIPPED",
                        "FAILED"
                    ]
                },
                "type": "Scope"
            },
            "Try": {
                "actions": {
                    "Response": {
                        "inputs": {
                            "body": "@triggerBody()",
                            "statusCode": 200
                        },
                        "kind": "Http",
                        "runAfter": {
                            "ThrowEx": [
                                "SUCCEEDED"
                            ]
                        },
                        "type": "Response"
                    },
                    "ThrowEx": {
                        "inputs": "@div(10,0)",
                        "type": "Compose"
                    }
                },
                "runAfter": {},
                "type": "Scope"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "kind": "Stateless"
}
```

### Screenshots or Videos

Screeshots taken when host json file set to 'Information':
     "Workflow.Operations.Actions": "**Information**",
     "Workflow.Operations.Triggers": "**Information**",

![image](https://github.com/Azure/LogicAppsUX/assets/67691937/f04e6d19-1676-47da-a5f1-66877725bd52)
![image](https://github.com/Azure/LogicAppsUX/assets/67691937/9bc8bcd5-6ca6-4200-8a3f-eb2f5373f0ae)

### Browser

Edge

### Additional context

Actual Host Json File:
I want the 'request' table to track the information when I set the host json as below:

--------------------
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  },
   "logging": {
   "applicationInsights": {
     "samplingSettings": {
       "isEnabled": true,
       "excludedTypes": "requests",
       "maxTelemetryItemsPerSecond": 999
     }
   },
   "logLevel": {
     "default": "Error",
     "Host.Results": "Error",
     "Host.Aggregator": "Error",
     "Host.Startup": "Error",
     "Workflow.Operations.Actions": "Error",
     "Workflow.Operations.Triggers": "Error",
     "Workflow.Host": "Error",
     "Workflow.Jobs": "Error",
     "Workflow.Runtime": "Error",
     "Workflow.Operations.Runs": "Error",
     "Workflow.Operations.Batch": "Error"
   }
 },
  "extensions": {
    "workflow": {
      "Settings": {
        "Runtime.ApplicationInsightTelemetryVersion": "v2"
      }
    }
  }
}

-------------

**Comment by kewear** [comment]
Hi @MohamedEliyas-A - I am discussing this with Engineering, will update the thread when I have more information.
