### ISSUE TITLE
HTTP-Trigger Logic Apps (Standard) 404 not found

### ISSUE THREAD

**Issue by a-messner** [Azure/logicapps#988]
### Describe the Bug with repro steps 

Since yesterday (15. Feb) around 5:30a.m. european some of the Workflows, based in the Standard LogicApp could not be triggered anymore. over their Http-Trigger-URL. Nothing was changed on the Logic App or releated resources.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

        "triggers": {
            "When_a_HTTP_request_is_received": {
                "inputs": {
                    "method": "GET"
                },
                "kind": "Http",
                "type": "Request"
            }

### Screenshots or Videos 

*No response*

### Browser 

Chrome. But the same is true if trying by Script or Postman

### Additional context 

Replicating the same functionality inside a Consumption Logic App works fine. But i need the original Logic Apps to resume their working state again.

AB#26856448

**Comment by karanbirsingh** [comment]
@a-messner Can you please share your logic app site name and extension version? This way we can investigate further. Thank you.

As a mitigation, you can try switching to bundle version [1.55.31] if on a newer build.

**Comment by a-messner** [comment]
The problem resolved itself over the weekend. But still doesn't leave me in trust to use this setting for a production-system. So i would rather know what has happened.

@karanbirsingh Not sure what you are referring 100% - It would be much appreciated, if you point me into the right direction.

- The Resource of the Standard LogicApp is called "apirequests" (based in North Europe)
- Runtime Version is "4.30.0.22097"
- Runtime Version of one Workflow, which has been affected is "1.58.21"
- I also added the Http-Trigger, which resolved to 404 on friday. Now if pasted the URL again, simply into a browser, it triggers again.

**Comment by karanbirsingh** [comment]
@a-messner Thanks for the info and patience. The behavior shown in your LogicApp logs matches a bug we discovered in bundle version `1.58.20` for certain workflows. We pushed a fix which got deployed to version `1.58.21` in all regions. Your app picked up the update, explaining why the problem resolved over the weekend. You should not need to do anything further here.

**Comment by KavyaMuniswamappa** [comment]
I have the same issue, getting "Request failed with status code 404" when I am in overview tab of Http trigger flow logic app (standard). Not able to see callback url. 
 "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "method": "POST"
                }
            }
        }

**Comment by crsnt** [comment]
For some reason we get this in our environment. Logic Apps Standard HTTP trigger stateless - debug mode on (allow all methods), no network restriction, callback URL just returns 404. No trigger run visible when called.

Runtime version 1.66.15 @karanbirsingh 

Any idea on what to look at?
